### ISSUE TITLE
Enabling the submit button when there is no invalid fields not working

### ISSUE THREAD

**Issue by chateauv** [formvalidation/support#10]
$('#myForm').formValidation({
                framework: 'bootstrap',
                icon: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                },
                err: {
                    container: 'tooltip'
                },
                fields: {
                    'emails[]': {
                        validators: {
                            regexp: {
                                regexp: /^([\w\.\-_]+)?\w+@[\w-_]+(\.\w+){1,}$/igm,
                                message: 'The input is not a valid email address'
                            }
                        }
                    }
                }
            })
            .on('success.field.fv', function(e, data) {
                if (data.fv.getInvalidFields().length > 0) {    // There is invalid field
                    data.fv.disableSubmitButtons(true);
                }
            });

**Comment by nghuuphuoc** [comment]
@chateauv 
Since this issue is solved through email discussions, please close this issue :)
