### ISSUE TITLE
Validate field only after user finish typing

### ISSUE THREAD

**Issue by audreyaw** [formvalidation/support#101]
Hi,

I have a field validation that requires data from server to compare whether the data input exists on the server or not. It makes the performance a little slow (about 400ms - 1s). I was requested to delay the validation to only when the user finishes typing and not to validate after every character is typed in/erased to find out if that affects the performance. Is there a way to do this?

I have searched around google for help, but to no avail. I hope you can help me with this.

Thank you in advance.

**Comment by nghuuphuoc** [comment]
Take a look at the [3 ways to solve it](http://formvalidation.io/validators/remote/#improving-the-performance).

**Comment by audreyaw** [comment]
I have tried using the remote method, but it doesn't work well with my code. Any way to do this using callback method?

**Comment by nghuuphuoc** [comment]
> it doesn't work well with my code

How does it work?

> Any way to do this using callback method?

No, it's not possible.

**Comment by audreyaw** [comment]
The callback method:

```javascript
callback : {
								message : [[#{error.unique}]].format([[#{table.name}]]),
								callback : function(value, validator) {
									if (!isUniqueWellName(null, $('#InputWellName').val())) {
										return false;
									} else
										return true;
								}
							}
```

And the JSON method in the controller:
```javascript
@RequestMapping(value = "/well/isUniqueName", produces = MediaType.APPLICATION_JSON_VALUE)
	public @ResponseBody boolean isUniqueName(@RequestParam(value = "id", required = false) Long id, 
												@RequestParam(value = "name", required = true) String name) {
		List<WellNoDDRs> results = wellRepo.findAllWellNoDDRs();
		for (WellNoDDRs r: results) {
			if (r.getName().toLowerCase().trim().equals(name)){
				if (id != null && r.getId().equals(id)) {
					continue;
				}
				return false;
			}
		}
		return true;
	}
```

Any suggestion?

**Comment by nghuuphuoc** [comment]
You should use the remote validator. The back-end ```/well/isUniqueName``` need to response an encoded JSON of ```{ "valid": true }``` or ```{ "valid": false }```

**Comment by audreyaw** [comment]
I'm not sure where to put the { "valid": true } or { "valid": false }. The example isn't too clear for me. Should I put it in the controller?

**Comment by nghuuphuoc** [comment]
> Should I put it in the controller?

Exactly. Put it in the server-side.

**Comment by audreyaw** [comment]
Any way to do that in a controller using Java? I found this post on stackoverflow, tried it but it doesn't work http://stackoverflow.com/questions/2463371/spring-mvc-jquery-remote-validation
