### ISSUE TITLE
IE validates on focus not other browsers (like chrome and firefox)

### ISSUE THREAD

**Issue by manthan1985** [formvalidation/support#102]
http://formvalidation.io/download/

above link is your main example link, when you open it in chrome and click on first name textbox it will not immediately validate the field. But open the same page on IE (I am using IE 11) and click on the first name text box it will immediately show you RED validation error message. 

I just want to validate fields when you move out of that text box for all browsers.

Let me know if I am doing something wrong.

**Comment by manthan1985** [comment]
I think it is only for those fields with placeholder.

**Comment by nghuuphuoc** [comment]
> I think it is only for those fields with placeholder

Exactly. This bug will be fixed for the next version.

**Comment by manthan1985** [comment]
when next version is coming, please let me know.

**Comment by nghuuphuoc** [comment]
I fixed the issue on both IE 10 and 11. You can check it again by reloading the [page](http://formvalidation.io/download/).
I will let you know when v0.6.3 is released.

**Comment by nghuuphuoc** [comment]
[v0.6.3](http://formvalidation.io/news/v0.6.3-released/) is released.
