### ISSUE TITLE
Bug: MP3 file return invalid in chrome browser

### ISSUE THREAD

**Issue by russellpabon** [formvalidation/support#104]
Hi, have you checked the mp3 file extension validation in chrome browser? It doesn’t accept mp3 file.

**Comment by nghuuphuoc** [comment]
Can you give me the full Javascript code?

**Comment by russellpabon** [comment]
This is the field validator object:

"fields":{"field_6506":{"validators":{"notEmpty":{"message":null},"file":{"extension":"mp3","type":"audio\/mpeg","message":"The selected file is not valid"},"type":"f_file"},"excluded":false}}

The object came from database and uses php json_encode to output, that is why you can see a backslash. The bug only in chrome browser. Please check the demo link below.

http://demo.guiform.com/?form=216

Thanks for the instantaneous support.

**Comment by nghuuphuoc** [comment]
mp3 file has different MIME type on browsers.
On Firefox, Opera, IE 7+, its MIME type is `audio/mpeg`. Meanwhile, on Chrome, it is `audio/mp3`.

In this case, you should accept both MIME values by separating them with a comma:

```javascript
$(form).formValidation({
    fields: {
        fileInput: {
            validators: {
                file: {
                    extension: 'mp3',
                    type: 'audio/mpeg,audio/mp3',
                    message: 'Please choose a MP3 file.'
                }
            }
        }
    }
});
```

References:
* https://code.google.com/p/chromium/issues/detail?id=227004

**Comment by nghuuphuoc** [comment]
__Updated__:
The official document added new [Supporting multiple MIME types](http://formvalidation.io/validators/file/#supporting-multiple-mime-types) section.

**Comment by russellpabon** [comment]
Thanks for the news. That solve my problem.
