### ISSUE TITLE
How to disable validation when triggering onChange?

### ISSUE THREAD

**Issue by metaxos** [formvalidation/support#107]
Hi

I have a selectbox on top of my form. If this changes the validation should be "disabled". I tried:

    $("#questionnaireSelect").on('change', function() {
		$('#ClientquestionnairesNew').formValidation('enableFieldValidators', 'tx_exaibbrplus_ibbratingplusclients[assistanceNeededDaysSelect]', false);
    });

My validations are all enabled: false, I just want to start validation explicit when clicking the submit button.

Any help is appreciated. Thank you.
Regards

**Comment by nghuuphuoc** [comment]
I see that you're using the ```enableFieldValidators``` method to disable validators. It's right direction.
What's wrong then?

**Comment by metaxos** [comment]
The idea is to set them all to enabled: false and then just activate them depending on the dynamic changes of the form, correct?

Does a selector named 'tx_exaibbrplus_ibbratingplusclients[newClientquestionnaires][pensum]' make trouble (because of the multiple []? Regarding your example it should work, correct? Triggering them via #selector (id) should also work right?

Thank you.

**Comment by nghuuphuoc** [comment]
> The idea is to set them all to enabled: false and then just activate them depending on the dynamic changes of the form, correct?

Yes!

> Does a selector named 'tx_exaibbrplus_ibbratingplusclients[newClientquestionnaires][pensum]' make trouble (because of the multiple []? Regarding your example it should work, correct?

Yes, it should work

**Comment by metaxos** [comment]
HI @nghuuphuoc 

Thank you. I was maybe too long on my code... I forgot the <div class="form-group"> :( my fault.
Sorry for that. Thanks for your help.
