### ISSUE TITLE
Remote.php 

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#11]
_From @moonrays00 on February 3, 2015 23:55_

can anyone gimme some advices on how can I integrate the remote.php into my own mysql database

_Copied from original issue: formvalidation/formvalidation#1410_

**Comment by nghuuphuoc** [comment]
@moonrays00
Basically, based on the POST data, you need to query your MySQL database to check if it's available/valid or not.
Then return an encoded JSON string containing the ```valid``` key.

For example:

```php
// Get the username from request
$username = $_POST['username'];

// Check its existence (for example, execute a query from the database) ...
$isAvailable = true; // or false

mysql_connect(...);
mysql_select_db(...);

$sql   = "SELECT count(user_id) as total FROM users WHERE `username`='" . mysql_escape_string($username) . "'";
$query = mysql_query($sql);
$row   = mysql_fetch_assoc($query);

$isAvailable = $row['total'] === 0;     

// Finally, return a JSON
echo json_encode(array(
    'valid' => $isAvailable,
));
```

**Comment by moonrays00** [comment]
thanks for clearing this up

**Comment by moonrays00** [comment]
$isAvailable = true; 

$connect = mysql_connect('localhost','root','') or die (mysql_error());
mysql_select_db('fitnessuredb',$connect); 

if(isset($_POST['uname']))
{ 
$username = $_POST['uname'];

$sql   = "SELECT count(id) as total FROM userstbl WHERE `uname`='" . mysql_escape_string($username) . "'";
$query = mysql_query($sql);
$row   = mysql_fetch_assoc($query); 
$isAvailable = $row['total'] === 0; 

}


echo json_encode(array(
    'valid' => $isAvailable,
));



it says valid true but it's not working on the form. it always says that it isn't available.

**Comment by nghuuphuoc** [comment]
@moonrays00 
Please give me your HTML form and Javascript code. I need to check if there's wrong usage in the client side.

**Comment by moonrays00** [comment]
my javascript form below
https://www.dropbox.com/s/a5zqfq6laqc21iu/function.js?dl=0

and this is the form

<form id="defaultForm" method="post" class="form-horizontal" action="insert.php">
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Full name</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="fname" placeholder="First name" />
                        </div>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="lname" placeholder="Last name" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label">Username</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" name="uname" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label">Email address</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" name="email" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label">Password</label>
                        <div class="col-sm-5">
                            <input type="password" class="form-control" name="pass" />
                        </div>
                    </div>
					
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Confirm Password</label>
                        <div class="col-sm-5">
                            <input type="password" class="form-control" name="passcon" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label">Gender</label>
                        <div class="col-sm-6">
                            <div class="radio">
                                <label>
                                    <input type="radio" name="gender" value="male" /> Male
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="gender" value="female" /> Female
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label" id="captchaOperation"></label>
                        <div class="col-sm-2">
                            <input type="text" class="form-control" name="captcha" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-6 col-sm-offset-3">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="agree" value="agree" /> Agree with the terms and conditions
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-9 col-sm-offset-3">
                            <button type="submit" class="btn btn-success" name="signup" value="Sign up">Submit</button>
                        </div>
                    </div>
                </form>

**Comment by nghuuphuoc** [comment]
@moonrays00 
The HTML and JS code look ok.
Do you add the remote validator to the username field as following

```javascript
$('#defaultForm').formValidation({
    message: 'This value is not valid',
    icon: {
        ...
    },
    fields: {
        ...
        uname: {
            message: 'The username is not valid',
            validators: {
                ...
                remote: {
                    url: '...'
                }
            }
        }
    }
});
```

**Comment by moonrays00** [comment]
yes I did and here it is

https://www.dropbox.com/s/cpchqkgqayu3yxv/function2.js?dl=0

**Comment by nghuuphuoc** [comment]
By default, the [remote](http://formvalidation.io/validators/remote/) validator will send an Ajax request using __GET__ method. Therefore, you will not get the sent data if using __POST__ method.
You need to set the ```type``` option to ```POST```:

```javascript
$('#defaultForm').formValidation({
    message: 'This value is not valid',
    icon: {
        ...
    },
    fields: {
        ...
        uname: {
            message: 'The username is not valid',
            validators: {
                ...
                remote: {
                    url: 'remote.php',
                    type: 'POST'   // <---- You need to add this option
                }
            }
        }
    }
});
```

**Comment by moonrays00** [comment]
a bit odd since when i add type: 'POST" it didn't work anymore

**Comment by moonrays00** [comment]
it says not available always?

**Comment by moonrays00** [comment]
I added the post but still doesn't work maybe there is something wrong in the remote.php not sure though

**Comment by nghuuphuoc** [comment]
I'm sure that there's issue with the back-end ```remote.php```.
You need to debug it based on various input to see how it works/returns the data.

Can I look at the live site?

**Comment by Himanshupiet** [comment]
When check the username by using servlet and bootstrap validator but it not work properly.
it all time give 'The username is not available'.

Please any one help me



**
Check.java**

public class Check1 extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException 
	{
		
	
		  PrintWriter out = response.getWriter();
		  
		  String uname=request.getParameter("username");
		  System.out.println(uname);
		  String SQL="SELECT username FROM userinfo WHERE username='"+uname+"'";   
		  Connection con=DBConnection.getConnection();
		  
		  Statement st;
		  ResultSet rs;
		
		  boolean status=false;
		  
		 try 
		 {
       	  st=con.createStatement();
       	   rs=st.executeQuery(SQL);
       	  System.out.println(SQL);
       
       	  if(!rs.next())
       	  { 
       		  status=false;
       		 out.print(status);
       		  System.out.println("false");
 		   }
       	  else
       	  { 
       		 status=true;
       		out.print(status);
       
       		  System.out.println("true");
            }
		 }
		 catch(Exception ex)
		 {
			 ex.printStackTrace();
		 }
 }
}

**Reg.jsp**

<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>	ON-DB 	&nbsp;	&nbsp;	&nbsp;Registration</title>
<link rel="shortcut icon" href="images/online-chart-sold-products-by-region.png">
<link rel="stylesheet" href="css/bootstrap.css"/>
    <link rel="stylesheet" href="css/bootstrapValidator.css"/>

    <script type="text/javascript" src="js/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/bootstrapValidator.js"></script>
</head>
<body>

<div class="main">
<%@include file="Header.jsp" %>
<div class="container">

    <div class="row">
      <section>
        <div class="col-lg-8 col-lg-offset-2">
        
            <div class="page-header">
                <h2>Registration</h2>
            </div>

            <form action="RegistrationSevlet" id="defaultForm" method="post" class="form-horizontal" >
                <div class="form-group" id="CheckUsername">
                    <label class="col-lg-3 control-label">Username</label>
                    <div class="col-lg-5">
                        <input type="text" class="form-control" name="username" /><span class="status"></span>
                    </div>
                     <div class="progress" id="progressBar" style="margin: 5px 0 0 0; display: none;">
                         <div class="progress-bar progress-bar-success progress-bar-striped active" style="width: 100%"></div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">First Name </label>
                    <div class="col-lg-5">
                        <input type="text" class="form-control" name="firstName" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Last Name </label>
                    <div class="col-lg-5">
                        <input type="text" class="form-control" name="lastName" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-3 control-label">Email </label>
                    <div class="col-lg-5">
                        <input type="text" class="form-control" name="email" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-3 control-label">Password</label>
                    <div class="col-lg-5">
                        <input type="password" class="form-control" name="password" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-9 col-lg-offset-3">
                        <input type="submit" class="btn btn-default" value="SignUp"/>
                    </div>
                </div>
            </form>
        </div>
        </section>s
    </div>
</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
    $('#defaultForm')
    
        .bootstrapValidator({
        	framework: 'bootstrap',
            message: 'This value is not valid',
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                username: {
                   threshold: 6,
                   message: 'The username is not valid',
                    validators: {
                    	
                        notEmpty: {
                            message: 'The username is required and can\'t be empty',
                        },
                        stringLength: {
                            min: 6,
                            max: 20,
                            message: 'The username must be more than 6 and less than 20 characters long',
                        },

                        regexp: {
                            regexp: /^[a-zA-Z0-9_\.]+$/,
                            message: 'The username can only consist of alphabetical, number, dot and underscore',
                        },
                          remote: {
                        	type: "POST",
                            url: 'Check1',
                            delay:1000,
 
                            message: 'The username is not available', 
                            
                        }, 

                    }
                },
                firstName: {
                    validators: {
                        notEmpty: {
                            message: 'The first name is required and cannot be empty'
                        }
                    }
                },
                lastName: {
                    validators: {
                        notEmpty: {
                            message: 'The last name is required and cannot be empty'
                        }
                    }
                },
           
                email: {
                    validators: {
                        notEmpty: {
                            message: 'The email is required and can\'t be empty'
                        },
                        emailAddress:{
                            message: 'The input is not a valid '
                        }
                    }
                },
                password: {
                    validators: {
                        notEmpty: {
                            message: 'The password is required and can\'t be empty'
                        }
                    }
                }
            }
        })
});
</script>
</body>
</html>
