### ISSUE TITLE
Provide support for bootstrap-datepicker.js

### ISSUE THREAD

**Issue by Aibu** [formvalidation/support#110]
Hi, 
would it be possible to provide support for the following plugin?
http://www.eyecon.ro/bootstrap-datepicker

Everything seems to work fine, except that when a date is selected from the datepicker widget, formValidation does not detect text was inserted into the form field. 

Many thanks

**Comment by nghuuphuoc** [comment]
Take a look at the [Bootstrap Datepicker](http://formvalidation.io/examples/bootstrap-datepicker/) example.

**Comment by Aibu** [comment]
Hi and thanks for your reply. 

That's another component. 

I need the first one because it gives me the possibility to insert a date range into 2 different fields. 

Would you be so kind to check it?
I have attached a screenshot with the problem. 

Basically, if I try to send the form before I have inserted any data, formValidation gives me error, which is correct. Then, if I click in the input field, select a date and the field is updated, formValidation would not understand some information have been inserted into the field (as you can see from the screenshot). 


Many thanks!
![formvalidation](https://cloud.githubusercontent.com/assets/19736/7227683/d61945b4-e752-11e4-9186-940254362cee.png)

**Comment by nghuuphuoc** [comment]
> That's another component

Yes, I know. But they have the same syntax `.datePicker()`, the same event (`changeDate`).
Anyway, I will spend time to make a complete example for you.

**Comment by nghuuphuoc** [comment]
Updated: Actually, the Bootstrap datepicker used in the example is https://github.com/eternicode/bootstrap-datepicker which is extended from http://www.eyecon.ro/bootstrap-datepicker :)

**Comment by Aibu** [comment]
Thanks a lot, that's really appreciated.

**Comment by nghuuphuoc** [comment]
I added the [Start and end dates](http://formvalidation.io/examples/bootstrap-datepicker/#start-and-end-dates) example.

The example uses Bootstrap datepicker, but you can apply the same principles if using (or not) other picker plugins.
