### ISSUE TITLE
MaskMoney, MaskedInput and  Bootstrap DatePicker plugins doesn't works.

### ISSUE THREAD

**Issue by RempelOliveira** [formvalidation/support#112]
When I work with these plugins, the validation doesn't works.

MaskMoney
https://github.com/plentz/jquery-maskmoney

MaskedInput Plugin
http://digitalbush.com/projects/masked-input-plugin

Bootstrap DatePicker
https://github.com/eternicode/bootstrap-datepicker

**Comment by nghuuphuoc** [comment]
@RempelOliveira 
When integrating FormValidation with other plugins, you need to follow these [principle](http://formvalidation.io/examples/#compatibility).

Take a look at the example showing how to use with Bootstrap Datepicker:
http://formvalidation.io/examples/bootstrap-datepicker/

After reading this, I think you will know how to make it work with remaining plugins such as MaskMoney.

PS: http://formvalidation.io/examples/mask/ might be also helpful.
