### ISSUE TITLE
FormValidation with Select2

### ISSUE THREAD

**Issue by wnjken** [formvalidation/support#113]
I'm using v0.6.2 with Select2 4.0.0-rc.2 on Bootstrap v3.3.4. I've taken a look at the Select2 example but frankly I'm struggling to get this one to work.

HTML

    <select id="join_country" name="join_country" class="form-control" value="" required="required">
        <option></option>
        <option>United Kingdom</option>
        <option>United States</option>
    </select>
    <script>
        $("#join_country").select2({
            minimumResultsForSearch: -1,
            placeholder: "country",
            allowClear: true
        });
    </script>

Javascript:

    .find('[name="join_country"]')
        .select2()
            .change(function(e) {
                $('#join').formValidation('revalidateField', 'join_country');
            })
        .end()

I've console logged the change event, so I know that's definitely firing. What I want to do is prevent the form from submitting with an empty value, which is possible due to the ````<option></option>```` requirement for a placeholder (https://select2.github.io/examples.html).

Validator - doesn't seem to get this far.

    join_country: {
        disabled: false,
            validators: {
                callback: {
                    callback: function(value, validator, $field) {
                        if(value === '')
                            {
                                console.log("A: "+value);
                                return {
                                   valid: false,
                                   message: 'Country is required',
                                };
                             } else {
                                 console.log("B: "+value);
                             }
                             
                             return {
                                 valid: true,
                              };
                          }
                      }
                  }
              }

**Comment by nghuuphuoc** [comment]
Try to add the [empty value](http://formvalidation.io/validators/notEmpty/#using-with-select-element) to the select box:

```html
<select id="join_country" name="join_country" class="form-control" required="required">
    <option value=""></option>
    ...
</select>
```

**Comment by wnjken** [comment]
Just tried that, unfortunately no luck.

I have however noticed some odd behaviour. When this section of code is live

    .find('[name="join_country"]')
    .select2()
        .change(function(e) {
            $('#join').formValidation('revalidateField', 'join_country');
        })
    .end()

the placeholder disappears from the field:

![screen shot 2015-04-15 at 17 22 04](https://cloud.githubusercontent.com/assets/6951966/7163860/351db62a-e394-11e4-8925-6e9fcdbb8b06.png)

When the aforementioned section of code is removed, the placeholder appears as expected:

![screen shot 2015-04-15 at 17 25 06](https://cloud.githubusercontent.com/assets/6951966/7163896/8186e69e-e394-11e4-8a5b-522604723fe0.png)

Irrelevant of the above code though, it appears that the validator section simply can't find name="join_country".

I've tested the validator with a non-Select2 field and it appears to function within expected parameters.

**Comment by nghuuphuoc** [comment]
Do you use the `excluded` option when calling `.formValidation()` as seen in the [select2](http://formvalidation.io/examples/select2/) example?

**Comment by wnjken** [comment]
I knew it was going to be something small (always is) - all working now, thanks!

**Comment by nghuuphuoc** [comment]
I'm glad that it works. In the next time, don't forget to follow these [principles](http://formvalidation.io/examples/#compatibility) when integrating with other plugins :).

**Comment by iamchriswick** [comment]
I have a similar issue, the Select2 fields are not revalidated on Select2 change: http://stackoverflow.com/questions/36999230/formvalidation-io-not-validating-on-select2-field-change
