### ISSUE TITLE
Website issue

### ISSUE THREAD

**Issue by raulgd** [formvalidation/support#114]
Hi,

Because I'm behind a proxy where I work, I cannot buy through Gumroad nor Sellfy because they are blocked, do you have a direct link to PayPal or anything else I could use to buy?

It also would be nice to have the direct link on the website in case anyone else is behind a proxy as well

**Comment by nghuuphuoc** [comment]
You can send a payment manually to my Paypal account (phuoc(at)huuphuoc.me), and then you will get the files via email.
