### ISSUE TITLE
Per Validator Custom Threshold

### ISSUE THREAD

**Issue by wnjken** [formvalidation/support#115]
http://formvalidation.io/settings/#field-threshold

I was thinking that it'd be useful to be able to specify a threshold for a particular validator. In example, I'm currently developing a signup screen and I'd like to live check the following password requirements:

- notEmpty
- stringLength
- different
- callback (uppercase, lowercase, numeric, special)
- password strength

However, what I don't want to be doing is firing off a remote request to check against a disallowed (common) password list every time a letter is typed (unnecessary DB queries/page requests!). Nor is it ideal to require a submit/validate and then provide the end user with a possible rejection.

Therefore it'd be beneficial to be able to only initiate the remote validator when the stringLength is achieved and/or a custom variable has been set (password strength returns true, even where requirements haven't been technically met).

**Comment by nghuuphuoc** [comment]
> However, what I don't want to be doing is firing off a remote request to check against a disallowed (common) password list every time a letter is typed (unnecessary DB queries/page requests!)

You can place the `remote` validator at the end of list of validators, and use the `verbose` option.
See [3 ways to improve the performance](http://formvalidation.io/validators/remote/#improving-the-performance) when using the remote validator.
