### ISSUE TITLE
Bootstrap Wizard validate whole form not working

### ISSUE THREAD

**Issue by Wintermute79** [formvalidation/support#116]
Hello and thank you for this great piece of software! I already purchased a license 10 days ago ;-)

I am currently building a form with Boostrap Wizard and it has more than 2 steps. When I use the nav pills to jump from the first tab to the last tab, the tabs in-between are not validated, of course. This is expected.
But when the final tab is validated, I would like to check if the whole form is valid before submit.
For this, I call the `function validateTab(index)` from your example at http://formvalidation.io/examples/bootstrap-wizard/ in a loop, iterating over all tabs.
But it returns `true` for all tabs which is wrong. There are required but empty fields in the tabs that I skipped.

To reproduce, I created a JsFiddle at http://jsfiddle.net/6zLnemey/3/ that extends your example with a third tab in the middle.
1. Fill the first tab's fields with valid input.
2. Jump to the last tab (Database) by clicking the last nav pill.
3. Fill the fields here with valid input, too.
4. Open the browser's JavaScript console
5. Click the submit button (Install) on the form.
6. Observe the console output
```
Tab 0 is valid
Tab 1 is valid
Tab 2 is valid
```

The output is from the loop I added in lines 92 - 95. Tab 1 should NOT be valid, it has a required but empty input field.

Can you please help me with this?

Thanks in advance!

**Comment by Wintermute79** [comment]
Never mind, I just found it. Your example code for Bootstrap Wizard has a tiny typo in the `options`. It must be _exclude**d**_, not _exclude_
It reads
  `exclude: ':disabled',`
but it should be
  `excluded: ':disabled',`
That was responsible for skipping the invisible tab's input elements.
(See http://formvalidation.io/settings/#form-excluded for details.)

**Comment by nghuuphuoc** [comment]
Thank a lot :+1:.
I updated the [Bootstrap Wizard](http://formvalidation.io/examples/bootstrap-wizard/) example.
