### ISSUE TITLE
undefine NAN issue in mozilla firefox

### ISSUE THREAD

**Issue by nishant-befree** [formvalidation/support#118]
![image](https://cloud.githubusercontent.com/assets/6196479/7214765/c99c2044-e5d7-11e4-8406-b4997b414452.png)

datepicker undefine NAN issue in mozilla firefox issue.

can anyone tell me how to solve this?

**Comment by nghuuphuoc** [comment]
It's not issue of FormValidation. The issue is caused by the Bootstrap datepicker plugin.
