### ISSUE TITLE
using remote validation and removing a field

### ISSUE THREAD

**Issue by JanaVanMaele** [formvalidation/support#12]
Thank you for the great plugin! It's very handy and neat.

I am creating a form and it has a functionality equal to an example from your example page: http://formvalidation.io/examples/adding-dynamic-field/

But in my case, I am using a remote validation and this throws an error, probably caused by the delay of the call. I applied remote validation to your example and it gives me the same error:
' Uncaught TypeError: Cannot read property 'find' of undefined' - formValidation.js:1309 Uncaught TypeError: Cannot read property 'find' of undefined

I can prevent this in the full version of the formValidation, but maybe you could integrate it in your next update, so it's also available in the minified version.

I solved it in my case by doing a check first:
line 1286

```javascript
updateMessage: function(field, validator, message) {
            var that    = this,
                ns      = this._namespace,
                $fields = $([]);
            switch (typeof field) {
                case 'object':
                    $fields = field;
                    field   = field.attr('data-' + ns + '-field');
                    break;
                case 'string':
                    $fields = this.getFieldElements(field);
                    break;
                default:
                    break;
            }

            $fields.each(function() {
                if($(this)
                    .data(ns + '.messages')){
                    $(this)
                        .data(ns + '.messages')
                        .find('.' + that.options.err.clazz + '[data-' + ns + '-validator="' + validator + '"][data-' + ns + '-for="' + field + '"]').html(message);
                }
            });
        },
```

Thank you in advance

**Comment by nghuuphuoc** [comment]
Thank a lot.
Can you give me the form markup and the JS, so maybe I can detect the root reason of the problem?

**Comment by JanaVanMaele** [comment]
Hello,


it's very similar to an example on your site :

http://formvalidation.io/examples/adding-dynamic-field/


( I can not show you my working example, we are in full development )


But in the validator options you have to add a remote validation.


fields: {

                question: {

                    validators: {

                        notEmpty: {

                            message: 'The question required and cannot be
empty'

                        }

                    }

                },

                'option[]': {

                    validators: {

                        notEmpty: {

                            message: 'The option required and cannot be
empty'

                        },

                        remote: {

                            url: '/path/to/backend/',

                            type: 'POST'

                      }

                    }

                }

            }


It all works fine, but when the focus is in an extra option input and I
directly click the remove button of that focused input, it will throw the
error.


I fixed it by writing an extra check around the code that’s throwing the
error, but maybe there is a better solution for this.


so in the formValidation „updateMessage” I added :

updateMessage: function(field, validator, message) {

            var that    = this,

                ns      = this._namespace,

                $fields = $([]);

            switch (typeof field) {

                case 'object':

                    $fields = field;

                    field   = field.attr('data-' + ns + '-field');

                    break;

                case 'string':

                    $fields = this.getFieldElements(field);

                    break;

                default:

                    break;

            }


            $fields.each(function() {

                if($(this)

                    .data(ns + '.messages')){

                    $(this)

                        .data(ns + '.messages')

                        .find('.' + that.options.err.clazz + '[data-' + ns
+ '-validator="' + validator + '"][data-' + ns + '-for="' + field +
'"]').html(message);

                }

            });

        },



Thank you for your time.

Jana
2015-02-04 11:42 GMT+01:00 Phuoc Nguyen <notifications@github.com>:
