### ISSUE TITLE
"yes no" confirm modal closes instantly

### ISSUE THREAD

**Issue by theFlob** [formvalidation/support#122]
Hello,

I'm facing an issue with using a yes/no confirm modal. The modal is displayed, but instantly closes without any action.

I have read an article here : http://stackoverflow.com/questions/13648979/bootstrap-modal-immediately-disappearing

One of the reasons invoked is that the bootstrap.min.js is loaded 2 times.

Effectively, I have 2 in my script : one for the bootstrap framework, and one for the formvalidation plugin. I know that you said in the instructions that these files are independant, but it seems that if I comment out the formvalidation involved bootstrap.min.js, the problem disappears...

here is my modal code :
```
<div class="modal fade" id="confirm-yes-no" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
       <div class="modal-content">
            <div class="modal-header">
               Confirmation`
            </div>
           <div class="modal-body">
                Voulez-vous réellement effectuer cette action ?`
           </div>
           <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Annuler</button>
                <a href="#" class="btn btn-danger danger">Confirmer</a>
           </div>
       </div>
    </div>
</div>
```
The modal is launched by  :
```
<div class="pull-left">
            <button type="button" class="btn bg-red" data-dismiss="modal" data-toggle="modal" data-target="#confirm-yes-no" data-href="/venues/delete/" onclick="">Supprimer</button>
</div>
```

do you have any idea why this is happening ? I'd appreciate your help, as I have spent a lot of time trying to fix the issue, with no success...

thanks for your help

regards,

Florent

**Comment by nghuuphuoc** [comment]
> One of the reasons invoked is that the bootstrap.min.js is loaded 2 times.
> 
> Effectively, I have 2 in my script : one for the bootstrap framework, and one for the formvalidation plugin. I know that you said in the instructions that these files are independant

There is nothing related/conflict between `formvalidation/dist/js/framework/bootstrap.min.js` with `bootstrap.min.js` provided by the Bootstrap framework.

You can take a look at the examples below which use FormValidation with the Bootstrap modal component:

* http://formvalidation.io/examples/modal/
* http://jsfiddle.net/nghuuphuoc/Lr7w0xLr/, a fiddle with the same code
