### ISSUE TITLE
Integer Validation - Leading Zero

### ISSUE THREAD

**Issue by ejio** [formvalidation/support#125]
What would be the best way to validate an integer with a leading zero?

Below is my current code.

I'm able to verify the string is X digits through the use of regexp, but between will only validate 1 through 12 without leading zeros and will not accept 01 as a min to validate 01 through 12 with leading zeros.

    field: {
        disabled: false,
        validators: {
            notEmpty: {
                message: 'field is required'
            },
            integer: {
                message: 'field must be an integer'
            },
            between: {
                min: 1,
                max: 12,
                message: 'field must be between 01 and 12'
            },
            regexp: {
                regexp: /^\d{2}$/,
                message: 'field is not two digits'
            }
        }
    },

**Comment by nghuuphuoc** [comment]
I think you can use the [regexp](http://formvalidation.io/validators/regexp/) validator:

```javascript
field: {
    disabled: false, // You don't need this unless you know what you're doing :)
    validators: {
        notEmpty: {
            message: 'field is required'
        },
        regexp: {
            regexp: /^(0[1-9]|1[0-2])$/,
            message: 'The field must be 01 - 12'
        }
    }
}
```

The pattern `/^(0[1-9]|1[0-2])$/` cover the number 1-12 with leading zero.

**Comment by ejio** [comment]
That's a really good point and a simple solution, long day, thanks!

/^(0[1-9]|1[0-9]|2[0-9]|3[0-1])$/ - the pattern for 01-31, if anyone ends up here through a Google :)

**Comment by nghuuphuoc** [comment]
> /^(0[1-9]|1[0-9]|2[0-9]|3[0-1])$/ - the pattern for 01-31

:+1:
