### ISSUE TITLE
How to enableFieldValidators on an array individual array element

### ISSUE THREAD

**Issue by shubbell** [formvalidation/support#127]
I have reviewed example:
http://formvalidation.io/examples/validating-array-inputs/#inputs-with-different-names

To create a form that has input values named like the following:
child[0].studentname, child[0].studentbirth,child[0].studentgrade, and child[0].student1absent

Then I reviewed example:
http://formvalidation.io/examples/adding-dynamic-field/

To clone the row of inputs to create inputs with the names:
child[1].studentname, child[1].studentbirth,child[1].studentgrade, and child[1].student1absent

The Adding Dynamic Field example validates all option[] fields visible on the form at one time

How can I validate only child[X].studentname field when both child[0].studentname and child[1].studentname are cloned on the form?  I have tried with an .on (keyup) function with no luck

$('#schoolreportingForm').on('keyup', '[name="child[0].studentname"], [name="child[1].studentname"], [name="child[2].studentname"], [name="child[3].studentname"], [name="child[4].studentname"]', function() {	
   var bootstrapValidator2 = $('#schoolreportingForm').data('formValidation'), isEmpty2 = ($(this).val() != '');
   var sm = $('#schoolreportingForm').data('formValidation');

   if (isEmpty2) {
     var cntStudentNamesOf = $('#schoolreportingForm').find('[id="' + $(this).attr('id') + '"]').val();
     if (cntStudentNamesOf != "") {
         //Enable the field validator of the row
	sm.enableFieldValidators(studentbirth[], true);
     }
   }

----
'studentbirth[]': {
				enabled: false,
                validators: {
                    notEmpty: {
                        message: 'Enter Student DOB'
                    },
			date: {
			format: 'MM/DD/YYYY',
                        message: 'Student DOB not valid'
			}
                }
            }

**Comment by nghuuphuoc** [comment]
So, do you want to add the dynamic field with different names?

**Comment by shubbell** [comment]
The page loads with child[0].studentname, child[0].studentbirth,child[0].studentgrade, and child[0].student1absent

Additional students can be added to the form by clicking the add button which creates
child[1].studentname, child[1].studentbirth,child[1].studentgrade, and child[1].student1absent using clone()

When an entry has been made into child[1].studentname .on(keyup function is triggered and catches what row the data entry occurred then I want it to only enable validation for field child[1].studentbirth not both child[0].studentbirth and child[1].studentbirth

**Comment by nghuuphuoc** [comment]
UPDATED: I will update the [Adding dynamic field]() example which covers your usecase.
You will get notified on tomorrow.

**Comment by shubbell** [comment]
I have not received notification that the Adding dynamic field example was updated.  Do you need any additional information from me?

**Comment by nghuuphuoc** [comment]
@shubbell 
I'm sorry for not to response in time.
Here is new [example](http://formvalidation.io/examples/adding-dynamic-field/#adding-fields-with-different-names) showing how to add new fields with different names.

![adding-fields-different-names](https://cloud.githubusercontent.com/assets/4226036/7362475/867e70e6-ed93-11e4-930e-d926fe6db4e1.png)

Let me know if you need futher help.

**Comment by shubbell** [comment]
When the 'Submit' button is clicked all visible fields on the form are validated. 
Instead, can the validation be triggered after a field has a value entered into it, and addionally requiring all 3 fields from the row?
