### ISSUE TITLE
Safari Form with multiple buttons how to get which was clicked

### ISSUE THREAD

**Issue by metaxos** [formvalidation/support#128]
Hi

I have a form with 3 buttons:
```
<button id="overviewQuestions" type="submit" name="overview" value="overview"></button>
<button id="nextQuestion" type="submit" name="submitbutton" value=""></button>
<button id="skipQuestion" type="submit" name="skipbutton" value=""></button>
```

There is no need to validate when clicking the "overview" button, see below. But when clicking this one I cannot see the value after submitting. If I remove formvalidation I receive the value. This problem only occurs with Safari.

```
$('#clientquestionnairesanswersEdit').formValidation({
			framework: 'bootstrap',
			button: {
				// The form will be validated when clicking the 
				// submit1Button and submit2Button buttons
				selector: '#previousQuestion, #nextQuestion',
				// The class for disabled button
				disabled: 'disabled',
			},
			icon: {
				valid: 'glyphicon glyphicon-ok',
				invalid: 'glyphicon glyphicon-remove',
				validating: 'glyphicon glyphicon-refresh'
			},
			locale: 'de_DE',
			fields: {
				'answer': {
					validators: {
						notEmpty: {
						}
					}
				}
			}
		});
```

Input which maybe could help:
http://stackoverflow.com/questions/5721724/jquery-how-to-get-which-button-was-clicked-upon-form-submission

Regards
metaxos

**Comment by nghuuphuoc** [comment]
The [Using multiple buttons](http://formvalidation.io/examples/using-multiple-buttons/) example might be helpful to you.

**Comment by metaxos** [comment]
Thank you. But, it seems that if I disable validation for one button (overview) then I cannot use $form.data('formValidation').getSubmitButton()... correct?

**Comment by nghuuphuoc** [comment]
I'm sorry for replying late.
If you skip validation on Overview button as above, then `$form.data('formValidation').getSubmitButton()` returns `null` if the Overview button is clicked.
