### ISSUE TITLE
TypeError: $(...).steps(...).formValidation is not a function

### ISSUE THREAD

**Issue by in2action** [formvalidation/support#129]
Cannot fix this problem.
I've just copy/paste the entire script part from formvalidation file.

Some ideas?

Thanks in advnace.

**Comment by nghuuphuoc** [comment]
> I've just copy/paste the entire script part from formvalidation file

Can you give me the HTML markup and the JS you're using for?

**Comment by in2action** [comment]
Thanks for replying.
I just found my mistake... forgive to close a tag.

Just fine right now.
Have a nice day.

Michel
