### ISSUE TITLE
Server-side validation after form submit

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#13]
_From @BenGiroux on February 3, 2015 19:6_

First of all, thank you for creating a fantastic plugin that makes validation with HTML5 so easy!

Quick question: Is there an easy way to do form validation after the form is submitted via AJAX? While the validation on-the-fly is a nice feature, I’d hoped that there was a fallback validation on the server end that would pass back a JSON string indicating which fields failed and update them accordingly. 

I’m currently doing it manually and copying the CSS styles for the errors…

_Copied from original issue: formvalidation/formvalidation#1409_

**Comment by nghuuphuoc** [comment]
@BenGiroux
It's interesting question! After submitting form data to the server via Ajax, you can make server-side validation, and then use 
* [updateStatus()](http://formvalidation.io/api/#update-status)  to set the field as invalid 
* and [updateMessage()](http://formvalidation.io/api/#update-message) to update the message which is returned from server

The code might look like

```javascript
$('#registrationForm')
    .formValidation({
        framework: 'bootstrap',
        fields: {
            email: {
                validators: {
                    emailAddress: {
                        message: 'The email address is not valid'
                    }
                }
            }
            ...
        }
    })
    .on('success.form.fv', function(e) {
        e.preventDefault();

        // Send data to server via Ajax request
        $.ajax({
            ...
        }).success(function(response) {
            // Assume that the response maps the validator name with message for each field
            //  {
            //      errors: {
            //          email: {
            //              emailAddress: 'The email address is already used. Please try another one'
            //          }
            //          ...
            //      }
            //  }
            if (response.errors) {
                for (var field in response.errors) {
                    for (var validatorName in response.errors[field]) {
                        $('#registrationForm')
                            // Update the status
                            .formValidation('updateStatus', field, 'STATUS_INVALID', validatorName)

                            // Update the message
                            .formValidation('updateMessage', field, validatorName, response.errors[field][validatorName]);
                    }
                }
            }
        });
    });
```

**Comment by sunilgupta0485** [comment]
Do we have any way to validate 2 textboxs on one button and other 4 textboxes on another button. Current when I clicked on any of these button validation get fire for all 6 text boxes. 

Please help me I got stuck here. Thanks in advance..
