### ISSUE TITLE
$.frm.formValidation is not a function

### ISSUE THREAD

**Issue by docahrens** [formvalidation/support#132]
//Declaring:
var $frm = $('#myFormId');

//Then:
$frm.formValidation({
	framework: 'bootstrap',
	icon: {
		valid: 'glyphicon glyphicon-ok',
		invalid: 'glyphicon glyphicon-remove',
		validating: 'glyphicon glyphicon-refresh'
	},
	fields: {
		'My Number Field': {
			validators: {
				numeric : {
					message: 'Please enter a valid number'
				}
			}
		},
		'My Integer Field': {
			validators: {
				integer : {
					message: 'please enter a valid number'
				}
			}
		}
	}
}).formValidation('validate');

// Console says: $.frm.formValidation is not a function
// I verified that $.frm is a JQuery object pointing to #myFormId
// a search of your bootstrapValidator.js file reveals there is not string formValidation in the entire file.
// But, there is $.fn.bootstrapValidator   Is your documentation out of date???

**Comment by nghuuphuoc** [comment]
The reason is that you're using old version which is named as bootstrapValidator.
