### ISSUE TITLE
How to download the latest version when already purchased a license?

### ISSUE THREAD

**Issue by amccoll111** [formvalidation/support#134]
Can anyone tell me how to download the latest version, I purchased v 0.6.0 and looking to upgrade to 0.6.2?

**Comment by nghuuphuoc** [comment]
You can re-use the download link from puchase email (all versions have the same download link).

**Comment by nghuuphuoc** [comment]
UPDATED: If you can't find that email, you can send an email to hello@formvalidation.io from the email you used to purchase.
Then you will get new download link :)
