### ISSUE TITLE
No form validation in modal forms using bootstrap and BootstrapValidator

### ISSUE THREAD

**Issue by vjitweb** [formvalidation/support#14]
Hello

I have used BootstrapValidator for forms in normal bootstap pages and it's working fine.
Now I need to use BootstrapValidator on a modal form.
Here is the code for my modal form
![modalcode](https://cloud.githubusercontent.com/assets/10865201/6060046/1ff76dea-ad39-11e4-9610-50450b971043.JPG)
And here is my JQuery/JS code inside `$(document).ready(function() {})`
![javascriptcode](https://cloud.githubusercontent.com/assets/10865201/6060096/d1a70708-ad39-11e4-8f85-83836788fb22.JPG)

I hope you can tell me what I'm doing wrong.

**Comment by nghuuphuoc** [comment]
In your HTML code, the fields don't have ```name``` attributes. You're using ```id``` one.
Please change ```id="..."``` to ```name="..."``` and try again.

**Comment by vjitweb** [comment]
Thank you so much :+1:
