### ISSUE TITLE
PDF and Word Doc Validation not working

### ISSUE THREAD

**Issue by nikmav** [formvalidation/support#142]
Hi, I'm using v0.6.2 and pdf and word validation won't work at all in that it keeps coming up as an invalid file type when using just a mime type application/pdf and/or application/msword.  I tried the demo on your website and that isn't validating either!

I'm using macosx 10.10, Firefox 37.0.2 and validating using pdf documents created in Acrobat v9 through to 11, and word documents created in both mac and windows and none are validating.

Any ideas?

**Comment by nghuuphuoc** [comment]
I'm using the latest MacOS 10.10.3 and test a simple example on Firefox, Chrome:

```javascript
$(form).formValidation({
    fields: {
        cv: {
            validators: {
                file: {
                    extension: 'pdf',
                    type: 'application/pdf',
                    message: 'Please choose a pdf file.'
                }
            }
        }
    }
});
```

Here's the result:

![validate pdf file](https://cloud.githubusercontent.com/assets/4226036/7570250/f792b710-f838-11e4-9388-52d9a29e6878.png)

Can you please tell me
* Does the example work on Chrome? Or it doesn't work on Firefox only
* What's the JS code you're using?

**Comment by nikmav** [comment]
JS Code is:

```
$('#sendmessage_form')
            .bootstrapValidator({
                feedbackIcons: {
                    valid: 'fa fa-ok',
                    invalid: 'fa fa-remove',
                    validating: 'fa fa-refresh'
                },
                fields: {
                    subject: {
                        validators: {
                            notEmpty: {
                                message: 'Please enter a subject for your message'
                            }
                        }
                    },
                    body: {
                        validators: {
                            notEmpty: {
                                message: 'Please enter your message'
                            }
                        }
                    },
                    attachment: {
                        validators: {
                                file: {
                                    extension: 'jpg,png,gif,pdf,doc,docx',
                                    type: 'image/jpeg,image/png,image/gif,application/pdf,application/msword',
                                    maxSize: 10485760, // 10 MB
                                    message: 'The selected file is not valid'
                                }
                        }
                    }

                }
            });
    });
```

In Firefox it doesn't validate pdf as below:

![screen shot 2015-05-12 at 9 19 35 am](https://cloud.githubusercontent.com/assets/7378273/7577172/aa028278-f888-11e4-960c-65f30dbaa6c2.png)

However in Chrome and Safari it appears to validate fine.   Haven't tested IE.

**Comment by nghuuphuoc** [comment]
Thank for your response. Can you please give me (by uploading here or sending to hello(at)formvalidation.io) a sample PDF file created by Adobe Acrobat?
I will check myself if it has different MIME type on Firefox.

Thank you!

**Comment by nikmav** [comment]
Thanks for all your help.  As it turns out I must've had corruption in Firefox because when I reinstalled it the validation worked as normal.

Awesome work!

**Comment by foxfrancis005** [comment]
I have a trouble: I cant validate the ".docx" file. Im using the v0.6.2dev.

Can you bring me an example if its work??

Thanks.

**Comment by kongolml** [comment]
@foxfrancis005 try removing spaces between extensions and MIME types.

`extension: 'pdf,doc,docx,rtf,ppt,pptx'`
instead of
`extension: 'pdf, doc, docx, rtf, ppt, pptx'`
