### ISSUE TITLE
Swapping countries for zip validation with HTML5 Attributes

### ISSUE THREAD

**Issue by austinstudio** [formvalidation/support#143]
I am using the HTML5 attributes to validate zip codes and want to switch out the country to be validated based on a country drop-down.  When the drop's value is US I want to use the US country zip code validator and when it is CA I want to use the CA validation. I see your example http://formvalidation.io/examples/switching-validators-same-field/ and that seems like it could work but that doesn't use the HTML5 attributes.  Do you know of a way of accomplishing this?  I tried switching out the country HTML5 attribute and that didn't work and I tried to disable the validation and re-enable it after changing the HTML5 attribute but that didn't seem to work either.

Thanks for any input you can provide.

**Comment by austinstudio** [comment]
Any help for this?  I am stumped on how to accomplish this with HTML5 attributes or if it is even possible.

Thank you.

**Comment by nghuuphuoc** [comment]
The validator option is NOT changed if you change the HTML attributes.
In this case, you should use the [dynamic option](http://formvalidation.io/settings/#dynamic-option)

```html
<select name="countryCode">
    <option value="CA">Canada</option>
    <option value="US">United State</option>
</select>

<input name="zipCode" data-fv-zipcode="true" data-fv-zipcode-country="countryCode" />
```

**Comment by austinstudio** [comment]
Thank you for the help.  I ended up using the standard method but it is really good to know that this can be done.  Hope it helps someone else.
