### ISSUE TITLE
resetForm() with bootstrap modal

### ISSUE THREAD

**Issue by medj** [formvalidation/support#144]
I would like to reset the validation of my form everytime a bootstrap modal window is opened. For example:

    $('#modal').on('show.bs.modal', function(){
        $('#form').data('formValidation').resetForm(true);
    });

This will reset the form values but will not reset the error messages.

If I use the 'shown' event rather than the 'show' event. Eg:

    $('#modal').on('shown.bs.modal', function(){
        $('#form').data('formValidation').resetForm(true);
    });

In this case, the validation will reset properly. But the problem now is that there is a brief time period (about a second) in which I see all the form validation errors before they disappear in front of me. Any idea why the validation messages won't disappear when using the 'show' event?

**Comment by nghuuphuoc** [comment]
The reason is that the `shown.bs.modal` event is fired when the modal has been made visible to the user (will __wait__ for CSS transitions to complete) (See http://getbootstrap.com/javascript/#modals-events)

**Comment by medj** [comment]
So what is the reason that I cannot use the resetForm method within the 'show' event? I would like to reset the form before the user sees the modal window. One clue is that it resets the values of the form but does not get rid of validation error messages.

**Comment by rodolfosouza** [comment]
I am in the same, other problem is tooltip does not work too, I am testing the example 


<p class="text-center">
    <button class="btn btn-default" id="test" data-toggle="modal" data-target="#loginModal">Login</button>
</p>

<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Login</h4>
            </div>

            <div class="modal-body">
                
                <form id="loginForm" method="post" class="form-horizontal">
                    <div class="form-group">
                        <label class="col-xs-3 control-label">Username</label>
                        <div class="col-xs-5">
                            <input type="text" class="form-control" name="username" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-3 control-label">Password</label>
                        <div class="col-xs-5">
                            <input type="password" class="form-control" name="password" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-5 col-xs-offset-3">
                            <button type="submit" class="btn btn-primary">Login</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <button type="button" class="btn btn-default" id="resetButton">Reset</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
	
	// Reset the Tooltip container form
    $('#resetButton').on('click', function(e) {
//     	$('#loginForm').each (function(){this.reset();});
        $('#loginForm').formValidation('resetForm', true);
    });	
    $('#test').on('click', function(e) {
    	$('#loginForm').each (function(){this.reset();});
        $('#loginForm').formValidation('resetForm', true);
    });
    
    $('#loginForm').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            username: {
            	err: 'tooltip',
                validators: {
                    notEmpty: {
                        message: 'The username is required'
                    }
                }
            },
            password: {
            	err: 'tooltip',
                validators: {
                    notEmpty: {
                        message: 'The password is required'
                    }
                }
            }
        }
    });
});
</script>

**Comment by rodolfosouza** [comment]
@medj I was with this problem but a simple solution is before close the "form" you call form reset, it's a workaround because I tried a lot of things and no solution

**Comment by medj** [comment]
I found a solution. I do the reset on modal "hide" instead.

$('#modal').on('hide.bs.modal', function(){
    $('#form').data('formValidation').resetForm(true);
});

**Comment by Liu-Huaqing** [comment]
@medj Thanks. I solve my problem during modal.hide event. But I do not know the root cause. I think this is a bug of formvalidation plugin.

**Comment by hddung89** [comment]
@medj Thanks, save my day.

**Comment by nikunjkansara** [comment]
` $('#form').data('formValidation').resetForm(true);` is giving me error like `undefind restForm() function` 

I am using the jQuery `1.10` and formValidator has requirement of `1.9`.

As of now I am using Jquery for reset form, but if anyone has idea how to resolve this error.

```
$('#signupForm')[0].reset();
$('#signupForm div').removeClass('has-error');
$('#signupForm .help-block').remove();
```

**Comment by Naveedulhassan** [comment]
This did the trick for me. Just use `empty()` method.

`$('#commander-modal').on('hidden.bs.modal', function () {
	$("#msgSubmit1").empty();
	$('#quoteform1')[0].reset();
	$('#quoteform1 div').removeClass('has-error');
	$('#quoteform1 .help-block').empty();
});`

**Comment by iscorporacion** [comment]
the correct solution is to use the hide.bs.modal event since the hidden.bs.modal event when executing all the fields becomes hidden and formavalidation ignores them

`$('#myModal').on('shown.bs.modal', function () {
            $(this).find("input:first-child").focus();
        }).on('hide.bs.modal', function (e) {
            $(this).find("form").formValidation('resetForm', true);
        })`
