### ISSUE TITLE
Angular Support?

### ISSUE THREAD

**Issue by sirwolfgang** [formvalidation/support#145]
I am currently trying to integrate the valiations with angular, and running into a few issues. Is there any documentation, or examples of someone getting it to work?

**Comment by sirwolfgang** [comment]
For anyone else that runs into this issue. I added my js `<script>` tag to the end of my page's template. Then in my controller where needed, I added
`$(form).formValidation('revalidateField', $('[name=attr]'));`

**Comment by jovana** [comment]
Dear @sirwolfgang,

Can you please give me more details on how you have manage to get this validator to work on AngularJS? I have now running version 1.4.3.

Please let me know, and many thanks for helping me out!

Kind regards,
Joël

**Comment by sirwolfgang** [comment]
Here is a long form version of the code I use. Not sure what more I can really say/show.
***

app/assets/javascripts/application.js
```javascript
function initializeFormValidation(){
  $('#item').formValidation({ ... });
  return true;
}

```

app/controllers/item_controller.js
```javascript
$timeout(function(){
  initializeFormValidation();
});

...

$timeout(function(){
  $('#item').formValidation('revalidateField', $('[name=width]'));
});
```

**Comment by jovana** [comment]
Thanks for sharing! I will take a look at this!

**Comment by jovana** [comment]
Where do you have "function initializeFormValidation", inside .run or .config (or outside angular files)?
I don't get it to work this way.

Thanks for your help.

**Comment by sirwolfgang** [comment]
It's just an a normal asset javascript non-angular file.

**Comment by san360** [comment]
Can some one share a working example? I cannot get it working
