### ISSUE TITLE
validating icon not working

### ISSUE THREAD

**Issue by brianlenz** [formvalidation/support#148]
Hello,

We are integrating formvalidation.io into our webapp, and it appears there is a bug that is preventing the validating icon from appearing properly. We are using the "remote" validator to do server-side validation via AJAX. I would expect the "validating" icon to appear during that process, but it is not. The AJAX check is working perfectly, but no icon appears until either the success/check or invalid/X appears.

FWIW, we are using FontAwesome, but that doesn't appear to be related. The validating CSS classes are being added to the icon, but then immediately they are being removed.

This appears to be the culprit in the updateStatus function:

```
                                $icon.addClass(isValidField === null
                                                ? ''
                                                : (isValidField ? this.options.icon.valid : (isValidating ? this.options.icon.validating : this.options.icon.invalid)))
                                    .show();
```

isValidating is true, but isValidField===null, so no class is being added.

We are using data-fv-remote-delay="500", but removing that doesn't seem to have any impact. Does the remote validator not support the validating icon? It seems to me that you'd always want the validating icon while the remote AJAX validation check is in process.

Am I missing something, or is this a bug?

Thanks in advance for any assistance you can provide!

Brian

**Comment by brianlenz** [comment]
Note that changing the above snippet to this seems to fix the issue:

```
                                $icon.addClass(isValidating ? this.options.icon.validating : (isValidField === null
                                                ? ''
                                                : (isValidField ? this.options.icon.valid : this.options.icon.invalid)))
                                    .show();
```

Is this a bug that needs to be fixed?

**Comment by nghuuphuoc** [comment]
Thank for reporting the issue.
You're right! Changing the above snippet fixes the issue.

```javascript
if (status === this.STATUS_VALID || numIgnored !== $allErrors.length) {
    $icon.addClass(isValidating
                    ? this.options.icon.validating
                    : (isValidField === null ? '' : (isValidField ? this.options.icon.valid : this.options.icon.invalid)))
         .show();
}
```

This fix will be available in the next v0.6.3 :+1:

**Comment by nghuuphuoc** [comment]
You might try the current workaround, place the `remote` validator at the end of validators.

For example:

```javascript
$('#defaultForm').formValidation({
    icon: {
        valid: 'glyphicon glyphicon-ok',
        invalid: 'glyphicon glyphicon-remove',
        validating: 'glyphicon glyphicon-refresh'
    },
    fields: {
        username: {
            message: 'The username is not valid',
            validators: {
                notEmpty: {
                    message: 'The username is required and can\'t be empty'
                },
                stringLength: {
                    min: 5,
                    message: '...'
                },
                remote: {
                    type: 'POST',
                    url: 'remote.php',
                    message: 'The username is not available',
                    delay: 5000
                }
            }
        }
    }
});
```

**Comment by brianlenz** [comment]
Hi Phuoc,

Thanks for the confirmation. We are currently using the declarative syntax, so almost all of our configuration is handled via HTML5 attributes. Because of that, we'll probably just wait until the 0.6.3 release is out. Here's a sample code snippet with the structure of our HTML using the remote:

```
<input id="xyz" type="text" name="xyz" maxlength="255" value="" required data-fv-notempty-message="ID is required." data-fv-stringlength data-fv-stringlength-trim="true" data-fv-stringlength-message="ID must be at most 255 characters." data-fv-remote data-fv-remote-url="http://example.com/check-id" data-fv-remote-name="id" data-fv-remote-delay="500" data-fv-remote-data="{&quot;sample&quot;:&quot;true&quot;}" />
```

As you can see, the remote is configured last in the attributes. I'm guessing the attributes just aren't processed in order, which is why the declarative equivalent of your workaround doesn't work?

Do you have an ETA for the 0.6.3 release as of yet?

Is there a place for us to monitor for new releases so we can be notified? E.g. RSS feed somewhere or email subscription? And is there a changelog?

Thank you for the great product!

**Comment by nghuuphuoc** [comment]
> As you can see, the remote is configured last in the attributes. I'm guessing the attributes just aren't processed in order, which is why the declarative equivalent of your workaround doesn't work?

Yes, it will NOT work.

> Do you have an ETA for the 0.6.3 release as of yet?

The v0.6.3 will be released in the next few days. I was going to release it a few days ago, but see this issue today, so it will be delayed a little bit.

> Is there a place for us to monitor for new releases so we can be notified?

You can follow FV on [Twitter](https://twitter.com/formvalidation/) or [Facebook](https://www.facebook.com/formvalidation/).
I also will let you know when v0.6.3 is available (at the same time this issue is closed).

> And is there a changelog?

Yes, of course. For example, this is change log of [v0.6.2](http://formvalidation.io/news/v0.6.2-released/).

**Comment by brianlenz** [comment]
Perfect, thanks!

**Comment by nghuuphuoc** [comment]
[v0.6.3](http://formvalidation.io/news/v0.6.3-released/) is out. You can use the previous download link to get the new version.
