### ISSUE TITLE
Identify and collect data from form where submit button was clicked

### ISSUE THREAD

**Issue by vjitweb** [formvalidation/support#15]
Hello

I have multiple forms with the same id and now I need to get only the data from the form from where the user clicked the submit button. Is that possible from inside the `.on('success.form.bv', function(e) {}` function?

/Peter Larsen

**Comment by nghuuphuoc** [comment]
Using same ```id``` attribute for multiple forms or elements on same page should be avoided. ```id``` attribute must be unique.
I am not sure the plugin works in that case.
