### ISSUE TITLE
Integer validator should accept leading zeros

### ISSUE THREAD

**Issue by brunchboy** [formvalidation/support#151]
When I changed one of our web applications to use input type=number for our two-factor authentication tokens, so that mobile users would be conveniently presented with the number keyboard and have an easier time entering their token, suddenly people were unable to enter tokens which had leading zeroes. These are valid TOTP tokens, and are accepted by the HTML5 validator, so they should be accepted by the integer validator as well.

For now, I have worked around this problem by simply disabling the integer validator for this field, but we can save other people this research project by generally accepting leading zeros, or at least having an option to do so.

**Comment by MB34** [comment]
I believe that TOTP tokens are supposed to be of string type.

**Comment by brunchboy** [comment]
However, in order to let users on iOS and Android devices conveniently enter them, without having to go to the extra step of selecting a numeric keyboard, it is necessary to set the HTML input type to "number". This causes it to be impossible to enter valid tokens with leading zeros because a numeric validator is automatically attached, and it rejects such tokens, even though the form itself accepts them.

**Comment by MB34** [comment]
Then you are going to have to use the events to take the number and convert it to a string to validate.
Validating a TOTP hash requires it to be a certain length so you will have to pad it to the length with zeros.

**Comment by brunchboy** [comment]
I think I failed to express myself properly. I don’t need to validate anything on the client side; the TOTP validation is performed cryptographically on the server, which has access to the necessary secret seed. The problem I encountered was that form validation suddenly and unexpectedly stopped letting my users submit some valid TOTP codes when I simply changed the HTML type of the input field in order to save them a step in selecting a numeric keyboard on their mobile devices.

I solved this by figuring out how to explicitly disable the integer validator, but I was hoping for a way to help future developers avoid this surprise and confusion by either having the default behavior of this validator change, or perhaps more prominently documenting this issue and perhaps adding support for this use case through some decoration which identifies the number input as a TOTP input, so the integer validator is either reconfigured or automatically disabled in such cases.

**Comment by nghuuphuoc** [comment]
The current workaround is that you can use the `type="number"` and the [transformer](http://formvalidation.io/settings/#validator-transformer) option:

```javascript
$(form).formValidation({
    fields: {
        token: {
            validators: {
                integer: {
                    message: '...',
                    transformer: function($field, validatorName, validator) {
                        // Get the field value
                        var value = $field.val();

                        // If it starts with zero
                        while (value.charAt(0) + '' === '0') {
                            // then strip the zero
                            value = value.substr(1);
                        }

                        if (value === '') {
                            value = '0';
                        }

                        // Return new value
                        return value;
                    }
                }
            }
        }
    }
});
```

The `transformer` option is useful when you want to allow more special formats for many validators.
See http://formvalidation.io/examples/modifying-value-before-validating/

**Comment by brunchboy** [comment]
Ok, thanks, that looks like a great way to do it. I would suggest adding it as an example to the documentation for people who are in a similar situation.

**Comment by nghuuphuoc** [comment]
@brunchboy 
The latest [v0.7.0](http://formvalidation.io/news/v0.7.0-released/) is released. Now the [integer](http://formvalidation.io/validators/integer/) validator accepts leading zeros by default. You don't need to do anything.
You can use the previous download link to grab new version.

![integer validator](https://cloud.githubusercontent.com/assets/4226036/9034809/c8b59ae2-39fc-11e5-8c22-b0667e4e236f.png)

**Comment by brunchboy** [comment]
Nice, that will save people some surprises in the future. Thank you.
