### ISSUE TITLE
API calls not working in some cases

### ISSUE THREAD

**Issue by medj** [formvalidation/support#152]
Can anyone think of a reason why API calls won't work in certain cases? Here's an excerpt of my code:

    var formvalidation = form.data('formValidation');
    formvalidation.addField('uploader', { validators: {
        callback: {
            // The error message
            message: 'There is a problem',
            callback: function(value, validator, $field) {
                alert('validatinguploader');
                return true;
            }
        }
    }});

    formvalidation.validateField('uploader;);

    var callback = function(error) {
        console.log(formvalidation);
        formvalidation.validateField('uploader');
    });

The first time I validateField, I get an alert. When I try running the callback() function, I don't get an alert. I know the callback runs and that the formvalidation object is available in the callback function since I see it being logged in the console. Why wouldn't the validateField work within the callback? Any ideas? Some kinda scope issue?

**Comment by medj** [comment]
I solved my problem by re-adding the field validator before validating it in the callback. Doesn't seem like the right solution, but it works for now.

**Comment by nghuuphuoc** [comment]
If the field is already validated (by calling the `validateField` method), then it will be ignored the second time you call the method. It is for improving the performance of validation process.

You should call the [revalidateField](http://formvalidation.io/api/#revalidate-field) method instead:

```javascript
var callback = function(error) {
    console.log(formvalidation);
    formvalidation.revalidateField('uploader');
});
```
