### ISSUE TITLE
The function 'resetForm' doesn't work in close modal

### ISSUE THREAD

**Issue by r3nan** [formvalidation/support#153]
I tried a implementation that reset form on close funcion of bootstrap modal.

My code:
$('.modal.resetable').on('hidden.bs.modal', function () {
$(this).find('form').formValidation('resetForm', true);
});

But, its doesn't work.

However, if i change 'hidden.bs.modal' to 'shown.bs.modal' it's work well. But i think is a ugly because the user can see the form reseting. It's more usefull do this in close function because when the user open a modal, it showed without validation.

**Comment by nghuuphuoc** [comment]
Does [this](https://github.com/formvalidation/support/issues/144#issuecomment-102054394) work?

**Comment by r3nan** [comment]
Only if i use on 'shown.bs.modal'. If i use on 'hidden.bs.modal', it does not work

**Comment by Arkni** [comment]
@r3nan 
See http://jsfiddle.net/Arkni/ndpv76bk/

**Comment by r3nan** [comment]
It doesn't work for me. =(

But thanks. With it, i could see that the blame is to framework that i'm using.

**Comment by Arkni** [comment]
@r3nan 

If you read the code of the fiddle, you will notice that I'm used
```js
excluded: ':disabled'
```
In order to make it possible for formvalidation to reset your form.

**Comment by r3nan** [comment]
This it is!!! Work for me now! Thanks a lot!

could you explain me? Please.

**Comment by nghuuphuoc** [comment]
After the model is hidden, all fields inside it are not visible. By default, the plugin will ignore disabled, hidden and inivisible fields when validating and reseting them.
Setting `excluded: ':disabled'` will just ignore disabled fields only.

You can look at the [excluded](http://formvalidation.io/settings/#form-excluded) option for more information.

Thanks both of you!!!

**Comment by r3nan** [comment]
Thanks for the explanation. =D My modal is so beautiful now rsrs
