### ISSUE TITLE
Form is validating but not sending

### ISSUE THREAD

**Issue by mravani** [formvalidation/support#154]
Hi! The live validation is ok, but when I click 'submit', nothing happens. If I disable formvalidation plugin, everything works.

Here is my page form:

```php
<?php
${(require_once('SimpleAuth.php'))}->protectme(array(
    'logoutPage' => './'
));
?>
<!DOCTYPE html>
<html>

<head>

  <?php include ('includes/head.php'); ?>
<div class="all-wrapper">
  <div class="row">
    <?php include ('includes/menu-lateral.php'); ?>
    <div class="col-md-9">
    <!-- Conexão com o Banco de Dados -->
        <?php
            $idInscrito = (isset($_GET["id"])) ? $_GET["id"] : "1";
            $Select = "SELECT * FROM tb_inscricoes WHERE id=". $idInscrito;
            $Inscritos = mysql_query($Select);
            
        ?>
      <div class="content-wrapper">
        <div class="content-inner">
          <div class="page-header page-header-blue">
  <div class="header-links hidden-xs">
    <!--<a href="notifications.html"><i class="icon-comments"></i> User Alerts</a>
    <a href="#"><i class="icon-cog"></i> Settings</a>-->
    Bem-vindo, <?php echo $simpleAuthInstance->getMetas("name");?><a href="?simple_auth_action=logout"><i class="icon-signout"></i> Logout</a>
  </div>
  <h1><i class="icon-file-text"></i> Ficha Cadastral - SebraeUp</h1>
</div>
          <div class="main-content">
          <?php while($Listagem = mysql_fetch_array($Inscritos)) {              ?>
            <div class="widget">              
            </div>
            <div class="widget" id="area_chart_anchor">
              <h3 class="section-title"><i class="icon-user"></i> <?php echo $Listagem['nome'] . " ( " . $Listagem['cpf'] . " )" . " - " . "<span style='color:#2980b9;'>" . $Listagem['emp_nome'] . "</span>"; ?></h3>
               <div class="form-group">
               <form id="formNotas" action="includes/salvar-nota.php?id=<?php echo $idInscrito; ?>&user=<?php echo $simpleAuthInstance->getLogin(); ?>" method="post">
              <div class="widget-content-white">                  
                <div class="shadowed-bottom">
                  <div class="row">
                    <div class="col-lg-5 col-md-3 visible-md visible-lg bordered">
                      <div class="value-block text-center">
                        <div class="value-self"><?php echo $Listagem['emp_endereco_empresa']; ?></div>
                        <div class="value-sub">Endereço da Empresa</div>
                      </div>
                    </div>
                    <?php
                        $Classificacao = '';
                        $Classificacao1 = $Listagem['sabe_seu_negocio']+$Listagem['validou_sua_ideia']+$Listagem['possui_cnpj'];
                        $Classificacao2 = $Listagem['possui_receita']+$Listagem['sabe_mvp']+$Listagem['possui_definicoes_estrategicas'];
                        $Classificacao3 = $Listagem['participa_de_eventos']+$Listagem['realiza_mentoria']+$Listagem['participa_de_eventos_parcerias'];

                        if($Classificacao3>=2){
                          $Classificacao = 'Tração';
                        }elseif($Classificacao2>=2 OR $Classificacao3<2){
                          $Classificacao = 'Operação';
                        }elseif($Classificacao1>=2 OR $Classificacao2<2){
                          $Classificacao = 'Ideação';
                        }elseif ($Classificacao1<2) {
                          $Classificacao = 'Curiosidade';
                        }
                    ?>
                    <div class="col-lg-2 col-md-3 visible-md visible-lg bordered">
                      <div class="value-block text-center">
                        <div class="value-self"><?php echo $Classificacao; ?></div>
                        <div class="value-sub">Classificação</div>
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-3 visible-md visible-lg bordered">
                      <div class="value-block text-center">
                        <div class="value-self"><?php echo $Listagem['emp_atividade_economica']; ?></div>
                        <div class="value-sub">Atividade Econômica</div>
                      </div>
                    </div>
                    <div class="col-lg-2 visible-lg">
                      <div class="value-block text-center">
                        <div class="value-self"><?php echo $Listagem['emp_abertura_empresa']; ?></div>
                        <div class="value-sub">Data de Abertura</div>
                      </div>
                    </div>
                    
                  </div>
                </div>
                <div class="padded">
                                                        
                            <h4>2. Capacidade de implantar o projeto</h4>
                            <hr>
                            
                            <div class="form-group">
                               <span class="label_nota">Equipe</span>
                               <div class="col-xs-12">
                                    <div class="resposta"><?php echo $Listagem['equipe']; ?></div>
                                </div>
                            </div>
                            <label class="control-label left custom_label">Sua nota para EQUIPE:</label><br>
                            <input type="text" size="5" class="form-control left custom_nota" name="avaliacao[equipe]" value="" /><br />
                            
                            <h4>3. Grau de inovação do Modelo de negócio, produto ou serviço inovador</h4>
                            <h7>O novo modelo de negócio, produto ou serviço precisa ser novo para o mercado Brasileiro ou significativamente melhorado em relação aos modelos existentes.</h7>
                            <hr>
                            
                            <div class="form-group">
                               <span class="label_nota">Proposta de Valor</span>
                               <div class="col-xs-12">
                                    <div class="resposta"><?php echo $Listagem['proposta_de_valor']; ?></div>
                                </div>
                            </div>
                            <label class="control-label left custom_label">Sua nota para PROPOSTA DE VALOR:</label><br>
                            <input type="text" size="5" class="form-control left custom_nota" name="avaliacao[proposta_de_valor]" value="" /><br />
                            
                            <div class="form-group">
                               <span class="label_nota">Diferenciação</span>
                               <div class="col-xs-12">
                            <div class="resposta"><?php echo $Listagem['diferenciacao']; ?></div>
                                </div>
                            </div>
                            <label class="control-label left custom_label">Sua nota para DIFERENCIAÇÃO:</label><br>
                            <input type="text" size="5" class="form-control left custom_nota" name="avaliacao[diferenciacao]" value="" /><br />
                            
                            <h4>4. Potencial Tecnológico</h4>
                            <small>Será avaliado viabilidade de implantação do novo modelo de negócio, produto ou serviço e sua produção/funcionamento para o mercado em que atuará (estadual/nacional/mundial).</small>
                            <hr>
                            
                            
                            <div class="form-group">
                               <span class="label_nota">Escalabilidade</span>
                               <div class="col-xs-12">
                                    <div class="resposta"><?php echo $Listagem['escalabilidade']; ?></div>
                                </div>
                            </div>
                            <label class="control-label left custom_label">Sua nota para ESCALABILIDADE:</label><br>
                            <input type="text" size="5" class="form-control left custom_nota" name="avaliacao[escalabilidade]" value="" /><br />
                            
                            
                            <div class="form-group">
                               <span class="label_nota">Etapas de Desenvolvimento</span>
                               <div class="col-xs-12">
                                    <div class="resposta"><?php echo $Listagem['etapas_de_desenvolvimento']; ?></div>
                                </div>
                            </div>
                            <label class="control-label left custom_label">Sua nota para ETAPAS DE DESENVOLVIMENTO:</label><br>
                            <input type="text" size="5" class="form-control left custom_nota" name="avaliacao[etapas_de_desenvolvimento]" value="" /><br />
                            
                            <h4>5. Potencial de Mercado</h4>
                            <small>Serão avaliados evidencias que o produto vai atender uma necessidade de mercado.</small>
                            <hr>
                            
                            
                            <div class="form-group">
                               <span class="label_nota">Canais de Comercialização</span>
                               <div class="col-xs-12">
                                    <div class="resposta"><?php echo $Listagem['canais_de_comercializacao']; ?></div>
                                </div>
                            </div>
                            <label class="control-label left custom_label">Sua nota para CANAIS DE COMERCIALIZAÇÃO:</label><br>
                            <input type="text" size="5" class="form-control left custom_nota" name="avaliacao[canais_de_comercializacao]" value="" /><br />
                            
                            <div class="form-group">
                               <span class="label_nota">Relevância para o mercado/sociedade</span>
                               <div class="col-xs-12">
                                    <div class="resposta"><?php echo $Listagem['relevancia_mercado']; ?></div>
                                </div>
                            </div>
                            <label class="control-label left custom_label">Sua nota para RELEVÂNCIA PARA O MERCADO/SOCIEDADE:</label><br>
                            <input type="text" size="5" class="form-control left custom_nota" name="avaliacao[relevancia_mercado]" value="" /><br />
                            
                            <h4>6. Contexto Econômico</h4>
                            <small>Será avaliado qual o impacto da solução na vida das pessoas e a relação com o contexto produtivo.</small>
                            <hr>
                            
                            <div class="form-group">
                               <span class="label_nota">Alinhamento com a economia local, nacional e/ou internacional</span>
                               <div class="col-xs-12">                            
                                    <div class="resposta"><?php echo $Listagem['alinhamento_economia']; ?></div>
                                </div>
                            </div>
                            <label class="control-label left custom_label">Sua nota para ALINHAMENTO COM A ECONOMIA LOCAL:</label><br>
                            <input type="text" size="5" class="form-control left custom_nota" name="avaliacao[alinhamento_economia]" value="" /><br />
                            
                            <h4>7. Envolvidos no Projeto</h4>
                            <small>Serão avaliados se estão claras e bem definidos, se há evidencias nas definições dos envolvidos no Projeto.</small>
                            <hr>
                            
                            
                            <div class="form-group">
                               <span class="label_nota">Público Alvo</span>
                               <div class="col-xs-12">
                                    <div class="resposta"><?php echo $Listagem['publico_alvo']; ?></div>
                                </div>
                            </div>
                            <label class="control-label left custom_label">Sua nota para PÚBLICO ALVO:</label><br>
                            <input type="text" size="5" class="form-control left custom_nota" name="avaliacao[publico_alvo]" value="" /><br />
                            
                            
                            <div class="form-group">
                               <span class="label_nota">Concorrentes</span>
                               <div class="col-xs-12">
                                    <div class="resposta"><?php echo $Listagem['concorrentes']; ?></div>
                                </div>
                            </div>
                            <label class="control-label left custom_label">Sua nota para CONCORRENTES:</label><br>
                            <input type="text" size="5" class="form-control left custom_nota" name="avaliacao[concorrentes]" value="" /><br />
                            
                            <h4>8. Potencial de Produção</h4>
                            <h7>Serão avaliados fatores e projeção de valores previstos.</h7>
                            <hr>
                            
                            
                            <div class="form-group">
                               <span class="label_nota">Formas de consumo e produção</span>
                               <div class="col-xs-12">
                                    <div class="resposta"><?php echo $Listagem['formas_de_consumo']; ?></div>
                                </div>
                            </div><label class="control-label left custom_label">Sua nota para FORMAS DE CONSUMO E PRODUÇÃO:</label><br>
                            <input type="text" size="5" class="form-control left custom_nota" name="avaliacao[formas_de_consumo]" value="" /><br />
                            
                            
                            <div class="form-group">
                               <span class="label_nota">Valores de Investimentos</span>
                               <div class="col-xs-12">
                                    <div class="resposta"><?php echo $Listagem['valores_de_investimentos']; ?></div>
                                </div>
                            </div>
                            <label class="control-label left custom_label">Sua nota para VALORES DE INVESTIMENTOS:</label><br>
                            <input type="text" size="5" class="form-control left custom_nota" name="avaliacao[valores_de_investimentos]" value="" /><br />
                            
                            
                            <div class="form-group">
                               <span class="label_nota">Projeção de Receitas</span>
                               <div class="col-xs-12">
                                    <div class="resposta"><?php echo $Listagem['projecao_de_receitas']; ?></div>
                                </div>
                            </div>
                            <label class="control-label left custom_label">Sua nota para PROJEÇÃO DE RECEITAS:</label><br>
                            <input type="text" size="5" class="form-control left custom_nota" name="avaliacao[projecao_de_receitas]" value="" /><br />
                              
                            </div><br><br>
              <?php } ?>
              </div>
                      
            </div>
          </div>
         
          <button type="submit" name="submitButton" class="btn btn-primary">Submit</button>
          </form>
        </div>
            </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>
<?php include('includes/footer.php'); ?>

</body>

</html>
```

The validation file:
```php
<script>
$(document).ready(function() {
    $('#formNotas').formValidation({
        framework: 'bootstrap',
        
        live: 'enabled',
        trigger: null,
        autoFocus: true,
        icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
        fields: {
            'avaliacao[equipe]': {
            <?php include('includes/validation-rules.php'); ?>
            },

            'avaliacao[proposta_de_valor]': {
            <?php include('includes/validation-rules.php'); ?>
            },

            'avaliacao[diferenciacao]': {
            <?php include('includes/validation-rules.php'); ?>
            },

            'avaliacao[escalabilidade]': {
            <?php include('includes/validation-rules.php'); ?>
            },

            'avaliacao[etapas_de_desenvolvimento]': {
            <?php include('includes/validation-rules.php'); ?>
            },

            'avaliacao[canais_de_comercializacao]': {
            <?php include('includes/validation-rules.php'); ?>
            },

            'avaliacao[relevancia_mercado]': {
            <?php include('includes/validation-rules.php'); ?>
            },

            'avaliacao[alinhamento_economia]': {
            <?php include('includes/validation-rules.php'); ?>
            },

            'avaliacao[publico_alvo]': {
            <?php include('includes/validation-rules.php'); ?>
            },

            'avaliacao[concorrentes]': {
            <?php include('includes/validation-rules.php'); ?>
            },

            'avaliacao[formas_de_consumo]': {
            <?php include('includes/validation-rules.php'); ?>
            },

            'avaliacao[valores_de_investimentos]': {
            <?php include('includes/validation-rules.php'); ?>
            },

            'avaliacao[projecao_de_receitas]': {
            <?php include('includes/validation-rules.php'); ?>
            },



        }
    });
});
</script>
```

And the validation rules include:

```php
validators: {
                    notEmpty: {
                        message: 'Você precisa preencher uma nota'
                    },
                    regexp: {
                        regexp: /^[0-9]+$/,
                        message: 'São permitidos apenas números'
                    },
                    stringLength: {
                        max: 2,
                        message: 'Valor inválido'
                    },
                    between: {
                        min: 0,
                        max: 10,
                        message: 'Sua nota precisa ser entre 1-10'
                    }
                }
```

Live validation working:
![worksfine2](https://cloud.githubusercontent.com/assets/6933922/7828819/1d514476-040f-11e5-8d3f-03925717d604.JPG)
Live validation working
![worksfine](https://cloud.githubusercontent.com/assets/6933922/7828820/1d531db4-040f-11e5-8177-b49f774dff71.JPG)

**Comment by nghuuphuoc** [comment]
I think the problem is caused by having multiple forms with the same Id created by the `while` loop:

```javascript
<?php while($Listagem = mysql_fetch_array($Inscritos)) { ?>
...
<form id="formNotas" action="includes/salvar-nota.php?id=<?php echo $idInscrito; ?>&user=<?php echo $simpleAuthInstance->getLogin(); ?>" method="post">
...
<?php } ?>
```

In this case, I think you should add a CSS class to the form:

```javascript
<?php while($Listagem = mysql_fetch_array($Inscritos)) { ?>
...
<form class="formNotasClass" ...>
...
<?php } ?>
```

and calling validation on all of these forms:

```javascript
$(document).ready(function() {
    $('.formNotasClass').formValidation({
        ...
    });
});
```

**Comment by mravani** [comment]
Thank you, nghuuphuoc, but doesn't work :(

First I change the class... then, remove the while and still not working :(

This may help:
![help](https://cloud.githubusercontent.com/assets/6933922/7840793/743fc9aa-046f-11e5-87af-a2fbfb27fa01.JPG)

**Comment by mravani** [comment]
No one? :(

**Comment by nghuuphuoc** [comment]
It's really strange. The frequent reason causing the form [can't be submitted](http://formvalidation.io/examples/cant-submit-form-after-validation/) is that the submit button has `name="submit"`. But your submit button has valid `name` attribute.

You can try the following snippet:

```javascript
$('.formNotasClass')
    .formValidation({
        ...
    })
    .on('success.form.fv', function(e) {
        e.preventDefault();
        $(e.target).formValidation('defaultSubmit');
    });
```

**Comment by scs-ben** [comment]
I am experiencing a similar issue, nothing I do can make it submit on first click:
```
<h3>Vendor Information</h3>

<form class="form-horizontal" role="form" id="vendor" method="post" action="{{ route('vendor.modify.vendor.post', $vendor->id) }}">
	<input type="hidden" name="_token" value="{{ csrf_token() }}" />
	<input type="hidden" name="id" value="{{ $vendor->id }}" />
	<div class="row">
		<div class="col-md-6">
    		<div class="form-group">
				<label for="name" class="col-sm-3 control-label">Vendor</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="name" value="{{$vendor->name}}" placeholder="Vendor Name" />
				</div>
			</div>
		</div>
		<div class="col-md-6">
			&nbsp;
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<label for="street_1" class="col-sm-3 control-label">Street 1</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="street_1" value="{{$vendor->street_1}}" placeholder="Street" />
				</div>
			</div>
			<div class="form-group">
				<label for="street_2" class="col-sm-3 control-label">Street 2</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="street_2" value="{{$vendor->street_2}}" placeholder="Secondary Street" />
				</div>
			</div>
			<div class="form-group">
				<label for="city" class="col-sm-3 control-label">City</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="city" value="{{$vendor->city}}" placeholder="City">
				</div>
			</div>
			<div class="form-group">
				<label for="state" class="col-sm-3 control-label">State &amp; Zip</label>
				<div class="col-sm-2">
					<input type="text" class="form-control" name="state" value="{{$vendor->state}}" placeholder="State">
				</div>
				<div class="col-sm-4">
					<input type="text" class="form-control" name="zip" value="{{$vendor->zip}}" placeholder="Zip">
				</div>
			</div>
			<div class="form-group">
				<label for="country" class="col-sm-3 control-label">Country</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="country" value="{{$vendor->country}}" placeholder="Country">
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group">
				<label for="phone" class="col-sm-3 control-label">Phone</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="phone" value="{{$vendor->phone}}" placeholder="Phone">
				</div>
			</div>
			<div class="form-group">
				<label for="fax" class="col-sm-3 control-label">Fax</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="fax" value="{{$vendor->fax}}" placeholder="Fax">
				</div>
			</div>
			<div class="form-group">
				<label for="website" class="col-sm-3 control-label">Website</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="website" value="{{$vendor->website}}" placeholder="Website">
				</div>
			</div>
		</div>
	</div>
	
	<div class="clearfix">
		<button class="pull-right btn btn-primary" id="submit_vendor" name="submit_vendor" type="submit">Save</button>
		<a class="pull-right btn btn-default" href="{{ URL::previous() }}">Cancel</a>
	</div>
	
</form>

@section('javascript')
@parent

<script>
	$('#vendor').formValidation({
    	framework: 'bootstrap',
	    icon: {
	        valid: 'fa fa-check',
	        invalid: 'fa fa-exclamation-triangle',
	        validating: 'fa fa-refresh'
	    },
	    fields: {
            name: {
            	validators: {
	                notEmpty: {
	                    message: 'Vendor name is required'
	                }
                }
            },
            street_1: {
            	validators: {
	                notEmpty: {
	                    message: 'Vendor name is required'
	                }
                }
            },
            city: {
            	validators: {
	                notEmpty: {
	                    message: 'City is required'
	                }
                }
            },
            state: {
            	validators: {
            		notEmpty: {
            			message: 'State is required'
            		}
            	}
            },
            zip: {
            	validators: {
            		zipCode: {
                        country: 'US',
                        message: 'The value is not valid %s postal code'
                    }
            	}
            },
            country: {
            	validators: {
	            	notEmpty: {
	            		message: 'Country is required'
	            	}
            	}
            },
            phone: {
            	validators: {
	            	notEmpty: {
	            		message: 'Phone is required'
	            	}
            	}
            },
            fax: {
            	validators: {
            		phone: {
                        country: 'US',
                        message: 'The value is not valid %s fax number'
                    }
            	}
            },
            website: {
            	validators: {
                    regexp: {
                    	regexp: /^((http|https|ftp):\/\/)?([A-Z0-9][A-Z0-9_-]*(?:\.[A-Z0-9][A-Z0-9_-]*)+):?(\d+)?\/?/i,
                        message: 'The website address is not valid'
                    }
           		}
            }
    	}
 	}).on('success.form.fv', function(e) {
        e.preventDefault();
        vendorForm.defaultSubmit();
    });
 	
 var vendorForm = $('#vendor').data('formValidation');
```

**Comment by nghuuphuoc** [comment]
@scs-ben 
I tried the exact form on my environment:

![form data](https://cloud.githubusercontent.com/assets/4226036/7951877/3cd3cc7e-09d7-11e5-90ab-8de3cc70852c.png)

and here is what I got after pressing the Submit button:

```
Array
(
    [_token] => {{ csrf_token() }}
    [id] => {{ $vendor->id }}
    [name] => Just a name
    [street_1] => Street 1
    [street_2] => Street 2
    [city] => New York
    [state] => {{1$1vendor->state}}
    [zip] => 0123
    [country] => US
    [phone] => 0123456789
    [fax] => 0123456789
    [website] => http://domain.co
    [submit_vendor] => 
)
```

Does the page have only one one `id="vendor"` element?

**Comment by scs-ben** [comment]
I had verified only one form with the id, but failed to check the parent page for conflicting id's.

Sorry for my hasty post. I had a div with id="vendor".

Maybe the original posting person has a similar issue?

**Comment by nghuuphuoc** [comment]
@scs-ben 
Thank for your confirmation. The [Can't submit form after validation](http://formvalidation.io/examples/cant-submit-form-after-validation/) example is now updated that covers some check list to avoid this issue.

**Comment by scs-ben** [comment]
This is a way to detect and warn about duplicate ID's:
```
 var formValidation = $('#id').data('formValidation');
 
if ($('[id='+formValidation.$form.attr('id')+']').length > 1) {
    console.error('Form Validation will have problems, duplicate IDs detected!');
}
```

**Comment by nghuuphuoc** [comment]
Thank @scs-ben :+1: 
It's good idea to make an add-ons to detect all these problems. I will think about it.

**Comment by SigalZ** [comment]
I have the same problem.
The id is not duplicated. Validation are done but the form is not submitted.

For some reason I could not display the form code here, the id of the form is checkoutForm
My html:
`
            <div class="row">
                <div class="col-md-12">
                    
                    <div class="form-group">
                        <label>First Name</label>
                        <p class="form-control-static">Sigal
                        <input type="hidden" name="customer_first_name" value="Sigal"></p>
                    </div>
                    <div class="form-group">
                        <label>Surname</label>
                        <p class="form-control-static">Zahavi
                        <input type="hidden" name="customer_surname" value="Zahavi"></p>
                    </div>
                    <div class="form-group">
                        <label for="customerEmail">Email (Will be used to email you the invoice)</label>
                        <input type="text" name="customer_email" id="customerEmail" class="form-control" value="sigalzahav@gmail.com">
                    </div>
                    <div class="form-group">
                        <label for="phone">Phone Number</label>
                        <input type="text" name="customer_phone" id="phone" class="form-control phone" autocomplete="off" value="(083) 289-5280">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <p><b>Billing Address</b></p>
                    <div class="blockContent">
                        <div class="form-group addr">
                            <label for="bAddr1">Address Line 1</label>
                            <input type="text" name="b_addr_line_1" id="bAddr1" class="form-control" value="Line 1">
                        </div>
                        <div class="form-group">
                            <label for="bAddr2">Address Line 2</label>
                            <input type="text" name="b_addr_line_2" id="bAddr2" class="form-control" value="Line 2">
                        </div>
                        <div class="form-group addr">
                            <label for="bSuburb">Suburb</label>
                            <input type="text" name="b_suburb" id="bSuburb" class="form-control" value="Suburb">
                        </div>
                        <div class="form-group addr">
                            <label for="bCity">City</label>
                            <input type="text" name="b_city" id="bCity" class="form-control" value="Clarens">
                        </div>
                        <div class="form-group listselect" id="bProvinceDiv">
                            <label for="bProvince">Province</label><br>
                            <select name="b_province" id="bProvince" class="list" style="width: 60%">
                                <option value="">Select...</option><option value='Eastern Cape'>Eastern Cape</option><option value='Free State' selected>Free State</option><option value='Gauteng'>Gauteng</option><option value='KwaZulu-Natal'>KwaZulu-Natal</option><option value='Limpopo'>Limpopo</option><option value='Mpumalanga'>Mpumalanga</option><option value='Northern Cape'>Northern Cape</option><option value='North West'>North West</option><option value='Western Cape'>Western Cape</option>
                            </select>
                        </div>
                        <div class="form-group addr">
                            <label for="bPostCode">Post Code</label>
                            <input type="text" name="b_post_code" id="bPostCode" class="form-control" style="width:100px" value="9707">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <p><b>Shipping Address</b></p>
                    <div class="blockContent">
                        <div class="checkbox checkbox-warning">
                            <input id="same" type="checkbox">
                            <label for="same">Same as Billing Address</label>
                        </div>
                        <div class="form-group addr">
                            <label for="sAddr1">Address Line 1</label>
                            <input type="text" name="s_addr_line_1" id="sAddr1" class="form-control" value="Line 1">
                        </div>
                        <div class="form-group">
                            <label for="sAddr2">Address Line 2</label>
                            <input type="text" name="s_addr_line_2" id="sAddr2" class="form-control" value="Line 2">
                        </div>
                        <div class="form-group addr">
                            <label for="sSuburb">Suburb</label>
                            <input type="text" name="s_suburb" id="sSuburb" class="form-control" value="Suburb">
                        </div>
                        <div class="form-group addr">
                            <label for="sCity">City</label>
                            <input type="text" name="s_city" id="sCity" class="form-control" value="Clarens">
                        </div>
                        <div class="form-group listselect" id="sProvinceDiv">
                            <label for="sProvince">Province</label><br>
                            <select name="s_province" id="sProvince" class="list" style="width: 60%">
                                <option value="">Select...</option><option value='Eastern Cape'>Eastern Cape</option><option value='Free State' selected>Free State</option><option value='Gauteng'>Gauteng</option><option value='KwaZulu-Natal'>KwaZulu-Natal</option><option value='Limpopo'>Limpopo</option><option value='Mpumalanga'>Mpumalanga</option><option value='Northern Cape'>Northern Cape</option><option value='North West'>North West</option><option value='Western Cape'>Western Cape</option>
                            </select>
                        </div>
                        <div class="form-group addr">
                            <label for="sPostCode">Post Code</label>
                            <input type="text" name="s_post_code" id="sPostCode" class="form-control" style="width:100px" value="9707">
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <a href='/index.php?page=view_shop_products' class="btn btn-default" id="continueBtn">Continue Shopping</a>
                </div>
                <div class="col-md-6" style="text-align: right">
                    <button type="submit" class="btn btn-success">Checkout</button>
                </div>
            </div>
        </form>`

My code:
`$('#checkoutForm')
        .formValidation({
            framework: 'bootstrap',
            excluded: ':disabled',
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                customer_first_name: {
                    validators: {
                        notEmpty: { message: "Please enter your first name" }
                    }
                },
                customer_surname: {
                    validators: {
                        notEmpty: { message: "Please enter your surname" }
                    }
                },
                customer_email: {
                    trigger: 'blur',
                    validators: {
                        notEmpty: { message: "Please enter your email" },
                        emailAddress: { message: "The email address you entered is not valid"}
                    }
                },
                customer_phone: {
                    validators: {
                        notEmpty: { message: "Please enter your phone number" }
                    }
                },
                b_addr_line_1: {
                    validators: {
                        notEmpty: { message: "Please enter your billing address line 1" }
                    }
                },
                b_city: {
                    validators: {
                        notEmpty: { message: "Please enter your billing city" }
                    }
                },
                b_province: {
                    validators: {
                        callback: {
                            message: 'Please select your billing province',

                            callback: function(value, validator, $field) {
                                if($field.val() == '') {
                                    $('#bProvinceDiv').find($('.select2-selection--single')).css('border', '1px solid #a94442');
                                } else {
                                    $('#bProvinceDiv').find($('.select2-selection--single')).css('border', '1px solid #aaa');
                                }

                                return ($field.val() != '');
                            }
                        }
                    }
                },
                b_post_code: {
                    validators: {
                        notEmpty: { message: "Please enter your billing post code" }
                    }
                },
                s_addr_line_1: {
                    validators: {
                        notEmpty: { message: "Please enter your shipping address line 1" }
                    }
                },
                s_city: {
                    validators: {
                        notEmpty: { message: "Please enter your shipping city" }
                    }
                },
                s_province: {
                    validators: {
                        callback: {
                            message: 'Please select your shipping province',

                            callback: function(value, validator, $field) {
                                if($field.val() == '') {
                                    $('#sProvinceDiv').find($('.select2-selection--single')).css('border', '1px solid #a94442');
                                } else {
                                    $('#sProvinceDiv').find($('.select2-selection--single')).css('border', '1px solid #aaa');
                                }

                                return ($field.val() != '');
                            }
                        }
                    }
                },
                s_post_code: {
                    validators: {
                        notEmpty: { message: "Please enter your shipping post code" }
                    }
                }
            }
        })
        .find('[name="customer_phone"]').mask('(999) 999-9999')
        .on('success.form.fv', function(e) {
            // Prevent form submission
            e.preventDefault();

            var $form = $(e.target);

            // Use Ajax to submit form data
            $form.ajaxSubmit({
                url: '/modules/shopping_cart/ajax/checkout.ajax.php',
                type: 'POST',
                beforeSubmit: function() {
                    $('.ajaxLoading').show();
                },
                success: function(result) {
                    $('.ajaxLoading').hide();
                    bootbox.dialog({
                        message: "Your order has been sent to Highland Coffee Roastery.<br>" +
                            "Please check your email for the invoice." +
                            "Once you send us the proof of payment we will post you the coffee.<br>" +
                            "Thank you for ordering from us.",
                        title: "<span class='dialogSuccess'>Success</span>",
                        buttons: {
                            exit: {
                                label: "OK",
                                className: "btn-success",
                                callback: function() {
                                  document.location = '/index.php';
                                }
                            }
                        }
                    });
                }
            });
        });`

**Comment by nghuuphuoc** [comment]
@SigalZ 
Your issue is caused by not returning the form instance after using the mark plugin:

```javascript
// Wrong
$('#checkoutForm')
    .formValidation(...)
    .find('[name="customer_phone"]').mask('(999) 999-9999')   // ---> It returns the customer_phone element
    .on('success.form.fv', function(e) {
        ...
    });
```
So, the code above will trigger the `success.form.fv` event for the `customer_phone` element, not the form.

```javascript
// Right
$('#checkoutForm')
    .formValidation(...)
    .find('[name="customer_phone"]')
        .mask('(999) 999-9999')
        .end() // ---> This will return back to the form instance
    .on('success.form.fv', function(e) {
        ...
    });
```

**Comment by SigalZ** [comment]
Thank you and god bless you
