### ISSUE TITLE
Trying to remove success icon getting error

### ISSUE THREAD

**Issue by SigalZ** [formvalidation/support#155]
Hello,
I am using version 0.6.2.

Trying to remove the success icons after successful form submit.

I get this error:
data is undefined

I am using a click event on the submit button because I build the forms dynamically.

My code: 
`$('.addToCartBtn').on('click', function() {
        product_id = $(this).data('id');
        weight = $(this).data('weight');

        $('#form_'+weight+'_'+product_id).formValidation({
            framework: 'bootstrap',
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                qty: {
                    validators: {
                        notEmpty: { message: "Please enter the quantity" }
                    }
                },
                ground: {
                    validators: {
                        notEmpty: { message: "Please select the ground" }
                    }
                }
            }
    })
        .on('success.form.fv', function(e, data) { 
            // Prevent form submission
            e.preventDefault();

            var $form = $(e.target);

            // Use Ajax to submit form data
            $.ajax({
                url: '/modules/shopping_cart/ajax/add_to_cart.ajax.php',
                type: 'POST',
                data: $form.serialize(),
                success: function(result) {
                    // ... Process the result ...
                    $('#cartItems').text(result);
                    $('#ground_'+weight+'_'+product_id).val(0);

                    var $parent = data.element.parents('.form-group');

                    // Remove the has-success class
                    $parent.removeClass('has-success');

                     // Hide the success icon
                     data.element.data('fv.icon').hide();
                }
            });
        });
    });`

I don't have this code online yet, is it possible to help with the code I gave you?

Thank you

**Comment by nghuuphuoc** [comment]
The [success.form.fv](http://formvalidation.io/settings/#event-form) event data does not have `data` parameter. That's why you get the error `data is undefined`.

You can use the [resetForm](http://formvalidation.io/api/#reset-form) method:

```javascript
$('#form_'+weight+'_'+product_id)
    .formValidation({
        ...
    })
    .on('success.form.fv', function(e, data) { 
        // Prevent form submission
        e.preventDefault();

        var $form = $(e.target);

        // Use Ajax to submit form data
        $.ajax({
            url: '...',
            type: 'POST',
            data: $form.serialize(),
            success: function(result) {
                // ... Process the result ...

                // Reset the form
                $form.formValidation('resetForm');
            }
        });
    });
});
```

**Comment by SigalZ** [comment]
LOL, thank you, just found it myself and changed it to success.form.field, but will change it to your way.
Thank you
