### ISSUE TITLE
Unable to validate cvv number

### ISSUE THREAD

**Issue by bling98** [formvalidation/support#156]
When I use cvv number, I get this odd error when I click my 'submit' button.

html:
`<input type="password" class="form-control" name="cvCode" placeholder="CVC" maxlength="4" data-stripe="cvc" required data-fv-cvv="true" data-fv-cvv-ccfield="ccNumber" data-fv-cvv-message="The CVV number is not valid" />`

chrome console error:
*Uncaught TypeError: Cannot read property 'replace' of undefined
FormValidation.Validator.cvv.validate @ formValidation.min.js:12
FormValidation.Base.validateField @ formValidation.min.js:10
FormValidation.Base.validate @ formValidation.min.js:10
(anonymous function) @ formValidation.min.js:10
m.event.dispatch @ jquery.min.js:3
m.event.add.r.handle @ jquery.min.js:3*

I have tried both programmatic and declarative codes. Both result in the same error.
I am using formValidation from dist-v0.6.2.

May someone point me in the right direction?

**Comment by nghuuphuoc** [comment]
Please give me your form markup and the JS.

**Comment by bling98** [comment]
```javascript
// Form validation for register form
    $('#registerForm').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            expMonth: {
                row: '.col-md-1',
                validators: {
                    notEmpty: {
                        message: 'The expiration month is required'
                    },
                    digits: {
                        message: 'The expiration month can contain digits only'
                    },
                    callback: {
                        message: 'Expired',
                        callback: function (value, validator, $field) {
                            value = parseInt(value, 10);
                            var year = validator.getFieldElements('expYear').val(),
                                currentMonth = new Date().getMonth() + 1,
                                currentYear = new Date().getFullYear();
                            if (value < 0 || value > 12) {
                                return false;
                            }
                            if (year == '') {
                                return true;
                            }
                            year = parseInt(year, 10);
                            if (year > currentYear || (year == currentYear && value >= currentMonth)) {
                                validator.updateStatus('expYear', 'VALID');
                                return true;
                            } else {
                                return false;
                            }
                        }
                    }
                }
            },
            expYear: {
                row: '.col-md-1',
                validators: {
                    notEmpty: {
                        message: 'The expiration year is required'
                    },
                    digits: {
                        message: 'The expiration year can contain digits only'
                    },
                    callback: {
                        message: 'Expired',
                        callback: function (value, validator, $field) {
                            value = parseInt(value, 10);
                            var month = validator.getFieldElements('expMonth').val(),
                                currentMonth = new Date().getMonth() + 1,
                                currentYear = new Date().getFullYear();
                            if (value < currentYear || value > currentYear + 10) {
                                return false;
                            }
                            if (month == '') {
                                return false;
                            }
                            month = parseInt(month, 10);
                            if (value > currentYear || (value == currentYear && month >= currentMonth)) {
                                validator.updateStatus('expMonth', 'VALID');
                                return true;
                            } else {
                                return false;
                            }
                        }
                    }
                }
            }
        }
    }).on('success.form.fv', function (e) {
        // Prevent form submission
        e.preventDefault();

        // Some instances you can use are
        var $form = $(e.target),        // The form instance
            fv = $(e.target).data('formValidation'); // FormValidation instance

        // Obtain Stripe Token
        Stripe.card.createToken($('#registerForm'), stripeCreateTokenResponseHandler);
    });

    // Description updates on page on selecting a plan
    $("input[name='planChoice']").change(function () {
        console.log(this.id);

        $('#description').html(this.id);

    });
```
`<html><form id="registerForm" method="post" class="form-horizontal" data-fv-framework="bootstrap" data-fv-icon-valid="glyphicon glyphicon-ok" data-fv-icon-invalid="glyphicon glyphicon-remove" data-fv-icon-validating="glyphicon glyphicon-refresh">
    <div class="form-group">
        <div class="col-md-2 col-md-offset-2">
            <label class="control-label" for="cardNumber">Card Number:</label>
        </div>
        <div class="col-md-4">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                <input type="text" class="form-control" name="cardNumber" id="cardNumber" placeholder="Enter valid card number" data-stripe="number" required data-fv-creditcard="true" data-fv-creditcard-message="The credit card number is not valid"/>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-2 col-md-offset-2">
            <label class="control-label" for="expMonth">Expiration Date:</label>
        </div>
        <div class="col-md-1">
            <input type="number" class="form-control" name="expMonth" placeholder="MM" data-stripe="exp-month" min="1" max="12" required/>
        </div>
        <div class="col-md-1">
            <input type="number" class="form-control" name="expYear" placeholder="YYYY" data-stripe="exp-year" min="2015" max="2099" required/>
        </div>
        <div class="col-md-1">
                <input type="password" class="form-control" name="cvCode" placeholder="CVC" maxlength="4" data-stripe="cvc" required 
                    data-fv-cvv="true" data-fv-cvv-ccfield="ccNumber" data-fv-cvv-message="The CVV number is not valid" />
        </div>
    </div>
    <div class="form-group"> 
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" id="registerBtn" class="btn btn-success">Register Now</button>
        </div>
    </div>
</form></html>`


I hope this is not too confusing.

**Comment by nghuuphuoc** [comment]
You should try to change `data-fv-cvv-ccfield="ccNumber"` to `data-fv-cvv-ccfield="cardNumber"`, because `cardNumber` is the name of credit card number field.

**Comment by bling98** [comment]
Great! That was it. Thank you Phuoc!
