### ISSUE TITLE
Validation with Slow Remote Method

### ISSUE THREAD

**Issue by scs-ben** [formvalidation/support#162]
If a form validates with a remote call and the remote call hangs, the table will come back as null for valid. The only way to check this (especially when using a container for validation) is to come up with a setTimeout system to check back with the validator until the remote call is done.

It would be nice to have a callback option on the validate function that will go off after the remote validation is done so that the form can then be submitted.

**Comment by nghuuphuoc** [comment]
> It would be nice to have a callback option on the validate function that will go off after the remote validation is done

You can trigger the [success.fv.validator event](http://formvalidation.io/settings/#event-validator) that is called after a validation process of given validator is done.

```javascript
$(form)
    .formValidation({
        fields: {
            username: {
                validator: {
                    remote: {
                        ...
                    }
                }
            }
        }
    })
    .on('success.validator.fv', function(e, data) {
        if (data.field === 'username' && data.validator === 'remote') {
            // The username field passes the remote validator
            // ... Do something here ...
        }
    });
```

The same way is to use the `onSuccess` callback:

```javascript
$(form)
    .formValidation({
        fields: {
            username: {
                validator: {
                    remote: {
                        // ... The remote validator options ...
                        onSuccess: function(e, data) {
                            // The username field passes the remote validator
                            // ... Do something here ...
                        }
                    }
                }
            }
        }
    });
```

**Comment by scs-ben** [comment]
I would also like to have a callback based on a valid container, not just a valid field. My data could have multiple remote validation checks and since this plugin supports validation containers, why not have a callback for them?

**Comment by nghuuphuoc** [comment]
Currently, there's no `onSuccess` callback or event like `success.container.fv`.
Maybe in the future, I can add an event after calling the [validateContainer](http://formvalidation.io/api/#validate-container) method.

> My data could have multiple remote validation checks

One more thing that you might be interested, in the next v0.7.0 version, the plugin will support using multiple validators (with the same name) for any field.
At the moment, we can use only 1 `remote` validator for each field.
