### ISSUE TITLE
between validator doesn't show the expected message

### ISSUE THREAD

**Issue by KimKJDesigns** [formvalidation/support#163]
Between is failing on both my code and your example codes supplied.

You'll see the errors if you test on your own examples.

**Comment by nghuuphuoc** [comment]
Can you tell me which thing is wrong?
I tried the [examples](http://formvalidation.io/validators/between/#example) and they work as expected.

**Comment by KimKJDesigns** [comment]
The issue seems to be resolved for your examples.
It was displaying The number of floors must be between $s and $s

**Comment by nghuuphuoc** [comment]
The improvement will be available in the next v0.7.0 version.
The [between](http://formvalidation.io/validators/between/), [greaterThan](http://formvalidation.io/validators/greaterThan/), [lessThan](http://formvalidation.io/validators/lessThan/) validators will show the message where %s are replaced with the `min`, `max`, `value` options when the input isn't a number.

Current v0.6.3 and earlier versions:

![between-message-before](https://cloud.githubusercontent.com/assets/4226036/8953515/537eb7e6-3609-11e5-9bf3-ec6c9bdf703c.gif)

Next v0.7.0:

![between-message-after](https://cloud.githubusercontent.com/assets/4226036/8953524/5f53ba76-3609-11e5-9737-de8996d6ca6b.gif)

**Comment by KimKJDesigns** [comment]
Great news :)

**Comment by nghuuphuoc** [comment]
Done. 
[v0.7.0](http://formvalidation.io/news/v0.7.0-released/) is released. You can use the previous download link to get new version.
