### ISSUE TITLE
Problem with numeric validator with comma separator

### ISSUE THREAD

**Issue by r3nan** [formvalidation/support#165]
I'm live in Brazil, here, our separator is comma (,).

Because this i have to validate with comma (,) in numeric fields. But it's not wornking well.

When i use separator atribute with comma (,), the validaton accepts comma (,) OR dot (.) but i need that it accept ONLY comma (,).

My code:
$(document).ready(function() {
    $('#formId').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            idFieldNumeric: {
                validators: {
                    numeric: {
                        separator: ','
                    }
                }
            }
        }
    });
});

**Comment by nghuuphuoc** [comment]
In the next v0.7.0, both [integer](http://formvalidation.io/validators/integer/) and [numeric](http://formvalidation.io/validators/numeric/) validators support more locales by providing new thousands and decimal separator options.

**Comment by nghuuphuoc** [comment]
The latest [v0.7.0](http://formvalidation.io/news/v0.7.0-released/) is released. Now both the [integer](http://formvalidation.io/validators/integer/) and [numeric](http://formvalidation.io/validators/numeric/) validators support custom thousands and decimal separator. 
See http://formvalidation.io/validators/numeric/#supporting-locales

You can use the previous download link to grab new version.

**Comment by r3nan** [comment]
Nice, thanks.

**Comment by uros** [comment]
There is still an issue with min/max interval checking while using different separators.
