### ISSUE TITLE
in v0.6.3 fields with placeholder text in IE validate automatically when they get focus

### ISSUE THREAD

**Issue by pagedo** [formvalidation/support#166]
Issue #102: "Fix an issue on IE 10/11 that causes an input element with placeholder attribute to be validated automatically when it's focused" is not fixed in v0.6.3 - the reason I upgraded and paid for formValidation as opposed to the not supported bootstrapValidator. A field with autofocus and placeholder text show a validation error immediately on load of the document in IE. Other fields with placeholder text show a validation error immediately when they are clicked on. This behaviour does not occur in Win Chrome, OS X Safari, Linux Chrome, Android or iOS devices -  only in Internet Explorer (I'm using IE 11).

Images of Initial Load Safari (same for other platforms except IE browser) and Initial Load IE and then click on another placeholder field in IE
![osxsafari_complexform](https://cloud.githubusercontent.com/assets/6880343/7980606/403f075a-0aec-11e5-8370-1d9a5162b0ac.png)
![win7ie11_complexform](https://cloud.githubusercontent.com/assets/6880343/7980614/4e60e4e8-0aec-11e5-8cc6-3122ab6f2059.png)
![win7ie11_complexform2](https://cloud.githubusercontent.com/assets/6880343/7980620/5918b604-0aec-11e5-92d1-b493be514ea2.png)

**Comment by nghuuphuoc** [comment]
Thank for reporting this. I can confirm that it's still there on IE10, IE11.
I made a quick fix. Can you please recheck [that page](http://formvalidation.io/download/tryit/bootstrap.html) on IE10 and IE11?

**Comment by pagedo** [comment]
yes that seems to fix the problem with placeholder fields in IE. When will
it be available. Is it possible to get/use your quick fix version?

**Comment by nghuuphuoc** [comment]
The fix will be included in the next version, maybe in the next month. Of course, I will let you know when it's released.

**Comment by pagedo** [comment]
thank you

**Comment by nghuuphuoc** [comment]
@pagedo 
[v0.7.0](http://formvalidation.io/news/v0.7.0-released/) is released. This issue is fixed.
You can use the previous download link to get new version.

**Comment by pagedo** [comment]
Thank You
