### ISSUE TITLE
field selector using Declarative code

### ISSUE THREAD

**Issue by serge512** [formvalidation/support#169]
Hi, first i love this plugin didn't think twice to buy it. the question is as follows i need to achieve this: http://formvalidation.io/settings/#field-selector so i can validate at least one phone number including their own validations. using Declarative code form

**Comment by nghuuphuoc** [comment]
The `selector` option, like other options, can be used by the `data-fv-selector` attribute:
http://formvalidation.io/settings/#field-settings

For example, the declarative code for the credit card number field in the example will be

```
<input type="text" class="form-control" id="ccNumber"
    data-fv-field="ccNumber"
    data-fv-selector="#ccNumber"
    data-fv-notempty="true"
    data-fv-notempty-message="The credit card number is required"
    data-fv-creditcard="true"
    data-fv-creditcard-message="The credit card number is not valid" />
```

Please notice that we use the `data-fv-field` attribute which presents the name field in the case the `name` attribute isn't used.

See this [jsfiddle](http://jsfiddle.net/nghuuphuoc/27th9n0r/1/).
