### ISSUE TITLE
regexp validator: Declarative code with OR

### ISSUE THREAD

**Issue by rienkok** [formvalidation/support#172]
Hi all,

I have two fields where a user can put the left and right margins of an image. Valid inputs are numbers OR the word 'auto'. 

The 'programmatic code' works:
.......
fields: {
   marginright: {
	validators: {
	    regexp: {
		   regexp: /^([0-9]|\bauto\b)+$/,
		   message: 'Vul een geheel getal in of het woord "auto"'
	    }
         }
    }
.......

The corresponding 'declarative code' does NOT work, it accept only numbers but not the word 'auto'!

data-fv-regexp='true'
data-fv-regexp-regexp='^([0-9]|\bauto\b)+$'
data-fv-regexp-message='Vul een geheel getal in of het woord \"auto\" '

Am I doing something wrong?

Regards,

Rien Kok (The Netherlands)

**Comment by nghuuphuoc** [comment]
Using exactly your code, I made this [fiddle](http://jsfiddle.net/nghuuphuoc/zm5zsgv4/).
It works as we expect. The field accepts both number and the word `auto`:

![regexp declarative usage](https://cloud.githubusercontent.com/assets/4226036/8036203/8f33bce8-0e20-11e5-97e2-5a7eb438d6e9.png)

**Comment by rienkok** [comment]
Using your code form the fiddle: it still doesn't work. The form is placed within a (Bootstrap) Tab, within a (Bootstrap) Modal. Can that be the reason why it doesn't work?
All other declarative validators within the form works very well.

**Comment by nghuuphuoc** [comment]
By default, the plugin will ignore disabled, hidden and invisible fields.
If the form is placed inside a Bootstrap tab/modal, the fields are invisible when initializing the plugin in declerative mode, and therefore they are ignored.

To solve this, just use the [excluded](http://formvalidation.io/settings/#form-excluded) setting.
```
<form data-fv-excluded=":disabled">
...
</form>
```

Setting `data-fv-excluded=":disabled"` will ignore disabled fields only.

The [Bootstrap modal](http://formvalidation.io/examples/modal/) example might be useful too.
