### ISSUE TITLE
Safari 5.1.7 error : TypeError: 'undefined' is not an object

### ISSUE THREAD

**Issue by rllola** [formvalidation/support#173]
I have this error when loading initiating the form : 
```
TypeError: 'undefined' is not an object (evaluating '$(this)
                    .data(ns + '.messages')
                    .find')
```

Someone has the same issue ?

**Comment by nghuuphuoc** [comment]
Can you please tell me
* Does this issue happen on other browser?
* Do you use the plugin with other plugins (In the pass, I saw that message when user try to use it with Typehead)?

It's great if you can also provide the HTML and the JS code.

**Comment by rllola** [comment]
I am sorry it was actually an issue on my code and not on the library.
