### ISSUE TITLE
isValidContainer() doesn't ignore field which validators are totally disabled

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#177]

**Comment by kiasoftware** [comment]
if(1) // if enabled status is true, so check it
				{ 
					// If the field is not validated
					if ($errors.filter('[data-' + ns + '-result="' + this.STATUS_NOT_VALIDATED + '"]').length > 0
						|| $errors.filter('[data-' + ns + '-result="' + this.STATUS_VALIDATING + '"]').length > 0)
					{
						return null;
					}
				}

**Comment by nghuuphuoc** [comment]
Thank you for the suggestion.
This bug will be fixed and the patch will be available in the next v0.7.0.

**Comment by nghuuphuoc** [comment]
The fix is already included in [v0.7.0](http://formvalidation.io/news/v0.7.0-released/).
