### ISSUE TITLE
Uncaught TypeError: message.replace is not a function when customizing i18n message in stringLength validator

### ISSUE THREAD

**Issue by littlee** [formvalidation/support#178]
```js
stringLength: {
	min: 6,
	max: 32,
	message: {
		en_US: 'string too long',
		zh_CN: '这个字符串太长了'
	}
}
```
When I try to input something, I get Uncaught TypeError: message.replace is not a function
This only happens when use stringLength validator, others works fine.

**Comment by nghuuphuoc** [comment]
Do you use the [i18n](http://formvalidation.io/addons/i18n/) add-on?

**Comment by littlee** [comment]
Yes, I did.

**Comment by nghuuphuoc** [comment]
Thank for reporting this. I can confirm that it also happens on my environment.
I will try to find the solution and get back to you.

**Comment by littlee** [comment]
Thanks.

**Comment by nghuuphuoc** [comment]
I fixed the issue.
Can you please download the [latest build](https://github.com/formvalidation/addon-i18n/archive/master.zip) and use the `i18(.min).js` located inside the `dist` directory?

Also, you can use `%s` in the message as following:

```javascript
stringLength: {
    min: 6,
    max: 32,
    message: {
        en_US: 'The value must be %s and %s long',
        zh_CN: '这个字符串太长了'
    }
}
```

**Comment by littlee** [comment]
Neat.

**Comment by nghuuphuoc** [comment]
New version of the [i18n add-on](http://formvalidation.io/addons/i18n/), v0.1.1, is released.
