### ISSUE TITLE
formV not defined ... and drop-down fields.

### ISSUE THREAD

**Issue by agratti** [formvalidation/support#183]
There are 4 versions of formvalidation in the package that we are bought.  we have 2 issues, tthat I imagine may be connected:

the first issue:
In the formValidation.popular.min.js that we are using, an error occours: formValidation.popular.min.js:34 Uncaught ReferenceError: formV is not defined

the second issue 
we can not validate the fields with a drop-down fields. In the site we are read that need an option with value="". 
http://formvalidation.io/validators/notEmpty/#using-with-select-element

.. but we have an error in initial phase .

can you help us?
thank you in advance
Andrea Gratti

**Comment by nghuuphuoc** [comment]
First of all, thanks for purchasing the plugin.
Can you please give me the HTML form and JS code you're using?

**Comment by agratti** [comment]
<div class="input-holder">
        <select id="univ_subject" name="univ_subject" required="required">
            <option value="" selected="selected">-</option>
            <option value="001">001 - pierce</option>
            <option value="002">002 - alberts3e</option>
        </select>
    </div>

    $('form').formValidation({
        framework: 'bootstrap',
        locale: 'it_IT',
        excluded: ':disabled', 
    });

Writing down the code I noticed that the required "form-group" container for bootstrap form is missing. Can you please tell me how to specify via HTML/HTML5 attributes a specific container (".input-holder")? I didn't find it on online documentation.

**Comment by nghuuphuoc** [comment]
> Writing down the code I noticed that the required "form-group" container for bootstrap form is missing

In this case, you need to use the [row](http://formvalidation.io/settings/#field-row) option which can be enabled by `data-fv-row` attribute:

```html
    <div class="input-holder">
        <select id="univ_subject" name="univ_subject" 
            required="required"
            data-fv-row=".input-holder">
            <option value="" selected="selected">-</option>
            <option value="001">001 - pierce</option>
            <option value="002">002 - alberts3e</option>
        </select>
    </div>
```

Here is the [jsfiddle](http://jsfiddle.net/nghuuphuoc/mfbq26aw/) showing how it works:

![row-option-usage](https://cloud.githubusercontent.com/assets/4226036/8453138/bd56fb96-201b-11e5-8b1b-6ee4814eec83.png)

You also take a look at these examples:
* http://formvalidation.io/examples/complex-form/
* http://formvalidation.io/getting-started/#complex-form

I hope it helps you.

**Comment by agratti** [comment]
Thanks, you have been very clear. Indeed I found the correct attribute to use but I forgot the dot in front of the class! My fault. 

What about the first issue (in the first post) about the error with the minified popular version of the library?

**Comment by nghuuphuoc** [comment]
There is no issue when switching to use the popular version as seen in this [jsfiddle](http://jsfiddle.net/nghuuphuoc/mfbq26aw/1/).
Because the popular version just consists of popular validators, so ensure that you don't use the validators which aren't enabled in `formValidation.popular.min.js`.
