### ISSUE TITLE
Way to test a subset of the form?

### ISSUE THREAD

**Issue by trainbolt** [formvalidation/support#185]
Is there any way to test sections of a form? For instance an ecomm form with shipping, billing, payment info. It would be nice to be able to know when each section passes.

**Comment by nghuuphuoc** [comment]
You can use the [validateContainer()](http://formvalidation.io/api/#validate-container) method to validate given area, and then use the [isValidContainer()](http://formvalidation.io/api/#is-valid-container) method to check if the area is valid or not.

It's recommended to use a wizard in this case.
Take a look at http://formvalidation.io/examples/#wizard
