### ISSUE TITLE
Uncaught TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by dnoray** [formvalidation/support#186]
I have a form that receives a user's spouse or child information. The user has the option to remove the child's input or spouse's input fields.
The form validates and functions fine until the user removes the child's input fields, then it throws the error when you try to submit the form.
" Uncaught TypeError: Cannot read property 'find' of undefined "

Form: http://northeastvision.org/family-info/

Any suggests as to how I can fix this?
Thanks!

**Comment by nghuuphuoc** [comment]
When working with dynamic fields, it's recommended to use the `addField()` and `removeField()` methods to manage them.
This example will help you: http://formvalidation.io/examples/adding-dynamic-field/

**Comment by dnoray** [comment]
Thanks for answering so quickly! But I have a little dilemma. I had set up my form that way before but the guy who is doing the database side of things could not tie it in to his db code.
So I had to use js to hide and reveal the divs with the fields.

Is there any way that I can work around your solution?
