### ISSUE TITLE
Terms and condition validation

### ISSUE THREAD

**Issue by andreapernici** [formvalidation/support#187]
I'm testing this
http://formvalidation.io/examples/terms-conditions-agreement-validation/

but is not working. Tha validation apply everywhere except on the checkboxes.

**Comment by nghuuphuoc** [comment]
Can you tell me which browser you are testing with? Also, it's great if you can give me a screenshot capturing what happens.

**Comment by andreapernici** [comment]
I'm using chrome.

The issue is that any validation happen on the checkboxes.

**Comment by nghuuphuoc** [comment]
> The validation apply everywhere except on the checkboxes

Can you please clear the cache of the browser?
Here is what I got on my Chrome:

![terms-conditions-validation-1](https://cloud.githubusercontent.com/assets/4226036/8505680/042572c4-2219-11e5-8c8c-4d9367dbbc7a.gif)
