### ISSUE TITLE
Remote Validator with custom message

### ISSUE THREAD

**Issue by san360** [formvalidation/support#189]
I am using remote validator to validate 3 to 5 entries at a time. The entries are retrieved from a third party database and its readonly. I would like to show user a message with a specified invalid entry.

for e.g. entries: A,B,C,D,E

Message: The entry A is invalid

Thanks
Sanjay

**Comment by nghuuphuoc** [comment]
It's possible for the `remote` validator to use a [dynamic message](http://formvalidation.io/settings/#dynamic-message).

The server need to response a encoded JSON string that consists of valid and message keys:

```
{ 
    valid: false, 
    message: 'The error message' 
}
```
