### ISSUE TITLE
Unnecessary request

### ISSUE THREAD

**Issue by concepto8** [formvalidation/support#19]
The remote validation should be the last validation to do, and only if the local validations are successful, since it uses the network and depending on delay it add weight to the server, you should avoid that.

**Comment by nghuuphuoc** [comment]
In order to improve the performance when using thre ```remote``` validator, there're [3 ways](http://formvalidation.io/validators/remote/#improving-the-performance).
The last one, [using verbose option](http://formvalidation.io/validators/remote/#using-verbose-option) is what you've suggested!
