### ISSUE TITLE
row validating

### ISSUE THREAD

**Issue by agratti** [formvalidation/support#190]
The row option ha three parameters:
* selector
* valid
* invalid

Why does it not have a "validating" parameter just like the icon option?
I would like to change the row class when using a remote validator. Is there a way to emultate this?

**Comment by nghuuphuoc** [comment]
You can trigger the `status.field.fv` event as seen in this http://formvalidation.io/examples/getting-notified-field-being-validated/#listening-event example:

```javascript
$(form)
    .formValidation({
        fields: {
            username: {
                validators: {
                    remote: {
                        type: 'POST',
                        url: '/path/to/your/api/',
                        message: 'The username is not available'
                    }
                }
            }
        }
    })
    .on('status.field.fv', function(e, data) {
        if (data.field === 'username' && data.status === 'VALIDATING') {
            // You might need to change username to your field name
            data.element.cloest('.form-group').addClass('your-class-here');
        }
    });
```

The `data` has 3 properties:
* `data.field` is the field name
* `data.status` is the current status of validator
* `data.element` is the field element

**Comment by agratti** [comment]
Thank you. It worked perfectly
