### ISSUE TITLE
Does the validator work with jquery ajaxForm, which is used to pass multiple files?

### ISSUE THREAD

**Issue by PritiShah** [formvalidation/support#194]
I have a requirement where in I submit multiple files via jquery ajaxForm method (jquery.form.js)

I am using bootstrap validator v0.4.5 on a form which submits multiple files along with data. It seems this validator does not recognize the jquery ajaxForm method (used to submit data and file) and hence nothing happens on submit button.

Just wanted to check if this is an issue with 0.4.5 version. 

Thanks,
Priti

**Comment by nghuuphuoc** [comment]
Since you're moving from v0.4.5 to the latest version of FormValidation, you can use the approach in this [Using Ajax to submit form data including files](http://formvalidation.io/examples/ajax-submit/#using-ajax-to-submit-form-data-including-files) example.

**Comment by PritiShah** [comment]
Yes, it is working with latest vesion, thanks.
