### ISSUE TITLE
Form submits twice

### ISSUE THREAD

**Issue by agratti** [formvalidation/support#195]
When I click the submit button the first time the form is submitted twice. If I click again the form is submitted only once. This problem does not occur if I disable all the form validation code. 

The form validation instantion:

    $('form.form-register').formValidation({
            framework: 'bootstrap',
            locale: 'it_IT',
            excluded: ':disabled',
            row: {
                valid: 'valid',
                invalid: 'not-valid'
            }
        }).on('status.field.fv', function(e, data) {
            if (data.field === 'user_email') {
                if (data.status === 'VALIDATING') {
                    data.element.closest('.form-group').addClass('validating');
                } else {
                    data.element.closest('.form-group').removeClass('validating');
                }
            }
        });

The submit handler:

    $('form.form-register').submit(function (e) {
            e.preventDefault();

            if (!$(this).data('formValidation').isValid()) {
                return false;
            }
            ...
    
Library version: 0.6.3

**Comment by nghuuphuoc** [comment]
Instead of using submit handler as above, it's recommended to trigger the `success.form.fv` event:

```javascript
$('form.form-register')
    .formValidation({
        framework: 'bootstrap',
        locale: 'it_IT',
        excluded: ':disabled',
        row: {
            valid: 'valid',
            invalid: 'not-valid'
        }
    })
    .on('status.field.fv', function(e, data) {
        ...
    })
    .on('success.form.fv', function(e) {
        // Prevent form submission
        e.preventDefault();

        // Get the form instance
        var $form = $(e.target);

        // and the FormValidation instance
        var fv = $form.data('formValidation');

        // Do whatever you want here ...

        // Use the defaultSubmit() method if you want to submit the form
        // See http://formvalidation.io/api/#default-submit
        fv.defaultSubmit();
    });
```

See http://formvalidation.io/examples/form-submit-twice/

**Comment by agratti** [comment]
Sorry, I didn't saw the example. It worked perfectly. 
Thank you
