### ISSUE TITLE
not working with latest version of summernote

### ISSUE THREAD

**Issue by lorvent** [formvalidation/support#196]
when using latest version of summernote, validation is not being done

its working only when using the summernote version used in examples page

**Comment by nghuuphuoc** [comment]
Can you tell me the Summernote version you're using?
Also, do you use excluded: 'disabled' option?

On Wednesday, July 8, 2015, lorvent <notifications@github.com> wrote:

> when using latest version of summernote, validation is not being done
>
> its working only when using the summernote version used in examples page
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formvalidation/support/issues/196>.
>


-- 
Phuoc Nguyen
Sent from my iPad

**Comment by lorvent** [comment]
I am trying to use ****0.8.8**** version but its not working

is that mandatory for summernote to work?

When i am using older version, without excluded:'disabled' its working fine

**Comment by nghuuphuoc** [comment]
Yes, you have to use the `excluded: [':disabled']` option as seen in the ___Programmatic code___ tab of the [example](http://formvalidation.io/examples/summernote/).

You should take a look at the [basic principles](http://formvalidation.io/examples#compatibility) when integrating FormValidation with other plugins.

**Comment by lorvent** [comment]
Hello,

its not working even when i include `excluded: [':disabled']`

try yourself with latest version of summernote and you will find that.


PS. i expected you will include examples in download bundle but sadly they were not included.

**Comment by nghuuphuoc** [comment]
You're right. The example doesn't work when upgrading Summernote from v0.6.2 to the latest version v0.6.9.

I updated it to work with v0.6.9: http://formvalidation.io/examples/summernote/

```javascript
$('#summernoteForm')
    .formValidation({
        framework: 'bootstrap',
        excluded: [':disabled'],
        icon: {
            ...
        },
        fields: {
            content: {
                validators: {
                    callback: {
                        message: 'The content is required and cannot be empty',
                        callback: function(value, validator, $field) {
                            var code = $('[name="content"]').code();
                            // <p><br></p> is code generated by Summernote for empty content
                            return (code !== '' && code !== '<p><br></p>');
                        }
                    }
                }
            }
        }
    })
    .find('[name="content"]')
        .summernote({
            height: 400
        })
        .on('summernote.change', function(customEvent, contents, $editable) {
            // Revalidate the content when its value is changed by Summernote
            $('#summernoteForm').formValidation('revalidateField', 'content');
        })
        .end();
```
