### ISSUE TITLE
Can't work for two forms on same page 

### ISSUE THREAD

**Issue by Prashu33** [formvalidation/support#199]
Hi i'm using this plugin for registration before i have only one form so it is working fine for first form but now after adding a new form it is not working for second form so please can u suggest me what to do .
and there is a error mesg of jquery -Uncaught RangeError: Maximum call stack size exceeded in Formvalidation.js

**Comment by nghuuphuoc** [comment]
There's no limitation of number of forms on the same page that can prevent the plugin from working properly.
Can you please give me the snippet code of your HTML forms and JS you're calling?

**Comment by Prashu33** [comment]
This is my First form--
<form role="form" method="post" class="form-signup">
                        <ul>
                            <li>Title (*)</li> 
                            <li> 
                                <select class="form-control" id="sign_up_id9" name="user_title">
                                    <option value="">Please select</option>
                                    <option value="Ms">Ms</option>
                                    <option value="Mr">Mr</option>
                                    <option value="Mrs">Mrs</option>
                                    <option value="Dr">Dr</option>
                                    <option value="Prof">Prof</option>
                                </select>
                            </li>
                            <li>First name(*)</li> 
                            <li><input type="text" id="sign_up_id1" name="first_name" class="form-control"></li>
                            <li>Last name(*)</li>
                            <li> <input  type="text" id="sign_up_id2" name="last_name" class="form-control"></li>
                            <li>Email(*)</li>
                            <li><input  type="email" id="user_email_reg" name="email" class="form-control"></li>
                            <li>Password(*)</li>
                            <li><input type="password"  id="inputPassword" name="user_password" class="form-control"></li>
                            <li>Confirm Password(*)</li>
                            <li><input  type="password" id="sign_up_id6" name="confirm_password" class="form-control"></li>
<input type="submit" id="user_register_submit" class="btn btn-lg btn-warning customLoginBtn" name="register" value="Sign Up"/>
</form>

This is my Second form--
<form role="form" method="post" class="form-letter">
                        <ul>
                            <li>Title (*)</li> 
                            <li> 
                                <select class="form-control" id="sign_up_id9" name="user_title">
                                    <option value="">Please select</option>
                                    <option value="Ms">Ms</option>
                                    <option value="Mr">Mr</option>
                                    <option value="Mrs">Mrs</option>
                                    <option value="Dr">Dr</option>
                                    <option value="Prof">Prof</option>
                                </select>
                            </li>
                            <li>First name(*)</li> 
                            <li><input type="text" id="sign_up_id1" name="first_name" class="form-control"></li>
                            <li>Last name(*)</li>
                            <li> <input  type="text" id="sign_up_id2" name="last_name" class="form-control"></li>
                            <li>Email(*)</li>
                            <li><input  type="email" id="user_email_reg" name="email" class="form-control"></li>
                            <li>Password(*)</li>
                            <li><input type="password"  id="inputPassword" name="user_password" class="form-control"></li>
                            <li>Confirm Password(*)</li>
                            <li><input  type="password" id="sign_up_id6" name="confirm_password" class="form-control"></li>
<input type="submit" id="user_register_submit" class="btn btn-lg btn-warning customLoginBtn" name="register" value="Sign Up">
</form>

And my js is like this-
$('#form-signup).formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            first_name: {
                validators: {
                    notEmpty: {
                        message: 'The first name is required'
                    }
                }
            },
            user_title: {
                validators: {
                    notEmpty: {
                        message: 'The title is required'
                    }
                }
            },
            country_code: {
                validators: {
                    notEmpty: {
                        message: 'Please select country code'
                    }
                }
            },
            user_profession: {
                validators: {
                    notEmpty: {
                        message: 'Please select profession'
                    }
                }
            },
            user_area_of_interest: {
                validators: {
                    notEmpty: {
                        message: 'Please select area of interest'
                    }
                }
            },
            last_name: {
                validators: {
                    notEmpty: {
                        message: 'The last name is required'
                    }
                }
            },
            email: {
                threshold: 4,
                validators: {
                    notEmpty: {
                        message: 'The email address is required'
                    },
                    emailAddress: {
                        message: ' '
                    },
                    regexp: {
                        regexp: '^[^@\\s]+@([^@\\s]+\\.)+[^@\\s]+$',
                        message: 'Please enter a valid email address'
                    },
                    remote: {
                        url: JS_BASE_URL + 'user/checkemail',
                        type: 'POST',
                        message: 'The email already exist',
                    }
                }
            },
            user_password: {
                validators: {
                    notEmpty: {
                        message: 'The password is required'
                    },
                    different: {
                        field: 'user_name',
                        message: 'The password cannot be the same as username'
                    },
                }
            },
            confirm_password: {
                validators: {
                    notEmpty: {
                        message: 'The confirm password is required'
                    },
                    identical: {
                        field: 'user_password',
                        message: 'The password and its confirm are not the same'
                    }
                }
            },
            phone_number: {
                validators: {
                    notEmpty: {
                        message: 'The phone number is required'
                    },
                    integer: {
                        message: 'The not valid number'
                    }
                }
            },
            user_date_of_birth: {
                validators: {
                    notEmpty: {
                        message: 'The date is required'
                    },
                    date: {
                        format: 'DD-MM-YYYY',
                        message: 'The date is not a valid'
                    }
                }


            }
        }
    });

And same for second form just change the form id

**Comment by nghuuphuoc** [comment]
> -Uncaught RangeError: Maximum call stack size exceeded

The issue is caused by the fact that the form doesn't follow the struture of Bootstrap form.
It's warned at the [Writing form](http://formvalidation.io/getting-started/#writing-form) section.

In short, when using the Bootstrap framework, the fields need to be placed inside a `.form-group` container.

In your case, you're special form structure where the fields are placed inside a `li` element, you should use the [row](http://formvalidation.io/settings/#form-row-selector) option for it:

```javascript
$('#form-signup).formValidation({
    framework: 'bootstrap',
    icon: {
        ...
    },
    row: {
        selector: 'li',
        valid: 'has-success',
        invalid: 'has-error'
    },
    fields: {
        ...
    }
});
```

In the above code, the `row.selector` option indicates a CSS selector which can be used to indicate the row container. And it's applied for all fields in form.
You also can use it for particular fields instead of all fields.
See the [Complex form](http://formvalidation.io/examples/complex-form/) example.

**Comment by Prashu33** [comment]
thanks working....
