### ISSUE TITLE
Custom Container / Adding up values

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#20]
_From @jacobkossman on February 9, 2015 2:41_

Hey. Thanks for this plugin. I have a situation where I want to validate a set of sliders which represent a percentage and I want to validate them to add up to 100 in total. I currently am populating a hidden field with javascript to get the value of all the slider and using the identical validator to compare it with another hidden field with a static value of 100. Is there a better way to do this? Include them all as the same field value and do it that way?

Also if I'm doing it correctly then I'd need a custom error container and I can only figure out how to get ALL messages to show up in a specific container not on a field by field basis. 

Thanks.

**Comment by nghuuphuoc** [comment]
@jacobkossman
> Is there a better way to do this? Include them all as the same field value and do it that way?

You can use the [callback](http://formvalidation.io/validators/callback/) validator.

> I'd need a custom error container and I can only figure out how to get ALL messages to show up in a specific container not on a field by field basis.

The [err](http://formvalidation.io/settings/#field-err) option should be useful in that case.

Based on the approach, I created this [fiddle](http://jsfiddle.net/nghuuphuoc/cypvL7fv/9/)

**Comment by jacobkossman** [comment]
@nghuuphuoc Thanks! Do the names have to be the same? I need to have each value posted as unique and grab them via POST.

**Comment by nghuuphuoc** [comment]
If you want each field to be unique, you need to adjust your ```callback``` validator.
Here is working fiddle: http://jsfiddle.net/nghuuphuoc/cypvL7fv/12/

> Do the names have to be the same?

No. You can use the [selector](http://formvalidation.io/settings/#field-selector) option to indicate the field via CSS selector.
Here is updated fiddle: http://jsfiddle.net/nghuuphuoc/cypvL7fv/13/

**Comment by jacobkossman** [comment]
Thanks again. Im using html number fields and it breaks the validation. Do
I need to do something special for these?

**Comment by nghuuphuoc** [comment]
Using number field might enable [numeric](http://formvalidation.io/validators/numeric/) validator.
You can switch to use ```type="text"```.

**Comment by jacobkossman** [comment]
Hopefully last question. I'm adding a field dynamically to this set of sliders. I've got the validation part working but it's not counting the additional fields as part of the set of sliders? How do i call the callback again in order to get it working?

**Comment by nghuuphuoc** [comment]
When adding dynamic fiels, you need to use [addField()](http://formvalidation.io/api/#add-field) method.
See the [Adding dynamic field](http://formvalidation.io/examples/adding-dynamic-field/) example.
