### ISSUE TITLE
open modale on success not work

### ISSUE THREAD

**Issue by Solaris67** [formvalidation/support#202]
Hello,
is the following code good?

jQuery(document).ready(function() {
    jQuery('#ajoutComment').formValidation({
        framework: 'bootstrap',
        icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            commentName: {
                validators: {
                    notEmpty: {
                        message: 'Un nom ou un pseudonyme est requis'
                    },
                    stringLength: {
                        min: 6,
                        max: 30,
                        message: 'Cette case doit comporter au minimum 6 caractères et au maximum 30 caractères'
                    },
                    regexp: {
                        regexp: /^[a-zA-Z0-9_\.]+$/,
                        message: 'Aucun caractère spécial n\'est permis dans cette case!'
                    }
                }
            },
            commentEmail: {
                validators: {
                    notEmpty: {
                    },
                    emailAddress: {
                    }
                }
            },
            commentMessage: {
                validators: {
                    notEmpty: {
                        message: 'Un commentaire est indispensable, c\'est le but de ce formulaire!'
                    },
                    stringLength: {
                        min: 50,
                        max: 500,
                        message: 'Cette case doit comporter au minimum 50 caractères et au maximum 500 caractères'
                    },
                }
            }   // fin du comment message sans virgule
		} // fin du fields
		
		
    }) // fin du formValidation
		.on('success.validator.fv', function(e) {
		e.preventDefault();
		 var $form = jQuery(e.target),        // The form instance
         fv = jQuery(e.target).data('formValidation'); // FormValidation instance
			jQuery('#commentSuccess').modal('show');	
	});
});

Every thing work fine so i would like to add a modale when success. So the modale is open when i load the php page where the formular is located. Not when the formular is sent!

Is the code above is good?

**Comment by Arkni** [comment]
Your code looks code, but the event you're using triggered when field passes given validator(s).

I think you want to show the modal when the form is valid and just before the submit, right ?

To do that, you can use the success event of the form _`success.form.fv`_, see following code:
```js
.on('success.form.fv', function(e) {
    // Prevent form submission
    e.preventDefault();
    var $form = jQuery(e.target), // The form instance
        fv = jQuery(e.target).data('formValidation'); // FormValidation instance

    jQuery('#commentSuccess').modal('show');

    // And then you can submit your form
});
```

**Comment by Solaris67** [comment]
Hello,
your code works very good.
Thank you very much sir!

Regards
Olivier
