### ISSUE TITLE
remote validator always send Post ajax, not GET

### ISSUE THREAD

**Issue by SumanSohal** [formvalidation/support#203]
I am trying to use form validation remote validator for validating a third party number from external web service.

        FHRSid: {
            validators: {
                notEmpty: {
                    message: 'FHRA is not valid'
                },
                remote: {
                    crossDomain: true,
                    type: 'GET',
                    url: appSetting + '/api/FHRSInfo',
                }
            }
        },

But the problem is that browser always send POST request instead of GET even when method type is GET.
![Image of Yaktocat](http://i.stack.imgur.com/Q8dL0.png)

My web api controller is defined as

				[RoutePrefix("api/FHRSInfo")]
				[EnableCors("*", "*", "*", SupportsCredentials = true)]
				public class FHRSInfoController : ApiController
				{
					ApplicationDbContext context = new ApplicationDbContext();
					[Route("{culture}/{FHRSid}")]
					[ResponseType(typeof(FMBP_FHRS_Info))]
					public async Task<IHttpActionResult> Get(string culture, int FHRSid)
					{

I am  using .Net web api 2 controller and Postman GET works.

**Comment by nghuuphuoc** [comment]
What's the version of plugin you're using?
I tried a sample code and it works as expect:

![remote-get](https://cloud.githubusercontent.com/assets/4226036/8640934/5fb330b0-2933-11e5-8b73-67475ee7326d.png)

```javascript
username: {
    message: 'The username is not valid',
    validators: {
        notEmpty: {
            message: 'The username is required and can\'t be empty'
        },
        remote: {
            type: 'GET',
            url: 'remote.php',
            message: 'The username is not available'
        },
        stringLength: {
            min: 5,
            message: 'min 5 chars'
        }
    }
},
```
