### ISSUE TITLE
Form validation not working

### ISSUE THREAD

**Issue by amucino** [formvalidation/support#206]
I created a dummy page to test the script. I linked all the necessary files and copy/pasted the example code you have, when I click submit button no validation happens. What am I missing ?
Attached is a screenshot showing the included files on the left and the code to link them on the right. 
The rest is just copy/pasted code from the example (login) on your site. 
When I click "Submit" it submits the page and no validation is done. 
![screenshot](https://cloud.githubusercontent.com/assets/13330689/8670812/08319bd6-29ee-11e5-976c-4a279cff75fa.PNG)

**Comment by nghuuphuoc** [comment]
It seems that you have the correct set of files in the correct order.
I am afraid that the relative paths might not be correct.
Do you see any issues in the Console window of browser?

**Comment by amucino** [comment]
There is an error. Here is a screenshot

![error](https://cloud.githubusercontent.com/assets/13330689/8670977/3eee42d6-29ef-11e5-8cda-592dc0d54297.PNG)

**Comment by amucino** [comment]
This is the console error:

![error2](https://cloud.githubusercontent.com/assets/13330689/8671005/74c6a33a-29ef-11e5-97e7-42428aeb0932.PNG)

**Comment by amucino** [comment]
All paths seem correct though.

**Comment by nghuuphuoc** [comment]
The issue message `$ is undefined` means that jQuery is not loaded.
Please ensure that jQuery is included ONCE, in a correct path.
Your code:

```javascript
<head>
    <script src="../includes/jquery/jquery.min.js"></script>
</head>

<script src="jquery.min.js"></script> <!-- Maybe you need to remove this? -->
```

**Comment by amucino** [comment]
You were correct. Thank you for your help !
