### ISSUE TITLE
Validation not working on my own page

### ISSUE THREAD

**Issue by amucino** [formvalidation/support#207]
I got the example page working, unfortunately I am getting an error when trying to add the validation to an actual page in the system. The page is at the same level as the example I just used so the links to the css pages are the same and the error seems to be different. 
Right now I am just trying to validate the first item in my form. 

This is the code in my form and the script is:

-- form --

```
 <form action="<%=MM_editAction%>" method="POST" name="form1" class="form-horizontal">
```

-- form element --

```
<input name="subject" type="text" class="form-control" id="subject" size="30" maxlength="30"> 
```

-- script -- 

```
$(document).ready(function() {
    $('#form1').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            subject: {
				validators: {
                    notEmpty: {
                        message: 'Subject is required'
                    }
                }
            },
            
        }
    });
});
```

Attached is the error screenshot. Help is appreciated.
![error1](https://cloud.githubusercontent.com/assets/13330689/8671895/e3d17df2-29f6-11e5-875d-e8848e2fe1d5.PNG)

**Comment by nghuuphuoc** [comment]
The `Object doesn't support property or method formValidation` issue proves that you doesn't include the formValidation scripts correctly.

Please always try to place the scripts as following:

```
<head>
   ... Include CSS files in the head ...
</head>
<body>
... Your HTML markup ...

<!-- Javascript files, code should be placed at the bottom to decrease the page loading time -->
<script src=/path/to/jquery.min.js></script>
<script src=/path/to/bootstrap.min.js></script>
<script src=/path/to/formValidation/js/formValidation.min.js></script>
<script src=/path/to/formValidation/js/framework/bootstrap.min.js></script>

<script>
$(document).ready(function() {
     ...
});
</script>
</body>

**Comment by amucino** [comment]
This is my code, I think it looks good. I made sure that is the order of my code. 

HEAD:



	
	<link href="../includes/css/plugins/datapicker/datepicker3.css" rel="stylesheet">
	<link href="../includes/css/plugins/clockpicker/clockpicker.css" rel="stylesheet">


<link rel="stylesheet" href="../includes/formvalidation/dist/css/formValidation.min.css">


<script type="text/javascript" src="../includes/jquery/jquery-1.11.3.min.js"></script>


<script src="../includes/js/bootstrap.min.js"></script>


<script src="../includes/formvalidation/dist/js/formValidation.min.js"></script>
<script src="../includes/formvalidation/dist/js/framework/bootstrap.min.js"></script>


<script language="javascript" type="text/javascript">
 
</script>
<script language="javascript" type="text/javascript">
 
</script>
    
</head>

.. then my HTML .. 

Then javascript files:


   


<script src="../includes/js/inspinia.js"></script>
<script src="../includes/js/plugins/pace/pace.min.js"></script>
<script src="../includes/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>


<script src="../includes/js/plugins/datapicker/bootstrap-datepicker.js"></script>


<script src="../includes/js/plugins/clockpicker/clockpicker.js"></script>

<script>
        $(document).ready(function(){

		 $('#data_1 .input-group.date').datepicker({
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                calendarWeeks: true,
                autoclose: true
            });
            

            $('.clockpicker').clockpicker();
		});
 </script>
 

<script type="text/javascript" src="../includes/jquery/jquery-1.11.3.min.js"></script>


<script src="../includes/js/bootstrap.min.js"></script>


<script src="../includes/formvalidation/dist/js/formValidation.min.js"></script>
<script src="../includes/formvalidation/dist/js/framework/bootstrap.min.js"></script>


<script language="javascript" type="text/javascript">
 
</script>
<script language="javascript" type="text/javascript">
 
</script> 
    
<script>
$(document).ready(function() {
    $('#form1').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            subject: {
				validators: {
                    notEmpty: {
                        message: 'Subject is required'
                    }
                }
            },
            
        }
    });
});
</script>

**Comment by nghuuphuoc** [comment]
Please, please ensure the JS files are included ONCE.
In the code above, I saw that there're a lot of JS files are included in the head and the body (scripts) sections.

**Comment by amucino** [comment]
If I move all the scripts to the bottom and only leave the css on the top I get ALL sort of errors. Now my page is not even working well  :(

**Comment by nghuuphuoc** [comment]
:) If you don't follow the principle I mentioned in the last comment, you should try the following approach:

* Keep your `head` as current. The `head` will includes all CSS and JS files
* Then include your HTML
* Then the scripts at the bottom of page:

```
<script>
        $(document).ready(function(){

         $('#data_1 .input-group.date').datepicker({
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                calendarWeeks: true,
                autoclose: true
            });


            $('.clockpicker').clockpicker();
        });
 </script>

<script>
$(document).ready(function() {
    $('#form1').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            subject: {
                validators: {
                    notEmpty: {
                        message: 'Subject is required'
                    }
                }
            },

        }
    });
});
</script>
```

**Comment by amucino** [comment]
I did. Now no errors but validation does not occur. 

-- HEAD--
<head>


<link href="../includes/css/plugins/datapicker/datepicker3.css" rel="stylesheet">
<link href="../includes/css/plugins/clockpicker/clockpicker.css" rel="stylesheet">


<link rel="stylesheet" href="../includes/formvalidation/dist/css/formValidation.min.css">    



<script type="text/javascript" src="../includes/jquery/jquery-1.11.3.min.js"></script>

<script src="../includes/js/bootstrap.min.js"></script>
</head>

---- form and form element remained the same

-- SCRIPTS--


   


<script src="../includes/js/plugins/datapicker/bootstrap-datepicker.js"></script>


<script src="../includes/js/plugins/clockpicker/clockpicker.js"></script>


<script>
        $(document).ready(function(){

		 $('#data_1 .input-group.date').datepicker({
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                calendarWeeks: true,
                autoclose: true
            });
            

            $('.clockpicker').clockpicker();
		});
 </script>
 

<script src="../includes/formvalidation/dist/js/formValidation.min.js"></script>
<script src="../includes/formvalidation/dist/js/framework/bootstrap.min.js"></script>


<script language="javascript" type="text/javascript">
 
</script>
<script language="javascript" type="text/javascript">
 
</script> 
    
<script>
$(document).ready(function() {
    $('#form1').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            subject: {
				validators: {
                    notEmpty: {
                        message: 'Subject is required'
                    }
                }
            },
            
        }
    });
});
</script>

**Comment by amucino** [comment]
![head](https://cloud.githubusercontent.com/assets/13330689/8672354/72a80006-29fb-11e5-9ea7-0b87c2114244.PNG)

![scripts](https://cloud.githubusercontent.com/assets/13330689/8672376/9d6d2352-29fb-11e5-8ec1-d3c742d90a04.PNG)
![scripts2](https://cloud.githubusercontent.com/assets/13330689/8672377/9d6e3580-29fb-11e5-9f07-ce57c9886458.PNG)

**Comment by nghuuphuoc** [comment]
The validation doesn't happen because there's no form with `id="form1"`.
You should 

1) add `id="form1"` to your form:

```html
<form action="<%=MM_editAction%>" method="POST" name="form1" id="form1" class="form-horizontal">
```

2) Or change the form selector

```javascript
$('form[name="form1"]').formValidation(...);
```

**Comment by nghuuphuoc** [comment]
PS: When inserting the sample code here, don't paste it directly.
Wrap the sample code between _```_ and _```_, and you will see the code.

I have to change all code in your comments by my hand :(

**Comment by amucino** [comment]
:( ... I thought I had done that. Sigh ! ... maybe its time to step off the computer for now. It works ! Thanks !  It helped me cleanup my code too. Appreciate your patience ! 
Oh ... thanks for the tip. I'll do that next time.

**Comment by nghuuphuoc** [comment]
Haha, you're welcome :)
