### ISSUE TITLE
Validating date w date picker and time w time picker

### ISSUE THREAD

**Issue by amucino** [formvalidation/support#208]
Hi ... sorry for all the questions. I am sure once I get this basics 'down' it will be a smooth ride to add validation to the rest of the pages. So far VERY happy with how this works.

When validating a date it works fine, but If I make the field required and try to submit the form I get the error, so far so good. Then I use my date picker bootstrap calendar which puts the date in the field, the validation does not recognize I did this, it stays showing the error. It will stay like that with the submit button disabled until I TYPE the date in the field.

I am also trying to validate time in this format:  09:30

I am also using a script that shows a clock and then places the time in the field when I make my selection. 

1) How do I make the validation work for the date when using the date calendar picker I have
2) What would be the script to add time validation ? 

-- This is my date validation at the moment --

```
			 startdate: {
                validators: {
                    notEmpty: {
                        message: 'Start date is required'
                    },
                    date: {
                        format: 'MM/DD/YYYY',
                        message: 'The start date is not valid'
                    }
                }
            },
```

**Comment by nghuuphuoc** [comment]
When using FormValidation with other plugins, please follow [2 principles](http://formvalidation.io/examples/#compatibility).

These examples show how to use FormValidation with some popular datepickers:
* http://formvalidation.io/examples/bootstrap-datepicker/
* http://formvalidation.io/validators/date#datetime-picker-example
* http://formvalidation.io/examples/jquery-ui-datepicker/
* http://formvalidation.io/examples/pickadate/

I think it's better if you can look at the documentation and [examples](http://formvalidation.io/examples/) first :)

**Comment by amucino** [comment]
Ill check it out. How about time validation ? what would be the code for that ?  I am trying to find it in the documentation.

**Comment by amucino** [comment]
I don't think I am using any of those scripts. :(  
I added my code like this to validate the start date, but I got an error:

'''
$(document).ready(function() {
    $('#startdate').pickadate({
        format: 'mm/dd/yyyy',
        formatSubmit: 'mm/dd/yyyy',
        hiddenName: true
    });

    $('#startdate')
        .pickadate('picker')
        .on('render', function() {
            // http://amsul.ca/pickadate.js/api.htm#events-callbacks
            // Revalidate the start date field
            $('#form1').formValidation('revalidateField', 'startdate');
        });

    $('#form1').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        excluded: ':disabled',
        fields: {
            dob: {
                validators: {
                    notEmpty: {
                        message: 'The date of birth is required'
                    },
                    date: {
                        format: 'MM/DD/YYYY',
                        message: 'The date of birth is not a valid date'
                    }
                }
            }
        }
    });
});

'''

---- ERROR ---

SCRIPT438: Object doesn't support property or method 'pickadate'
File: Add.asp, Line: 904, Column: 5

**Comment by nghuuphuoc** [comment]
The examples just give you the idea of how to integrate FormValidation with other plugins.
So, if you're using other datepicker plugin, calling `. pickadate()` as above will raise the issue, of course.

> Then I use my date picker bootstrap calendar

Please tell me the link of that date picker plugin.
I will spend time to help you.

Again, please wrap the code between _```_, not '''.

**Comment by amucino** [comment]
Thank you. Ill put things together. I am having a hard time with this. I am trying to create a 'template' where I have all my validations for different types, so that I can later on just copy/paste the code and use it in all my system when needed. 
What is your time zone ? I am in Eastern Time. Just so I know how much time I have left today.

**Comment by amucino** [comment]
I am using a template that perhaps is using some bootstrap code. 

http://wrapbootstrap.com/preview/WB0R5L90S

I am using the date picker, the date range picker and the clock picker. 

This are the most difficult validation seems to me, the rest of the fields should be fairly straight forward. But I have dates and date pickers all over my system so its important to get those to work well. 

Would you like for me to just email you or use my template code and paste it here ?

**Comment by amucino** [comment]
Closing this because of duplicate.
