### ISSUE TITLE
select with multiple and required attributes don't shows required icon

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#21]
_From @phlegx on February 9, 2015 17:2_

Hi!

I try out ```formvalidation``` with a ```select``` tag with the possibility to select multiple options. The choice is required. I use ```bootstrap-select```.

```html
<select name="colors" class="form-control"  required="required" 
 multiple="multiple" title="Choose min. one color" data-fv-choice-min="1">
      <option value="black">Black</option>
      <option value="blue">Blue</option>
      <option value="green">Green</option>
      <option value="orange">Orange</option>
      <option value="red">Red</option>
      <option value="yellow">Yellow</option>
      <option value="white">White</option>
</select>
```

**The required asterisk is not shown on the select box. Any idea?**

_Copied from original issue: formvalidation/formvalidation#1418_

**Comment by nghuuphuoc** [comment]
@phlegx
You forgot to enable the ```choice``` validator by setting ```data-fv-choice="true"```.
Also, since the field is required, you don't need to use both [notEmpty](http://formvalidation.io/validators/notEmpty/) (via ```required="required"```) and [choice](http://formvalidation.io/validators/choice/) validator at the same time. 

Here are 
* fiddle using choice validator: http://jsfiddle.net/nghuuphuoc/4unyeLd8/
* fiddle using notEmpty validator: http://jsfiddle.net/nghuuphuoc/4unyeLd8/1/

If you use with Bootstrap Select, ensure that you follow the [principles](http://formvalidation.io/examples#compatibility).
See the [example](http://formvalidation.io/examples/bootstrap-select/) and [jsfiddle](http://jsfiddle.net/nghuuphuoc/4unyeLd8/3/).

**Comment by phlegx** [comment]
Thx! :D
