### ISSUE TITLE
Typeahead + Dynamic Field Example

### ISSUE THREAD

**Issue by Erocanti** [formvalidation/support#213]
An example of dynamic fields with typeahead would be greatly appreciated. Thanks

**Comment by nghuuphuoc** [comment]
There's not an example of using Typehead and dynamic field together, but you can take a look at these separated one:
* http://formvalidation.io/examples/typeahead/
* http://formvalidation.io/examples/adding-dynamic-field/

I hope it helps you.

**Comment by Erocanti** [comment]
Thanks, reinitializing typeahead on 'added.field.fv' got it working.

**Comment by nghuuphuoc** [comment]
Thank for the idea. It will work with other plugins too.
I added new [Using other plugin for added fields](http://formvalidation.io/examples/adding-dynamic-field/#using-other-plugin-for-added-fields) section :+1:
