### ISSUE TITLE
adding-dynamic-field

### ISSUE THREAD

**Issue by mkondakow** [formvalidation/support#214]
Need help on how to pass the array of dynamic fields to a mysql database.

from your example  http://formvalidation.io/examples/adding-dynamic-field/

Is there a call back function? 

Thank you.
Mickey

**Comment by nghuuphuoc** [comment]
When submitting the form, all of all added fields (`option[]`, as seen in the [example](http://formvalidation.io/examples/adding-dynamic-field/#adding-fields-with-same-names)) are also sent to your server as usual.
The server then can connect to the database, and insert these fields to the database.

**Comment by mkondakow** [comment]
Thank You Phuoc for the quick reply.

The following code works to store form values in my database


When using Adding fields with same names  name= option[] works fine.


Foreach (_POST[option]as $key=>$value)


{ My database insert code here}


------------------------------------------------------------------------------------------------------


But when using Adding fields with different names : example from your code names = book[i].title Does not work.


I don’t know how to handle name = book[i].title (The “.” is confusing me)


What is the proper syntax for the _POST[???????]


Foreach (_POST[book.title]as $key=>$value)  ---Not working


{ My database insert code here}


Thank You


Mickey


Canada

**Comment by nghuuphuoc** [comment]
It's up to you to choose a way of naming fields. The field name can be in various kinds:
* same names (`option[]`, for example)
* or different names with index (`book[index].title`, `book[index].price`, , for example)
* or different names without index (`bookTitle[]`, `bookPrice[]`, for example)

You can choose the way that it's easy for you to get the submitted form data in the server side.

Also, no matter what kind of naming convension you decide to use, you can use 

```php
var_dump($_POST);
```

to see what you get on server (assume that you're using PHP).

**Comment by mkondakow** [comment]
Thank you
That's what I did to solve the problem.
I just have never seen the use of a period in a variable.
One more question.
How do I upgrade my version of for validation to ver 6 ?
Is there a free download for owners of yor software?

Thank you once again for the quick reply. You have a great product!
Mickey

**Comment by nghuuphuoc** [comment]
I'm glad that you found the solution.
In order to use v0.6.0 or later versions, you have to [purchase](http://formvalidation.io/download/) it (this is life time order, means that you are free to upgrade to ALL feature releases).

**Comment by mkondakow** [comment]
Hello Phuoc

 

I just Checked my license and its ver. 6.2

On your web site you say that there is an upgrade to 6.3

Do you send notifications with download link? Where do I get the link?

Thanks

Mickey

P.S. What country are you in?

**Comment by nghuuphuoc** [comment]
So you can use the previous download link to get new version :)
If you can't find that email, just [email me](mailto: phuoc@huuphuoc.me) your email address you used to purchase, then the new download link will be sent to your mailbox.

**Comment by mkondakow** [comment]
I found the email. All is good.

It was sent from Selfly  not formvalidation.

P.S.


If any of you users need a solution for submitting data to a database for your “Adding fields with different names”


Let me know.

**Comment by Ottiko** [comment]
https://github.com/formvalidation/support/issues/261Here I try similar function, but didn't work... Maybe it's a bug...
Thx.
Respect ))

**Comment by kittu421** [comment]
I am using dynamic fields with different names, I am facing issues in passing these values to the php as i am getting only the last field value as stated in the issue # https://github.com/formvalidation/support/issues/325#issuecomment-173817459

Any help will be great help ful for me
