### ISSUE TITLE
regexp returns false but the field is valid

### ISSUE THREAD

**Issue by rarutu** [formvalidation/support#216]
this is the code for my input

<input type="text" class="form-control" id="client[username]" name="client[username]" placeholder="Client Username" data-fv-notempty="true" data-fv-stringlength-trim="true" data-fv-stringlength="true" data-fv-stringlength-min="4" data-fv-promise="true" data-fv-promise-promise="uniqueNewLogin" data-fv-regexp="true" data-fv-regexp-regexp="^[a-zA-Z]+$" required="" />

function uniqueNewLogin(value, validator, $field) {
            var dfd   = new $.Deferred();
            jQuery.ajax({
                url: '/members/update/uniqueNewLogin',
                method: 'post',
                data: {
                    input: {
                        index: $field[0].id,
                        value: value
                    }
                },
                complete: function(data) {
                    if (parseInt(data.responseText) <= 0) {
                        dfd.resolve({ valid: true });
                    } else {
                        dfd.reject();
                    }
                }
            });
            return dfd.promise();
        };

so the input should be valid only for upper and lower case characters ... but it appear valid for anything .. although the regexp validator returns false (i checked that with a console.log on line 6595)

thanks,
Rares

**Comment by nghuuphuoc** [comment]
> although the regexp validator returns false

I think you're using the [promise](http://formvalidation.io/validators/promise/) validator, not [regexp](http://formvalidation.io/validators/regexp/) one.

I also suggest you should use the [remote](http://formvalidation.io/validators/remote/) validator in this case:

```javascript
$('#yourForm').formValidation({
    framework: 'bootstrap',
    fields: {
        fieldNameHere: {
            validators: {
                remote: {
                    url: '/members/update/uniqueNewLogin',
                    type: 'POST',
                    data: function(validator, $field, value) {
                        // validator is FormValidation instance
                        // $field is the field element
                        // value is the field value

                        // Return an object
                        return {
                            index: $field[0].id,
                            value: value
                        };
                    }
                }
            }
        }
    }
});
```

When using `remote` validator, you need to adjust the back-end, `/members/update/uniqueNewLogin`, to return an encoded JSON of array `{ "valid": true }` or `{ "valid": false }`.
