### ISSUE TITLE
Does the latest FormValidation support Jquery Form - jquery.form.js?

### ISSUE THREAD

**Issue by PritiShah** [formvalidation/support#218]
Hello ,

I have this below method that works without FormValidation but not with it.

It is basically a jquery Ajax Form, that I have used to send multiple input files.

functions.js

function submitNewCaseForPendingStatus(targetUrl, form) {
	
    var isFormValid = $('#' + form).data('formValidation').validate().isValid();
	
	if (isFormValid) {

	    if (validateCorrectNoOfAnswers()){
	
		postAjaxDataWithImageFile(null, 'content', targetUrl, form, null, function(data){
			
			scrollWindowToTop();
		});
		
	   }
		
	}		
	
}

function validateCorrectNoOfAnswers() {
	// To check if atleast one answer is marked correct.
	
       if (noOfCorrectAnswers > 1 || noOfCorrectAnswers < 1) {
		alert("Please mark only/atleast one Answer as correct");
		return false;
	} else {
		return true;
	}

}

function postAjaxDataWithImageFile(initiatingElement, targetElement, targetUrl,
		form, additionalParamMap, successCallback) {

	var $targetElement = $('#' + targetElement);
	var $form = $('#' + form);

	$form.ajaxForm(
			{

				type : "POST",
				enctype : "multipart/form-data",
				contentType : false,

				url : targetUrl,

				success : function(data) {
					processRedirect(data);

					$targetElement.html(data);
					$targetElement.show();

					if (successCallback != null) {
						successCallback(data);
					}
				},
				error : function(xhr, httpRequest, textStatus, errorThrown) {
					var errorId = xhr.getResponseHeader("errorId");

					var errorMsg = xhr.getResponseHeader("errorMessage");

					if (errorId != null && errorId != undefined) {
						$("#page_error").html(
								"An unexpected error has occurred.  Error Id: "
										+ errorId);
					} else {
						$("#page_error").html(
								"An unexpected error has occurred.");

					}
				}

			}).submit();

}

validations.js

function validateCaseSubmissionForPendingStatusForm(){
	
	$('#submitCasePendingStatusForm').formValidation({
		 // Only disabled elements are excluded
        // The invisible elements belonging to inactive tabs must be validated
        excluded: [':disabled'],
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
        	caseName: {
                validators: {
                    notEmpty: {
                        message: 'Case Name is Required.'
                    }
                }
            },
            caseLearningObj:{
            	validators: {
                    notEmpty: {
                        message: 'Case Learning Objective is Required.'
                    }
                }
            },
            questionDesc:{
            	validators: {
                    notEmpty: {
                        message: 'Question Description is Required.'
                    }
                }
            },
            questionToAsk:{
            	validators: {
                    notEmpty: {
                        message: 'Question is Required.'
                    }
                }
            },
            author:{
            	validators: {
                    notEmpty: {
                        message: 'Author is Required.'
                    }
                }
            },
            answerDesc0:{
            	validators: {
                    notEmpty: {
                        message: 'Answer Description Required.'
                    }
                }
            },
            answerExplanation0:{
            	validators: {
                    notEmpty: {
                        message: 'Answer Explanation Required.'
                    }
                }
            }
    
        }   
             
        
	 
	});

return true;
}

JSP  - snippet

		<button type="submit" class="btn btn-primary btn-lg pull-right spacer-right" onclick="submitNewCaseForPendingStatus('submitNewCaseForPendingStatus.html','submitCasePendingStatusForm'); return false;">Submit Case</button>

Thanks.

**Comment by PritiShah** [comment]
Thank you for the update.

Many of my web pages use jquery.ajaxForm for uploading files. 

Do you have an approx. time for the v- 0.7 release? Is there any work around to this for now?

Thanks,
Priti

**Comment by nghuuphuoc** [comment]
I added the [Using jQuery Form plugin](http://formvalidation.io/examples/ajax-submit/#using-jquery-form-plugin) section.
I tested my example and it worked with latest version of FormValidation (v0.6.3) and jQuery Form (v3.51).

Your code might look like as following:

```html
<!-- Including jQuery Form plugin -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>

<form id="submitCasePendingStatusForm" method="post" class="form-horizontal">
    ...
    <button type="submit" class="btn btn-primary btn-lg pull-right spacer-right">Submit Case</button>
</form>
```

Note that there's no `onclick` handler for the submit button. Instead we will trigger the `success.form.fv` to handle form submission:

```javascript
$('#submitCasePendingStatusForm')
    .formValidation({
        ... options ...
    })
    .on('success.form.fv', function(e) {
        // Prevent form submission
        e.preventDefault();

        // The form is valid now
        // If you need to perform addition checking
        if (validateCorrectNoOfAnswers()) {
            var $form = $(e.target);
            $form.ajaxSubmit({
                // You can change the url option to desired target
                url: $form.attr('action'),
                type: 'POST',
                dataType: 'json',
                success: function(responseText, statusText, xhr, $form) {
                    // Process the response returned by the server ...
                    // console.log(responseText);
                    
                    // Do whatever you want here
                    // ...
                },
                error: function() {
                    // Do whatever you want here
                    // ...
                }
            });
        }
    });
```

**Comment by PritiShah** [comment]
Can I have the addn checking inside .on('success.form.fv',) event , as a function in another JS and call that function from inside .on('success.form.fv',) event ?  I did try it, but didnt work. 

If you see my functions.js, this method - postAjaxDataWithImageFile
  $form.ajaxForm  has a .submit() at the end. Will that pose any problem, since it will return true or false to 'success.form.fv' event and it might go into stack error?

Thanks for your help and clarification.

Priti

**Comment by nghuuphuoc** [comment]
Priti,
My suggestion is that
1) Always handle additonal things inside `success.form.fv` event instead of using custom `onclick` event handler for the submit button. By doing this:
* The `success.form.fv` event is triggered ensure that the entire form is already valid
So we don't need to care about checking if the form is valid or not

```javascript
var isFormValid = $('#' + form).data('formValidation').validate().isValid();
if (isFormValid) {
    ...
}
```

* We don't need to worry about which handler of `success.form.fv` or `onlick` event will come first.
Place everything inside `success.form.fv` will give us 1-way workflow, therefore it's more easy for debugging.

2) Inside `success.form.fv` event hanlder, just simply place some `console.log(message here)` to see where we go.
It's simple but effective.

3) You don't need to worry two separated `ajaxForm()` and `submit()`.
`ajaxSubmit()` does everything.

4) Let's make it work first. You might need to move the code inside separated functions to inside `success.form.fv` first to make it work first.
Then make some refactoring later.

So, try this first:

```javascript
$('#submitCasePendingStatusForm')
    .formValidation({
        ... options ...
    })
    .on('success.form.fv', function(e) {
        // Prevent form submission
        e.preventDefault();

        console.log('The form is valid. DO YOU SEE THIS MESSAGE?');

        // The form is valid now
        // If you need to perform addition checking
        if (validateCorrectNoOfAnswers()) {
            console.log('The answers are correct. DO YOU SEE THIS MESSAGE?');

            var $form = $(e.target);
            $form.ajaxSubmit({
                // You can change the url option to desired target
                url: $form.attr('action'),
                type: 'POST',
                dataType: 'json',
                success: function(responseText, statusText, xhr, $form) {
                    console.log('Submitted successfully. DO YOU SEE THIS MESSAGE?');
                
                    // Process the response returned by the server ...
                    // console.log(responseText);

                    // Do whatever you want here
                    // ...
                },
                error: function() {
                    // Do whatever you want here
                    // ...
                }
            });
        }
    });
```

If it works, then change the `postAjaxDataWithImageFile()` method a little bit:

```javascript
function postAjaxDataWithImageFile(initiatingElement, targetElement, targetUrl, form, additionalParamMap, successCallback) {
    var $targetElement = $('#' + targetElement);
    var $form = $('#' + form);
    
    // Use ajaxSubmit
    $form.ajaxSubmit({
        ...
    });
}
``` 

and use it inside `success.form.fv` event hanlder:

```javascript
$('#submitCasePendingStatusForm')
    .formValidation({
        ... options ...
    })
    .on('success.form.fv', function(e) {
        // Prevent form submission
        e.preventDefault();

        console.log('The form is valid. DO YOU SEE THIS MESSAGE?');

        // The form is valid now
        // If you need to perform addition checking
        if (validateCorrectNoOfAnswers()) {
            console.log('The answers are correct. DO YOU SEE THIS MESSAGE?');

            // Remember to set the targetUrl and form here
            postAjaxDataWithImageFile(null, 'content', targetUrl, form, null, function(data) {
                console.log('Submitted successfully. DO YOU SEE THIS MESSAGE?');
                scrollWindowToTop();
            });
        }
    });
```

**Comment by PritiShah** [comment]
Hello, thank you very much for your clarification and suggestion.

Turns out my $form.ajaxForm(....).submit() method does not work with formValiation framework.
I just changed to  $form.ajaxSubmit (... ) as you suggested, and its working as expected. I wonder why I had the  $form.ajaxForm(....).submit() to begin with, but well it's something that i had written very long time back. I think if you could mention it in your ajaxForm example, it might help some ajaxForm users.

Thanks again for superb help!
Priti

**Comment by nghuuphuoc** [comment]
Awesome! :+1:
