### ISSUE TITLE
Different and identical validators: support selectors

### ISSUE THREAD

**Issue by brianlenz** [formvalidation/support#219]
It would be a very nice enhancement to the different and identical validators if they supported selectors for fields that should be different or identical. Right now, you must enter specific field names separated by commas. It would be quite powerful (and very useful to us) if you alternatively supported selectors to compare against so that the set of fields to compare against doesn't have to be preset.

This would be useful on forms that have dynamic numbers of elements where you want to require all values to be unique, for example.

**Comment by nghuuphuoc** [comment]
Thank for the suggestion.
I added the [Asking fields to be unique](http://formvalidation.io/examples/asking-fields-be-unique/) example which will be useful to you.

**Comment by brianlenz** [comment]
Ah, thank you for that example! I hadn't seen it yet, but I will be checking it out.

**Comment by nghuuphuoc** [comment]
You hadn't seen it because I made it for you. It's just available after your suggestion :)

**Comment by brianlenz** [comment]
Oh, even better. Thank you!! :D

**Comment by josuelmm** [comment]
I need you help. I have a problem validating different select the same data
