### ISSUE TITLE
lenght validation nor working

### ISSUE THREAD

**Issue by amucino** [formvalidation/support#220]
I am trying to validate the field 'to' for length and to be required, I am using the code found in the length example but not working. This is what I have:
```
         $(document).ready(function(){

             $("#form1").validate({
                 rules: {
                     to: {
                         validators: {
                    required: true,
					stringLength: {
                        max: 50,
                        message: 'The full name must be less than 50 characters'
                    }
                }


                     },
				 }
             });
        });
```
Any help is appreciated.

**Comment by nghuuphuoc** [comment]
I think you're using another validators.
FormValidation doesn't provide something called `validate` or `rules`.

**Comment by amucino** [comment]
what is the link to the page that has the types of validations so I can make sure I have the correct link ?

**Comment by nghuuphuoc** [comment]
You should read the documentation first:
http://formvalidation.io/validators/stringLength/

**Comment by amucino** [comment]
I did somehow the script got mixed with another validation script. It's working now. .
