### ISSUE TITLE
Validation with type=reset

### ISSUE THREAD

**Issue by Ottiko** [formvalidation/support#221]
When I filled the form, and click reset type button
```<button type="reset">Reset</button>```
validation can't to check this event.
Please check.
![reset](https://cloud.githubusercontent.com/assets/7046596/8857647/ff24db50-3183-11e5-83e7-935b264f813d.jpg)

**Comment by nghuuphuoc** [comment]
You have to handle this manually with the [resetForm()](http://formvalidation.io/api/#reset-form) method:

```javascript
$('#resetButton').on('click', function() {
    // Reset the form
    $('#yourForm').formValidation('resetForm', true);
});
```

**Comment by Ottiko** [comment]
Thx.

**Comment by Ottiko** [comment]
resetForm() is reset all validation fields, and if I want:

1. To reset only one validation field (user_name), with all options (notEmpty, regexp)
2. To reset only one validation field (notEmpty), only one option (notEmpty)
```
	user_name: {
	    validators: {
	        notEmpty: {
        		message: 'Empty'
	        },
	        regexp: {
	            regexp: '^[a-zA-Z]+$',
	            message: 'Error'
	        }
	    }
	},
```

And I want to enabled: true,
```
    notEmpty: {
        enabled: false,
        message: 'Empty'
    },
```
When same event is do exp.
```
    $("#TypesTab li a").on("click", function () {
        enabled: true,
    });
```

Can I do it?

**Comment by nghuuphuoc** [comment]
> 1. To reset only one validation field (user_name), with all options (notEmpty, regexp)
> 2. To reset only one validation field (notEmpty), only one option (notEmpty)

(1) is possible meanwhile (2) is not.

You can use the [resetField()](http://formvalidation.io/api/#reset-field) method.

**Comment by Ottiko** [comment]
(2) This way is work $('#signUpForm').formValidation('updateOption', 'gender', 'notEmpty', 'enabled', true) or $('#signUpForm').formValidation('enableFieldValidators', 'gender', true, 'notEmpty') but when I call this method my field input is already show error status focus, but I think need show only when I start to fill anythink...

Can I use same method which clear check, If can, I use this after updateOption or enableFieldValidators
