### ISSUE TITLE
Upgrading from earlier version

### ISSUE THREAD

**Issue by crumpley** [formvalidation/support#222]
I have an earlier version of the validator called bootstrapValidator.
I purchased the current version and replaced the old .js files with the new formValidation files.

All of the form validations work fine. However, the older version calls a submitHandler function for form submission that does not get called in this new version.

What do I need to do to handle form submission with this new version?

**Comment by nghuuphuoc** [comment]
First of all, thank for purchasing the plugin.

* The `submitHanlder` was [removed from v0.5.0](http://formvalidation.io/news/upgrading-to-v0.5.0/).

In v0.4.5 and earlier versions:

```javascript
$(form).bootstrapValidator({
    submitHandler: function(form, validator, submitButton) {
        ...
    }
});
```

Now:

```javascript
$(form)
    .formValidation({
        // Removing submitHandler option
    })
    .on('success.form.fv', function(e) {
        // Prevent form submission
        e.preventDefault();

        var $form        = $(e.target),
            validator    = $form.data('formValidation');

        // Do whatever you want here ...
    });
```

See an [example](http://formvalidation.io/examples/ajax-submit/).

* To upgrade to latest v0.6.x, you should follow the [Upgrading to v0.6.0](http://formvalidation.io/news/upgrading-to-v0.6.0/) instruction.
