### ISSUE TITLE
Dynamic forms : enabling

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#23]
_From @haldiggs on February 9, 2015 23:24_

Sorry, this isn't really an issue but more of a question. I didn't see anywhere else to ask. I have a form that I am loading dynamically (partial). I tried `$(form).data('formValidation').resetForm();` but nothing seems to make the controls respect the validation.

The validation code lives in a separate js file so its obvious it won't get initialized upon the first screen load. It might just be the selectors. I'm using bootstrap and the controls are in this format:

	<div class="row">
		<div class="col-md-12">
			<input type="text" name="idTest" id="idTest" />
		</div>
	</div>
is it simply that its not in perfect bootstrap form? with a form-group class?

_Copied from original issue: formvalidation/formvalidation.io#10_

**Comment by nghuuphuoc** [comment]
@haldiggs
Since the field is placed inside ```col-md-12``` div, you need to set [row](http://formvalidation.io/settings/#field-row) option.
See http://formvalidation.io/getting-started/#complex-form

```javascript
$(form).formValidation({
    framework: 'bootstrap',
    fields: {
        idTest: {
            row: '.col-md-12',
            validators: {
                ...
            }
        }
    }
});
```

**Comment by haldiggs** [comment]
thanks I see that option but I think the original question still stands. I load the controls (HTML) after the javascript files have been run. So I need to initialize the validation after this. I tried to execute 

`$('#myform').data('formValidation').validate();`

I get an error `Unable to get property 'find' of undefined or null reference`. I was guessing this is because the controls do not have the initialized validation.

I tried running a script like below...

	$('#myform')
		.formValidation({
			framework: 'bootstrap',
			excluded: ':disabled',
			message: 'This value is not valid.',
			fields: {
				'Customer.FirstName': {
					row: '.col-md-6',
					excluded: false,    // Don't ignore me
					validators: {
						notEmpty: {
							message: 'At least one Id is required'
						},
					}
				}
			}
		});

but I am still getting the same error `Unable to get property 'find' of undefined or null reference`. I need to know what its trying to find in order to correct the issue.

**Comment by haldiggs** [comment]
ok I think I know what is wrong. Maybe you can tell me what to do to make it work :)

if I run the options

	$('#ifaWiz2')
		.formValidation({
			framework: 'bootstrap',
			excluded: ':disabled',
			message: 'This value is not valid.',
			fields: {
				'Customer.FirstName': {
					row: '.col-md-6',
					excluded: false,    // Don't ignore me
					validators: {
						notEmpty: {
							message: 'At least one Id is required'
						},
					}
				}
			}
		});
when the form is first loaded then everything works. However after I replace the controls inside the form using ajax.done()... 

	ifaCustomer.html("");
	ifaCustomer.append(data);

The form still retains the validation settings, but the controls have now been replaced. It seems I need to remove the forms validation and replace it. Re-running the validation options do not re-write the validation settings.

I adjusted some code on line 1332

	var $parent = $field.closest(row);
	if ($parent.length == 0)
        {
		var n = $field.prop("name");
		throw new Error('Cannot find \'' + n + '\' using the row selector \'' + row + '\'.');
	}

which helped me see the issue. Maybe I cannot use dynamic html?

**Comment by haldiggs** [comment]
$('#ifaWiz2')
				.formValidation({
					framework: 'bootstrap',
					excluded: ':disabled',
					message: 'This value is not valid.',
					fields: {
						'Customer.FirstName': {
							validators: {
								notEmpty: {
									message: 'First Name is required'
								},
							}
						},
						'Customer.LastName': {
							validators: {
								notEmpty: {
									message: 'Last Name is required'
								},
							}
						}
					}
				});
I made this work by running it right after I loaded the html in the ajax done() method.

**Comment by nghuuphuoc** [comment]
> I made this work by running it right after I loaded the html in the ajax done() method

That's the solution!

**Comment by DaleMckeown** [comment]
FYI nghuuphuoc, this is te exact same issue that happens when the Google reCaptcha times out, or if the recaptcha is reset.
