### ISSUE TITLE
Changing the default message

### ISSUE THREAD

**Issue by SigalZ** [formvalidation/support#231]
Hi,
I am trying to change the default message, but it keeps getting the default message you set as default and not mine.

My code:
`formValidation({
                framework: 'bootstrap',
                excluded: ':disabled',
                message: 'This field is required',`

I get the message: 'Please enter a value.'

Why is that?

**Comment by nghuuphuoc** [comment]
Thank you for reporting.
I can confirm that it's a bug and will be fixed in the next v0.7.0 version.

**Comment by SigalZ** [comment]
Thank you. I just went and changed it in your code for now.

**Comment by nghuuphuoc** [comment]
Done. 
[v0.7.0](http://formvalidation.io/news/v0.7.0-released/) is released. You can use the previous download link to get new version.
