### ISSUE TITLE
Wrong validation message for stringlength validator

### ISSUE THREAD

**Issue by ochnygosch** [formvalidation/support#234]
When using the stringlength validator with the maxlength or minlength constraint, the displayed error message is wrong.

For example:
    &lt;input name="test" data-fv-stringlength="true" data-fv-stringlength-min="6" />
yields the error message: "Please enter more than 6 characters" but the any string containing 6 characters is accepted. 
So the error message should rather be:
"Please enter at least 6 characters".
The same is true for maxlength:
&lt;input name="test" data-fv-stringlength="true" data-fv-stringlength-max="9" />
yields "Please enter less than 9 characters", when 9 characters are accepted.

**Comment by nghuuphuoc** [comment]
Thanks for reporting the issue. In the next v0.7.0, the default message will be adjusted.

* If only `min` option is used, for example `min=6` (`data-fv-stringlength-min="6"`), the message will be
`Please enter more than 5 characters`.

* If only `max` option is used, for example `max=9` (`data-fv-stringlength-max="9"`), the message will be
`Please enter less than 10 characters`.

* If both `min` and `max` option are used, the default message is `Please enter value between 6 and 9 characters long`.

**Comment by nghuuphuoc** [comment]
Done. 
[v0.7.0](http://formvalidation.io/news/v0.7.0-released/) is released. You can use the previous download link to get new version.

**Comment by ochnygosch** [comment]
Thanks. Works as expected.
