### ISSUE TITLE
File name with the wrong country language code "be_FR" should be "fr_BE"

### ISSUE THREAD

**Issue by Ronan-Lenor** [formvalidation/support#235]
as writed in the title. the language is "fr"ench in the country "BE"LGIUM.

same problem with "be_NL" which should be "nl_BE"

All code is here:
https://msdn.microsoft.com/en-us/library/ee825488%28v=cs.20%29.aspx

**Comment by nghuuphuoc** [comment]
Thank you so much.
From next v0.7.0, the language files and their definitions will be changed as follow

Old   | New
------|------
be_FR | fr_BE
be_NL | nl_BE
gr_EL | el_GR

**Comment by nghuuphuoc** [comment]
[Done](http://formvalidation.io/getting-started/#language-packages).
