### ISSUE TITLE
Captcha with ASP code

### ISSUE THREAD

**Issue by amucino** [formvalidation/support#236]
Hi,

I am trying to use Captcha add-on.

http://formvalidation.io/addons/recaptcha1/

But the example uses PHP. I am using ASP. Is there any example with ASP that I can use as reference ? 

Help is appreciated. 

BTW - Not that I have learned how to use the script I LOVE the validation !!! 

Aleks

**Comment by nghuuphuoc** [comment]
It's recommended to use the new version of Google reCaptcha which is also supported by [recaptcha2](http://formvalidation.io/addons/recaptcha2/).

Anyway, if you want to integrate with other server side, you should try the following plugins from Google:

* Classic ASP: https://developers.google.com/recaptcha/old/docs/asp
* ASP.Net: https://developers.google.com/recaptcha/old/docs/aspnet

**Comment by amucino** [comment]
Yes. I got it working thanks so much !
