### ISSUE TITLE
field selector not working

### ISSUE THREAD

**Issue by ale1981** [formvalidation/support#240]
I am using the following code to validate 3 input fields, the form is also attached to jquery steps, the rest of the validation is working great but no matter what I can't get the selector working with a class ".phone-group".

        var form = $("#newClientForm");
        form.steps({
                cssClass: 'wizard',
                enableCancelButton: true,
                headerTag: "h3",
                bodyTag: "section",
                transitionEffect: "slideLeft",
                titleTemplate: '#title#',
                labels: {
                    finish: "Save Client"
                },
                onStepChanging: function (e, currentIndex, newIndex)
                {
                    var fv         = form.data('formValidation'),
                        $container = form.find('section[data-step="' + currentIndex +'"]');

                    // Validate the container
                    fv.validateContainer($container);

                    var isValidStep = fv.isValidContainer($container);
                    if (isValidStep === false || isValidStep === null) {
                        return false;
                    }

                    return true;
                },
                onFinishing: function (e, currentIndex)
                {
                    var fv         = form.data('formValidation'),
                        $container = form.find('section[data-step="' + currentIndex +'"]');

                    // Validate the last step container
                    fv.validateContainer($container);

                    var isValidStep = fv.isValidContainer($container);
                    if (isValidStep === false || isValidStep === null) {
                        return false;
                    }

                    return true;
                },
                onFinished: function (e, currentIndex)
                {

                },
                onCanceled: function(e) {

                }
            })
            .formValidation({
                framework: 'bootstrap',
                icon: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                },
                excluded: ':disabled',
                fields: {
                    postcode: {
                        validators: {
                            notEmpty: {
                                message: 'Please enter a valid postcode'
                            },
                            zipCode: {
                                country: 'GB',
                                message: 'Please enter a valid %s postcode'
                            }
                        }
                    },
                    date_of_birth: {
                        validators: {
                            notEmpty: {
                                message: 'Please select a valid Date of Birth'
                            },
                            date: {
                                format: 'DD/MM/YYYY',
                                message: 'Please select a valid Date of Birth'
                            }
                        }
                    },
                    email: {
                        validators: {
                            emailAddress: {
                                message: 'Please enter a valid email address'
                            }
                        }
                    },
                    phones: {
                        selector: '.phone-group',
                        validators: {
                            callback: {
                                message: 'You must enter at least one contact number',
                                callback: function(value, validator, $field) {
                                    var isEmpty = true,
                                        // Get the list of fields
                                        $fields = validator.getFieldElements('phones');
                                    for (var i = 0; i < $fields.length; i++) {
                                        if ($fields.eq(i).val() !== '') {
                                            isEmpty = false;
                                            break;
                                        }
                                    }

                                    if (!isEmpty) {
                                        // Update the status of callback validator for all fields
                                        validator.updateStatus('phones', validator.STATUS_VALID, 'callback');
                                        return true;
                                    }

                                    return false;
                                }
                            }
                        }
                    }
                }

**Comment by ale1981** [comment]
After reading through a few more support issues I found the problem on another thread.
The input boxes also had required, minlength and maxlength attribute, after I removed them it worked, so it seems that (some?) input attributes and JS settings don't work together?

**Comment by nghuuphuoc** [comment]
Exactly. When using `selector` option, don't use the [HTML attributes](http://formvalidation.io/examples/html5/) which enables the validators automatically.

**Comment by ale1981** [comment]
I think this should be documented, unless I missed it when I was looking through the docs?

**Comment by nghuuphuoc** [comment]
I will update the document :+1:

**Comment by nghuuphuoc** [comment]
The [selector option](http://formvalidation.io/settings/#field-selector) usage is updated.
