### ISSUE TITLE
Dynamically adding lots of fields is very slow

### ISSUE THREAD

**Issue by Mike-Dax** [formvalidation/support#241]
Hi,

I've got a form which uses ajax to grab a list of checkboxes after the user types in some input further up the form. The only validation I need to do with the checkboxes is to make sure one of them is clicked. I'm adding them like this:

    $("[name='checkboxes[]']").each(function() {
        $('#form').formValidation('addField', $(this));
    });

And the validation is as follows:

    'checkboxes[]': {
                validators: {
                    choice: {
                        min: 1,
                        message: 'Please check at least one of the checkboxes'
                    }
                }
            },

My problem is, sometimes 400 or so are returned, and it takes 25+ seconds for the validation to initialise. 

Is there a quicker way to do this, or an alternate way I can do the validation?

**Comment by nghuuphuoc** [comment]
What happens if you change
```javascript
$("[name='checkboxes[]']").each(function() {
    $('#form').formValidation('addField', $(this));
});
```

to

```javascript
$('#form').formValidation('addField', '[name="checkboxes[]"]');
```

**Comment by Mike-Dax** [comment]
Incredible speed improvement. Thank you very much, I didn't realise we could use selectors there!

**Comment by nghuuphuoc** [comment]
Actually, the second parameter of `addField()` can be the field name.
So you can do the same thing with:
```javascript
$('#form').formValidation('addField', 'checkboxes[]');
```
