### ISSUE TITLE
is Valid without a "submit" button

### ISSUE THREAD

**Issue by manovraresoft** [formvalidation/support#242]
I have been on the plugin site for 2 hours trying to find a way to validate the form without a type="submit" button...  need to validate on a type='button'  or even in a hyperlink, just need the name of a function i can invoke to test validity.

I am using bootstrap 3  I have a select box.  Want to make sure it has something selected.

```html
<form id='mainform'>
   <select id="PeopleType" name="PeopleType" class="selectpicker">	
      <option value="">Select One</option> 
      <option value="1">Applicant</option>
      <option value="2">Owner</option>
   </select>
</form>
```

add the select picker functionality:

````javascript
$(\'.selectpicker\').selectpicker();
````

Now I want to add the validation:

````javascript
		$('#mainform').formValidation({
			framework: 'bootstrap',
			icon: {
				valid: 'glyphicon glyphicon-ok',
				invalid: 'glyphicon glyphicon-remove',
				validating: 'glyphicon glyphicon-refresh'
			},
			fields: {
				PeopleType: {
					validators: {
						notEmpty: {
								message: "You must select the person's role"
						}
					}
				}
			}
		});
````

Now, this is a step wizard where I need to validate each step as I go.  I just need to be able to invoke validation on the entire form.  True if valid, false if not. simple as that.

How can I accomplish this?  Is it possible? I don't see any documentation on this anywhere now that I have purchased the plug in.

**Comment by nghuuphuoc** [comment]
First of all, thank for purchasing the plugin.
Currently the plugin requires form to have a submit button (I will think about improving this, see similar issue #188).

Anyway, you can use the [validate](http://formvalidation.io/api/#validate) and [isValid](http://formvalidation.io/api/#is-valid) methods to validate and check whether the form is valid or not.

```javascript
// Validate the form manually
$('#mainform').formValidation('validate');

var isValidForm = $('#mainform').data('formValidation').isValid();
```

* If you use FormValidation with other plugin, you should take a look at [these principles](http://formvalidation.io/examples/#compatibility).
See the [Bootstrap Select integration](http://formvalidation.io/examples/bootstrap-select/) example.

* If you want to use a wizard, these [wizard examples](http://formvalidation.io/examples/#wizard) might be useful too.

**Comment by nghuuphuoc** [comment]
The most important things you need to take care are:

1) To use the plugin, the field and label need to be placed inside a `.form-group` element:

```html
<form id='mainform'>
    <div class="form-group">
        <select id="PeopleType" name="PeopleType" class="selectpicker">  
          <option value="">Select One</option> 
          <option value="1">Applicant</option>
          <option value="2">Owner</option>
       </select>
    </div>
</form>
```

2) Use the [principles](http://formvalidation.io/examples/#compatibility) when integrating with other plugins:

```javascript
$('#mainform')
    .find('[name="PeopleType"]')
        .selectpicker()
        .change(function(e) {
            // revalidate the field when it is changed
            $('#mainform').formValidation('revalidateField', 'PeopleType');
        })
        .end()
    .formValidation({
        framework: 'bootstrap',
        excluded: ':disabled',   // <=== Pay attention on this setting
        icon: {
            ...
        },
        fields: {
            PeopleType: {
                validators: {
                    notEmpty: {
                        message: "You must select the person's role"
                    }
                }
            }
        }
    });
```

**Comment by DuyetDo** [comment]
<div class="modal fade bs-example-modal-sm" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="exampleModalLabel">Please fill in user info</h4>
                    </div>
                    <div class="modal-body">
                        <h:form id="registrationForm">
                            <div class="form-group">
                                <h:inputText class="form-control" id="username" a:name="username" a:placeholder="User name" value="#{userJSFManagedBean.user.name}">
                                </h:inputText>
                            </div>
                            <div class="form-group">
                                <h:inputSecret class="form-control" id="password" a:name="password" a:placeholder="Password" value="#{userJSFManagedBean.user.password}">
                                </h:inputSecret>
                            </div>
                            <div class="form-group">
                                <h:inputText class="form-control" id="email" a:name="email" a:placeholder="E-mail" value="#{userJSFManagedBean.user.email}">
                                </h:inputText>
                            </div>
                            <div class="form-group">
                                <h:inputText class="form-control" id="phone" a:name="phone" a:placeholder="Phone number" value="#{userJSFManagedBean.user.phone}">
                                </h:inputText>
                            </div>
                            <div class="form-group">
                                <h:inputText class="form-control" id="address" a:name="address" a:placeholder="Address" value="#{userJSFManagedBean.user.address}">
                                </h:inputText>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <h:commandButton class="btn btn-primary" action="#{userJSFManagedBean.addUsers()}" value="Send"></h:commandButton>
                            </div>
                        </h:form>
                    </div>

                </div>
            </div>
        </div>

 $(document).ready(function () {
                $('#registrationForm').formValidation({
                    framework: 'bootstrap',
                    icon: {
                        valid: 'glyphicon glyphicon-ok',
                        invalid: 'glyphicon glyphicon-remove',
                        validating: 'glyphicon glyphicon-refresh'
                    },
                    fields: {
                        username: {
                            validators: {
                                notEmpty: {
                                    message: 'The username is required'
                                },
                                stringLength: {
                                    min: 6,
                                    max: 30,
                                    message: 'The username must be more than 6 and less than 30 characters long'
                                },
                                regexp: {
                                    regexp: /^[a-zA-Z0-9_\.]+$/,
                                    message: 'The username can only consist of alphabetical, number, dot and underscore'
                                }
                            }
                        },
                        email: {
                            validators: {
                                notEmpty: {
                                    message: 'The email address is required'
                                },
                                emailAddress: {
                                    message: 'The input is not a valid email address'
                                }
                            }
                        },
                        password: {
                            validators: {
                                notEmpty: {
                                    message: 'The password is required'
                                },
                                different: {
                                    field: 'username',
                                    message: 'The password cannot be the same as username'
                                }
                            }
                        },
                        phone: {
                            validators: {
                                notEmpty: {
                                    message: 'The phone is required'
                                }
                            }
                        },
                        address: {
                            validators: {
                                notEmpty: {
                                    message: 'The address is required'
                                }
                            }
                        }
                    }
                });
            });

            $('#addModal').on('hidden.bs.modal', function () {
                $('#registrationForm').formValidation('resetForm', true);
            });

cho em hỏi sửa ở đâu để khi submit thì nó nhận hàm addUser().bình thường nếu e ko dùng formValidation thì khi click button nó vẫn add dữ liệu vì nó vẫn nhận hàm addUser(), nhưng khi dùng formValidation thì nó không nhận nữa
