### ISSUE TITLE
Tool tip wont pop up when string length violates

### ISSUE THREAD

**Issue by mulagala** [formvalidation/support#244]
Although validation works

**Comment by nghuuphuoc** [comment]
Please notice that the tooltip/popover is only shown when 
* we hover on the feedback icon,
* or focus on an invalid field

I made a simple [jsfiddle](http://jsfiddle.net/nghuuphuoc/c0mywymb/3/).

![tooltip](https://cloud.githubusercontent.com/assets/4226036/9076031/39a2b604-3b47-11e5-8448-9711c9e11448.png)

**Comment by mulagala** [comment]
Thank you for your quick reply.  I was wondering if you have 2 more examples. One is cascading dropdowns and another is image upload with preview and crop, edit etc
RgdsSuresh


Sent from my Samsung device

-------- Original message --------

**Comment by nghuuphuoc** [comment]
> One is cascading dropdowns and another is image upload with preview and crop, edit etc

I'm sorry. It's beyond the scope of the plugin.
