### ISSUE TITLE
MAC address validation not validating IEEE 802 standards

### ISSUE THREAD

**Issue by gajeramahesh** [formvalidation/support#245]
IEEE 802 standards define 3 commonly used formats to print a MAC address in hexadecimal digits:

    Six groups of two hexadecimal digits separated by hyphens (-), like 01-23-45-67-89-ab
    Six groups of two hexadecimal digits separated by colons (:), like 01:23:45:67:89:ab
    Three groups of four hexadecimal digits separated by dots (.), like 0123.4567.89ab

**Comment by nghuuphuoc** [comment]
Thank you for reporting this.
In the next v0.7.1, all of the formats above are supported.
