### ISSUE TITLE
reCAPTCHA 2 add-on should support secure tokens

### ISSUE THREAD

**Issue by brianlenz** [formvalidation/support#247]
http://formvalidation.io/addons/recaptcha2/

It would be nice if this add-on supported Secure Tokens:

https://developers.google.com/recaptcha/docs/secure_token

We're going to build in support for it, so we may create a pull request if we come up with a solution.

**Comment by nghuuphuoc** [comment]
Thank @brianlenz and @JonmarkWeber.
New [recaptcha](http://formvalidation.io/addons/recaptcha2/) version is released that supports `sToken` parameter.
