### ISSUE TITLE
Stop validating form after one error

### ISSUE THREAD

**Issue by chicagosky** [formvalidation/support#248]
Hello

I have a form with multiple fields that are validated on submit. However I would like to stop the validation when the first error occurs on any field. Display that error message and stop there. I see lots of examples on how to limit multiple field-level validations but no example on how to limit form-level validation.

Help is appreciated

Thanks

**Comment by nghuuphuoc** [comment]
> I see lots of examples on how to limit multiple field-level validations

Exactly, you can use the [verbose](http://formvalidation.io/settings/#form-verbose) option.

> but no example on how to limit form-level validation

I'm sorry. It's not possible.

**Comment by chicagosky** [comment]
So - all errors on a form will be displayed. Hmm.. I wonder if we can exit the function after first validation error
