### ISSUE TITLE
date no active

### ISSUE THREAD

**Issue by ajithgani** [formvalidation/support#249]
Once type the date and press enter, date will disapper

**Comment by nghuuphuoc** [comment]
Do you use a date picker element, `type="date"` or just `type="text"`?

**Comment by ajithgani** [comment]
<input class="form-control date-picker ng-dirty ng-valid ng-valid-required" id="dob" ng-model="user_data.DOB" type="text" data-date-format="dd-mm-yyyy" placeholder="DD-MM-YYYY" required="">

**Comment by ajithgani** [comment]
<input class="form-control date-picker ng-dirty ng-valid ng-valid-required" id="dob" ng-model="user_data.DOB" type="text" data-date-format="dd-mm-yyyy" placeholder="DD-MM-YYYY" required="">

**Comment by ajithgani** [comment]
<input class="form-control date-picker ng-dirty ng-valid ng-valid-required" id="dob" ng-model="user_data.DOB" type="text" data-date-format="dd-mm-yyyy" placeholder="DD-MM-YYYY" required="">

**Comment by ajithgani** [comment]
<input class="form-control date-picker ng-dirty ng-valid ng-valid-required" id="dob" ng-model="user_data.DOB" type="text" data-date-format="dd-mm-yyyy" placeholder="DD-MM-YYYY" required="">

**Comment by nghuuphuoc** [comment]
In order to use the date validator, you need to add `data-fv-date="true"` attribute.
`data-date-format` is not valid attribute too. It should be `data-fv-date-format`.
