### ISSUE TITLE
I got error : Cannot read property 'validateContainer' of undefined in "validateTab" function

### ISSUE THREAD

**Issue by ryantranvn** [formvalidation/support#252]
First, I thank you for your guide about this section.
I read and did like your guide, but i got this error : 
"Cannot read property 'validateContainer' of undefined" in validateTab function.

Please help me how to fix it ?

Thanks again !

**Comment by nghuuphuoc** [comment]
> "Cannot read property 'validateContainer' of undefined" in validateTab function

Please tell me where you got the `validateTab` function.
You can see the code in [Bootstrap tab](http://fvdoc.dev/examples/bootstrap-tab/) example again.

**Comment by ryantranvn** [comment]
I use bootstrapValidator in one function and validateTab function put out, in other function.
By the way, i can not open your link Bootstrap tab example.

**Comment by nghuuphuoc** [comment]
I'm sorry, I gave the incorrect link of Bootstrap tab example.
The correct link is http://formvalidation.io/examples/bootstrap-tab/
