### ISSUE TITLE
Purchase license

### ISSUE THREAD

**Issue by JPMallow** [formvalidation/support#253]
We are service based company, we are doing multiple web projects for multiple clients. Which license do we need to purchase?

**Comment by nghuuphuoc** [comment]
If the plugin is used by multiple developers in the company, I suggest to purchase the Organization license. Then the company can use it in multiple projects, for multiple clients.
Customers and users of your products do not need to purchase their own license, so long as they are not developing their own products with FormValidation.

**Comment by JPMallow** [comment]
ok thanks.
