### ISSUE TITLE
formvalidation and UIKIT show/hide password component not compatible

### ISSUE THREAD

**Issue by tbba** [formvalidation/support#256]
Each of the script worked here, but not both at the same time.

**Comment by nghuuphuoc** [comment]
Can you please give me the code sample?

**Comment by nghuuphuoc** [comment]
Thank you for reporting the issue. I made this [jsfiddle](http://jsfiddle.net/nghuuphuoc/mwdpLm1f/3/) showing that the validation works fine, but clicking on Show/Hide label doesn't do anything as it should toggle the password.

![form-password](https://cloud.githubusercontent.com/assets/4226036/9221821/52d28688-4117-11e5-9de2-cf275510ca2e.png)

I will try to fix it out.

**Comment by tbba** [comment]
Thank you very much. I did not have a valid example as I had removed the UIKIT component already.
Great you could build an example.

By the way:
- the same problem is with the other jquery-validation module
- I sent a bug report to UIKIT already a while ago but had no reply yet.

**Comment by nghuuphuoc** [comment]
> the same problem is with the other jquery-validation module

You can create another issue with more information (including a jsfiddle is great, and much easier for me to fix the issue).

**Comment by tbba** [comment]
You are right, UIKIT could need your jsfiddle. 
I am not sure on which end the problem needs to be addressed. 
At least its good to inform the UIKIT team, which I just did:
https://github.com/uikit/uikit/issues/1353

**Comment by nghuuphuoc** [comment]
Looking at the source of UIKit form-password component, the input is retrieved by the following line 
```javascript
this.input = this.element.next("input").length ? this.element.next("input") : this.element.prev("input");
```
(Here `this.element` is the Show/Hide label)

That code works fine until we use FormValidation rules on field which adds a feedback icon right after the input:

```html
<div class="uk-form-password">
    <input name="password" type="password" data-fv-field="password">
    <i class="fv-control-feedback" data-fv-icon-for="password" style="display: none;"></i>
    <a href="#" class="uk-form-password-toggle" data-uk-form-password="">Show</a>
</div>
```

Now we can't get the input element by
```
this.input = this.element.next("input").length ? this.element.next("input") : this.element.prev("input");
```

So, we have two solutions

1) Don't use the feedback icon on field: http://jsfiddle.net/nghuuphuoc/mwdpLm1f/5/

```javascript
$('#testForm').formValidation({
    framework: 'uikit',
    icon: {
        valid: 'uk-icon-check',
        invalid: 'uk-icon-times',
        validating: 'uk-icon-refresh'
    },
    fields: {
        password: {
            icon: false,   // Here it is
            validators: {
                ...
            }
        }
    }
});
```

2) Move the feedback icon to other place.
The idea is taken from the [Showing icons in custom area](http://formvalidation.io/examples/showing-icon-custom-area/) example.

The working fiddle: http://jsfiddle.net/nghuuphuoc/mwdpLm1f/7/

```javascript
$('#testForm')
    .on('init.field.fv', function(e, data) {
        // $(e.target)  --> The field element
        // data.fv      --> The FormValidation instance
        // data.field   --> The field name
        // data.element --> The field element
    
    	if (data.field === 'password' && data.element.parent().hasClass('uk-form-password')) { 
        	var $icon = data.element.data('fv.icon');
	        $icon.insertAfter(data.element.parent());
        }
    })
    .formValidation({
        framework: 'uikit',
        icon: {
            valid: 'uk-icon-check',
            invalid: 'uk-icon-times',
            validating: 'uk-icon-refresh'
        },
        fields: {
            password: {
                validators: {
                    ...
                }
            }
        }
    });
```

DONE :+1: 

===

I will add an example on the official website later.

**Comment by tbba** [comment]
This worked great - problem solved!
Your are genious!!!
