### ISSUE TITLE
Remote in Select Option 

### ISSUE THREAD

**Issue by teguhpribadia** [formvalidation/support#260]
I already try implement remote validation in select option but no luck , do you have an example or clue for this? , thanks in advance

**Comment by nghuuphuoc** [comment]
Basically, using the remote validator doesn't depend on the kind of inputs which can be a textbox, text area or select element.
Can you please give me your sample code?

**Comment by teguhpribadia** [comment]
Oh god sorry My mistake , My code is horrible , thanks for response and you can close this
