### ISSUE TITLE
Error messages to dialog block

### ISSUE THREAD

**Issue by Pantela777** [formvalidation/support#261]
My formValidation code is:
```
    $('#orderForm').formValidation({
        framework: 'bootstrap',
        err: {
            container: '#messages'
        },
        icon: {
          valid: 'fa fa-check',
          invalid: 'fa fa-remove',
          validating: 'fa fa-refresh fa-spin'
        },
        // This option will not ignore invisible fields which belong to inactive panels
        excluded: ':disabled',
        fields: {
            'name': {
                validators: {
                    notEmpty: {
                        message: 'The name is required'
                    }
                }
            },
            'city': {
                validators: {
                    notEmpty: {
                        message: 'The city is required'
                    }
                }
            },
            'phone': {
                validators: {
                    notEmpty: {
                        message: 'The phone is required'
                    }
                }
            },
            'email': {
                validators: {
                    notEmpty: {
                        message: 'The email is required'
                    }
                }
            }
        }
    });
```

I have jquery-ui dialog block
```
<div id="dialog" title="Error" style="display: none;">
    *Here need output error message*
</div>

<script>
function dialog() {
  $("#dialog").dialog({
      dialogClass: "alertCustom",
      resizable: false,
      width: 600,
      modal: true,
      buttons: {
          "OK": function () {
              $(this).dialog("close");
          }
      }
  });
};
</script>
```

You can see in formValidation code I added:
```
err: {
    container: '#messages'
},
```
And then:
```
<div class="form-group">
    <div class="col-md-12">
        <div id="messages"></div>
    </div>
</div>
```
Move to my dialog block:
```
<div id="dialog" title="Error" style="display: none;">
    <div class="form-group">
	    <div class="col-md-12">
	        <div id="messages"></div>
	    </div>
	</div>
</div>
```
It's, but, how I can to call him and output error message?

**Comment by Ottiko** [comment]
???

**Comment by nghuuphuoc** [comment]
> ???

Thank for reminding me about the question. Because it might be useful to other users, I'm going to create an official example for you.
Give me a few hours.

**Comment by nghuuphuoc** [comment]
I added new [Showing messages in a modal](http://formvalidation.io/examples/showing-messages-modal/) example.
Hopefully it helps you.

**Comment by Ottiko** [comment]
Respect.

Can you tell me, why I have same error...
JS Log

*Port: Could not establish connection. Receiving end does not exist. lastError:29
Port: Could not establish connection. Receiving end does not exist. lastError:29
Port: Could not establish connection. Receiving end does not exist. lastError:29*

**Comment by nghuuphuoc** [comment]
Where do you get the message log as above?
I think there's problem with your Internet connection, not the code itself.

**Comment by Ottiko** [comment]
I work with localhost... Can you look http://goo.gl/ugKWBi

**Comment by nghuuphuoc** [comment]
I did access your page (http://goo.gl/ugKWBi) but it loads properly. There's nothing in the Console window.

**Comment by Ottiko** [comment]
ups sorry maybe you haven't access to AJAX query... But if you can to see my source code, how I try to show error message, maybe tell where I do error...

P.S. Now I can't to add you permission

**Comment by Ottiko** [comment]
P.S. Please clear your last two post.
Question is closed.
Agane respect.

**Comment by Ottiko** [comment]
I use http://formvalidation.io/examples/fuel-ux-wizard
And here I can't call my JS function to show modal message...
If I insert in```
.on('actionclicked.fu.wizard', function(e, data) {
    dialog_error_message();
}```
and click to prev button, I call this function too, because validate is check too, but I think validate need to check if click next, because maybe I didn't fill form and want to back prev step...

**Comment by Ottiko** [comment]
???
