### ISSUE TITLE
Validator ordering and the verbose option

### ISSUE THREAD

**Issue by rosskevin** [formvalidation/support#266]
Using 0.7.0

http://formvalidation.io/settings/#form-verbose

```
verbose: false	
when a field has multiple validators, validation for this field will be terminated upon the first encountered error. Thus, only the very first error message related to this field will be displayed to the user
```

I'm seeing all validators for a single field fire, even with the verbose option set to false and validators are returning `valid:false`.  It's important that my simple validators fail first and not fire off remote.

Would you check to see if your tests assert this behavior?  It is possible that my javascript could be interfering, I don't think so, but certainly possible.

**Comment by rosskevin** [comment]
It may be that I have  mis-ordered my validators.  Hold on this.

**Comment by rosskevin** [comment]
Confirmed, bad ordering on my end.  Wow, would be nice to add some kind of rank to these validators to order them.

**Comment by rosskevin** [comment]
It doesn't appear that the validators are fired in the order I have specified them in the options.

For example:

```json
{
    "validators": {
        "notEmpty": {
            "message": "can't be blank"
        },
        "intl_phone": {
            "message": "is not a valid phone number",
            "preferredCountries": "us"
        },
        "remote_uniqueness": {
            "message": "has already been taken"
        }
    },
    "trigger": "blur"
}
```

This executes:
1. notEmpty
2. uniqueness
3. intl_phone (actually doesn't run because uniqueness fails)

It should/I want it to execute in the order given or an order I can specify:
1. notEmpty
2. intl_phone
3. uniqueness

**Comment by nghuuphuoc** [comment]
Thanks for your confirmation.
Under the hood, the plugin loops through the set of validators by using a simple `for ... in` loop such as
```javascript
var validators = this.options.fields[field].validators;
for (validatorName in validators) {
    // Perform validation on current validator ...
}
```

Anyway, the `for ... in` loop doesn't waranty the order of the item as they appear 
* https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...in#Deleted_added_or_modified_properties

> A for...in loop iterates over the properties of an object in an arbitrary order (see the delete operator for more on why one cannot depend on the seeming orderliness of iteration, at least in a cross-browser setting)

* The SO thread: http://stackoverflow.com/questions/280713/elements-order-in-a-for-in-loop

So, to ensure it work properly without depending on the browser implementation, I will add new option to define the priority of validator named `priority`:

```
{
    "validators": {
        "notEmpty": {
            priority: 1
        },
        "intl_phone": {
            priority: 2
        },
        "remote": {
            priority: 1000
        }
    }
}
```

Each built-in validators will have the default `priority` value (1, for example). The `remote` validator will have highest value of `priority` (1000, for example).

Higher priority the validator has, later it will be executed. (_Does this sentence cause any confusion?_)

I will mark this issue as an enhancement for next v0.7.1. 
I really appriciate if you let me know your though on this.

**Comment by rosskevin** [comment]
I think `priority` as you proposed is a good solution and makes sense.  I'm sure that will satisfy my needs.

**Comment by rosskevin** [comment]
@nghuuphuoc  Please let me know an eta on 0.7.1?  Since my upgrade from 0.6.0, my CI is failing due to this ordering issue.  It doesn't appear that I can point at a commit to workaround a release date anymore since bower support and the git source is removed (or am I misunderstanding where the source is?)

**Comment by nghuuphuoc** [comment]
It's just an milestone for me to manage the issues. I will let you know when it's done.

**Comment by rosskevin** [comment]
Can I get a patch?  We are readying our first release and this is blocking us.  Thank you.

**Comment by nghuuphuoc** [comment]
@rosskevin 
Give me a few days. I will send you the patch.

**Comment by rosskevin** [comment]
Any update?

**Comment by rosskevin** [comment]
Confirmed the 0.7.1-dev patch I received fixes the issue, thank you.
