### ISSUE TITLE
Select Box Keeps Validating, No Rule Present!

### ISSUE THREAD

**Issue by manovraresoft** [formvalidation/support#267]
Check out my fiddle: http://jsfiddle.net/markbad311/94o8zx04/3/

In the fiddle select a user from each select box, then go back and select "select one"

Why does the "Secondary Staff" ask me to enter a value?  It is not defined as required.

**Comment by Arkni** [comment]
From [notEmpty documentation](http://formvalidation.io/validators/notEmpty/):
>When setting options via HTML attributes, remember to enable the validator by setting data-fv-notempty="true".
You don't need to do that when using HTML 5 required attribute.

See also [this example](http://formvalidation.io/validators/notEmpty/#html-5-example) on the same page.

**Comment by manovraresoft** [comment]
I don't see this as a question.  I see this as a problem.  I am not setting attributes via HTML.

I am telling the validating to validating one form element and erroneously it is validating another.

**Comment by nghuuphuoc** [comment]
> Why does the "Secondary Staff" ask me to enter a value? It is not defined as required.

Both select boxes are required because they're using the `required` attribute.

```
<select required data-live-search="true" name="SecondaryStaff" ...>
...
</select>
```

By default, using this attribute will enable the [notEmpty]() validator automatically.
See 
* http://formvalidation.io/examples/html5/ 
* http://formvalidation.io/validators/notEmpty/#html-5-example

**Comment by manovraresoft** [comment]
I see what is going on, you are saying that the validator, even though I have not defined any rules is still validating the select box because of the "required" html attribute.  That should not have been outputted in that select box on from generation.  .... I erased my previous comment and see that you commented before I responded with this one.

Very sorry for the confusion.
