### ISSUE TITLE
Why didn't check

### ISSUE THREAD

**Issue by Ottiko** [formvalidation/support#268]
I have JS array where each ```<h4 name="title" onclick="GetTitle()">This is title</h4>```

And have validate code:
```
                // Add formValidation check field
                $('#orderForm').formValidation('addField', 'title', {
                    validators: {
                        notEmpty: {
                            message: 'Error'
                        }
                    }
                });
```
But if I click at this ```<h4>```, validator is didn't work...

**Comment by nghuuphuoc** [comment]
The plugin supports input elements only. So, something like `h4` tags aren't supported and will not work.

**Comment by Ottiko** [comment]
Can I add another elements type support? Maybe use same left method?

**Comment by nghuuphuoc** [comment]
It's not possible technically.

**Comment by Ottiko** [comment]
I have one ides...
If I add hide field (input type) and give him js .attr() or .val() event from my h4 element, I think it's work...
What do you think?

**Comment by Ottiko** [comment]
I add ```<input type="text" name="title" value="" style="display: none;"/>``` and now validator is work.
