### ISSUE TITLE
Geocomplete sample selects wrong address

### ISSUE THREAD

**Issue by AdamantUK** [formvalidation/support#270]
Hi,

On the geocomplete sample at http://formvalidation.io/examples/geocomplete/.

Sometimes when searching for addresses and entering them, the wrong address is entered.

E.g. search for 'The O2', and click the first result which should the 'The O2 London, United Kingdom' and what then gets entered into the address box is 'O2, 3400 Hillerød, Denmark'.

Any ideas on what may be causing this?

**Comment by nghuuphuoc** [comment]
I tried some keywords but can't repeat the issue.

**Comment by AdamantUK** [comment]
Made a demo video of how it happens for me here https://www.youtube.com/watch?v=IeK3cN8DWTo

This happens across multiple different devices for me, although possibly it's region specific to me in the UK?

I first show the issue happening and then the second time it works, but you can see the wrong address goes into the textbox and is then overwritten with the correct address.  Is this behaviour you see?

If so, perhaps when it's not working then the wrong address is getting inserted and the overwrite bit isn't working?

The Google sample at https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform is working fine, however.

Any ideas / anything I can check?

**Comment by AdamantUK** [comment]
Any other thoughts on maybe what I can look at to resolve this?

**Comment by AdamantUK** [comment]
I've got this working by changing blur to false in the geocomplete section (see below).

From my testing, everything still works as it should but now the correct address is always selected.

Adam

						.geocomplete({
							details: '#addressDetails',
							map: '#map',
							blur: false,
							restoreValueAfterBlur: true
						})

**Comment by nghuuphuoc** [comment]
Thank you so much :+1: 
I updated the [geocomplete](http://formvalidation.io/examples/geocomplete/) example too.
