### ISSUE TITLE
Bootstrap multiple .formValidation

### ISSUE THREAD

**Issue by wasim1623** [formvalidation/support#272]
If there are multiple  contacts and demos form on single and multiple buttons validation required.
What we use for it.

Let suppose:
$(document).ready(function() {
    $('#form1').formValidation({   //For button one with different required fields related to Contacts
    $('#form1').formValidation({   //For other button with different required fields related to demos.

Thanks

**Comment by nghuuphuoc** [comment]
I'm sorry, it's not possible.

**Comment by wasim1623** [comment]
Thank you!

There are two solution for such type of users.
Solution 1:
First solution, you can use two different forms pages with validation and include it in desired page by using iframe.

Solution 2:
you can use nested forms and use such type of formValidatoin within that form with distinct form ID.
But need to add two scripts with different form ID.

Make it easy life :)
