### ISSUE TITLE
off topic: change subject "...[support]..." for Github Mailings

### ISSUE THREAD

**Issue by tbba** [formvalidation/support#274]
Hi, you send "…[support]…" in your email subject line. So it is not easy to identify what the message is about.

Normally Github developers put the name of their software there, like "…[FormValidation]…" in your case.

Would it be possible for you to change that?

**Comment by nghuuphuoc** [comment]
Actually, the subject of email is generated and sent by Github automatically.
The prefix `[support]` is the name of this repository. So, if we want to get something like `[formvalidation-support]`, I have to change the path of this repository to `https://github.com/formvalidation/formvalidation-issues` which is not good as the current.

In this case, as I did, you can make a filter in your mailbox which move all notification emails for this repository to certain folder in your mailbox.

**Comment by tbba** [comment]
I see.... did not know this comes from the second element of the url...
Other developers have their name identifyer first, then the project name:
https://github.com/pn/formvalidation/issues

But no big deal, I close this for now.
