### ISSUE TITLE
Email Validation

### ISSUE THREAD

**Issue by PaulVipond** [formvalidation/support#276]
Hi, I've been testing the email validation and 'a@a' passes as a valid email and I don't think it should. Shouldn't there be at least one dot afterwards, followed by a top-level domain?

**Comment by tbba** [comment]
A.f.i.k. this is a valid email (in rare cases). I think html5 also would validate that as correct.
I remember that there is an example in the documentation given how to solve the problem (by adding your own validator).
http://formvalidation.io/validators/emailAddress/   "Is a@b valid email address?"

**Comment by PaulVipond** [comment]
Wow, lightning fast response! Sorry missed that note :-) As it happens I have already created a remote email validator, so that's OK.

**Comment by nghuuphuoc** [comment]
Thank @tbba for giving the [Is a@b valid email address](http://formvalidation.io/validators/emailAddress/#is-ab-valid-email-address) section here.

There're some solutions for @PaulVipond such as:
* Using the [regexp](http://formvalidation.io/validators/regexp) validator
* Using the [remote](http://formvalidation.io/validators/remote) validator to validate the email on server side
* Using API provided by third party, such as [Mailgun](http://formvalidation.io/examples/using-mailgun-api-validate-email-address/)
