### ISSUE TITLE
Radio inline groups

### ISSUE THREAD

**Issue by xclntdesign** [formvalidation/support#278]
Using the mandatoryIcons add-on with a required radio group causes the icon to overlap the last label.
![mandatoryicon_radiogroup](https://cloud.githubusercontent.com/assets/8462053/9494559/8e11a1d0-4bd4-11e5-921a-2a53f176bf95.jpg)

**Comment by xclntdesign** [comment]
Turns out its not just the mandatoryIcons add-on. It seems to affect all radio-inline groups.

**Comment by nghuuphuoc** [comment]
In some special cases, you can adjust the icon position.
See 
* http://formvalidation.io/examples/adjusting-feedback-icon-position/
* http://formvalidation.io/examples/showing-icon-custom-area/

If these examples don't help me, give me your form markup. I will try to make it displayed properly.
