### ISSUE TITLE
updateOption/updateMessage fails/resets is more than 1 validator in use

### ISSUE THREAD

**Issue by haldiggs** [formvalidation/support#28]
sorry I tried finding a way to create a fiddle or jsbin but this library isn't available so I have to do this here.

given the following HTML

	<div class="container" id="divTest">
		<form id="frmTest" action="test.htm" method="get" class="form-horizontal">
			<div class="row">
				<div class="form-group">
					<label class="col-xs-3 control-label">File type</label>
					<div class="col-xs-6">
						<select name="IdTypeCode" class="selectpicker form-control " id="IdTypeCode" data-style="btn-primary">
							<option value="2">Drivers License or State Id</option>
							<option value="3">Social Security Number</option>
							<option value="17">Client Provided Identifier</option>
						</select>
					</div>
				</div>
				<div class="form-group">
					<label class="col-lg-2 control-label" for="txtTest2">Test ssn mask</label>
					<div class="col-lg-3">
						<input type="text" id="ssn" name="ssn" value="" />
					</div>
				</div>
			</div>
		</form>
		<div class="row">
			<button id="btnSave" type="button">Save</button>
		</div>
		<div class="row results">
		</div>
	</div>
and the following js

		$("#frmTest").submit(function (event) {
			//event.preventDefault();  //prevent all _Wiz forms being submitted unless I allow it.
		});

		$(".container").on("click", "#btnSave", function (e) {
			//console.log($(this).text());
			$(".results").html("");
			$("input").each(function (index) {
				$(".results").append('</br>' + $(this).val());
			});

			if (validateForm($("#frmTest")))
			{
				$("#frmTest").submit();
			}
		});

		$('#frmTest')
			.formValidation({
				framework: 'bootstrap',
				excluded: ':disabled',
				message: 'This value is not valid.',
				fields: {
					ssn: {
						validators: {
							notEmpty: {
								message: 'Id is required'
							},
							regexp: {
								regexp: /\w+/,
								message: 'no regex message'
							},
							stringLength: {
								message: 'no string message',
								max: 50
							}
						}
					}
				}
			})
			.on('change', '[name="IdTypeCode"]', function (e) {
				var idType = $(this).val(),	regexp,	type, maxLen, regexpMsg, strMsg;

				if (idType === '') {
					return;
				}

				switch (idType) {
					case '3':
						regexp = /^\d{9}$/;
						regexpMsg = "must be 9 digits";
						maxLen = 9;
						strMsg = "Must be exactly 9 digits";
						$("#ssn").attr('type', 'password');
						//$("#ssn").inputmask('remove');
						//$("#ssn").inputmask("999999999", { placeholder: " " });
						break;
					default:
						regexp = /^[A-Za-z0-9]+[A-Za-z0-9.-\s]{1,50}$/;
						//$("#ssn").inputmask('remove');
						regexpMsg = "Max 50 characters [A-Za-z0-9. -]";
						maxLen = 50;
						strMsg = "Must be less than 51 characters";
						$("#ssn").attr('type', 'text');
				}

				$('#frmTest')
					// Update options
					//.formValidation('updateOption', 'ssn', 'regexp', 'regexp', regexp)
					.formValidation('updateOption', 'ssn', 'stringLength', 'max', maxLen)
					// Update message
					//.formValidation('updateMessage', 'ssn', 'regexp', regexpMsg)
					.formValidation('updateMessage', 'ssn', 'stringLength', strMsg)
					// You might need to revalidate field
					.formValidation('revalidateField', 'ssn');
			});

		$('#IdTypeCode').change();  //loads the defaults.
	});

	function validateForm(element) {
		if (!element || !$(element).is('form'))
			return alert("a form was expected.");

		var form = $(element);
		console.log('validating form: ' + form.attr('id'));

		var v = form.data('formValidation');
		if (v) {
			v.validate();
			var result = v.isValid();
			console.log('Validation result ' + form.prop('id') + ' : ' + result);
			return v.isValid();
		}

		return true;
	}
I am attempting to alter both the stringLength validator and the regex validator. However the stringLength never seems to stay in place. I noticed that when I am typing the html for the validator (similar to this)
	<small class="help-block" style="display: none;" data-fv-validator="stringLength" data-fv-for="ssn" data-fv-result="VALID">no string message</small>
changes back to the original setting, the one I am overwriting. Can this be changed or am I only allowed to use a single validator?

**Comment by nghuuphuoc** [comment]
For stringLength (and other supporting dynamic option) validators, beside calling ```.formValidation('updateMessage')```, you might need to call 
```.formValidation('updateOption', 'ssn', 'stringLength', 'message', strMsg);```.

Here is the fiddle: http://jsfiddle.net/nghuuphuoc/zmbe1yqb/3/

**Comment by haldiggs** [comment]
thanks!

**Comment by nghuuphuoc** [comment]
The [Updating validator options](http://formvalidation.io/examples/updating-validator-options/) example is also updated.
