### ISSUE TITLE
resetForm is not working

### ISSUE THREAD

**Issue by claudionorborges** [formvalidation/support#287]
Hi all, I have a problem here. When I try to clean the form that is inside a dropdown menu, it only resets the fields, it is not cleaning the messages. My code:

 $('#loginDrop').on('hidden.bs.dropdown', function() {
        $('#loginForm').formValidation('resetForm', true);
    });

<li class="dropdown" id="loginDrop">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-log-in"></span>  Login</a>
                        <ul class="dropdown-menu" style="padding: 15px; min-width: 250px;">
                            <li>
                                <div class="row">
                                    <div class="col-md-10">
                                        {!! Form::open(['method'=>'post'/*,'url'=>'auth/login'*/, 'id'=>'loginForm']) !!}
                                        <div class="form-group">
                                            {!! Form::email('email',null,['placeholder'=>'email@provedor.com.br','class'=>'form-control']) !!}
                                        </div>
                                        <div class="form-group">
                                            {!! Form::password('password',['placeholder'=>'Senha','class'=>'form-control']) !!}
                                        </div>
                                        <div class="form-group">
                                            {!! Form::checkbox('remember',null,['class'=>'form-control']) !!} <span style="color:white;">Lembrar-me</span>
                                        </div>
                                        <div class="form-group">
                                            {!! Form::submit('Entrar',['class'=>'btn btn-custom']) !!}
                                        </div>
                                        {!! Form::close() !!}
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </li>

I am using laravel as a MVC framework..
Does anyone know what is going on?

**Comment by claudionorborges** [comment]
Problem solved, I had forgiven to add the  excluded: ':disabled'. Now it is working! By the way, does anyone know what that does?

**Comment by nghuuphuoc** [comment]
See a simillar example: http://formvalidation.io/examples/modal/

> By default, the plugin will not initialize the fields which are disabled, hidden, or not visible. Since the form is placed inside a model which is not visible after loading page, the plugin might ignore the fields.

> That's the reason why we need to set excluded: ':disabled'. Take a look at the [excluded](http://formvalidation.io/settings#form-excluded) setting for more information.
