### ISSUE TITLE
Detect step number event

### ISSUE THREAD

**Issue by Ottiko** [formvalidation/support#288]
Can you tell me how I can detect step number event (step number and direction) when click at this button 
[Image of steps](http://i.imgur.com/ILrYBsv.png)

I need this, becouse I have same custom code to **.on('actionclicked.fu.wizard', function(e, data) {...}**

**Comment by Ottiko** [comment]
I try to kill event **$('body').on('click', 'ul.steps li', function(e) {
														return false;
												});** but can't...

**Comment by nghuuphuoc** [comment]
I think currently Fuelux Wizard doesn't support for that kind of event.
This might be useful to you: https://github.com/ExactTarget/fuelux/issues/175
