### ISSUE TITLE
formValidation in MVC

### ISSUE THREAD

**Issue by jclange** [formvalidation/support#289]
Hi 

I am attempting to get formValidation to work in ASP.NET MVC, but not having any luck.  
I have a page in Webforms that works, but when I try to copy the same markup and scripting to an MVC project, it doesn't work. 

I am often seeing this error:

Unhandled exception at line 10, column 14 in http://localhost:55683/Scripts/formValidation.bootstrap.min.js

0x800a1391 - JavaScript runtime error: 'FormValidation' is undefined

which leads me to think that I have not loaded the scripts correctly.

Do you have an example of this please?  Or can you point me in the right direction.

Thanks for your help.

Cheers
Jarrod

**Comment by nghuuphuoc** [comment]
Hi Jarrod,

You forgot to include `formValidation.min.js`.
In short, you need at least 3 scripts:

```html
<!-- jQuery v1.9.1 or higher -->
<script type="text/javascript" src="/vendor/jquery/jquery.min.js"></script>

<!-- FormValidation plugin and the class supports validating Bootstrap form -->
<script src="/vendor/formvalidation/dist/js/formValidation.min.js"></script>
<script src="/vendor/formvalidation/dist/js/framework/bootstrap.min.js"></script>
```

See the [Including library](http://formvalidation.io/getting-started/#including-library) section.

**Comment by claudionorborges** [comment]
Make sure you also have the right file structure in your project.... you might have paste the files in the wrong folders...

**Comment by jclange** [comment]
Thanks for the quick replies guys!  Unfortunately, I went to bed straight after sending the message.

I've got past that original error message now.  It was to do with the loading of scripts (and being 2am in the morning!).

However I now get the following, after typing one letter into the input field:

Unhandled exception at line 10, column 19915 in http://localhost:55683/Scripts/formValidation.min.js
0x800a138f - JavaScript runtime error: Unable to get property 'find' of undefined or null reference

![image](https://cloud.githubusercontent.com/assets/10137178/9629947/95b89e80-516e-11e5-90a9-076df2b3f0d7.png)

![image](https://cloud.githubusercontent.com/assets/10137178/9629951/a301bbbc-516e-11e5-87aa-176563403e4b.png)

Thanks again.

**Comment by nghuuphuoc** [comment]
Please give me your sample form markup and Javascript validation code.

**Comment by jclange** [comment]
Here is the cshtml page

@model SpeekRate.Models.Client

@{
    ViewBag.Title = "ClientDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ClientDetails</h2>

<div id="stripeContainer" class="container">
    <h1>Enter your details:</h1>
    <form method="post" id="paymentForm" class="form-horizontal">
        <span id="paymentErrors" class="payment-errors"></span>

        <div class="form-group">
            <label class="col-xs-3 control-label">Full name</label>
            <div class="col-xs-4 has-feedback">
                <input type="text" class="form-control" id="firstName" name="firstName" placeholder="First name" data-fv-field="firstName" />
            </div>
            <div class="col-xs-4 has-feedback">
                <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Last name" data-fv-field="lastName" />
            </div>
        </div>
    </form>
</div>

@section scripts {
    <script src="~/Scripts/formValidation.min.js"></script>
    <script src="~/Scripts/formValidation.bootstrap.min.js"></script>    
    <script src="~/Scripts/mandatoryIcon.min.js"></script>

    <script type="text/javascript">
        debugger;
        
        $(document).ready(function () {
            $('#paymentForm').formValidation
            (
                {
                    framework: 'bootstrap',
                    icon: {
                        required: 'glyphicon glyphicon-asterisk',
                        valid: 'glyphicon glyphicon-ok',
                        invalid: 'glyphicon glyphicon-remove',
                        validating: 'glyphicon glyphicon-refresh'
                    },
                    addOns: {
                        mandatoryIcon: {
                            icon: 'glyphicon glyphicon-asterisk'
                        }
                    },
                    fields: {
                        firstName: {
                            validators: {
                                notEmpty: {
                                    message: 'The first name is required'
                                }
                            }
                        },
                    }
                }
            )
        })
    </script>
}

**Comment by jclange** [comment]
And it is rendered in the browser (IE) as follows:

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ClientDetails - My ASP.NET Application</title>
    <link href="/Content/bootstrap.css" rel="stylesheet"/>
<link href="/Content/site.css" rel="stylesheet"/>

    <script src="/Scripts/modernizr-2.6.2.js"></script>

    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Application name</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                    <li><a href="/Home/About">About</a></li>
                    <li><a href="/Home/Contact">Contact</a></li>

                </ul>
                    <ul class="nav navbar-nav navbar-right">
        <li><a href="/Account/Register" id="registerLink">Register</a></li>
        <li><a href="/Account/Login" id="loginLink">Log in</a></li>
    </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        


<h2>ClientDetails</h2>

<div id="stripeContainer" class="container">
    <h1>Enter your details:</h1>
    <form method="post" id="paymentForm" class="form-horizontal">
        <span id="paymentErrors" class="payment-errors"></span>

        <div class="form-group">
            <label class="col-xs-3 control-label">Full name</label>
            <div class="col-xs-4 has-feedback">
                <input type="text" class="form-control" id="firstName" name="firstName" placeholder="First name" data-fv-field="firstName" />
            </div>
            <div class="col-xs-4 has-feedback">
                <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Last name" data-fv-field="lastName" />
            </div>
        </div>
    </form>
</div>


        <hr />
        <footer>
            <p>&copy; 2015 - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="/Scripts/jquery-1.10.2.js"></script>

    <script src="/Scripts/bootstrap.js"></script>
<script src="/Scripts/respond.js"></script>


    <script type="text/javascript">
        $('#how_it_works').click(function () {
            debugger;

            var jump = $(this).attr('href');
            var new_position = $('#' + jump).offset();
            window.scrollTo(new_position.left, new_position.top);
            return false;
        });

    </script>

    
    <script src="/Scripts/formValidation.min.js"></script>
    <script src="/Scripts/formValidation.bootstrap.min.js"></script>    
    <script src="/Scripts/mandatoryIcon.min.js"></script>

    <script type="text/javascript">
        debugger;
        
        $(document).ready(function () {
            $('#paymentForm').formValidation
            (
                {
                    framework: 'bootstrap',
                    icon: {
                        required: 'glyphicon glyphicon-asterisk',
                        valid: 'glyphicon glyphicon-ok',
                        invalid: 'glyphicon glyphicon-remove',
                        validating: 'glyphicon glyphicon-refresh'
                    },
                    addOns: {
                        mandatoryIcon: {
                            icon: 'glyphicon glyphicon-asterisk'
                        }
                    },
                    fields: {
                        firstName: {
                            validators: {
                                notEmpty: {
                                    message: 'The first name is required'
                                }
                            }
                        },
                    }
                }
            )
        })
    <

**Comment by nghuuphuoc** [comment]
Under the hood, each field and its associated label need to be placed inside a `.form-group` element. By following this default structure, the plugin can indicate where to place the error messages.

In the case we have multiple fields in the same container, we need to use the [row](http://formvalidation.io/settings/#field-row) option to define the parent element:

```javascript
$('#paymentForm').formValidation({
    framework: 'bootstrap',
    icon: {
        ...
    },
    addOns: {
        ...
    },
    fields: {
        firstName: {
            row: '.col-xs-4',   // Because the firtName field now is placed inside .col-xs-4 div
            validators: {
                ...
            }
        },
    }
});
```

See 
* The [row](http://formvalidation.io/settings/#field-row) option
* The [Complex form](http://formvalidation.io/examples/complex-form/) example

**Comment by jclange** [comment]
Brilliant, thank you very much.  That has it working now. (Though I have moved the First and Last Name fields on to separate rows now).

Hopefully a couple of last questions - as I mentioned earlier I am copying a working page I built in ASP.NET webforms to MVC.  In my Webforms page, the mandatoryIcon appears on the right hand side of the input field, but in my MVC page, the icon appears below.  I can't see anything different in my markup.

![mvc](https://cloud.githubusercontent.com/assets/10137178/9631310/f6c26fea-5177-11e5-88ee-c05509d39ed5.jpg)
![webforms](https://cloud.githubusercontent.com/assets/10137178/9631311/f6c87c50-5177-11e5-9e25-f47c5e17863d.jpg)

![mvc error](https://cloud.githubusercontent.com/assets/10137178/9631378/698d310e-5178-11e5-844c-e65c7d402528.jpg)
![webforms error](https://cloud.githubusercontent.com/assets/10137178/9631379/6992df6e-5178-11e5-91b7-de5dd1a3b831.jpg)

Also notice that the first name field is behaving differently to the other fields.  That is when I click away from the first name field, no error message is displayed, but when I click away from the last name field an error message is displayed.  This also happens on the last field in the form (Webforms: CVV; MVC: AddressLine1 )

Thanks again.

**Comment by nghuuphuoc** [comment]
> In my Webforms page, the mandatoryIcon appears on the right hand side of the input field, but in my MVC page, the icon appears below

I am sorry because I don't have any experiences with ASP.Net/MVC. As I think, the icon position might be override by other CSS styles from MVC.
You should use the Chrome DevTools or Firebug to inspect and fix it.

**Comment by jclange** [comment]
It appears that I had a stray piece of CSS that was limiting the max width of the input and hence the icon was not lining up correctly.

Everything seems to be working fine now - thanks for all your help, most appreciated.
