### ISSUE TITLE
formvalidation with "jQuery-Timepicker-Addon "

### ISSUE THREAD

**Issue by WalhallaAT** [formvalidation/support#29]
Hello,

just tried out formvalidation.
Everything is working fine, except of an input-field, which gets populated by a Date-Time-Picker.

I use the following Picker: http://trentrichardson.com/examples/timepicker/

I can't get it working. I tried some examples in the docs on your website, but it doesn't work.
When the form is submitted the data gets validated fine. It's OK, but the data should also get validated right after input. I used "revalidateField", but now I'm stuck...

Thank you!

**Comment by nghuuphuoc** [comment]
When integrating FormValidation with other plugin, you need to follow the [principles](http://formvalidation.io/examples/#compatibility).

You're in the right direction when trying to revalidate field.
Here is code snippet:

```javascript
$('#profileForm')
    .formValidation({
        framework: 'bootstrap',
        icon: {
            ...
        },
        fields: {
            time: {
                validators: {
                    notEmpty: {
                        message: 'The time is required'
                    }
                }
            }
        }
    })
    .find('[name="time"]')
        .timepicker({
            onSelect: function() {
                // We need to revalidate the time field when a date/time is choosen
                $('#profileForm').formValidation('revalidateField', 'time');
            }
        });
```

You can look at the working fiddle: http://jsfiddle.net/nghuuphuoc/nm89yser/2/

Here is the result:

![time picker](https://cloud.githubusercontent.com/assets/4226036/6201920/3582474e-b4f9-11e4-8afe-c327553cee18.png)

**Comment by WalhallaAT** [comment]
Hi,

It was a bit more complicated, but thank to your working fiddle I finally got it to work :-) :-) :-) :-) :-)

Thank you!

**Comment by nghuuphuoc** [comment]
To help other users who might have the same issue, I added [Playing with jQuery UI Datepicker](http://formvalidation.io/examples/jquery-ui-datepicker/) example :+1:
