### ISSUE TITLE
case insensitive regexp in declarative code

### ISSUE THREAD

**Issue by MartialSeron** [formvalidation/support#291]
Hi,

In [this example](http://formvalidation.io/validators/regexp/#basic-example), the programmatic code sets the regexp to `/^[a-z\s]+$/i`. 
But in the declarative code there is `data-fv-regexp-regexp="^[a-z\s]+$"`.

How can I specified the "ignore case" flag in declarative code ?
I tried `data-fv-regexp-regexp="/^[a-z\s]+$/i"` but it does'nt work.

**Comment by nghuuphuoc** [comment]
Thank for the good question. Currently, it's not possible to set the flag (`i`) when using the declarative mode.
In the next version, I will add new option (`flag`) or `data-fv-regexp-flag` attribute which indicates the regular expression flag (`i`, `g`, `m`).

**Comment by MartialSeron** [comment]
Glad to help
