### ISSUE TITLE
number validation per line

### ISSUE THREAD

**Issue by keestimmer** [formvalidation/support#293]
After struggling with my problem for some time I am asking to help me: 
I am trying to achieve that my textarea can have multiple lines of  6 numbers separated with a return.

Can you please take a look help me to get this to work..?
thanks in advance Kees Timmer

![screen shot 2015-09-04 at 11 55 52](https://cloud.githubusercontent.com/assets/1588334/9681117/f39dfb06-52fb-11e5-87c9-854685a5c41b.png)

**Comment by keestimmer** [comment]
with the regexp validator i can also not manage what i am trying to achieve. This is my regex expression 
^(\d{6}\n)$
It is only validating the first line in my textarea.
Hopefully you or someone else can point me to a solution...
thanks!

**Comment by keestimmer** [comment]
I think that I have figured it out:
^(\d{6}\n)+$
will do the trick!
;-)

**Comment by nghuuphuoc** [comment]
Awesome :+1:
