### ISSUE TITLE
additional  question number validation per line #293

### ISSUE THREAD

**Issue by keestimmer** [formvalidation/support#295]
oeps, there is one problem left over to solve...
Is it possible to change the behaviour of the reg. expression that it would produce an error when there is a duplicate entry in the list:

123456
234567
123456

error duplicate numbers in list...
If you can give me a hint... many thanks!

**Comment by nghuuphuoc** [comment]
You can use the [callback](http://formvalidation.io/validators/callback/) validator in this case.
Since it provides the [dynamic message](http://formvalidation.io/validators/callback/#dynamic-message-example) ability, you can try the following code:

```javascript
$(form).formValidation({
    fields: {
        numberList: {
            validators: {
                callback: function(value, validator, $field) {
                    if (value === '') {
                        return true;
                    }
                    if (!^(\d{6}\n)+$.test(value)) {
                        return {
                            valid: false,
                            message: 'Each line must be a number'
                        }
                    }

                    // Get the list of numbers
                    var numbers    = value.split('\n'),
                        obj        = {},
                        duplicated = false,
                        prop;

                    for (var i = 0; i < numbers.length; i++) {
                        prop = numbers[i] + ''; // Convert to string
                        if (obj[prop]) {
                            duplicated = true;
                            break;
                        } else {
                            obj[prop] = true;
                        }
                    }

                    return !duplicated
                            ? true
                            : {
                                valid: true,
                                message: 'There are duplicated items'
                            }
                }
            }
        }
    }
});
```

The algorithm to check if an array consists of duplicated items is quite simple.
You can see it from the [Asking fields to be unique](http://formvalidation.io/examples/asking-fields-be-unique/#checking-duplicate-items-in-array) example.

**Comment by keestimmer** [comment]
This is what I have now, not able to validate, I do not know what is going on here,,?

$(document).ready(function() {
    $('#meetingForm').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
    fields: {
            email: {
                validators: {
                    notEmpty: {
                        message: 'verplicht veld'
                    },
                    emailAddress: {
                        message: 'Dit is geen email adres'
                    }
                }
            },
            numberList: {
                validators: {
                callback: function(value, validator, $field) {
                    if (value === '') {
                        return true;
                    }
                    if (!^(\d{6}\n)+$.test(value)) {
                        return {
                            valid: false,
                            message: 'Each line must be a number'
                        }
                    }
                    // Get the list of numbers
                    var numbers    = value.split('\n'),
                        obj        = {},
                        duplicated = false,
                        prop;
                    for (var i = 0; i < numbers.length; i++) {
                        prop = numbers[i] + ''; // Convert to string
                        if (obj[prop]) {
                            duplicated = true;
                            break;
                        } else {
                            obj[prop] = true;
                        }
                    }
                    return !duplicated
                            ? true
                            : {
                                valid: true,
                                message: 'There are duplicated items'
                            }
                }
            }
        }
        }
});
});

**Comment by nghuuphuoc** [comment]
Do you use `numberList` as the name of the textarea element? (`name="numberList"`)

**Comment by keestimmer** [comment]
Yes sure, but also the email validator does not work anymore.., that is the strange thing...

**Comment by nghuuphuoc** [comment]
Since the `numberList` doesn't have any connections with the email fields, you should check it again (use the `email` as name of email fields).

**Comment by keestimmer** [comment]
Hi

**Comment by keestimmer** [comment]
Hi Phuoc, the email validator field was just to test this. But also without this field and the form name  "numberList" your code does not work. I found out that it is in the line with the regular expression:
if (!/^(\d{6}\n)+$/.test(value)) {
When I change this to if (!'/^(\d{6}\n)+$/'.test(value)) { it starts validating. Off course the expression is not doing anything but the code seems oké. Can you perhaps take a look.... Thanks

**Comment by nghuuphuoc** [comment]
I'm so sorry. There're some typos in my previous code.
Here is working version:

```javascript
$('#testForm').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            numberList: {
                validators: {
                    callback: {
                        callback: function(value, validator, $field) {
                            if (value === '') {
                                return true;
                            }

                            // Get the list of numbers
                            var numbers    = value.split(/[\n\r]/g),
                                obj        = {},
                                duplicated = false,
                                prop;

                            for (var i = 0; i < numbers.length; i++) {
                                if (numbers[i] === '' || !/^\d{6}$/.test(numbers[i])) {
                                    return {
                                        valid: false,
                                        message: 'Each line must be a number'
                                    };
                                }

                                prop = numbers[i] + '';
                                if (obj[prop]) {
                                    duplicated = true;
                                    break;
                                } else {
                                    obj[prop] = true;
                                }
                            }

                            return !duplicated
                                    ? true
                                    : {
                                        valid: false,
                                        message: 'There are duplicated items'
                                    };
                        }
                    }
                }
            }
        }
    });
```

You can try this [fiddle](http://jsfiddle.net/nghuuphuoc/t6r6v3a5/1/) as well.

![each line must be a number](https://cloud.githubusercontent.com/assets/4226036/9719359/ba7f7f52-55ad-11e5-9849-faa34b34a8ff.png)

![duplicated items](https://cloud.githubusercontent.com/assets/4226036/9719362/c5b9e4e8-55ad-11e5-9abd-7547c368544d.png)

**Comment by keestimmer** [comment]
Yep it works indeed. Many thanks you for your help. GREAT!
