### ISSUE TITLE
not working on android and even crashes other jquery scipts, works fantastic with pc

### ISSUE THREAD

**Issue by kslakhani** [formvalidation/support#296]
Hi, 
first, thanks for this great tool.
Got a issue with android on any browser not working at all tried android default, chrome and opera none of them works and it even crashes other jquery script, there is no problem in other jquery i tried to disable formvalidation script and other script works just fine on android powered device. i am not sure about other mobile platforms.
Any suggestion, solution would be really appreciated
thanks

**Comment by kslakhani** [comment]
Hi,
This problem is solved. The jQuery was conflicting each others. Using jQuery.noConflict() will resolve the problems.

**Comment by nghuuphuoc** [comment]
Thank you for your useful feedback :+1:
