### ISSUE TITLE
Form need to be submitted twice when using callback

### ISSUE THREAD

**Issue by jeanphilippealbert** [formvalidation/support#299]
Hi!

I have an issue where the form need to be submitted twice (the submit button clicked twice) to actually submit it. If I remove the callback, it works as usual. I am trying to use a callback to make sure another field is not empty. Everything works excepted the fact that I have the press the submit button twice and I can't figure out why. There is my code:

```javascript
$('#contact form').formValidation({
	live: 'disabled',

	icon: {
		valid: 'glyphicon glyphicon-ok',
		invalid: 'glyphicon glyphicon-remove',
		validating: 'glyphicon glyphicon-refresh'
	},
	
   fields: {
		nom: {
			validators: {
				notEmpty: {
					message: "Veuillez inscrire votre nom"
				}
			}
		},
		courriel: {
			validators: {
				emailAddress: {
					message: "Veuillez inscrire une adresse courriel valide"
				},
				callback:{
					message: "Veuillez inscrire au moins votre adresse courriel",
					callback: function(value, validator, $field) {
						if(document.getElementById('tel').value == '' && document.getElementById('courriel').value == ''){
							return false;
						}else{
							return true;
						}
					}
				}
			}
		}
	}
	
}).on('keyup', '[name="tel"]', function() {
	$('#contact form').formValidation('revalidateField', 'courriel');
}).on('success.field.fv', function(e, data) {
	var $parent = data.element.parents('.form-group');
	$parent.removeClass('has-success');
	data.element.data('fv.icon').hide();
});
```

**Comment by nghuuphuoc** [comment]
This example will help you: http://formvalidation.io/examples/ajax-submit/

**Comment by jeanphilippealbert** [comment]
Hi, thanks for reaching out. I don't want to use Ajax to submit the form, I'm just trying to figure out why I have to press the submit button twice to submit the form when I use this callback. Is there anything wrong with my code?

**Comment by nghuuphuoc** [comment]
I've update the link. Please take a look at it and you will see how to make a custom submit handler.

**Comment by jeanphilippealbert** [comment]
I appreciate your help but it looks like you are not reading my issue properly, no offence though. I use FormValidator everyday on all our client's project, I know how it works. However,it is the first time I use a "callback" validator. At the second I use the callback shown above, the submit button need to be press twice to submit the form. This is clearly not a normal behavior. Is my callback code wrong?

**Comment by nghuuphuoc** [comment]
I am sorry. I got your problem now. I will take a look at it soon.

**Comment by jeanphilippealbert** [comment]
Ok, I figured out. I was using name="submit" on my submit button. That caused the problem.

**Comment by nghuuphuoc** [comment]
Ah :) I'm glad you found the solution. Next time, I should point you to [The submit button's name is not valid](http://formvalidation.io/examples/cant-submit-form-after-validation/#the-submit-buttons-name-is-not-valid) :+1:
