### ISSUE TITLE
FormValidation not compatible with IE8?

### ISSUE THREAD

**Issue by jeanphilippealbert** [formvalidation/support#300]
Hi, do you support IE8? I just tested a project I am working on and it does not work in IE8. Thank you!

**Comment by nghuuphuoc** [comment]
Basically, it works IE 8 as it should. Do you see any warnings/issues which I can track on?

**Comment by jeanphilippealbert** [comment]
Thanks for the quick reply. On IE8, no validation occurs and the form is submitted twice.

**Comment by nghuuphuoc** [comment]
So, maybe you are missing something. Can you please give me the form's HTML and JS validation code you are using?

**Comment by jeanphilippealbert** [comment]
Ok, got it. I was using IE Developers mode to test IE8 and it seems it doesnt work well. On a real IE8, everything works fine!

**Comment by nghuuphuoc** [comment]
Thanks for the confirmation.
