### ISSUE TITLE
the plugin doesn't work properly on hew.to

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#303]
[hew.to](http://hew.to) uses the uri validator, but there're two issues:
* The feedback icon isn't shown up
* The input field's color isn't changed when it's valid or invalid

![uri validator](https://cloud.githubusercontent.com/assets/4226036/9738759/32380e96-5677-11e5-9935-d42c1cda01d5.png)

**Comment by nghuuphuoc** [comment]
At the moment, the current form is structured as following

```html
<form id="hewto" role="form" method="post">
    <div class="input-group">
        <input type="url" class="form-control" name="hewit" placeholder="paste a link to hew it" />
        <span class="input-group-btn">
            <button class="btn btn-danger disabled" type="submit" disabled="disabled">hew.to</button>
        </span>
    </div>
</form>
```

Each field and its label (if available) need to be placed inside a `.form-group` element. By following this standard Bootstrap markup form, the plugin know where to place the error messages as feedback icon.

In our special case, the input isn't placed inside `.input-group`, we need to change the markup a little bit:

```html
<form role="form" method="POST" id="hewto">
    <div class="form-group">
    ...
    </div>
</form>
```

The field and message now have the success/error classes/colors when the field is valid/invalid. The remaining issue is that the icon is not displayed properly.

![icon](https://cloud.githubusercontent.com/assets/4226036/9739377/af62acbc-5679-11e5-8716-17f1f1e3fc93.png)

It's easy for us to [adjust the icon position](http://formvalidation.io/examples/adjusting-feedback-icon-position/):

```css
#hewto .form-control-feedback {
    right: 70px;
}
```

Here is the result:

![adjust icon position](https://cloud.githubusercontent.com/assets/4226036/9739451/fa57b80c-5679-11e5-874e-06deb43a3356.png)

All the modifications can be seen in this [fiddle](http://jsfiddle.net/nghuuphuoc/3d20xwf4/3/).

**Comment by lucasvrm** [comment]
Thanks very much! Now it's working!

I adjusted the icon position but it still doesn't show...

![image](https://cloud.githubusercontent.com/assets/13227132/9747713/cbb44912-5655-11e5-8010-f8896337dd0c.png)

What should I do?

**Comment by Arkni** [comment]
Check your assets.

![screenshot from 2015-09-08 23 07 18](https://cloud.githubusercontent.com/assets/6888059/9748684/78a54ee6-567e-11e5-9838-16ab343a16f2.png)

**Comment by lucasvrm** [comment]
Thanks @nghuuphuoc and @Arkini it's working perfectly!

**Comment by Arkni** [comment]
You're welcome :)
By the way, my name is @Arkni with just one `i` :smiley:

**Comment by lucasvrm** [comment]
I am sorry @Arkni ! Thanks again!

How do I close this issue topic? It's solved... I am new to github, javascript, css, etc etc...

**Comment by Arkni** [comment]
@lucasvrm no worries :)

You can only close issues that you have opened. You can't close issues you haven't created unless you're the owner of the repository :)
