### ISSUE TITLE
recaptcha2 js error on Submit

### ISSUE THREAD

**Issue by csmith77** [formvalidation/support#305]
Unhandled exception at line 45, column 482 in https://www.gstatic.com/recaptcha/api2/r20150901234645/recaptcha__en.js

0x800a138f - JavaScript runtime error: Unable to get property 'children' of undefined or null reference

**Comment by csmith77** [comment]
This was happening when I tried to hide a panel w/ the form on postBack, to show a message back to the user that their request had been submitted...  Resolved by using a div w/ display=none on postBack so that it is still accessible on the server side, just hidden to client.

**Comment by nghuuphuoc** [comment]
Thank for your confirmation!
