### ISSUE TITLE
Different with multiple fields.

### ISSUE THREAD

**Issue by polexian** [formvalidation/support#308]
I am trying to use the different validation with multiple fields separated by a command and I can't get it to work.

I have tried the following, am I mis-reading the instructions?

$('#emergencyForm').formValidation({
    framework: 'bootstrap',
    fields: {
        emergency_phone3: {
            validators: {
                different: {

//tried this
                    field: 'emergency_phone', 'emergency_phone2',
//tried this
                    field: 'emergency_phone, emergency_phone2',

//then finished with this.
                    message: 'the message'
                }
            }
        }
    }
});

**Comment by polexian** [comment]
Ok, so it's done like this:  'emergency_phone,emergency_phone2'  without a space between any fields.

**Comment by nghuuphuoc** [comment]
You're right. In the next version, all of the following values are supported
* `a,b,c` 
* `a, b, c` 
* 
```   
       a,        b,              c
```

**Comment by polexian** [comment]
Good. Guess you are using trim space. Thanks for this great package.


Thank you for your time
Joseph Williams

<div>-------- Original message --------</div><div>From: Phuoc Nguyen <notifications@github.com> </div><div>Date:09/12/2015  05:17  (GMT-06:00) </div><div>To: formvalidation/support <support@noreply.github.com> </div><div>Cc: polexian <getjoseph79@gmail.com> </div><div>Subject: Re: [support] Different with multiple fields. (#308) </div><div>
</div>You're right. In the next version, all of the following values are supported

a,b,c
a, b, c
       a,        b,              c
