### ISSUE TITLE
Where can I download the latest version?

### ISSUE THREAD

**Issue by littlee** [formvalidation/support#309]
the http://formvalidation.io/ says the latest version is v0.7.0
![qq 20150913180641](https://cloud.githubusercontent.com/assets/7534668/9836196/b6868082-5a42-11e5-8461-748ce77aec18.png)

but the code in master branch is v0.6.2
https://github.com/formvalidation/formvalidation/blob/master/dist/js/formValidation.js#L5

**Comment by nghuuphuoc** [comment]
If you already purchased the license, you can use the current download link to get the latest (and future) releases.
