### ISSUE TITLE
Date is not parsed correctly (at least with german date format)

### ISSUE THREAD

**Issue by dasniko** [formvalidation/support#311]
In your `date` validator, you are doing a

    isNaN(Date.parse(z)))

in the switch statement.
This expression evaluates to `true` if using a date in german format (`DD.MM.YYYY`) when the day is greater than 12. I.e. for today, we have September, 14th, which ist in Germany "14.09.2015", the expression is `false`, two days ago, on "12.09.2015", it evaluated to `true`. This is, because `Date.parse()` doesn't allow the german date format, only international/ISO-8601 formats.

Subsequently, the `b.getDynamicOption(c, z)` function yields to an error, if there are no dynamic option or whatever... In fact, I don't need the dynamic option and if `Date.parse()` would evaluate correctly, I wouldn't care about dynamic option. But with this behaviour, I can't use the date validator for my project.

Possible solution could be to separate the day, month and year values from the `min`/`max` variables and create a `Date` object with them.

If I specify the date in another format than the `format` variable of the validator, the date won't evaluate/validate to true at all.

*(the variable names above are taken from your minimized code)*

**Comment by Arkni** [comment]
@nghuuphuoc @dasniko 

The problem can be fixed like this:
```diff
 src/js/validator/date.js | 12 ++++++++++--
 1 file changed, 10 insertions(+), 2 deletions(-)

diff --git a/src/js/validator/date.js b/src/js/validator/date.js
index 3d8c78a..c3ae961 100644
--- a/src/js/validator/date.js
+++ b/src/js/validator/date.js
@@ -197,7 +197,7 @@
                 maxOption = options.max;
 
             if (minOption) {
-                if (isNaN(Date.parse(minOption))) {
+                if (isNaN(this._parseDate(minOption, dateFormat, separator))) {
                     minOption = validator.getDynamicOption($field, minOption);
                 }
 
@@ -207,7 +207,7 @@
             }
 
             if (maxOption) {
-                if (isNaN(Date.parse(maxOption))) {
+                if (isNaN(this._parseDate(maxOption, dateFormat, separator))) {
                     maxOption = validator.getDynamicOption($field, maxOption);
                 }
 
@@ -257,6 +257,14 @@
          * @returns {Date}
          */
         _parseDate: function(date, format, separator) {
+            if (date instanceof Date) {
+                return date;
+            }
+
+            if (typeof date === "function") {
+                return "function";
+            }
+
             var minutes     = 0, hours = 0, seconds = 0,
                 sections    = date.split(' '),
                 dateSection = sections[0],
```

**_NB:_**
* **_This patch's based on the code found on Github._**
* **_I don't know if this is the better solution or not._**

**Comment by dasniko** [comment]
Surely a possible solution and I would have loved to send a PR, but there are no up-to-date sources (aka "closed source") and if I have to pay for usage, I'd expect a fast fix from the provider, or, at least a fast reaction/comment from him.
Unfortunately there's nothing at all...

**Comment by nghuuphuoc** [comment]
Sorry @dasniko for replying late. There are some users asking me to support via emails as well.
This will be fixed in the next version.
