### ISSUE TITLE
USA phone number parsing (123) 456-7890 not supported

### ISSUE THREAD

**Issue by tomscharf** [formvalidation/support#312]
The following format is very common in the USA and is not supported

(123) 456-7890

Note the space after the parenthesis. Validation should ignore all spaces probably.

![image](https://cloud.githubusercontent.com/assets/13559295/9911100/76ce9762-5c6e-11e5-86f1-3ac75367cea0.png)

**Comment by nghuuphuoc** [comment]
I will add support for this format in the next version. For now, you can
* [Use the transformer option to adjust the phone before validating](http://formvalidation.io/examples/modifying-value-before-validating/#using-with-the-phone-validator)
* [Use the intl-tel-input plugin](http://formvalidation.io/examples/validating-international-phone-numbers/)

**Comment by tomscharf** [comment]
Thanks, I did the transformer option and it solved it for now.
