### ISSUE TITLE
isValidContainer() doesn't work for Remote validator

### ISSUE THREAD

**Issue by kiasoftware** [formvalidation/support#313]

**Comment by nghuuphuoc** [comment]
Please note that `isValidContainer()` will return `null` if the remote validator isn't completed.

**Comment by kiasoftware** [comment]
i using wizard with remote validator field. and i need when user clicked next button , the isValidContainer() function returns true or false to move (or not move) next step of wizard.
the problem is moment of checking isValidStep=isValidContainer(container)  and it always returns null...

**Comment by willianantunes** [comment]
@kiasoftware I am facing the same problem right now and perhaps I have the same situation as you. My project is setup with bootstrap and bootstrap wizard. There is a part where I have to validate a field, but it always return null because its state is "STATUS_VALIDATING".

**Comment by willianantunes** [comment]
@nghuuphuoc Is there a way to add a new parameter for validateContainer method such as [async](http://api.jquery.com/jquery.ajax/) flag? Thus STATUS_VALIDATING would be updated to STATUS_VALID before reaching isValidContainer method. One more thing, when I call isValidContainer it calls my remote validation as well, maybe both methods must have the flag. What do you think? The code I've been using:
```
function validateTab(wizardId, index) 
{
	var fv   = $(wizardId).data('formValidation'), // FormValidation instance
	// The current tab
	$tab = $(wizardId).find('.tab-pane').eq(index);

	// Validate the container
	fv.validateContainer($tab);

	var isValidStep = fv.isValidContainer($tab);
	if (isValidStep === false || isValidStep === null) 
	{
		// Do not jump to the target tab
		return false;
	}

	return true;
}
```

**Comment by willianantunes** [comment]
Guys, I figured out how to solve it. Go at line 7153 in **formValidation.js** and configure **ajaxOptions** like below:

```
var ajaxOptions = {
	data: data,
	dataType: options.dataType || 'json',
	headers: options.headers || {},
	type: options.type || 'GET',
	url: url,
	async: options.async == null? true : options.async                
};
```

Then in your formValidation configuration you can set your remote with **async** property as follows:

```
remote: {
	name: "value",
	url: "http://willianantunes.blogspot.com.br/validations",
	type: 'POST',
	async: false,
	data: function(validator, $field, value) {
		return {
			questionId: $field.attr('data-question-id')
		};
	},	                        
}
```

I hope it helps.

**Comment by kiasoftware** [comment]
thank you willianantunes my problem solved with your solution.

**Comment by djdenv** [comment]
Also thank you @willianantunes. A couple more thoughts:
1. If you use programmatic code (i.e. HTML) to define your options, you will also need to add the async variable to the html5Attributes object: 
```
FormValidation.Validator.remote = {
        html5Attributes: {
            crossdomain: 'crossDomain',
            data: 'data',
            datatype: 'dataType',
            delay: 'delay',
            message: 'message',
            name: 'name',
            type: 'type',
            url: 'url',
            validkey: 'validKey',
            async: 'async'
        }
...
```

2. If you also use a delay in  your configuration, this will not work because delay automatically makes the entire validate method asyncronous because it wraps it into setTimeout().

For reference, here is an example of now working programmatic code. This creates a textarea as a required field, using a remote validatior (that checks the max characters per line and maximum lines) set to async=false.

```
<textarea required="required" data-fv-stringlength-message="area exceeds the maximum length of 50" data-fv-stringlength-max="50" data-fv-stringlength-trim="true" data-fv-stringlength="true" data-fv-remote-url="/validations/string?MAX_CHARACTERS_PER_LINE=15&amp;MAX_LINES=4" data-fv-remote-async="false" data-fv-remote-type="POST" data-fv-remote-name="value" data-fv-remote="true" name="a" class="form-control constrained lowercase" rows="1" data-fv-field="a" style="min-height: 4em; height: 56px;"></textarea>
```

I've created a fork and pull request for this feature located here: https://github.com/formvalidation/formvalidation/pull/1469

**Comment by nghuuphuoc** [comment]
Thank @willianantunes and @djdenv for your solution.
I will add the `async` option in the next version.

**Comment by djdenv** [comment]
thank you. I'm sure it will be a good feature for others but I wanted to share that I was able to get around this problem with the current code base. The problem lies in that .validateContainer() may still be running (async) when you call isValidContainer() which returns NULL. That is by design, however simply looping until it is not null won't work. What I was able to do was call .validateContainer, but then recursively call a handler until all fields were no loner in a "VALIDATING" state. 

```
getFormValidationObject().validateContainer($editStory);

	//the validateContainer can take some time to do and may be async when using a remote valdiator. In such a case we
    // wrap the isValid() check in a method that can be recursively called with a small delay.
    function customIsValidHandler() {
        var isContainerValid = getFormValidationObject().isValidContainer($editStory);
        if (isContainerValid) {
        	//we're happy and can do something with the valid data now
        }
        else if (isContainerValid == null){
        	//still validating
        	setTimeout(customIsValidHandler, 50);
        }
        //isContainerValid == false will fall through here.
    }

    customIsValidHandler();

}

```

**Comment by willianantunes** [comment]
In order to avoid synchronous AJAX call which completely freezes the browser until its process is finished I believe should be better include a callback function like "success" with the data returned from the server-side. I suggest it now because I've been facing it.

**Comment by nghuuphuoc** [comment]
> I believe should be better include a callback function like "success" with the data returned from the server-side

You can reuse the data returned from the server side as seen in the http://formvalidation.io/examples/using-data-returned-validator/ example

**Comment by willianantunes** [comment]
@nghuuphuoc I have the same scenario as @kiasoftware. I use [validateContainer](http://formvalidation.io/api/#validate-container) (with ASYNC flag) method to see if all my fields are valid or not in some tab. 

I call the following method to validated a tab inside my bootstrap wizard event:

```
 function validateTab(wizardId, index) 
 {
	var fv   = $(wizardId).data('formValidation'), // FormValidation instance
	// The current tab
	$tab = $(wizardId).find('.tab-pane').eq(index);

	// Validate the container
	fv.validateContainer($tab);

	var isValidStep = fv.isValidContainer($tab);
	if (isValidStep === false || isValidStep === null) 
	{
		// Do not jump to the target tab
		return false;
	}

	return true;
 }
```

Thus in my wizard event I only have this:

```
var isValidTab =  validateTab('#unify-wizard', $currentIndex);
```

As you can see I need to wait to get the response from the server, but until it happens my users suffer from "freeze browser" issue.

**Comment by willianantunes** [comment]
@nghuuphuoc Just to inform you about one more thing, if you insert **delay** option in **remote validator** the method **validateContainer** does not wait for the response, it always return false even with ASYNC flag.
