### ISSUE TITLE
formnovalidate does not work in Safari or IOS

### ISSUE THREAD

**Issue by mischiefgithub** [formvalidation/support#315]
I have tried to use formnovalidate with both .62 and .70 and it does not seem to work.  Going to try the button method.

**Comment by mischiefgithub** [comment]
I think my issue could be the fact that I have multi buttons with the same Name as I check the Value on the server to determine what to do.

**Comment by dtkujawski** [comment]
this could be the same issue as:  https://github.com/formvalidation/support/issues/600

**Comment by nghuuphuoc** [comment]
The latest version [v0.8.0](http://formvalidation.io/news/v0-8-0-released-supports-bootstrap-4-alpha-foundation-6/) might fix that.
Please upgrade the plugin.
