### ISSUE TITLE
re: email validation

### ISSUE THREAD

**Issue by UltraFlux** [formvalidation/support#316]
Either I'm confused as to why this validates, or this is an actual issue.
https://gyazo.com/e21839b37f3df820af75bef73788033c

So I'm curious, why does this validate?

**Comment by nghuuphuoc** [comment]
You can take a look at the [Is a@b valid email address](http://formvalidation.io/validators/emailAddress/#is-ab-valid-email-address) section.

**Comment by andreasba** [comment]
Sorry, but this is not an answer :-) In daily live, a@b is NOT a valid e-mail address with the exception of company intranets etc where you could have such e-mail addresses, but not on the Internet, or? :-)

Also, signs like " # etc are normally not considered valid for an email address. So what about create a emailStrict and email "normal" validator? Good email validation is extremely important and I think one of the most widely used validators of the tool, right?

Thanks
Andreas
