### ISSUE TITLE
Question about maxLength

### ISSUE THREAD

**Issue by haldiggs** [formvalidation/support#32]
I know there was something about maxLength in the documentation enforcing a validation action. Could you clarify? 

I noticed that when I added maxLength to my fields I no longer have the regex validation firing sometimes. Specifically if I only had a single regex validator on the field, and then added maxLength then the validator reports good on blank fields but doesn't look at the characters I am typing. Only the maxLength value.

**Comment by nghuuphuoc** [comment]
> I know there was something about maxLength in the documentation enforcing a validation action. Could you clarify

Adding ```maxLength``` attribute will [enable](http://formvalidation.io/examples/html5/) the [stringLength](http://formvalidation.io/validators/stringLength/) validator __automatically__.

For the issue that occurs when using with regexp validator, please create a [fiddle](http://jsfiddle.net/) for me.

**Comment by haldiggs** [comment]
ahh nevermind... its seems this was a case of my javascript getting cached copy
