### ISSUE TITLE
No validation shown! What am I doing wrong?

### ISSUE THREAD

**Issue by potouridisg** [formvalidation/support#328]
Hello,

I've downloaded "formvalidation-dist-v0.7.0.zip", and placed content in "..\project\assets\formvalidation". I've linked bootstrap and formvalidation css and js in my page.
Bootstrap is running and working so I don't have something wrong in linking formvalidation too.

Here's my code in a testing page:

![q](https://cloud.githubusercontent.com/assets/14877295/10144545/e5a327cc-6626-11e5-839b-e425812292f4.jpg)

I see no validation on submit, am I missing something?

**Comment by potouridisg** [comment]
Problem seemed to be jquery, I moved it's link to head.

**Comment by nghuuphuoc** [comment]
I'm glad that you found and fixed that :+1: 
You actually shouldn't move the jQuery to the head. Just move all JS to the bottom of page, right before the close `body` tag. It will improve the page loading time.
