### ISSUE TITLE
Conflict with Flat UI Pro (designmodo) 

### ISSUE THREAD

**Issue by microluxnet** [formvalidation/support#33]
Hello,
I've problem with Formvalidation and Flat UI (http://designmodo.com/flat/).
The problem is with select menus.

I've tested that every time I use this script, the alert not works:

```
$(document).ready(function(){
  $('select[name="username"]').select2({dropdownCssClass: 'select-inverse-dropdown show-select-search'});
});
```

I think the conflict is in the bootstrap.min.js (the custom file js included in formvalidation plugin).
If I delete it, the validation works good (but lost the css style from Flat UI).

Any ideas to resolve this issue?
Thanks.
Regards,
Michele

**Comment by nghuuphuoc** [comment]
You mention that the alert not works but I don't see any alert code. I don't know how to reproduce the issue.
Please create a [jsfiddle](http://jsfiddle.net/) or provide more HTML form and JS code.

**Comment by microluxnet** [comment]
Hi,
this is the demo:
http://goo.gl/mn8Kkq

This is the custom script for the Flat UI select (and checkbox):
http://goo.gl/wPHwSl

Regards,
Michele

**Comment by nghuuphuoc** [comment]
When using FormValidation with other plugins, you need to follow the [principles](http://formvalidation.io/examples/#compatibility).
We also provide the [select2](http://formvalidation.io/examples/select2/) example.

```javascript
$('#login-form').formValidation({
    framework: 'bootstrap',
    excluded: ':disabled',    // ----> You need to add it
    icon: {
        valid: 'glyphicon glyphicon-ok',
        invalid: 'glyphicon glyphicon-remove',
        validating: 'glyphicon glyphicon-refresh'
    },
    locale: 'it_IT',
    fields: {
        username: {
            validators: {
                notEmpty: {
                    message: 'Indicare il nome utente'
                }
            }
        },
        password: {
            validators: {
                notEmpty: {
                    message: 'Inserire la password di accesso'
                }
            }
        }
    }
});
```

Here is the result:

![select2](https://cloud.githubusercontent.com/assets/4226036/6246769/187a6322-b79f-11e4-8644-bd42027bc85b.png)

**Comment by microluxnet** [comment]
Ok, thanks!

**Comment by nghuuphuoc** [comment]
Added the [Playing with Flat UI](http://formvalidation.io/examples/flat-ui/) example.
