### ISSUE TITLE
calendar stays open after selecting when validating

### ISSUE THREAD

**Issue by amucino** [formvalidation/support#331]
I added the code below to re-validate the field if user uses the bootstrap calendar. That part works great, the only problem is that the calendar stays open after the user clicks on it. If I remove this code then it closes fine but its not validated. How can I make it close after user clicks on it ?
The field I am validating is: rcptdate

```
   $('#rcptdate')
        .datepicker({
            format: 'mm/dd/yyyy'
        })
        .on('changeDate', function(e) {
            // Revalidate the date field
            $('#form1').formValidation('revalidateField', 'rcptdate');
        });
```

**Comment by nghuuphuoc** [comment]
The [Bootstrap Datepicker](https://github.com/eternicode/bootstrap-datepicker) will not be closed after selecting a date.
You need to set the [autoclose: true](http://bootstrap-datepicker.readthedocs.org/en/stable/options.html#autoclose) option:

```javascript
$('#rcptdate')
    .datepicker({
        autoclose: true,    // The default value is false
        format: 'mm/dd/yyyy'
    })
    ... 
```

**Comment by amucino** [comment]
That worked !  thanks.
