### ISSUE TITLE
no validation on jquery steps previous button

### ISSUE THREAD

**Issue by prietoedgardo** [formvalidation/support#335]
Hi again!

Like always im working on bootstrap with you excellent plugin. Im using the jquery steps plugins to validate each tab, but the validation fires on previous button. There is a way to validate each tab when you go forward using next button, but not on previous button?

Thank you!

Edgardo

**Comment by abstractindia** [comment]
Thank you for providing such a wonderful plugin. Sir, I am also using jquery-steps. I am able to get the validation rules working on field while typing (it shows the validation on the fly while user is typing). But If a required field is left blank, or the user did not provide a valid information in a field and clicks on the next, the step moves ahead. I want to prevent the user from moving on to next step if any field is showing "Invalid" or a "Required" field is not filled. How to accomplish this?

I tried the example given on your site (http://formvalidation.io/examples/jquery-steps/) but not working. It stoped moving on to next step.

**Comment by abstractindia** [comment]
Here is my pastebin: http://pastebin.com/85iMt3QG

**Comment by nghuuphuoc** [comment]
The [onStepChanging](https://github.com/rstaib/jquery-steps/wiki/Settings#events) event provided by _jQuery Steps_ has `currentIndex` and `newIndex` parameters.
So, we can compare these parameters to check whether the user click on _Previous_ button or not:

```javascript
    $('#profileForm')
        .steps({
            headerTag: 'h2',
            bodyTag: 'section',
            // Triggered when clicking the Previous/Next buttons
            onStepChanging: function(e, currentIndex, newIndex) {
                var fv         = $('#profileForm').data('formValidation'), // FormValidation instance
                    // The current step container
                    $container = $('#profileForm').find('section[data-step="' + currentIndex +'"]');
                
                // If user click on "Previous" button, we just normally let he/she goes
                if (newIndex < currentIndex) {
                	return true;
                }

                // Validate the container
                fv.validateContainer($container);

                var isValidStep = fv.isValidContainer($container);
                if (isValidStep === false || isValidStep === null) {
                    // Do not jump to the next step
                    return false;
                }

                return true;
            },
            onFinishing: function(e, currentIndex) {
                ...
            },
            onFinished: function(e, currentIndex) {
                ...
            }
        })
        .formValidation({
            framework: 'bootstrap',
            icon: {
                ...
            },
            // This option will not ignore invisible fields which belong to inactive panels
            excluded: ':disabled',
            fields: {
                ...
            }
        });
```

**Comment by prietoedgardo** [comment]
hi nghuuphuoc!

excellent! i will test the code right now, thank you for your great work and support!

edgardo.

**Comment by abstractindia** [comment]
This works perfect.

**Comment by glocifyhimanshu** [comment]
The code has worked properly.

**Comment by johanvdr** [comment]
Hi my code is a bit easier to read:

`			{	
				if (newIndex > currentIndex) {
				form.validate().settings.ignore = ":disabled,:hidden";
				return form.valid();
				}
				
				if (newIndex < currentIndex) {
					return true;
				}
			},`
