### ISSUE TITLE
file upload validation: zip file validation is not working

### ISSUE THREAD

**Issue by luckyali55** [formvalidation/support#339]
i am using file validation for uploading zip file. i allowed zip file but it always says not allowed.

```javascript
file: {
            extension: 'jpg,jpeg,zip',
            type: 'image/jpeg,image/png,application/zip', 
            message: 'The selected file is not valid'
        }
```

**Comment by nghuuphuoc** [comment]
Can you tell me the browser info (including name, version, operating system)?
Here is a [basic fiddle](http://jsfiddle.net/nghuuphuoc/Lth41y3o/) that works on Chrome, Firefox

```javascript
    $('#testForm').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            yourFile: {
                validators: {
                    file: {
                        extension: 'jpg,jpeg,zip',
                        type: 'image/jpeg,image/png,application/zip', 
                        message: 'The selected file is not valid'
                    }
                }
            }
        }
    });
```

![file-validator](https://cloud.githubusercontent.com/assets/4226036/10303117/a9cb2f86-6c3b-11e5-9ce7-ca87b0945dd9.png)

**Comment by luckyali55** [comment]
thanks for reply. 
I am using chrome Version 45.0.2454.101 m, 
I have fixed the problem already by using "application/zip,application/x-compressed,application/x-zip-compressed,multipart/x-zip"


file: {
                        extension: 'jpg,jpeg,zip',
                        type: 'image/jpeg,image/png,application/zip,application/zip,application/x-compressed,application/x-zip-compressed,multipart/x-zip', 
                        message: 'The selected file is not valid'
                    }

http://jsfiddle.net/Lth41y3o/1/

**Comment by luckyali55** [comment]
using only application/zip didn't work for me .

**Comment by nghuuphuoc** [comment]
You're right. In the case the mime type are different on multiple browsers, we need to add all of them as you did :+1:
