### ISSUE TITLE
Validate bootstrap datepicker inside a jquery-step

### ISSUE THREAD

**Issue by abstractindia** [formvalidation/support#340]
I am using bootstrap datepicker (https://github.com/eternicode/bootstrap-datepicker) inside a jquery-steps (https://github.com/rstaib/jquery-steps) form. There are 4 to 5 steps which contains datepicker. 

I am having a strange behavior. If a date field is left blank, it throws validation error and do not let the user go ahead (that's OK). But after that even if I select a date and click next, the validator says : This field is required and do not let the user go ahead.

**Comment by abstractindia** [comment]
Here is my pastbin: http://pastebin.com/mMSJSDQ3

(I have removed other html code to make it short.)

**Comment by nghuuphuoc** [comment]
> But after that even if I select a date and click next, the validator says : This field is required and do not let the user go ahead.

You need to ask the plugin to revalidate the field whenever its value is changed by external plugins.
See the [Bootstrap Datepicker](http://formvalidation.io/examples/bootstrap-datepicker/) example.

> You also should look at the [principles](http://formvalidation.io/examples/#compatibility) when integrating FormValidation with other plugins.

```javascript
$('.datepicker').datepicker({
   format: "dd-mm-yyyy",
   autoclose: true,
   todayHighlight: true,
   //orientation: "bottom"
   todayBtn: "linked",
   todayHighlight: true
})
.on('changeDate', function(e) {
    // Get the field name
    var field = $(this).attr('name');

    // Revalidate the field
    $('#multiphase').formValidation('revalidateField', field);
});
```

Also, you should apply the [date](http://formvalidation.io/validators/date/) validator to the `sd_dob` and `pd_dob` fields.
