### ISSUE TITLE
Datepicker and IBAN validation on same view gve problem

### ISSUE THREAD

**Issue by AMGJMEE** [formvalidation/support#342]
Best, the code I bought I find fantastic, personel very kind but when adding a datepicker is becoming visible after clicking a date e nothing please help me. I add the code snippet.
 Thanks in advance.

```
<link href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.min.css" rel="stylesheet" type="text/css" />
<link href="~/Content/vendor/formvalidation/dist/css/formValidation.min.css" rel="stylesheet" type="text/css" />

<script src="~/Scripts/jquery.min.js"></script>
<script scr="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/vendor/formvalidation/dist/js/formValidation.min.js"></script>
<script src="~/Scripts/vendor/formvalidation/dist/js/framework/bootstrap.min.js"></script>
<link href="~/Content/datepicker.min.css" rel="stylesheet" />
<link href="~/Content/datepicker.min3.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap-datepicker.min.js"></script>
<style type="text/css">
    /**
    * Override feedback icon position
    * See http://formvalidation.io/examples/adjusting-feedback-icon-position/
    */
    #eventForm .form-control-feedback {
        top: 0;
        right: -15px;
    }
</style>

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    <form id="eventForm" method="post" class="form-horizontal">
        @Html.AntiForgeryToken()


        <div id="ibanForm" class="form-horizontal">
            <h4>IBAN</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.IBAN_NUMMER, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.IBAN_NUMMER, new { @class = "form-control", style = "width:300px", @name = "IBAN_NUMMER" })
                    @Html.ValidationMessageFor(model => model.IBAN_NUMMER, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BIC, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.BIC, new { @class = "form-control", style = "width:300px", @name = "BIC" })
                    @Html.ValidationMessageFor(model => model.BIC, "", new { @class = "text-danger" })
                </div>
            </div>
        
            <div >
                @Html.LabelFor(model => model.DATUM, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="input-group input-append date" id="DATUM">
                    @Html.EditorFor(model => model.DATUM, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DATUM, "", new { @class = "text-danger" })
                </div>
            </div>
            <div>
                <input name="model.DATUM" type="text" />
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
       
    </form>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}
<script>
    //TEST
    //BE68539007547034
    $(document).ready(function() {
        $('#ibanForm').formValidation({
            framework: 'bootstrap',
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                IBAN_NUMMER: {
                    validators: {
                        iban: {
                            message: 'Dit is geen geldig IBAN nummer'
                        }
                    }
                },
                DATUM: {
                    validators: {
                        notEmpty: {
                            message: 'The date is required'
                        },
                        DATUM: {
                            format: 'MM/DD/YYYY',
                            min: '01/01/2010',
                            max: '12/30/2020',
                            message: 'The date is not a valid'
                        }
                    }
                }
            }
        });
        $('#DATUM')
      .datepicker({
          format: 'mm/dd/yyyy',
          startDate: '01/01/2010',
          endDate: '12/30/2020'
      })
      .on('changeDate', function (e) {
          // Revalidate the date field
          $('#ibanForm').formValidation('revalidateField', 'DATUM');
      });
    });
    $(function () {
        $("#DATUM").datepicker();
    });


    
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
```

**Comment by nghuuphuoc** [comment]
There is a typo in your code. The `DATUM` validator should be `date`.

```javascript
    $('#ibanForm').formValidation({
            framework: 'bootstrap',
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                IBAN_NUMMER: {
                    validators: {
                        iban: {
                            message: 'Dit is geen geldig IBAN nummer'
                        }
                    }
                },
                DATUM: {
                    validators: {
                        notEmpty: {
                            message: 'The date is required'
                        },
                        date: {   // <== It should be date, not DATUM
                            format: 'MM/DD/YYYY',
                            min: '01/01/2010',
                            max: '12/30/2020',
                            message: 'The date is not a valid'
                        }
                    }
                }
            }
        });
```

**Comment by AMGJMEE** [comment]
Hello, 

 

Hello, first of all thank you so much for your quick response. The problem is that the datepicker remains open also when you start page. Also after improving my typing error (my apology before that). When you select a date remains open.




 

<link href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.min.css" rel="stylesheet" type="text/css" />

<link href="~/Content/vendor/formvalidation/dist/css/formValidation.min.css" rel="stylesheet" type="text/css" />

 

<script src="~/Scripts/jquery.min.js"></script>

<script scr="~/Scripts/bootstrap.min.js"></script>

<script src="~/Scripts/vendor/formvalidation/dist/js/formValidation.min.js"></script>

<script src="~/Scripts/vendor/formvalidation/dist/js/framework/bootstrap.min.js"></script>

<link href="~/Content/datepicker.min.css" rel="stylesheet" />

<link href="~/Content/datepicker.min3.css" rel="stylesheet" />

<script src="~/Scripts/bootstrap-datepicker.min.js"></script>

<style type="text/css">

    /**

    * Override feedback icon position

    * See http://formvalidation.io/examples/adjusting-feedback-icon-position/

    */

    #eventForm .form-control-feedback {

        top: 0;

        right: -15px;

    }

</style>

 

@{

    ViewBag.Title = "Create";

}

 

@using (Html.BeginForm())

{

    <form id="eventForm" method="post" class="form-horizontal">

        @Html.AntiForgeryToken()

 

 

        <div id="ibanForm" class="form-horizontal">

            <h4>IBAN</h4>

            <hr />

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">

                @Html.LabelFor(model => model.IBAN_NUMMER, htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-2">

                    @Html.EditorFor(model => model.IBAN_NUMMER, new { @class = "form-control", style = "width:300px", @name = "IBAN_NUMMER" })

                    @Html.ValidationMessageFor(model => model.IBAN_NUMMER, "", new { @class = "text-danger" })

                </div>

            </div>

 

            <div class="form-group">

                @Html.LabelFor(model => model.BIC, htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-2">

                    @Html.EditorFor(model => model.BIC, new { @class = "form-control", style = "width:300px", @name = "BIC" })

                    @Html.ValidationMessageFor(model => model.BIC, "", new { @class = "text-danger" })

                </div>

            </div>

        

            <div >

                @Html.LabelFor(model => model.DATUM, htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="input-group input-append date" id="DATUM">

                    @Html.EditorFor(model => model.DATUM, new { htmlAttributes = new { @class = "form-control" } })

                    @Html.ValidationMessageFor(model => model.DATUM, "", new { @class = "text-danger" })

                </div>

            </div>

            <div>

            </div>

            <div class="form-group">

                <div class="col-md-offset-2 col-md-10">

                    <input type="submit" value="Create" class="btn btn-default" />

                </div>

            </div>

        </div>

       

    </form>

    <div>

        @Html.ActionLink("Back to List", "Index")

    </div>

}

<script>

    //TEST

    //BE68539007547034

    $(document).ready(function() {

        $('#ibanForm').formValidation({

            framework: 'bootstrap',

            icon: {

                valid: 'glyphicon glyphicon-ok',

                invalid: 'glyphicon glyphicon-remove',

                validating: 'glyphicon glyphicon-refresh'

            },

            fields: {

                IBAN_NUMMER: {

                    validators: {

                        iban: {

                            message: 'Dit is geen geldig IBAN nummer'

                        }

                    }

                },

                DATUM: {

                    validators: {

                        notEmpty: {

                            message: 'The date is required'

                        },

                        date: {

                            format: 'MM/DD/YYYY',

                            min: '01/01/2010',

                            max: '12/30/2020',

                            message: 'The date is not a valid'

                        }

                    }

                }

            }

        });

        $('#DATUM')

      .datepicker({

          format: 'mm/dd/yyyy',

          startDate: '01/01/2010',

          endDate: '12/30/2020'

      })

      .on('changeDate', function (e) {

          // Revalidate the date field

          $('#ibanForm').formValidation('revalidateField', 'DATUM');

      });

    });

    $(function () {

        $("#DATUM").datepicker();

    });

 

 

    

</script>

 

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

}

 

 

    

            <div >

                @Html.LabelFor(model => model.DATUM, htmlAttributes: new { @class = "control-label col-md-2" })

                @*<div class="input-group input-append date" id="DATUM">*@ ç===================

                    @Html.EditorFor(model => model.DATUM, new { htmlAttributes = new { @class = "input-group input-append date" } })ç======== To change this form-control to the input-group input-append date itself

                    @Html.ValidationMessageFor(model => model.DATUM, "", new { @class = "text-danger" })

                </div>

            </div>

            <div>

            </div>

            <div class="form-group">

                <div class="col-md-offset-2 col-md-10">

                    <input type="submit" value="Create" class="btn btn-default" />

                </div>

            </div>

        @*</div>*@ ç=======================================

 

 



 

When I put this in place I see no datepicker comment more. Can you tell me what error I make.

 


Best regards 

 

 

 

 

Met vriendelijke groeten

 

Johan Meersman

Weverstraat 121

9100 Sint-Niklaas

Tel:   03/7770965

GSM: 0498/254013

Website <http://users.telenet.be/johan.meersman/> 

 

Van: Phuoc Nguyen [mailto:notifications@github.com] 
Verzonden: donderdag 8 oktober 2015 07:15
Aan: formvalidation/support <support@noreply.github.com>
CC: AMGJMEE <johan.meersman@telenet.be>
Onderwerp: Re: [support] Datepicker and IBAN validation on same view gve problem (#342)

 

There is a typo in your code. The DATUM validator should be date.

    $('#ibanForm').formValidation({
            framework: 'bootstrap',
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                IBAN_NUMMER: {
                    validators: {
                        iban: {
                            message: 'Dit is geen geldig IBAN nummer'
                        }
                    }
                },
                DATUM: {
                    validators: {
                        notEmpty: {
                            message: 'The date is required'
                        },
                        date: {   // <== It should be date, not DATUM
                            format: 'MM/DD/YYYY',
                            min: '01/01/2010',
                            max: '12/30/2020',
                            message: 'The date is not a valid'
                        }
                    }
                }
            }
        });

**Comment by nghuuphuoc** [comment]
> When you select a date remains open.

Please see #331
