### ISSUE TITLE
Example "Using Mailgun API to validate email address" response.did_you_mean in wrong code block

### ISSUE THREAD

**Issue by streifi** [formvalidation/support#346]
I think in this example the "response.did_you_mean" is in the wrong code block.

Because only when the validation fails, then the "response.did_you_mean" is filled.
Therefore if i move the code block in "err.validator.fv" it works as expected.

**Comment by nghuuphuoc** [comment]
Thank for the suggestion. Actually, the Mailgun API still responses `did_you_mean` when the email address is valid:

<img width="877" alt="mail gun" src="https://cloud.githubusercontent.com/assets/4226036/10472839/4d72ad76-724f-11e5-93d1-8b45f9bea31b.png">

In this case, I think we should check `response.did_you_mean` in both `success.validator.fv` and `err.validator.fv` event handlers.

**Comment by nghuuphuoc** [comment]
The [Using Mailgun API to validate email address](http://formvalidation.io/examples/using-mailgun-api-validate-email-address/) example is updated!
