### ISSUE TITLE
How to validate bootstrap touchspin?

### ISSUE THREAD

**Issue by abstractindia** [formvalidation/support#348]
We are using bootstrap touchspin (https://github.com/istvan-ujjmeszaros/bootstrap-touchspin). We need to validate is as the value must be greater than 2. We added the greaterThan validator but not working.

**Comment by abstractindia** [comment]
Sir, any clue. We are stuck in a project due to the inability to validate touchspin. Please guide.

**Comment by nghuuphuoc** [comment]
The example is now available at http://formvalidation.io/examples/bootstrap-touchspin/
I hope it helps you.

**Comment by abstractindia** [comment]
Ya, Its working. But I have another issue. I have 2 touchspin fields, I want to validate that the second one's value is greater than the first one. I tried this:

    field_1: {
    validators: {
        ....
				}
    },
			
    field_2: {
    validators: {
       greaterThan: {
           field: field_1,
           message: 'The value must be greater than field_1'
                    } 
				}
    }

This did not worked. Moreover, I want to be the second field `>` **(greater than)** and not `>=` **(greater than or equal to).** How to accomplish this?

**Comment by abstractindia** [comment]
Sir, any comments on this?

**Comment by nghuuphuoc** [comment]
You can use the [between](http://formvalidation.io/validators/between/) validator:

```javascript
$('#touchspinForm')
    	.formValidation({
            ...
            fields: {
                firstField: {
                    validators: {
                        between: {
                            min: 0,
                            max: 'secondField',    // <--- It's a dynamic option
                            message: 'The value must be between 0 and second field'
                        }
                    }
                },
                secondField: {
                    validators: {
                        between: {
                            min: 'firstField',  // <--- It's a dynamic option
                            max: 100,
                            message: 'The value must be between first field and 100'
                        }
                    }
                }
            }
        })
```

When we change either `firstField` or `secondField`, we need to revalidate both

```javascript
$('#touchspinForm')
    	.formValidation({
            ...
        })
        .find('[name="firstField"], [name="secondField"]')
            .TouchSpin({
                min: 0,
                max: 100
            })
            .on('keyup touchspin.on.min touchspin.on.max', function() {
                // Revaliate the field
                $('#touchspinForm')
                    .formValidation('revalidateField', 'secondField')
                    .formValidation('revalidateField', 'firstField');
            })
            .end();
```

Here is the working [fiddle](http://jsfiddle.net/nghuuphuoc/r86spfod/2/) that you can play with.
