### ISSUE TITLE
How to disable a field validator on the fly ?

### ISSUE THREAD

**Issue by chateauv** [formvalidation/support#35]
The xample show how to start with a disabled field validator, but how can we disable field's validator on the fly ?

**Comment by nghuuphuoc** [comment]
Does the [Enabling validators](http://formvalidation.io/examples/enable-validator/) example help?

**Comment by chateauv** [comment]
Not really as is shows only how to enable on the fly and not how to disable on the fly.

**Comment by nghuuphuoc** [comment]
You can enable/disable validators use the same method ```enableFieldValidators```.
In the [Enabling validators](http://formvalidation.io/examples/enable-validator/) example:

```javascript
// Enable validators
$('#enableForm').formValidation('enableFieldValidators', 'password', true);

// Disable validators
$('#enableForm').formValidation('enableFieldValidators', 'password', false);
```

**Comment by chateauv** [comment]
Euhhh, sorry it was too obvious....:/ Thank you ! ;)
