### ISSUE TITLE
Where can I download the files

### ISSUE THREAD

**Issue by amucino** [formvalidation/support#350]
I seem to have made  a mess of my files when updating my bootstrap files.
Where can I download the latest files ? 

Aleks

**Comment by nghuuphuoc** [comment]
You must make a purchase to get the latest versions. If you already do it, just use the current download link to get the latest files.

**Comment by amucino** [comment]
I did purchase, I just can't find the original email. Can I download it from my account here ?

**Comment by nghuuphuoc** [comment]
Can you please tell me your email address (that you used to purchase)? I will send new download link to your mailbox then.

**Comment by amucino** [comment]
amucino@mac.com

**Comment by nghuuphuoc** [comment]
The link is just sent to your mailbox. Please keep this email because you can use the link to get the future releases.

**Comment by amucino** [comment]
Got it!  thank you. Will there be any updates in the next few months ?
