### ISSUE TITLE
how to validate check box list such that atleast one checkbox is checked

### ISSUE THREAD

**Issue by laxman4434** [formvalidation/support#351]
Hi,
I want to validate check box list such that at least one check box is checked.

I followed the link
http://formvalidation.io/examples/validating-array-inputs/

But in my case the names of checkboxes are different. Also i don't have class attributes for the inputs.

Could you please help me out with this one

**Comment by nghuuphuoc** [comment]
If the names of check boxes are different, you must specific the same class for them.
Otherwise, it's not possible to validate them.

I'm curious that is there any special reason that you can't add a class attribute for the check boxes?

**Comment by laxman4434** [comment]
Hi nghuuphuoc,
Thanks for your reply. i added same class name ("checkevents") to all the inputs and wrote the validation as following

checkevents: {
                                selector: '.checkevents',
                                row: '.showerror',
                                validators: {
                                    notEmpty: {
                                        message: 'Please select atleast one reminder'
                                    }
                                }
                            }

But it is validating only the last the last checkbox and has success and has error classes are missing.Also my last check box becomes invisible and only text is visible.

**Comment by laxman4434** [comment]
Hi nghuuphuoc,,

Here is the html code of my checkbox list.

<div class="form-group">
        <h4>Send reminder email</h4>
        <label class="control-label" for="chk_Alert">You can choose to receive as many reminders as you wish</label>
        <span id="htp_cph_chk_Alert" class="chk_ReceiveOffers">
            <span class="col-md-6">
                <input id="htp_cph_chk_Alert_0" type="checkbox" name="ctl00$htp_cph$chk_Alert$0" value="0" class="checkevents"/>
                <label for="htp_cph_chk_Alert_0">On event day</label>
            </span>
            <span class="col-md-6">
                <input id="htp_cph_chk_Alert_3" type="checkbox" name="ctl00$htp_cph$chk_Alert$3" value="3" class="checkevents"/>
                <label for="htp_cph_chk_Alert_3">3 days before</label>
            </span>
            <span class="col-md-6">
                <input id="htp_cph_chk_Alert_1" type="checkbox" name="ctl00$htp_cph$chk_Alert$1" value="1" class="checkevents"/>
                <label for="htp_cph_chk_Alert_1">1 day before</label>
            </span>
            <span class="col-md-6">
                <input id="htp_cph_chk_Alert_4" type="checkbox" name="ctl00$htp_cph$chk_Alert$4" value="7" class="checkevents"/>
                <label for="htp_cph_chk_Alert_4">1 week before</label>
            </span>
            <span class="col-md-6">
                <input id="htp_cph_chk_Alert_2" type="checkbox" name="ctl00$htp_cph$chk_Alert$2" value="2" class="checkevents"/>
                <label for="htp_cph_chk_Alert_2">2 days before</label>
            </span>
            <span class="col-md-6">
                <input id="htp_cph_chk_Alert_5" type="checkbox" name="ctl00$htp_cph$chk_Alert$5" value="14" class="checkevents"/>
                <label for="htp_cph_chk_Alert_5">2 weeks before</label>
            </span>
        </span>
    </div>

I need to validate such that atleast one check box is checked on button click.

**Comment by nghuuphuoc** [comment]
Here is the working [fiddle](http://jsfiddle.net/nghuuphuoc/wgwmy95s/1/):

![multiple-checkboxes](https://cloud.githubusercontent.com/assets/4226036/11413831/586e9850-9420-11e5-91b5-2e9452e45997.gif)

You need to [adjust the feedback icon position](http://formvalidation.io/examples/showing-icon-custom-area/) and [define the custom area to show message](http://formvalidation.io/examples/showing-message-custom-area/):

```html
<div class="form-group">
    <!-- The feedback icon will be placed here -->
     <span id="feedbackIcon"></span>

     <span id="htp_cph_chk_Alert" class="chk_ReceiveOffers">
         ...
    </span>
</div>

<!-- The container to place the error of checkboxes -->
<div class="form-group" id="message"></div>    
```

```javascript
$(document).ready(function() {
    $('#testForm')
    	.on('init.field.fv', function(e, data) {
            // data.field   --> The field name
            // data.element --> The field element
        	if (data.field === 'checkEvents') {
                var $parent = data.element.parents('.form-group'),
                    $icon   = data.element.data('fv.icon');
                $icon.appendTo('#feedbackIcon');  // <--- Move the icon to this element
            }
        })
        .formValidation({
            framework: 'bootstrap',
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                checkEvents: {
                    selector: '.checkevents',
                    err: '#message',      // <---- All messages of checkEvents will be placed inside this element
                    validators: {
                        notEmpty: {
                            message: 'Please choose at least one checkbox'
                        }
                    }
                }
            }
        });
});
```

I hope it helps you.

**Comment by laxman4434** [comment]
thyank you nghuuphuoc. That worked perfectly. you are a legend

**Comment by nghuuphuoc** [comment]
The example is now available on official website at http://formvalidation.io/examples/validating-checkbox-list-placed-multiple-columns/

**Comment by CTorres18** [comment]
And if I have 2 groups of checkbox?
