### ISSUE TITLE
require form init before setting session value and revalidate fields

### ISSUE THREAD

**Issue by diadys** [formvalidation/support#356]
Hi,

First many thanks for your awesome plugin !

Here is my use case :
I have some data stored in sessionStorage I want to put back after page reload and revalidate fields afterward.
The only form event available is "init.form.fv" from which I could trigger data loading and revalidation, but actually I can't because it traps me in an infinite loop. $(form).data is still empty when calling :
```
    .on('init.form.fv', function(e, data) {
        var $form = $(e.target);
        $form.formValidation('revalidateField', 'firstname'); <- this causes to trigger again and again init.form.fv
    })    
```

Thanks in advance for your support

**Comment by nghuuphuoc** [comment]
What happens if we do is as following

```javascript
// Init the form with validation rules as usual
$(yourForm).formValidation(... options ...);

// Loading the data from sessionStorage
...

// Finally, validate the form manually
$(yourForm).formValidation('validate');
```

**Comment by diadys** [comment]
Exactly what I wish.

Sorry, I'm so used to asynchronous programming, I forgot Javascript calls are sequential...Form has been initialized, data loaded and validation made !

Cheers !

**Comment by nghuuphuoc** [comment]
I'm glad that it helps you :+1:
