### ISSUE TITLE
Bug FormValidation Reset Field

### ISSUE THREAD

**Issue by milindex** [formvalidation/support#36]
Hello good day,

I found a small problem, maybe this is a mistake on my part or a bug, did not know how to explain and for that reason had to do a video less than a minute, where I explain the problem clearly.

Here link video: https://www.youtube.com/watch?v=G0RqQn0BRzc

Link the code: http://jsfiddle.net/milindex/pnpowx88/1/

I hope you can help me.

Thank you very much.

**Comment by nghuuphuoc** [comment]
Actually, there's a typo in the example code.
The exclude option should be changed to `excluded: ':disabled'`.

Here is the working [fiddle](http://jsfiddle.net/nghuuphuoc/rgpzf1d8/1/).
The [Playing with jQuery Steps](http://formvalidation.io/examples/jquery-steps/) example was also updated.
