### ISSUE TITLE
validator for decimal places

### ISSUE THREAD

**Issue by joomlaA1** [formvalidation/support#367]
hello Nguyen Phuoc

is there a validator for limit of decimal places

ex upto 2 decimal places only:
10.01 - ok!
10.001 - not ok!

how is this? thank you...

**Comment by nghuuphuoc** [comment]
You can use the [regexp](http://formvalidation.io/validators/regexp/) validator:

```javascript
    $('#testForm').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            number: {
                validators: {
                    regexp: {
                        message: 'The number is not valid',
                        regexp: /^-?([0-9]+)(\.[0-9]{1,2})?$/
                    }
                }
            }
        }
    });
```

Here is the [working fiddle](http://jsfiddle.net/nghuuphuoc/hLeys6tj/).

The pattern `/^-?([0-9]+)(\.[0-9]{1,2})?$/` will cover the following cases
* -5
* 10
* 10.0
* 10.01
Meanwhile, 10.001 and so forth are not valid. You can play with the pattern at http://www.regexr.com/3c1mr

**Comment by joomlaA1** [comment]
Thank you!!! i learned something from this...

**Comment by ffrewer** [comment]
I didn't found this issue, so I wrote my own validator. Maybe it's helpful for someone:
<pre>
(function($) {
    FormValidation.I18n = $.extend(true, FormValidation.I18n || {}, {
        'en_US': {
            decimalPlaces: {
                'default': 'Please enter a valid float number with decimal places less than or equal to %s'
            }
        },
        'de_DE': {
            decimalPlaces: {
                'default': 'Bitte Nummer mit Nachkommastellen kleiner gleich %s eingeben.'
            }
        }
        // ToDo Other Languages
    });
    
    FormValidation.Validator.decimalPlaces = {
        html5Attributes: {
            message: 'message',
            value: 'value'
        },

        enableByHtml5: function($field) {
            return ('number' === $field.attr('type')) && ($field.attr('step') !== undefined) && ($field.attr('step') % 1 !== 0);
        },        
        /**
         * Return true if the input value has decimal places less than or equal to given number
         *
         * @param {FormValidation.Base} validator The validator plugin instance
         * @param {jQuery} $field Field element
         * @param {Object} options Can consist of the following keys:
         * - value: The number used to compare to. It can be
         *      - A number
         *      - Name of field which its value defines the number
         *      - Name of callback function that returns the number
         *      - A callback function that returns the number
         * - message: The invalid message
         * @returns {Boolean|Object}
         */
        validate: function(validator, $field, options, validatorName) {
            if (this.enableByHtml5($field) && $field.get(0).validity && $field.get(0).validity.badInput === true) {
                return false;
            }
            var value = validator.getFieldValue($field, validatorName);
            if (value === '') {
                return true;
            }
            value = this._format(value);
            var locale         = validator.getLocale(),
                decimalPlaces  = $.isNumeric(options.value) ? options.value : validator.getDynamicOption($field, options.value),
                decimalPlacesValue = parseInt(this._format(decimalPlaces));
 
            return {
                valid: $.isNumeric(value) && (value === parseInt(parseFloat(value)) || value * Math.pow(10,decimalPlacesValue) === parseInt(parseFloat(value) * Math.pow(10,decimalPlacesValue))),
                message: FormValidation.Helper.format(options.message || FormValidation.I18n[locale].decimalPlaces['default'], decimalPlaces)
            };        
        },
        _format: function(value) {
            return (value + '').replace(',', '.');
        }        
    };
}(window.jQuery));

</pre>

**Comment by nghuuphuoc** [comment]
Thanks @ffrewer 👍
