### ISSUE TITLE
Showing all messages when using callback validator

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#37]
Asked by @cdomkokao

I would like to have the callback options in my IF statement above return all conditions at once... that is to say, when a user starts putting in the password field, I want all of the messages to display and go away as they are satisfied rather than the way it is now where it only shows one message at a time. Is that possible with the callback function?

Thank you so much for your help.

**Comment by nghuuphuoc** [comment]
@cdomkokao
Yes, it's possible. Your question is interesting.
We can archive it via events. I added an [example](http://formvalidation.io/validators/callback/#showing-all-messages).
If you're using 0.5.0, look at this [fiddle](http://jsfiddle.net/nghuuphuoc/ubozvunf/2/).

The following animated image shows how it works

![showing all messages](https://cloud.githubusercontent.com/assets/4226036/6344699/c766b618-bc2e-11e4-852c-d78ddf2d4008.gif)

PS: From the next time, please submit the issue on this respo.

**Comment by cdomkokao** [comment]
This works......!!  Thank you so much.  I was really struggling with this.

**Comment by cdomkokao** [comment]
One more question, if I may.  Do you know if I could then make only 3 out of 4 of the validators required for it to be successful?

**Comment by nghuuphuoc** [comment]
Looking at the [fiddle](), you will see that the field will pass our callback validator if all of 4 rules are satisfied:

```javascript
$('#passwordForm')
    .bootstrapValidator({
        feedbackIcons: {
            ...
        },
        fields: {
            pwd: {
                validators: {
                    callback: {
                        callback: function(value, validator, $field) {
                            ...
                            
                            // Pass if and only if all rules are passed
                            if (passedRules.length < PASSWORD_RULES.length) {
                                $field.data('passedRules', passedRules);  
                                return false;
                            }
                            
                            ...
                        }
                    }
                }
            }
        }
    })
```

If you want the field to be valid if there're at least 3 passed rules, then you can adjust the condition above:

```javascript
$('#passwordForm')
    .bootstrapValidator({
        feedbackIcons: {
            ...
        },
        fields: {
            pwd: {
                validators: {
                    callback: {
                        callback: function(value, validator, $field) {
                            ...
                            
                            if (passedRules.length < PASSWORD_RULES.length - 1) {
                                $field.data('passedRules', passedRules);  
                                return false;
                            }
                            
                            ...
                        }
                    }
                }
            }
        }
    })
```
