### ISSUE TITLE
JPEG Validation is not working

### ISSUE THREAD

**Issue by nineonine** [formvalidation/support#384]
Hi there

jpeg file validation is not working ( png is ok though )

even the example in documentation has same bug

http://formvalidation.io/validators/file/

Tested on : 
G Chrome 46.0.2490.80 (64-bit)
Safari 9.0.1 (10601.2.7.2)

**Comment by nghuuphuoc** [comment]
Please ensure that you add `jpg` extension to the `extension` option:

```javascript
    $('#testForm').formValidation({
        framework: 'bootstrap',
        icon: {
            ...
        },
        fields: {
            avatar: {
                validators: {
                    file: {
                        extension: 'jpg,jpeg,png',   // --> List of allowed extensions
                        type: 'image/jpeg,image/png',
                        maxSize: 2097152,
                        message: 'The selected file is not valid'
                    }
                }
            }
        }
    });
```

You can try this jsfiddle: http://jsfiddle.net/nghuuphuoc/w7ecez58/1/

**Comment by nineonine** [comment]
all good ! thanks for help !
