### ISSUE TITLE
Form not submitting

### ISSUE THREAD

**Issue by Danielss89** [formvalidation/support#385]
Hi
I'm having a problem with the form not submitting when it's valid.
This is my html: https://gist.github.com/Danielss89/4e6b4710ea141556c8ce
This is the JS: https://gist.github.com/Danielss89/fb79d0fde2567dc7def4

I've read this page http://formvalidation.io/examples/cant-submit-form-after-validation/ and it doesn't seem like i violate any of those rules.

**Comment by nghuuphuoc** [comment]
By default, the plugin will not submit the form if the submit button isn't clicked.
In this case, instead of calling the `validate` method manually, you can trigger the `click` event of the submit button:

```javascript
    $('#photographer-base-edit').formValidation({
        framework: 'bootstrap',
        icon: {
            ...
        },
        fields: {
            ...
        },
        addOns: {
            i18n: {}
        },
        locale: 'da_DK'
    }).on('err.form.fv', function(e) {
        Ladda.stopAll();
    })
    .find('[name="submitButton"]').trigger('click');
```

**Comment by Danielss89** [comment]
I do click the submit button.

I wan't to validate the form on page load(without submitting if it's correct).
And i also want to validate and post the form when clicking submit.

**Comment by Danielss89** [comment]
@nghuuphuoc Any idea on this?

**Comment by nghuuphuoc** [comment]
> I want to validate the form on page load(without submitting if it's correct)

So, we just use the `validate` method as you did

> And i also want to validate and post the form when clicking submit

It's the default behavior

I create a simple jsfiddle that does the 2 things as above: http://jsfiddle.net/nghuuphuoc/q3s6mv4k/1/
Do you see any warnings in the Console when running your code?

**Comment by Danielss89** [comment]
Any possibility you have skype, slack, irc or some other IM? I'd like to show you the full source code.
You can email  me at danielss89@gmail.com with your IM, if it's not a part of the support package, i guess we can pay.

**Comment by Danielss89** [comment]
ping @nghuuphuoc

**Comment by Danielss89** [comment]
@nghuuphuoc Any possibility you can accept my skype request this weekend? I really need to get this going. It's the only thing missing before i can launch my project
