### ISSUE TITLE
FormValidation VS Bootstrap Validator

### ISSUE THREAD

**Issue by amytymail** [formvalidation/support#39]
Hi,
The validation is very good and i am using it in my web application but the problem is like previously every example is using Bootstrapvalidator and now in every example you are using FormValidation
or data-bv-* fields and now data-fv-* field name.
can you please clarify me as i have already used bv in my existing application and is shows error if i am using your examples.

**Comment by nghuuphuoc** [comment]
Here it is http://formvalidation.io/news/upgrading-to-v0.6.0/
It shows the chances when upgrading from Bootstrapvalidator to FormValidation.
