### ISSUE TITLE
EIN validation fails a valid EIN number

### ISSUE THREAD

**Issue by ohlincik** [formvalidation/support#395]
We are using formValidation to validate nonprofit organizations. We ran into an issue when a valid EIN number is deemed as invalid by the EIN validator.

Valid number: 47-2163956

You can see that the EIN is clearly valid because an organization is registered using this EIN: http://www.guidestar.org/organizations/47-2163956/arkansas-heart-foundation.aspx

**Comment by nghuuphuoc** [comment]
You're right. In the next v0.7.1, the ein validator will supports identification numbers that start with "47-".
I will let you know when v0.7.1 is released.
