### ISSUE TITLE
Validate dynamically added rows to a table

### ISSUE THREAD

**Issue by abstractindia** [formvalidation/support#397]
Hi,
I am adding rows dynamically to a table, the rows are having form fields. How do I validate the form fields that are dynamically created. One of the form field is a select menu and there is also one file field. I have posted my code here at [pastebin](http://pastebin.com/QTN1eDN2).

**Comment by nghuuphuoc** [comment]
The [Adding dynamic field](http://formvalidation.io/examples/adding-dynamic-field/) example will give you the idea.

**Comment by abstractindia** [comment]
It's too complex for me. Let me try...
