### ISSUE TITLE
zipCode Validation

### ISSUE THREAD

**Issue by bdolleschal** [formvalidation/support#4]
How can I change the Language of the countries, if I use this message

message: 'The value is not valid %s postal code'

in an other language. 
For example: message: 'Das ist keine gültige %s Postleitzahl' 
And instead of the Country name "Germany" I would like to have "Deutschland" 

http://formvalidation.io/validators/zipCode/#options

**Comment by nghuuphuoc** [comment]
Please take a look at the [Using language package](http://formvalidation.io/examples/using-language-package/) example.
