### ISSUE TITLE
Does it support bower?

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#40]
_From @AndrewEastwood on February 26, 2015 21:51_

_Copied from original issue: formvalidation/formvalidation#1437_

**Comment by nghuuphuoc** [comment]
@AndrewEastwood
It doesn't support Bower anymore.

**Comment by AndrewEastwood** [comment]
why so?

**Comment by nghuuphuoc** [comment]
Because it's commercial project, I can't control who download the scripts when using Bower.
A private bower might be useful, but I don't have time to look at it currently.
