### ISSUE TITLE
Visa validation doesn't allow for 13 digit Visa Debit cards

### ISSUE THREAD

**Issue by blair-skipthedishes** [formvalidation/support#402]
Hello,

Foremost, thank you for this fantastic library! It's elegant, easy to use and is flexible for customized validation.  It's our go-to for front-side validation in all our projects!

We are currently using the library to validate Visa Debit cards. However, those types of cards have 13 digits instead of the usual 16. For now, we've had to change the code to allow those cards. We're using version 0.7.0 but it looks like previous versions used to support 13 digits.

For now, we changed `...., VISA:{length:[16], ....` to `...., VISA: { length: [13, 16], ....`

We just wanted to let you know that VISA Debit cards are still being used out here in the ether.

Cheers! :)

**Comment by nghuuphuoc** [comment]
First of all, thanks for using the plugin.
Are you sure that the VISA 13 digits are still being used? Do you have any reference?
Thanks.

**Comment by blair-skipthedishes** [comment]
We found that some TD bank members have old Visa Debit cards and were trying to use them to pay online. TD bank is still in the process of replacing all of their cards with the new 16 digit ones. It looks like the older ones will, hopefully, be completely replaced soon

**Comment by nghuuphuoc** [comment]
Thank you for your confirmation.
I will add support for VISA 13 digits back in the next version!

**Comment by blair-skipthedishes** [comment]
Awesome! Thanks again for a great plugin. :+1:
