### ISSUE TITLE
Uncaught TypeError: Cannot read property 'not' of undefined

### ISSUE THREAD

**Issue by chateauv** [formvalidation/support#404]
Uncaught TypeError: Cannot read property 'not' of undefined ....and in your js it is something about these line :this._cacheFields[b]=this._cacheFields[b].not(h)}return this._cacheFields[b]&&0!==this._cacheFields[b].length||delete this.options.fields[b].
Any idea why I am getting the error with the "not" of the "this._cacheFields[b]"

**Comment by chateauv** [comment]
The problem was that some field rows were added by php (so before the formValidation instantiate) so in order to add these fields to formValidation object, I add to loop through all the fields previously added from php and add them to the form using $j('#form')
                .formValidation('addField', 'field[' + i + '].type', typeValidators).
With this modification it was working fine.

**Comment by nghuuphuoc** [comment]
Thank you for your confirmation.
