### ISSUE TITLE
formvalidation with durandal issues

### ISSUE THREAD

**Issue by acrigney** [formvalidation/support#406]
I am trying to use formvalidation with a Durandal SPA using asp.net boiler plate, its a really great framework. However getting all these to work together is really hard.

I have several issues in that 
1 . My submit button is initially enabled where none of the fields have any data, however validation then works on most of the fields expect for.
2 my mobilePhone validation does not validate the field at all.
3 My dateofbirth does not re-validate the field once an incorrect value is input, so the warning text stays even after a valid value is input. I have the
.on('changeDate', function (e) {
                     // Revalidate the date field
                     $('#validateEndUser').formValidation('revalidateField', 'dateOfBirth');
                 });
but it does not work

Here is all of my durandal module. Perhaps its to do with my environment.
I have the

define(['service!telstra/readycare/clarityenduserweb', 'service!telstra/readycare/enduserweb', 'service!telstra/readycare/claritypatientweb', 'service!telstra/readycare/patientweb', 'plugins/history', 'durandal/enduser', 'plugins/router', 'knockout', 'knockout.validation'],
    function (clarityenduserService, endUserService, claritypatientService, patientService, history, enduser, router, ko) {

        //var localize = abp.localization.getSource('SimpleTaskSystem');
        return function () {
            var that = this;
            
            that.enduser = enduser;
            that.enduser.init();
            that.user = that.enduser.enduser;

            var _$view = null;
            var _$form = null;

            
            that.attached = function (view, parent) {

                _$view = $(view);
                _$form = _$view.find('form');
                //_$form.validate();

                $('#dateRangePicker')
                    .datepicker({
                        format: 'dd/mm/yyyy',
                        startDate: '01/01/1900',
                        endDate: '12/30/2050'
                    })
                 .on('changeDate', function (e) {
                     // Revalidate the date field
                     $('#validateEndUser').formValidation('revalidateField', 'dateOfBirth');
                 });
                             
                $('#validateEndUser').off('click');

                $('#validateEndUser').on('click', function () {
                    $('#registrationForm')
                        //.formValidation('revalidateField', 'mobilePhone')
                        .formValidation({
                            framework: 'bootstrap',
                            icon: {
                                valid: 'glyphicon glyphicon-ok',
                                invalid: 'glyphicon glyphicon-remove',
                                validating: 'glyphicon glyphicon-refresh'
                            },
                            fields: {
                                userName: {
                                    validators: {
                                        notEmpty: {
                                            message: 'The userName is required and cannot be empty'
                                        }
                                        //,
                                        //stringLength: {
                                        //    min: 6,
                                        //    max: 30,
                                        //    message: 'The userName must be more than 6 and less than 30 characters long'
                                        //},
                                        //regexp: {
                                        //    regexp: /^[a-zA-Z0-9]+$/,
                                        //    message: 'The userName can only consist of alphabetical and digits'
                                        //}
                                    }
                                },
                                firstName: {
                                    validators: {
                                        notEmpty: {
                                            message: 'The First Name is required'
                                        }
                                    }
                                },
                                dateOfBirth: {
                                    validators: {
                                        notEmpty: {
                                            message: 'The Date Of Birth is required'
                                        },
                                        date: {
                                            format: 'DD/MM/YYYY',
                                            message: 'The date of birth is not a valid date'
                                        }
                                    }
                                },
                                lastName: {
                                    validators: {
                                        notEmpty: {
                                            message: 'The Last Name is required'
                                        }
                                    }
                                },
                                //mobilePhone: {
                                //    validators: {
                                //        digits: {
                                //            message: 'The phone number can contain digits only'
                                //        },
                                //        notEmpty: {
                                //            message: 'The phone number is required'
                                //        }
                                //    }
                                //},
                                //mobilePhone: {
                                //    validators: {
                                //        notEmpty: {
                                //            message: 'The phone number is required'
                                //        },
                                //        mobilePhone: {
                                //            country: 'MA',
                                //            message: 'The phone number is not valid'
                                //        }
                                //    }
                                //},
                                mobilePhone: {
                                    validators: {
                                        notEmpty: {
                                            message: 'The Mobile Phone is required'
                                        },
                                        mobilePhone: {
                                                regexp: {
                                                    regexp: '^\d{10}$',
                                                //regexp: /^\d{10}$/,
                                                message: 'The Mobile Phone number is not valid'
                                            }
                                           
                                        } // mobilePhone
                                    }
                                },

                                email: {
                                    validators: {
                                        notEmpty: {
                                            message: 'The Email is required'
                                        },
                                        emailAddress: {
                                            message: 'The value is not a valid email address !'
                                        },
                                        regexp: {
                                            regexp: /^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i,
                                            message: 'The value is not a valid email address !!'
                                        }
                                    }
                                }
                            }
                        })
                        .on('err.validator.fv', function (e, data) {
                            // data.bv        --> The FormValidation.Base instance
                            // data.field     --> The field name
                            // data.element   --> The field element
                            // data.validator --> The current validator name

                            if (data.field === 'email') {
                                // The email field is not valid
                                data.element
                                    .data('fv.messages')
                                    // Hide all the messages
                                    .find('.help-block[data-fv-for="' + data.field + '"]').hide()
                                    // Show only message associated with current validator
                                    .filter('[data-fv-validator="' + data.validator + '"]').show();
                            }
                        })

                        // Removed the previous success.form.fv handler
                        //.off('success.form.fv')

                        //.on('success.field.fv', function(e, data) {
                        //    if (data.fv.getInvalidFields().length > 0) {    // There is invalid field
                        //        data.fv.disableSubmitButtons(true);
                        //    }
                        //})
                        .on('success.form.fv', function (e) {

                            e.preventDefault();
                            
                            abp.ui.setBusy(_$view);

                            //var xx = ko.mapping.toJS(that.user); 

                            if (endUserService.checkIfEndUserExists(ko.mapping.toJS(that.user))) {
                                abp.ui.clearBusy(_$view);

                                abp.notify.info("New user name is valid.");
                                //var $form = $(e.target),
                                //fv = $(e.target).data('formValidation');
                                //fv.defaultSubmit();
                                that.directToTermsAndConditionsPage();
                            }
                            else {
                                abp.ui.clearBusy(_$view);
                                abp.notify.info("User already exists.");

                                history.navigate('');
                                
                            }
                        });
                });                             
            };

            that.directToTermsAndConditionsPage = function () {
                router.navigate("#/accept");
                return;
            };

           

        };
    });

**Comment by acrigney** [comment]
if anyone wants to help me work this out I can pay them.

**Comment by nghuuphuoc** [comment]
I haven't tried Durandal framework but there are some problems with the code above.

> my mobilePhone validation does not validate the field at all

It doesn't works because there's no `mobilePhone` validator. You need to try

```javascript
mobilePhone: {
    validators: {
        notEmpty: {
        message: 'The Mobile Phone is required'
    },
    // mobilePhone: {   <--- you need to remove this line because you are trying to use the regexp validator
    regexp: {
        regexp: '^\d{10}$',
        message: 'The Mobile Phone number is not valid'
    }
  }
},
```

> My dateofbirth does not re-validate the field once an incorrect value is input

You need to change
```javascript
...
.on('changeDate', function (e) {
    // Revalidate the date field
    $('#validateEndUser').formValidation('revalidateField', 'dateOfBirth');
});
```

to 

```javascript
...
.on('changeDate', function (e) {
    // You are calling .formValidation on the form (registrationForm not validateEndUser)
    $('#registrationForm').formValidation('revalidateField', 'dateOfBirth');
});
```
