### ISSUE TITLE
iCheck radiobuttons and checkboxes inside multi Bootstrap3 tabs

### ISSUE THREAD

**Issue by yuwen0405** [formvalidation/support#408]
Hi, I want to use FormValidation with iCheck radiobuttons and checkboxes inside multi Bootstrap3 tabs. Both of these features must be included:
	http://formvalidation.io/examples/bootstrap-tab/
	http://formvalidation.io/examples/icheck/
Which version should I use? Is there any free-trials?
Thank you.

**Comment by nghuuphuoc** [comment]
As seen in the example, you can use FormValidation with external iCheck and Bootstrap plugins.
There's no free trials version, but you can download the minified files as following
```
<!-- The CSS file -->
<link rel="stylesheet" href="http://formvalidation.io/vendor/formvalidation/css/formValidation.min.css">

<!-- The JS files -->
<script src="http://formvalidation.io/vendor/formvalidation/js/formValidation.min.js"></script>
<script src="/http://formvalidation.io/vendor/formvalidation/js/framework/bootstrap.min.js"></script>
```

**Comment by yuwen0405** [comment]
I tried the iCheck and Bootstrap plugins you supplied. It's working. Thank you very much. But I get some problems...

The requirement is:
   When I change the value of an radio button(ex:sortType), the validation fields must be changed too.
   So I must remove original validation attributes and then register to new validation fields.

1. When I call removeData, the validation css class is not be removed like glyphicon-ok, glyphicon-remove, has-error, has-success...	
   So I add the script as follows:
      delete $('#customerForm').data('formValidation').options.fields[key];
	  $('input[name="'+key+'"]').removeAttr('data-fv-field').removeAttr('value').parent()
	  .removeClass('has-feedback has-success has-error')
	  .find('i, small').remove();
		
   Is there any method chould be used to reset css attribues?
   
2. An error occured: "Uncaught TypeError: Cannot read property 'threshold' of undefined" when I run the steps as follows:
		(1) change the icheck radiobutton "sortType" from [value=0] to [value=1]
		(2) call removeData and registerValidation
		(3) enter value on the unquired field (it's required before removeData)
		(4) the error message "Uncaught TypeError: Cannot read property 'threshold' of undefined" showed in browser console

3. When I open the chrome developer tool, the icheck option(value=0) icon of sortType will disappear. 

4. My html is as below:
<!DOCTYPE>
<html>
	<head>
		<meta charset="utf-8">
		<meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'>	


	
    
    <script src="/wsms/webjars/jquery/2.1.1/jquery.js"></script>     
    <script src="/wsms/webjars/jquery/2.1.1/jquery.min.js"></script> 
    <script src="/wsms/webjars/jquery-ui/1.11.2/jquery-ui.min.js"></script>
    <script src="/wsms/webjars/jquery-tmpl/beta1.0.0/jquery.tmpl.min.js"></script>      
    <script src="/wsms/webjars/jquery-tmpl/beta1.0.0/jquery.tmpl.js"></script>   
        
    
    <script src="/wsms/webjars/bootstrap/3.3.1/js/bootstrap.min.js"></script> 
	<script src="/wsms/public-resources/js/bootstrap-submenu.js"></script>    

	
	<script src="/wsms/public-resources/AdminLTE/app.js"></script>		
	
	
	<script src="/wsms/public-resources/AdminLTE/iCheck/icheck.js"></script>

    
    <script src="/wsms/webjars/bootbox/4.4.0/bootbox.js"></script>   
    
    
	<script src="/wsms/public-resources/js/jquery.xml2json.js"></script> 	      
         
    
   	
	<script src="/wsms/public-resources/js/jquery.loadJSON.js"></script> 
		

	
    <link href="/wsms/webjars/jquery-ui/1.11.2/jquery-ui.css" rel="stylesheet"/>
    
    
    <link href="/wsms/webjars/bootstrap/3.3.1/css/bootstrap.css" rel="stylesheet"/>
    <link href="/wsms/webjars/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="/wsms/webjars/bootstrap/3.3.1/css/bootstrap-theme.min.css" rel="stylesheet"/>    
    <link href="/wsms/public-resources/css/bootstrap-submenu.css" rel="stylesheet"/>        
    <link href="/wsms/public-resources/css/bootstrap-submenu.min.css" rel="stylesheet"/>    
	
    
    <link href="/wsms/public-resources/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet"/>         

	
	<link href="/wsms/public-resources/AdminLTE/AdminLTE.css" rel="stylesheet"/>       

	
    <link href="/wsms/public-resources/AdminLTE/iCheck/square/pink.css" rel="stylesheet"/> 

<script>
	// Use iCheck CSS Pattern
	$(document).ready(function(){
	  $('input').iCheck({
	    checkboxClass: 'icheckbox_square-pink',
	    radioClass: 'iradio_square-pink',
	  });
	});   
</script>		
      
<script>
	jQuery.browser = {};
	$(function() {
		jQuery.browser.msie = false;
		jQuery.browser.version = 0;
		if (navigator.userAgent.match(/MSIE ([0-9]+)\./)) {
			jQuery.browser.msie = true;
			jQuery.browser.version = RegExp.$1;
		}
	});
</script>

		<style type="text/css">
			@media ( max-width : 980px) {
				.navbar-right {
					width: 70% !important;
				}
			}
			
			html, body {
				height: 100%;
			}
			
			/* navbar */
			.navbar-default {
				background-color: #F8F8F8;
				border-color: #E7E7E7;
			}
		</style>	
		
	<style type = "text/css">
		.col-lg-1 {
			padding-left:6px !important;
			padding-right:1px !important;
		}
		.col-md-1 {
			padding-right:5px !important;
			padding-left:5px !important;
		}
		.col-xs-1 {
			width:1px !important;
		}
		.col-xs-2 {
			width:60px !important;
		}
		.col-notsms {
			color:blue !important;
		}
	</style>

    <script>
		var project = 'wsms';
		var module = 'customer';
		var programId = 'wicumb';
	</script>
	
	
	<script src="http://formvalidation.io/vendor/formvalidation/js/formValidation.min.js"></script>
	<script src="http://formvalidation.io/vendor/formvalidation/js/framework/bootstrap.min.js"></script>

	
	<link rel="stylesheet" href="http://formvalidation.io/vendor/formvalidation/css/formValidation.min.css">
	
    <style type="text/css">
		#customerForm {
		    margin-top: 15px;
		}
	</style>
	
	
	<style type="text/css">
		#customerForm .radio label, #customerForm .checkbox label {
		    padding-left: 0;
		}
	</style>

	</head>

	<body class="skin-blue">

	
	<header class="header">

		

		
		<nav class="navbar navbar-static-top" role="navigation">
			<div class="container-fluid" style="background-color: #3c8dbc;">
				
				<div class="col-sm-1" >
					<a href="#" class="navbar-btn sidebar-toggle"
						data-toggle="offcanvas" role="button"> <span class="sr-only">Toggle
							navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
				</div>

				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					
						<ul class="nav navbar-nav">
							<img src="/wsms/public-resources/images/wsmsLogo.jpg" width="auto" height="auto" />
						</ul>
				</div>
				
			</div>
			

		</nav>
	</header>

	
	<div class="wrapper row-offcanvas row-offcanvas-left">

		
		<aside class="left-side sidebar-offcanvas">
			
			<section class="sidebar">

				
				<div class="user-panel">
					<div class="pull-left image"></div>
					<div class="pull-left info">

						<a href="#"><i class="fa fa-circle text-success"></i> Online </a>
					</div>
				</div>

				
				<form action="#" method="get" class="sidebar-form">
					<div class="input-group">
						<input type="text" name="q" class="form-control"
							placeholder="Search..." /> <span class="input-group-btn">
							<button type='submit' name='search' id='search-btn'
								class="btn btn-flat">
								<i class="fa fa-search"></i>
							</button>
						</span>
					</div>
				</form>

				
				<ul class="sidebar-menu">
					<li class="treeview"><a href="#"> <i class="fa fa-laptop"></i>
							<span>開戶作業</span> <i class="fa fa-angle-left pull-right"></i>
					</a>
						<ul class="treeview-menu">
							<li><a
								href="/wsms/customer/wicumb.html"><i
									class="fa fa-angle-double-right"></i> 財管信託開戶作業 </a></li>
						</ul></li>
				</ul>
			</section>
			
		</aside>

		
		<aside class="right-side">
			
			<section class="content-header">
				<h1>
					 開戶作業 
				</h1>
				<ol class="breadcrumb">
					<li><a href="#"><i class="fa fa-dashboard"></i> Home </a></li>
					<li class="active">Welcome!!</li>
				</ol>
			</section>

			
			<section class="content">
				
				<div class="row">
					<div class="col-lg-12">
						
	
	<form id="conditionForm" class="form-horizontal" action="/wsms/customer/wicumb" method="post">
		<div class="form-group">
			<label for="label" class="col-lg-1 control-label"> 分公司  </label>
			<div class="controls col-lg-2">
				<input id="area-in" name="parameters[&#39;area-in&#39;]" class="searchCondition form-control" type="text" value="9600"/>
			</div>					
			<label for="label" class="col-lg-1 control-label"> 客戶帳號  </label>
			<div class="controls col-lg-2">
				<input id="cseq-in" name="parameters[&#39;cseq-in&#39;]" placeholder="xxxxxx (不含檢查碼)" class="searchCondition form-control" type="text" value=""/>
			</div>
         	<button class="btn btn-primary" type="button" id="search" style="cursor:pointer;"> 查詢 </button>		
		</div>         	
	</form>	
	
	
	<form id="customerForm" class="form-horizontal" action="/wsms/customer/wicumb" method="post">
		<div class="col-md-10 box box-primary">
			<div class="box-body">	
				<div class="form-group">
						<label for="label" class="col-lg-1 control-label">分公司</label>
						<div class="col-lg-2">
							<input id="bhno" name="bhno" placeholder="xxxx" class="editCondition form-control" type="text" value=""/>
						</div>
						
						<label for="label" class="col-lg-1 control-label">客戶帳號</label>
						<div class="controls col-lg-2">
							<input id="cseq" name="cseq" placeholder="xxxxxx" class="editCondition form-control" type="text" value=""/>
						</div>
						<div class="controls col-xs-1">-</div>
						<div class="controls col-lg-1">
							<input id="ckno" name="ckno" placeholder="x" class="editCondition form-control" type="text" value=""/>
						</div>
						
						<label class="col-lg-1 control-label">帳號類別</label>
						<div class="controls col-lg-2">
							<div class="radio">
								<input id="sortType" name="sortType" type="radio" value="0" checked="checked"/> 自然人
								<input id="sortType" name="sortType" type="radio" value="1"/> 法人
							</div>
						</div>
						<div style="color:red"> (法人不須輸入*欄位) </div>
				</div>
				
				
			    <ul class="nav nav-tabs" role="tablist">
			    	<li class="active"><a href="#profile" role="tab" data-toggle="tab"><i class="fa" class="fa-user"></i> 客戶基本資料</a></li>
					<li><a href="#others" role="tab" data-toggle="tab"><i class="fa" class="fa-list-ul"></i> 其他記載事項</a></li>
					<li><a href="#account" role="tab" data-toggle="tab"><i class="fa" class="fa-bank"></i> 出金帳戶資料</a></li>
			    </ul>

				
			    <div class="tab-content">
					
					<div class="tab-pane fade active in" id="profile">
						<div class="col-md-10 box box-primary">	
							<div class="box-body">	
								<div class="row">
									<div class="form-group">
										<label for="label" class="col-md-2 control-label">中文姓名</label>
										<div class="controls col-lg-2">
											<input id="sname" name="profile.sname" class="editCondition form-control" type="text" value=""/>
										</div>

										<label for="label" class="col-md-2 col-notsms control-label">英文姓名</label>
										<div class="controls col-lg-2">
											<input id="ename" name="profile.ename" class="editCondition form-control" type="text" value=""/>
										</div>
		
										<label for="label" class="col-lg-1 control-label">*性別</label>
										<div class="controls col-lg-2">
											<div class="radio">
												<input id="gender" name="profile.gender" type="radio" value="MALE"/> 男
												<input id="gender" name="profile.gender" type="radio" value="FEMALE"/> 女
											</div>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label for="label" class="col-lg-2 control-label">身分證字號/統一編號</label>
									<div class="controls col-lg-2">
										<input id="idno" name="profile.idno" class="editCondition form-control" type="text" value=""/>
									</div>
									<label for="label" class="col-lg-2 control-label">生日/設立日期</label>
									<div class="controls col-xs-2">民國</div>
									<div class="controls col-lg-1">
										<input id="birthYear" name="profile.birthday.birthYear" class="editCondition form-control" type="text" value=""/>
									</div>
									<div class="controls col-xs-1">年</div>
									<div class="controls col-lg-1">
										<input id="birthMonth" name="profile.birthday.birthMonth" class="editCondition form-control" type="text" value=""/>
									</div>
									<div class="controls col-xs-1">月</div>
									<div class="controls col-lg-1">
										<input id="birthDate" name="profile.birthday.birthDate" class="editCondition form-control" type="text" value=""/>
									</div>
									<div class="controls col-xs-1">日</div>
								</div>	
						
								<div class="form-group">
									<label for="label" class="col-lg-2 control-label">*學歷</label>
									<div class="controls col-lg-6">
										<input id="education" name="profile.education" type="radio" value="1"/> 博士
										<input id="education" name="profile.education" type="radio" value="2"/> 碩士
										<input id="education" name="profile.education" type="radio" value="3"/> 大學
										<input id="education" name="profile.education" type="radio" value="0"/> 大專
										<input id="education" name="profile.education" type="radio" value="4"/> 高中(職)
										<input id="education" name="profile.education" type="radio" value="5"/> 國中
										<input id="education" name="profile.education" type="radio" value="6"/> 國小
									</div>
								</div>		
												
								<div class="form-group">
									<label for="label" class="col-lg-2 col-notsms control-label">*出生地</label>
									<div class="controls col-lg-2">
										<input id="birthplace" name="profile.birthplace" class="editCondition form-control" type="text" value=""/>
									</div>
									<label for="label" class="col-lg-2 col-notsms control-label">*是否為本公司員工</label>
									<div class="controls col-lg-4">
										<input id="staffType" name="profile.staffType" type="radio" value="0"/> 本公司員工
										<input id="staffType" name="profile.staffType" type="radio" value="1"/> 員工親屬
										<input id="staffType" name="profile.staffType" type="radio" value="2"/> 一般客戶
									</div>
								</div>
																	
								<div class="form-group">
									<label for="label" class="col-lg-2 control-label">電話</label>
									<div class="controls col-lg-2">
										<input id="tel" name="profile.tel" class="editCondition form-control" type="text" value=""/>
									</div>
									<label for="label" class="col-lg-2 control-label">*行動電話</label>
									<div class="controls col-lg-2">
										<input id="mobile" name="profile.mobile" class="editCondition form-control" type="text" value=""/>
									</div>		
									<label for="label" class="col-lg-1 control-label">傳真</label>
									<div class="controls col-lg-2">
										<input id="fax" name="profile.fax" class="editCondition form-control" type="text" value=""/>
									</div>														
								</div>	

								<div class="form-group">
									<label for="label" class="col-lg-2 col-notsms control-label">*服務機構</label>
									<div class="controls col-lg-2">
										<input id="employerName" name="profile.employerName" class="editCondition form-control" type="text" value=""/>
									</div>
									<label for="label" class="col-lg-2 control-label">*公司電話</label>
									<div class="controls col-lg-2">
										<input id="employerTel" name="profile.employerTel" class="editCondition form-control" type="text" value=""/>
									</div>		
									<label for="label" class="col-lg-1 col-notsms control-label">*職稱</label>
									<div class="controls col-lg-2">
										<input id="employerTitle" name="profile.employerTitle" class="editCondition form-control" type="text" value=""/>
									</div>														
								</div>	

								<div class="form-group">											
									<label for="label" class="col-lg-1 control-label">E-mail</label>
									<div class="controls col-lg-3">
										<input id="email" name="profile.email" class="editCondition form-control" type="text" value=""/>
									</div>	
									<label for="label" class="col-lg-2 control-label">*國籍</label>
									<div class="controls col-lg-2">
										<input id="isNative" name="profile.isNative" type="radio" value="true"/> 本國人
										<input id="isNative" name="profile.isNative" type="radio" value="false"/> 其他：
									</div>										
									<div class="controls col-lg-2">
										<input id="nationality" name="profile.nationality" class="editCondition form-control" type="text" value=""/>
									</div>

								</div>
								
								<div class="form-group">
										<label for="label" class="col-lg-2 control-label">戶籍地址<br>公司登記地址</label>
										<div class="controls col-lg-1">
											<input id="homeZipCode" name="profile.homeAddress.zipCode" class="editCondition form-control" type="text" value=""/>
										</div>
										<div class="controls col-lg-6">
											<input id="homeAddr" name="profile.homeAddress.addr" class="editCondition form-control" type="text" value=""/>
										</div>
								</div>	

								<div class="form-group">
									<label for="label" class="col-lg-2 control-label">通訊地址</label>
									<div class="controls col-lg-1">
										<input id="correspondenceZipCode" name="profile.correspondenceAddress.zipCode" class="editCondition form-control" type="text" value=""/>
									</div>
									<div class="controls col-lg-6">
										<input id="correspondenceAddr" name="profile.correspondenceAddress.addr" class="editCondition form-control" type="text" value=""/>
									</div>
								</div>	

								<div class="form-group">
									<label for="label" class="col-lg-2 control-label">公司負責人</label>
									<div class="controls col-lg-2">
										<input id="pname" name="profile.owner" class="editCondition form-control" type="text" value=""/>
									</div>
									<label for="label" class="col-lg-2 control-label">負責人身份證號</label>
									<div class="controls col-lg-2">
										<input id="lidno" name="profile.ownerIdno" class="editCondition form-control" type="text" value=""/>
									</div>														
								</div>	
														
								<div class="form-group">
									<label for="label" class="col-lg-2 control-label">緊急聯絡人</label>
									<div class="controls col-lg-2">
										<input id="emergencyName" name="profile.emergencyName" class="editCondition form-control" type="text" value=""/>
									</div>
									<label for="label" class="col-lg-2 col-notsms control-label">*關係</label>
									<div class="controls col-lg-2">
										<input id="emergencyRelationship" name="profile.emergencyRelationship" class="editCondition form-control" type="text" value=""/>
									</div>		
									<label for="label" class="col-lg-2 control-label">聯絡電話</label>
									<div class="controls col-lg-2">
										<input id="emergencyTel" name="profile.emergencyTel" class="editCondition form-control" type="text" value=""/>
									</div>														
								</div>	
																																		
							</div>
						</div>
					</div>

					
					<div class="tab-pane fade" id="others">
						<div class="col-md-10 box box-primary">		
							<div class="box-body">	
								<div class="form-group">
									<label for="label" class="col-lg-2 control-label">對帳單取得方式</label>
									<div class="controls col-lg-8 radio">
										<input id="statementSending" name="otherStatement.statementSending" type="radio" value="1"/> 郵寄通訊地址
										<input id="statementSending" name="otherStatement.statementSending" type="radio" value="2"/> 郵寄戶籍地址
										<input id="statementSending" name="otherStatement.statementSending" type="radio" value="2"/> 郵寄公司登記地址(限法人戶)
										<input id="statementSending" name="otherStatement.statementSending" type="radio" value="0"/> 自行領取
									</div>
								</div>	
							</div>		
						</div>
					</div>

			    	
					<div class="tab-pane fade" id="account">
						<div class="col-md-10 box box-primary">		
							<div class="box-body">	
								<div class="form-group" id="twdAccount">
								    <h3>台幣帳戶</h3>
								    <div class="form-group">
										<label for="label" class="col-md-1 control-label">銀行名稱</label>
										<div class="controls col-lg-2">
											<input id="twdBankName" name="bankAccount.twdAccount.bankName" class="editCondition form-control" type="text" value=""/>
										</div>								    
										<label for="label" class="control-label">分行</label>
									</div>
									<div class="form-group">
										<label for="label" class="col-md-1 control-label">帳號</label>
										<div class="controls col-lg-5">
											<input id="twdAccountNo" name="bankAccount.twdAccount.accountNo" class="editCondition form-control" type="text" value=""/>
										</div>		
									</div>							
								</div>	
								<div class="form-group" id="fcyAccount">
									<h3>外幣帳戶</h3>
									<div class="form-group">
										<label for="label" class="col-md-1 control-label">銀行名稱</label>
										<div class="controls col-lg-2">
											<input id="fcyBankName" name="bankAccount.fcyAccount.bankName" class="editCondition form-control" type="text" value=""/>
										</div>	
										<label for="label" class="control-label">分行</label>
									</div>
									<div class="form-group">
										<label for="label" class="col-md-1 control-label">帳號</label>
										<div class="controls col-lg-4">
											<input id="fcyAccountNo" name="bankAccount.fcyAccount.accountNo" class="editCondition form-control" type="text" value=""/>
										</div>									
									</div>
									<div class="form-group">
										<label for="label" class="col-md-1 control-label">戶名</label>
										<div class="controls col-lg-4">
											<input id="fcyAccountName" name="bankAccount.fcyAccount.accountName" class="editCondition form-control" type="text" value=""/>
										</div>									
									</div>
								</div>	
								
							    <div class="form-group">		
							    	<h3>集保帳號</h3>							
									<div class="controls col-lg-5">
										<input id="tdccAccountNo" name="bankAccount.tdccAccount.accountNo" class="editCondition form-control" type="text" value=""/>
									</div>			
								</div>									
							</div>		
						</div>
			    	</div>
			    </div>				
				
				<div align="center">
					<button class="btn btn-success" type="submit" id="viewPdf" > 報表預覽 </button>
				</div>
			</div>	    
		</div>
    </form>

	<script>	
		var natureValidateFields = {       	  
	    	'bhno': {
	    		row: '.col-lg-2',
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	    	}, 	
	    	'cseq': {
	    		row: '.col-lg-2',
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	    	}, 	
	    	'ckno': {
	    		row: '.col-lg-1',
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	    	}, 		  
	    	'sortType': {
	    		row: '.col-lg-2',
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	        },	    	
	    	'profile.sname': {
	    		row: '.col-lg-2',
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	    	}, 
	    	'profile.ename': {
	    		row: '.col-lg-2',
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	    	}, 		            	
	    	'profile.gender': {
	    		row: '.col-lg-2',
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	        },
	    	'otherStatement.statementSending': {
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	        },
	    	'bankAccount.twdAccount.bankName': {
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	        },		                
	    	'bankAccount.twdAccount.accountNo': {
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	        }				                
	    };
		
		var corporateValidateFields = {         	
	    	'bhno': {
	    		row: '.col-lg-2',
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	    	}, 	
	    	'cseq': {
	    		row: '.col-lg-2',
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	    	}, 	
	    	'ckno': {
	    		row: '.col-lg-1',
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	    	}, 		
	    	'sortType': {
	    		row: '.col-lg-2',
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	        },		    	
	    	'profile.sname': {
	    		row: '.col-lg-2',
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	    	}, 
	    	'otherStatement.statementSending': {
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	        },
	    	'bankAccount.twdAccount.bankName': {
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	        },		                
	    	'bankAccount.twdAccount.accountNo': {
	            validators: {
	                notEmpty: {
	                    message: '※ 請輸入此欄位!'
	                }
	            }
	        }				                
	    };
		
		function registerValidation(validationFields) {
			// $('#customerForm').removeData('formValidation');
			
			$('#customerForm')
			.formValidation({
	            framework: 'bootstrap',
	            // Only disabled elements are excluded
	            // The invisible elements belonging to inactive tabs must be validated
	            excluded: [':disabled'],
	            icon: {
	                valid: 'glyphicon glyphicon-ok',
	                invalid: 'glyphicon glyphicon-remove',
	                validating: 'glyphicon glyphicon-refresh'
	            },
	            fields: validationFields
			})
			// Called when a field is invalid
			.on('err.field.fv', function(e, data) {
	            // data.element --> The field element
	
	            var $tabPane = data.element.parents('.tab-pane'),
	                tabId    = $tabPane.attr('id');
	
	            $('a[href="#' + tabId + '"][data-toggle="tab"]')
	                .parent()
	                .find('i')
	                .removeClass('fa-check')
	                .addClass('fa-times');
			})
	        // Called when a field is valid
			.on('success.field.fv', function(e, data) {
	            // data.fv      --> The FormValidation instance
	            // data.element --> The field element
	
	            var $tabPane = data.element.parents('.tab-pane'),
	                tabId    = $tabPane.attr('id'),
	                $icon    = $('a[href="#' + tabId + '"][data-toggle="tab"]')
	                            .parent()
	                            .find('i')
	                            .removeClass('fa-check fa-times');
	
	            // Check if all fields in tab are valid
	            var isValidTab = data.fv.isValidContainer($tabPane);
	            if (isValidTab !== null) {
	                $icon.addClass(isValidTab ? 'fa-check' : 'fa-times');
	            }
			}).on('removed.field.fv', function(e, data) {
				$('input[name="'+data.field+'"]').removeAttr('data-fv-field, value').parent()
					.removeClass('has-feedback has-success has-error')
					.find('i, small').remove();			
			})
	        .find('input[name="profile.gender"], input[name="otherStatement.statementSending"]')
	        // Init icheck elements
	        .icheck({
	            // The tap option is only available in v2.0
	            tap: true,
	            checkboxClass: 'icheckbox_square-pink',
	            radioClass: 'iradio_square-pink'
			})
			// Called when the radios/checkboxes are changed
			.on('ifChanged', function(e) {
	           // Get the field name
	           var field = $(this).attr('name');
	           $('#customerForm').formValidation('revalidateField', field);
			});
			
			// $('#customerForm').data('formValidation').resetForm();
		}

	 	
	    $(function() { 
		    registerValidation(natureValidateFields);
		    
		 	// 帳號類別點選 "自然人"
		    $(document).on('ifChecked', '#sortType[value=0]', function() {
		    	console.log("sortType=0");
			    $.each($('#customerForm').data('formValidation').options.fields, function(key, value) {
			    	delete $('#customerForm').data('formValidation').options.fields[key];
			    	$('input[name="'+key+'"]').removeAttr('data-fv-field').removeAttr('value').parent()
					.removeClass('has-feedback has-success has-error')
					.find('i, small').remove();	
			    });
			    
				 $('#customerForm').removeData('formValidation');

			    registerValidation(natureValidateFields);
				// $('#customerForm').data('formValidation').resetForm();
			});
		    
		 	// 帳號類別點選 "法人"
		    $(document).on('ifChecked', '#sortType[value=1]', function() {
		    	console.log("sortType=1");
		    	$.each($('#customerForm').data('formValidation').options.fields, function(key, value) {
			    	delete $('#customerForm').data('formValidation').options.fields[key];
			    	$('input[name="'+key+'"]').removeAttr('data-fv-field').removeAttr('value').parent()
					.removeClass('has-feedback has-success has-error')
					.find('i, small').remove();	
			    });
			    
				$('#customerForm').removeData('formValidation');

			    registerValidation(corporateValidateFields);
				// $('#customerForm').data('formValidation').resetForm();
			});
		    
		 	// 按 "查詢"
			$('button#search').on('click', function(e) {
				console.log('ajaxSearch() Start Time=' + new Date());
				
				// Clean Field Value
				$('#customerForm').trigger("reset");
				$('.iradio_square-pink.checked').removeClass('checked')
				
				$.ajax ({
					type : 'POST', 
					url : '/wsms/customer/wicumb/query/s',  
					data : $('#conditionForm').serialize(),			
					dataType: 'json', 
					success : function(result, status) {
						console.log("result.responseMsg.status=" + result.responseMsg.status);
						if (result.responseMsg.status == "success") {
							console.log("result.listdata=" + result.listdata);	
							parseResult("customerForm", $.parseJSON(result.listdata));
						} else {
				            bootbox.alert(result.responseMsg.message, function() {
				            	console.log("result.responseMsg.message=" + result.responseMsg.message);
				            });						
						};	
						console.log('ajaxSearch() Success Time=' + new Date() + ', status=' + status);	
					}, error: function(xmlHttpRequest, textStatus, errorThrown) { 
						alert("頁面閒置太久，連線逾時，重新導回登入頁!");
						window.location.href = "http://localhost:8080/wsms/";
						console.log('ajaxSearch() Error Time=' + new Date() + ' ,textStatus=' + textStatus + ', errorThrown=' + errorThrown);	
	                    console.log('xmlHttpRequest.status=' + xmlHttpRequest.status + ', xmlHttpRequest.readyState=' + xmlHttpRequest.readyState);
					}, complete: function(xmlHttpRequest, textStatus) { 
						console.log('ajaxSearch() Complete Time=' + new Date() + ', xmlHttpRequest=' + xmlHttpRequest + ', textStatus=' + textStatus);
					} 
				});
		    });
		 	
		 	// 按 "報表預覽"
			$('button#viewPdf').on('click', function(e) {
				$('#customerForm').attr('action', "/wsms/customer/wicumb/viewPdf").submit();
			});
	    });

	    function parseResult(divId, data) {	
			$.each(data, function(key, value) {
				console.log("key=" + key + ", value=" + value);
				if (jQuery.type(value) == "object") {
					parseResult(key, value);
				} else if ($("#" + divId + " #" + key).length && value!="") {
					var element = $("#" + divId + " #" + key);
		            switch (element[0].type) {
		                case 'radio':
							$("#" + divId + " #" + key + "[value=" + value + "]").iCheck('check');	
		                    break;
		                case 'select':
		                case 'select-one':
		                case 'text':
		                case 'hidden':
							element.val(value);	
		                    break;
		                case 'img': //Assumption is that value is in the HREF$ALT format
							element.attr("src", "data:image/jpeg;base64," + value)			
		                    break;
		                default:
		                    try {
		                        $(element).html(value);
		                    } catch (exc) { }		            
		            }
				};
			});    	
	    }
	</script> 
	
					</div>
				</div>
			</section>
			

		</aside>
		

	</div>
	
</body>

</html>

**Comment by nghuuphuoc** [comment]
> When I change the value of an radio button(ex:sortType), the validation fields must be changed too.
> So I must remove original validation attributes and then register to new validation fields

In stead of removing validators and adding another one to fields, you should add all of them initially. Some of validators can be disabled initially by setting `enabled: false`, and then based on the selected radio, you can enable them (and disable other validators too).

See 
* http://formvalidation.io/examples/conditional-validation/
* http://formvalidation.io/examples/enable-validator/

**Comment by yuwen0405** [comment]
The problems are solved by setting the validators enabled:true/false. Thanks for your feedback!

**Comment by nghuuphuoc** [comment]
Awesome :+1:
