### ISSUE TITLE
Validate name input field with no number or symbol like $#%@ ....

### ISSUE THREAD

**Issue by naktieuthu** [formvalidation/support#414]
As the title said, I want to validate my first name, last name field so that customers cannot input number, symbol like /#$@[ ....etc, and no space at the beginning and the end of the string. Right now, my validation is just not empty:
```
firstName: {
                	message: 'First name is not valid',
               		validators: {
                   		notEmpty: {
                        	message: 'First name is required and can\'t be empty'
							}						
						}
					}
```

So, how can I do that with your validation.? I'm not good at all with the pattern....

**Comment by nghuuphuoc** [comment]
Please look at the [Basic example](http://formvalidation.io/validators/regexp/#basic-example) of [regexp validator](http://formvalidation.io/validators/regexp/)

**Comment by naktieuthu** [comment]
Oh well, I forgot to check those examples, thank you
