### ISSUE TITLE
i18n add on

### ISSUE THREAD

**Issue by ugrinwald** [formvalidation/support#417]
Hi Phuoc.

I've followed the instructions for the i18n add on and I am trying to support english and french using the object literal method. I am receiving this error:

Cannot read property 'updateOption' of undefined

It's pointing to the i18n.min.js file.

Any ideas?

Thanks

**Comment by nghuuphuoc** [comment]
Can you give me the sample code you're using?

**Comment by ugrinwald** [comment]
Hi. So the set up is inside my local machine and is using AEM 6.1.
the dependencies are brought in by way of clientlibs and I know they are loading fine. This file looks like this.

jquery-ui/jquery-ui.min.js
bootstrap/js/bootstrap.min.js
handlebars/handlebars.runtime-v3.0.3.js
fontfaceobserver/fontfaceobserver.js
formvalidator/js/formValidation.min.js
formvalidator/js/bootstrap.min.js
formvalidator/js/i18n.min.js
modernizr/modernizr.custom.js
polyfills/Number.toLocaleString.js
adobeautocomplete/jquery.adobe.autocomplete.min.js

**Comment by ugrinwald** [comment]
The code block with form validation looks like this.

ShoppingListEmailForm.prototype._formValidation = function _formValidation() {
    	this._$configForm
        .formValidation({
            framework: 'bootstrap',
            excluded: ':disabled',
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
           addOns: {
            i18n: {}
            },
            fields: {
                'shoppinglist-emailform_youremail': {
                	icon: false,
                    validators: {
	                    notEmpty: {
                        	message: {
                            en_US: 'The username and password cannot be the same',
                            vi_VN: 'Mật khẩu và tên đăng nhập phải khác nhau'
                        }
	                    },
                        emailAddress: {
                        	message: 'ERROR: Please check your email address.'
                        },
	                    regexp: {
                            regexp: '^[^@\\s]+@([^@\\s]+\\.)+[^@\\s]+$',
                            message: 'ERROR: Please check your email address.'
                        }
                    }
	            },

**Comment by ugrinwald** [comment]
For sake of speed the above code would have all messages as object literals like the one in 'notEmpty'
So emailAddress would also have the message as:

message: {
                 en_US: 'The message in English',
                 fr_FR: 'The message in French'
                }
And all messages are en and fr only.
