### ISSUE TITLE
Bootstrap 4 support ?

### ISSUE THREAD

**Issue by Izopi4a** [formvalidation/support#418]
With the alpha 2, i think i am not the only one who started re-organizing his project, and icons and stuff is quite different there, can we expect a support ? and eventually when ?

**Comment by nghuuphuoc** [comment]
Absolutely, the plugin will support Bootstrap 4. I still wait for it to get stable version.

**Comment by tobsn** [comment]
Are there any work arounds to make this work already? Thanks!

**Comment by nghuuphuoc** [comment]
I haven't tried Bootstrap 4, but can you tell me the problem you got?

**Comment by Izopi4a** [comment]
icons are different now and they are misplaced cuz they changed it a little bit. 
From my experience so far those are the 2 issues, which should not be gigantic ( i think )

**Comment by tobsn** [comment]
Maybe I'm also doing something wrong... I don't see it adding a form input group around it - below is after render required field and leaving the input empty:

	<fieldset class="form-group has-feedback has-error">
		<label for="formStreetAddress">Street Address:</label>
		<input type="text" name="ship[street]" class="form-control form-control-sm" id="formStreet" placeholder="Your Address" autocomplete="off" required="" data-fv-notempty-message="Please enter your Street" data-fv-field="ship[street]">
		<i class="form-control-feedback fa-times fa" data-fv-icon-for="ship[street]" style="display: inline;"></i>
		<small class="help-block" data-fv-validator="notEmpty" data-fv-for="ship[street]" data-fv-result="INVALID" style="">Please enter your Street</small>
	</fieldset>

the setup is just:

    framework: 'bootstrap',
    icon: {
                required: 'fa fa-asterisk',
                valid: 'fa fa-check',
                invalid: 'fa fa-times',
                validating: 'fa fa-refresh'
        }
