### ISSUE TITLE
Icon for parent field (identical)

### ISSUE THREAD

**Issue by Pantela777** [formvalidation/support#419]
I think it's bug...
Exp. if I have two fields and join one of with identical.
I can't see parent field error icon:
![](http://i.imgur.com/aLJpYF2.png)
```
user_email: {
	verbose: false,
	validators: {
		notEmpty: {
			message: 'Empty'
		}
	}
},
user_confirm_email: {
	validators: {
		notEmpty: {
			message: 'Empty'
		}
		identical: {
			field: 'user_email',
			message: 'Not match'
		}
	}
},
```

**Comment by nghuuphuoc** [comment]
Maybe you missed a comma 

```javascript
user_email: {
    verbose: false,
    validators: {
        notEmpty: {
            message: 'Empty'
        }
    }
},
user_confirm_email: {
    validators: {
        notEmpty: {
            message: 'Empty'
        }, // <---- Yes, you missed this
        identical: {
            field: 'user_email',
            message: 'Not match'
        }
    }
}
```

I created a [simple fiddle](http://jsfiddle.net/nghuuphuoc/cv24hqL0/) and it works as expected:

<img width="372" alt="icon" src="https://cloud.githubusercontent.com/assets/4226036/11704928/8846fab4-9f1e-11e5-8f92-73b0b3136250.png">

**Comment by Pantela777** [comment]
When I add "**regexp**", You can see bug: http://jsfiddle.net/cv24hqL0/2/

**Comment by naktieuthu** [comment]
Move regexp before notEmpty solves your problem

```
user_email: {
          verbose: false,
          validators: {
          	regexp: {
							regexp: '^[a-zA-Z0-9-_+\\.]+@([a-zA-Z0-9-_]+\\.)+[a-zA-Z]+$',
							message: 'Regexp'
						},
            notEmpty: {
              message: 'Empty'
            }						
          }
        },
```

http://jsfiddle.net/cv24hqL0/5/

**Comment by Pantela777** [comment]
Thx. bug is fixed, but I have another validators params, and I must to write "notEmpty" param the last.
I think you are must to fixed this moment, because this is not 100% correctly way...
