### ISSUE TITLE
Failed to send and receive AJAX form data

### ISSUE THREAD

**Issue by funcion** [formvalidation/support#422]
I made a form Codeigniter with PHP, MySQL and AJAX, and while sending and receiving the request form displays this error:

fv.resetForm(true); Uncaught ReferenceError: fv is notdefined

Please appreciate your support!

**Comment by nghuuphuoc** [comment]
Can you please give me the form markup and the Javascript code?

**Comment by funcion** [comment]
Hi Phuoc,

Thank you very much for your quick response, code here.

.on('success.form.fv', function(e) {
          // Prevent form submission
          e.preventDefault();

          var $form       = $(e.target),
              formData    = new FormData(),
              params      = $form.serializeArray(),
              image       = $form.find('[name="image"]')[0].file,
              dni_files   = $form.find('[name="dni"]')[0].file;

          $.each(dni_files, function(i, file) {
              // Prefix the name of uploaded files with "uploadedFiles-"
              // Of course, you can change it to any string
              formData.append('dni[]', file);
          });

          formData.append('image', image[0]);
    formData.append('id', Math.random());

          $.each(params, function(i, val) {
              formData.append(val.name, val.value);
          });

          // Use Ajax to submit form data
          $.ajax({
              url: '<?php echo base_url() . "home/register"; ?>',
              data: formData,
              cache: false,
              contentType: false,
              processData: false,
              type: 'POST',
              dataType: "json",
              xhr: function () {
              //var xhr = new window.XMLHttpRequest();
              var xhr2 = $.ajaxSettings.xhr();
                  xhr2.upload.addEventListener("progress", function (evt) {

                      if (evt.lengthComputable) {
                          //Pencent native with decimal
                          var percentComplete = evt.loaded / evt.total;
                          //Convert percentage integer
                          var porcentageRound = Math.round(percentComplete
* 100);
                          //Mostramos la ventana modal
                          $('#msg').modal('show');

                          //Settings and show values progress bar percent
                            $("#msg .progress .progress-bar").attr(
'aria-valuenow', porcentageRound );
                            $('#msg .progress .progress-bar').css( 'width',
porcentageRound + '%' );
                            $("#msg .progress .progress-bar").html(
porcentageRound  + '%' );

                          //Una vez completado podemos manipular el DOM
                          if (percentComplete === 1) {

                            //Mostramos un mensaje mientra recibimos
respuesta del servidor
                            $('#msg .modal-title').html('<i class="fa
fa-cog fa-spin font20"></i> Procesando espere por favor!');
                            $('#msg .modal-body').html('<p>Estamos
procesando su registro, por favor espere un momento, esta operación puede
tardar unos pocos segundos.</p>');
                          }
                      }
                  }, false);

                  return xhr2;
              },
              error: function () {
                alert( 'If there is an error message' );
              },
              beforeSend: function () {
                //Events prevent automated browser to (F5 - X - Previous
page)
                window.onbeforeunload = function() { return "Todavía hay un
proceso activo, espere al completar la operación."; };
              },
              complete: function () {
                //Events prevent automated browser to (F5 - X - previous
page)
                window.onbeforeunload = function() { /*NULL*/ };
              },
              success: function(result) {

                if( result.response == true ) {
                  //Events prevent automated browser to (F5 - X - previous
page)
                  window.onbeforeunload = function() { /*NULL*/ };
                  //Close modal window
                  $('#msg').modal('hide');
                  //Show message server
                  $('#msg-server .ctn').html( result.message );

                  // You can reset the form if you want
                  fv.resetForm(true);

                  // You can enable the submit button
                  // to allow the user to add new record
                  fv.disableSubmitButtons(true);
                }

                if( result.response == false ) {
                  //Events prevent automated browser to (F5 - X - previous
page)
                  window.onbeforeunload = function() { /*NULL*/ };
                  //Show message server
                  $('#msg').modal('hide');
                  $('#msg-error').modal('show');
                  $('#msg-error .title').html('Estatus de la petición');
                  $('#msg-error .ctn').html( result.message );

                  // You can reset the form if you want
                  fv.resetForm(true);
                }
              }
          });
      });

2015-12-13 21:36 GMT-05:00 Phuoc Nguyen <notifications@github.com>:

> Can you please give me the form markup and the Javascript code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formvalidation/support/issues/422#issuecomment-164326134>
> .
>



-- 
*Atte:*
Luis Figuera

*Skype: *milindex
*PIN:* 796A23A6
*WhatsApp:* 04248429422
*Email: *contacto@tb.com.ve - milindex@gmail.com
*Teléfonos: *+58 (0424) - 842.94.22 - (0281) - 996.93.65
---------------------------------------------------------------------------
---------------------------------------------------------------------------

*Dios le continúe bendiciendo!*

**Comment by nghuuphuoc** [comment]
There is issues of `Uncaught ReferenceError: fv is notdefined` because you don't declare the `fv`.

You should declare it at the top of `success.form.fv` event handler:

```javascript
.on('success.form.fv', function(e) { 
    // Prevent form submission e.preventDefault(); 
    var $form = $(e.target),
        fv = $form.data('formValidation'),  // <--- You missed that line
        formData = new FormData(),

    // Do other things as above
    ... 
});
```

**Comment by funcion** [comment]
Ok perfect thank you very much for your help.

Another thing I developed a system tarball to see my progress as a
programmer, it is a system of user registration and login.
I want a programmer experienced as you revice and tell me if something
better in terms of safety, performance and functionality.

It can help you with this?

2015-12-15 10:03 GMT-05:00 Phuoc Nguyen <notifications@github.com>:

> There is issues of Uncaught ReferenceError: fv is notdefined because you
> don't declare the fv.
>
> You should declare it at the top of success.form.fv event handler:
>
> .on('success.form.fv', function(e) {
>     // Prevent form submission e.preventDefault();
>     var $form = $(e.target),
>         fv = $form.data('formValidation'),  // <--- You missed that line
>         formData = new FormData(),
>
>     // Do other things as above
>     ...
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formvalidation/support/issues/422#issuecomment-164790883>
> .
>



-- 
*Atte:*
Luis Figuera

*Skype: *milindex
*PIN:* 796A23A6
*WhatsApp:* 04248429422
*Email: *contacto@tb.com.ve - milindex@gmail.com
*Teléfonos: *+58 (0424) - 842.94.22 - (0281) - 996.93.65
---------------------------------------------------------------------------
---------------------------------------------------------------------------

*Dios le continúe bendiciendo!*

**Comment by nghuuphuoc** [comment]
I'm sorry that I can't help on reviewing that due to the limitation of my time :(
