### ISSUE TITLE
callback validator  does not calculate integer value correctly

### ISSUE THREAD

**Issue by Dror1966** [formvalidation/support#423]
I tried to  validated between 2 fields expiredBox1 and expiredBox2

This is the callback validation on a field name expiredBox2
expiredBox2 must be grater then expiredBox1

Validation code:
-------------------------------------------------------------------------------------------------------
expiredBox2: {
	validators: {
			callback: {
					message: 'Must be greater then itemBox1 value',
					callback: function (value, validator, $field) {
					var itemBox1 = $('#expiredBox1').val();
					return value > itemBox1;
					};
                }
            }
}
-------------------------------------------------------------------------------------------------------
expiredBox1 = 30  expiredBox2 = 20   -  validation done ok send error 
expiredBox1 = 30  expiredBox2 = 40  -  validation done ok send success
expiredBox1 = 30  expiredBox2 = 90   -  validation done ok send success
expiredBox1 = 30  expiredBox2 = 100   -  validation failed  << this is the problem any number between 100 - 299 failed to validate  
if expiredBox2 is above 299 validation done ok .. 

I suspect that  validation is done for first digit... .. 

please help 

Thank Dror

**Comment by Dror1966** [comment]
Sorry this is not a bug , I  found the problem I  had to add parseInt() to line 
var itemBox1 = parseInt($('#expiredBox1').val());

and all works fine 

Thank

**Comment by nghuuphuoc** [comment]
Thank for your confirmation!
