### ISSUE TITLE
Validate only the field in Bootstrap Modal Dialog

### ISSUE THREAD

**Issue by laxman4434** [formvalidation/support#425]
Hi nghuuphuoc,

I have situation where i need to show forgot password section in a bootstrap modal dialog, while asking for username and password on the main page. The problem is when i open the modal dialog and click the button in modal dialog to validate the email field, the button click event is validating the username and password fields on the page as well.

Could you please help me out to validate only the email field in modal dialog when the button in modal dialog is clicked, not to validate the username and password fields on the main page.

Thanks in advance

**Comment by nghuuphuoc** [comment]
I think you should split the username/password and forgot password section into separated forms. So clicking on the forgot password form doesn't effect on the form in main page.

**Comment by laxman4434** [comment]
Thanks for your reply. What if i have a main form in master page. 

I tried to put the modal content in separate form as advised in

http://formvalidation.io/examples/modal/

But it did not worked for me.

**Comment by nghuuphuoc** [comment]
This is interesting case.
I made new http://formvalidation.io/examples/toggling-validators-master-page/ example for you!

**Comment by laxman4434** [comment]
That worked like a charm.

Thank you very much nghuuphuoc. You are the best.
Never seen anyone replying this fast.

Your plugin and you, both are wonderful.
Totally worth buying your plugin.

**Comment by nghuuphuoc** [comment]
Thank a lot!

**Comment by laxman4434** [comment]
Hi nghuuphuoc,

With the above example, can i use a class name instead of field name.

I got more than ten fields on main  page and more than 5 fields on modal dialog. With the above example i need to enable and disable ten fields on main page and also the 5 fields on modal dialog.

So I am just wondering, is there any way to use class name or container name to disable and enable validators.

Thanks in advance.
