### ISSUE TITLE
Revalidate select list to change Jquery

### ISSUE THREAD

**Issue by funcion** [formvalidation/support#429]
I'm doing a system for selecting dynamically core of countries, states, provinces and cities data, but changing the select are as validated when you actually have the invalid option, but this happens when you change with JQuery when I do it manually if It works.

Example: The user selects his country after US, selecting a state appear cities, but if the user changes Pais, have to reset the fields of states, provinces and cities, and seleecioanr The first option is zero appear, and I do it with jQuery.

I'm trying to do it:
$('#bootstrapSelectForm').formValidation('revalidateField', 'colors');

And it does not work, the selection of the first do option through Jquery.
$('#province, #city').val( $("#city option:first").val() );

I'm doing this: 
 $('#city').on('change', function(e) {
    $('#form_register').formValidation('revalidateField', 'city');
  });

Neither works.

As I can defend select list that has changed with jQuery.

Here the code:

switch(id_select) {
      case 'state':
        $.ajax({
            url: '/systems/has_provinces',
            type: 'POST',
            dataType: 'json',
            data: {
              'state_id':val_select,
              'id':Math.random(),
              'csrf_token_sf' : csrf_name
            },
            success: function(result) {
              
              if(result.response == true) {
                //Remove [select#state] attr disable
                $('#province, #city').attr('disabled', 'disabled');
                //Remove all option select
                //$('#province, #city').html('<option value="" selected>Localidad</option>');
                $('#province, #city').val( $("#city option:first").val() );
                //Add [<option>] to select html
                $('#province').html( '<option value="" selected>Seleccione</option>' + result.message );
                //Remove [select#state] attr disable
                $('#province').removeAttr('disabled');
              } 

              if(result.response == false) {
                //Remove [select#state] attr disable
                $('#province, #city').attr('disabled', 'disabled');
                //Remove all option select
                $('#province, #city').html('');
                //Show message error system
                alert( result.message );
              }
            }
        });
      break;

**Comment by nghuuphuoc** [comment]
Can you please give me the form markup, especially the HTML code containing the `state`, `city`, `province` fields?
