### ISSUE TITLE
Validating danielfarrell bootstrap-combobox

### ISSUE THREAD

**Issue by prietoedgardo** [formvalidation/support#43]
Hi!

Im trying to validate danielfarrell bootstrap-combobox

https://github.com/danielfarrell/bootstrap-combobox

But I can't make it work, I applied the basic principles for integration, the revalidateField, but then the combobox dont take the design, and it can't be validated, any ideas to make it work?

Thank you for your great plugin!

**Comment by nghuuphuoc** [comment]
@prietoedgardo 
I made new [Playing with Bootstrap Combobox](http://formvalidation.io/examples/bootstrap-combobox/) example for you.

Hopefully it helps you.

![bootstrap combobox](https://cloud.githubusercontent.com/assets/4226036/6457117/00a37a0a-c1a3-11e4-8f91-ce70f601f300.png)

**Comment by prietoedgardo** [comment]
Thank you, thank you, thank you! it works very well!, btw this bootstrap combobox plugin is super nice, im glad to see it working together with your excellent validation plugin, thank you again!
