### ISSUE TITLE
Implementing password policy

### ISSUE THREAD

**Issue by amucino** [formvalidation/support#433]
I am trying to validate a password field to implement the following password policy:

'Password must be minimum 8 characters at least 1 Uppercase Alphabet, 1 Lowercase Alphabet, 1 Number and 1 Special Character such as:  ~!@#$%^+-'

I tried looking for examples on your site but couldn't find any. I found this source but seems to only work for ASP.net, I copied the code on the regexp:  but doesn't seem to validate properly.

 regexp: /^(?=.[a-z])(?=.[A-Z])(?=.\d)(?=.[$@$!%?&])[A-Za-z\d$@$!%?&]{8,} $/i,
                        message: 'Password must be minimum 8 characters at least 1 Uppercase Alphabet, 1 Lowercase Alphabet, 1 Number and 1 Special Character such as:  ~!@#$%^+-'

but that didn't work. Any ideas ?

**Comment by nghuuphuoc** [comment]
You can use either the [regexp](http://formvalidation.io/validators/regexp/) validator or make [your own](http://formvalidation.io/developing/) one.

**Comment by nghuuphuoc** [comment]
New better example that integrates Dropbox zxcvbn library is available at http://formvalidation.io/examples/building-password-strength-meter/
