### ISSUE TITLE
Date range

### ISSUE THREAD

**Issue by Tranchetes** [formvalidation/support#435]
Hi, just testing date range in my web app and wasn't working. I checked if I was doing something wrong on http://formvalidation.io/validators/date/ and the Date range example is not working at all. The only date that is validating the input is when is empty.
Thanks

**Comment by nghuuphuoc** [comment]
There's a typo in the example. The `min` and `max` should be correct dates that follow the same format as defined by the `format` option:

```javascript
$(document).ready(function() {
    $('#rangeForm').formValidation({
        framework: 'bootstrap',
        icon: {
            ...
        },
        fields: {
            date: {
                validators: {
                    date: {
                        message: 'The date is not valid',
                        format: 'YYYY/MM/DD',
                        // min and max options can be strings or Date objects
                        min: '2000/01/01',    // BEFORE: '2000-01-01'
                        max: '2020/12/30'    // BEFORE: '2020-12-30'
                    }
                }
            }
        }
    });
});
```

The [date range](http://formvalidation.io/validators/date/#date-range-example) example is also updated.

**Comment by Tranchetes** [comment]
Thanks!
