### ISSUE TITLE
Framework undefined

### ISSUE THREAD

**Issue by Dewey12** [formvalidation/support#436]
Hi,

I don’t understand why the FormValidator not working :

![image](https://cloud.githubusercontent.com/assets/16401481/11956022/3df4dd80-a8b7-11e5-9441-807c50054163.png)
![image](https://cloud.githubusercontent.com/assets/16401481/11956030/4a1fbf26-a8b7-11e5-98cb-e811f134996a.png)

In the master page : 
![image](https://cloud.githubusercontent.com/assets/16401481/11956035/56581130-a8b7-11e5-9bb3-054baa1906b6.png)

In my JavaScript :
```
$('#FORM_SC')
        .formValidation({
            framework: 'bootstrap',
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                IPT_TAB1_PRO_OPE: { validators: { notEmpty: {}} }
            }
        })
        .on('success.form.bv', function (e) {

            e.preventDefault();

            alert('hello');
        });
```
The function called after ajax response.
My ajax return my form -> “FORM_SC”. I think is that the problem.

If I used BoostrapValidator 0.5.3 it’s working !

**Comment by nghuuphuoc** [comment]
Does the issue occur on all browsers, including Chrome, Firefox, and IE?

**Comment by nghuuphuoc** [comment]
Feel free to reopen it when you provide more information. I can reproduce the issue currently.
