### ISSUE TITLE
Is there any way to use class names or container name for enabling and disabling "enablefieldValidators"

### ISSUE THREAD

**Issue by laxman4434** [formvalidation/support#437]
Hi nghuuphuoc,

http://formvalidation.io/examples/toggling-validators-master-page/

With the above example, can i use a class name instead of field name.

I got more than ten fields on main page and more than 5 fields on modal dialog. With the above example i need to enable and disable ten fields on main page and also the 5 fields on modal dialog.

So I am just wondering, is there any way to use class name or container name to disable and enable "enablefieldValidators" validator.

class name would be a better option for me, as my modal dialog is in almost all the pages of the website and it is conflicting with all the fields on main pages.

Thanks in advance.

**Comment by nghuuphuoc** [comment]
There isn't official method to enable/disable validators for multiple fields at the same time, but you can do it yourself.

For example, you can create a simple method for that

```javascript
// form: The form instance
// fields: Array of field names
// enabled: Can be true or false
function enableFieldsValidators(form, fields, enabled) {
    for (var i in fields) {
        form.formValidation('enableFieldValidators', fields[i], enabled);
    }
}
```

Usage:
```javascript
// Enable validators for both username and password fields
enableFieldsValidators($("#yourForm"), ['username', 'password'], true);

// Disable validators for both username and password fields
enableFieldsValidators($("#yourForm"), ['username', 'password'], false);
```

**Comment by nghuuphuoc** [comment]
Or, more flexible way, enable/disable by given CSS class of field:

```javascript
function enableFieldsValidators($form, className, enabled) {
    // Find all fields have the class name
    $form.find('.' + className).each(function(index, field) {
        $form.formValidation('enableFieldValidators', $field, enabled);
    });
}
```

Usage:
```html
<!-- All fields inside a modal should have the same CSS class, such as `inside-modal` -->
<form id="signInForm">
    <!-- modal -->
    <div class="modal fade">
        <input type="text" class="form-control inside-modal" name="email" />
    </div>
</form>
```

```javascript
// Enable validator of all fields that have the `inside-modal` class:
enableFieldsValidators($('#signInForm'), 'inside-modal', true);

// Disable
enableFieldsValidators($('#signInForm'), 'inside-modal', false);
```

I hope these approaches give you an idea to solve your problem.

**Comment by laxman4434** [comment]
Hi nghuuphuoc,

Thanks for your reply. I tried the following method.

function enableFieldsValidators($form, className, enabled) {
    // Find all fields have the class name
    $form.find('.' + className).each(function(index, field) {
        $form.formValidation('enableFieldValidators', $field, enabled);
    });
}

$field is throwing the following error

"JavaScript runtime error: '$field' is undefined"

**Comment by laxman4434** [comment]
Hi nghuuphuoc,

I have tried the following method.

function enableFieldsValidators($form, className, enabled) {
    // Find all fields have the class name
    $form.find('.' + className).each(function(index, field) {
        $form.formValidation('enableFieldValidators', $field, enabled);
    });
}

But $field is throwing following error.

**Comment by nghuuphuoc** [comment]
I'm sorry, it's my fault. There's a typo in the code. It should be

```javascript
function enableFieldsValidators($form, className, enabled) {
    // Find all fields have the class name
    $form.find('.' + className).each(function(index, field) {
        $form.formValidation('enableFieldValidators', $(field).attr('name'), enabled);
    });
}
```

**Comment by laxman4434** [comment]
That worked perfectly. Thank you very much.
