### ISSUE TITLE
Re-Validating Awesome bootstrap Checkbox using FormValidatio.IO

### ISSUE THREAD

**Issue by rajukt** [formvalidation/support#438]
How to revalidate Awesome Bootstrap Checkbox using Formvalidation.IO ..Revalidate is not Working ...
How to fire revalidate event in Formvalidatio.IO for Awesome Bootstrap Checkbox.
Can Anyone Help me??

**Comment by nghuuphuoc** [comment]
Can you tell me which Bootstrap checkbox plugin you're using?
Is it https://github.com/flatlogic/awesome-bootstrap-checkbox?

**Comment by rajukt** [comment]
Yes @nghuuphuoc.The link you  have mentioned is Currect.

**Comment by nghuuphuoc** [comment]
I added new [Playing with Awesome Bootstrap Checkbox](http://formvalidation.io/examples/awesome-bootstrap-checkbox/) example.
Hopefully it helps you.
