### ISSUE TITLE
Is there a way to add test credit card to creditCard validator?

### ISSUE THREAD

**Issue by laxman4434** [formvalidation/support#441]
Hi nghuuphuoc,

I have a situation where I need to enter test credit card ( ex:- '4444111144441111') on payment section and go through the payment section for our initial test purposes. I was just wondering, is there any way to validate some test card number by modifying the creditCard validator.

Thanks
laxman4434

**Comment by nghuuphuoc** [comment]
I don't understand what you want. At the moment, clearly `4444111144441111` is a valid credit card number.

**Comment by laxman4434** [comment]
Sorry, my mistake. I should have explained it more clearly.

I want to enter some  card number like '3333222233332222'. This is clearly invalid credit card number, but I want it to be validated.

**Comment by nghuuphuoc** [comment]
> It's kind of weird, but my client wants it to be validated

And this newly created [Accept test credit card numbers](http://formvalidation.io/validators/creditCard/#accept-test-credit-card-numbers) example will make both you and your customers happy :dancers: 

Hopefully, you will see how powerful the `transformer` option is.

![accept-test-card-number](https://cloud.githubusercontent.com/assets/4226036/12061435/a0f1ee84-afb8-11e5-98f6-a21399acb442.gif)

**Comment by laxman4434** [comment]
That worked perfectly. Thank you very much nghuuphuoc. 
You are the best.
