### ISSUE TITLE
Two custom valid messages position

### ISSUE THREAD

**Issue by ottokupradze** [formvalidation/support#442]
I have form with wizard step block, and need to show valid messages to two different position...
Exp. 1) now my message is output block bottom, and I want to move up and change label color
http://i.imgur.com/G1GxhrX.png

Exp. 2) I want to show message at bottom, but change only label color http://i.imgur.com/yu1Wuiy.png

How I can do it? I must use this http://formvalidation.io/examples/showing-message-custom-area/

**Comment by nghuuphuoc** [comment]
* In the case you need to validate multiple radio buttons which are placed at special layout as in the image, you should take a look at [this comment](https://github.com/formvalidation/support/issues/351#issuecomment-159785395)

* The label color can be adjusted via pure CSS.
See the [Changing success and error colors](http://formvalidation.io/examples/changing-success-error-colors/) example.

**Comment by ottokupradze** [comment]
Ok, But if I want at same field to output icon and message one place, and another field another place... How can I do it? I must use
```
// data.field   --> The field name
// data.element --> The field element
```

**Comment by ottokupradze** [comment]
I try two moments:
**1.** Use tooltip: http://formvalidation.io/examples/using-tooltip-to-show-message
**2.** Move validate icon custom position http://formvalidation.io/examples/validating-checkbox-list-placed-multiple-columns

I have next problem when I change icon position:
**1.** Tooltip doesn't
**2.** icon can't change css style color

I see this http://formvalidation.io/examples/changing-success-error-colors/ but I want to use base plugin color style...
http://i.imgur.com/dHKJXRD.png

**HTML**
```
<div class="control-group">
	<div class="form-group">
		<div class="col-md-12">
			<span id="validation_icon"></span>
		</div>
	</div>
</div>
```

**JS**
```
$('#orderForm')
.on('init.field.fv', function(e, data) {
	if (data.field === 'field_name') {
		var $icon = data.element.data('fv.icon');
		$icon.appendTo('#validation_icon');
	}
})
.formValidation({
	framework: 'bootstrap',
	icon: {
		valid: 'fa fa-check',
		invalid: 'fa fa-remove',
		validating: 'fa fa-refresh fa-spin'
	},
	err: {
		container: 'tooltip'
	},
	...
});
```

**Comment by Pantela777** [comment]
My all problem is **col-md-4** how I can fixed?

**Comment by ottokupradze** [comment]
My all problem is **col-md-4** how I can fixed? Because if I remove this class, form work well.

**Comment by ottokupradze** [comment]
Please help anybody...

**Comment by ottokupradze** [comment]
???

**Comment by nghuuphuoc** [comment]
Currently, I haven't found the solution for it.
It works if you don't use `col-md-4` for each radio container. Need more time to look at this.

**Comment by ottokupradze** [comment]
This bug is on my side or it's plugin problem?

**Comment by nghuuphuoc** [comment]
It's not a bug. Just it's not easy to adjust to suit with your need now.

**Comment by ottokupradze** [comment]
I think I must use 
```row: {
    selector: null,
    valid: '',
    invalid: ''
}```
But, can't understand how...

**Comment by ottokupradze** [comment]
I think, need use ```row: { selector: null, valid: '', invalid: '' }``` But, can't understand how...

I try to fixed so... I created hidden input ```<input type="hidden" name="deal_type_key_pref" value="" />``` and event
```
$("input[name=deal_type_key]").change(function() {
			$("input[name=deal_type_key_pref]").val($(this).val());

			// Update formValidation field
			$('#orderForm').formValidation('revalidateField', 'deal_type_key_pref');
		});
```
Put hidden input near ```<span id="validation_icon_deal_type_key"></span>```
Understand is not good way, but I haven't any ideas :(
