### ISSUE TITLE
CVV number validation does not fire

### ISSUE THREAD

**Issue by heyanctil** [formvalidation/support#445]
I try to validate a CVV number with his credit card number but there is no validation raised.

I create a fiddle from the sample on the website to demonstrate the behavior: https://jsfiddle.net/heyanctil/9bx6j4qs/

    <form id="cvvForm" class="form-horizontal">
        <div class="form-group">
             <label class="col-xs-3 control-label">Credit card number</label>
             <div class="col-xs-6">
                 <input type="text" class="form-control" name="ccNumber" />
             </div>
         </div>
         <div class="form-group">
             <label class="col-xs-3 control-label">CVV</label>
             <div class="col-xs-3">
                 <input type="text" class="form-control" name="cvvNumber" />
             </div>
         </div>
     </form>

    $(document).ready(function() {
        $('#cvvForm').formValidation({
            framework: 'bootstrap',
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                ccNumber: {
                    validators: {
                        creditCard: {
                            message: 'The credit card number is not valid'
                        }
                    }
                },
                cvvNumber: {
                    validators: {
                        cvv: {
                            creditCardField: 'ccNumber',
                            message: 'The CVV number is not valid'
                        }
                    }
                }
            }
        });
    });

**Comment by nghuuphuoc** [comment]
The reason is that you use both `formValidation.min.js` (which consists of all validators) and `formValidation.popular.min.js` (which consists of popular validators, not including `cvv`) files.

The popular version supports the following validators which you can see at the beginning of the file:

```
/*!
 * ...
 * 
 * This is a custom build that does NOT consist of all validators. Only popular validators are included:
 * - between
 * - callback
 * - choice
 * - color
 * - creditCard
 * - date
 * - different
 * - digits
 * - emailAddress
 * - file
 * - greaterThan
 * - identical
 * - integer
 * - lessThan
 * - notEmpty
 * - numeric
 * - promise
 * - regexp
 * - remote
 * - stringLength
 * - uri
 *
 * Use formValidation(.min).js file if you want to have all validators.
```

So, you just use `formValidation.min.js` and it works as seen in this [jsfiddle](https://jsfiddle.net/nghuuphuoc/L9b1p81p/).

![demo](https://cloud.githubusercontent.com/assets/4226036/12162946/16b87a16-b53b-11e5-9010-40fc01d3edca.png)

**Comment by heyanctil** [comment]
You are totally right, my bad, thanks a lot!!!
