### ISSUE TITLE
creditCard validator seems to only work with input type text

### ISSUE THREAD

**Issue by soelvar** [formvalidation/support#45]
CreditCard validator seems to only work with input type text - it would be nice for it to work with input type number as well.

**Comment by nghuuphuoc** [comment]
@soelvar 
Can you tell me what's the problem when using ```type="number"```?
You can use this [fiddle](http://jsfiddle.net/nghuuphuoc/upum1eqn/2/).

**Comment by soelvar** [comment]
I am using it with the fontawsome cc icons. When number, data.result only
contains true

**Comment by nghuuphuoc** [comment]
@soelvar 
Thank for the feedback. You can use ```type="number"```.
I updated the [example](http://formvalidation.io/validators/creditCard/#showing-card-icon):

```javascript
$('#creditCardForm')
    .formValidation({
        ...
    })
    .on('success.validator.fv', function(e, data) { // ---> The updated line
        if (data.field === 'cc' && data.validator === 'creditCard') { // ---> The updated line
            ... 
        }
    });
```

**Comment by soelvar** [comment]
Thanks a lot:0)
