### ISSUE TITLE
Validate wrong username or password !!

### ISSUE THREAD

**Issue by naktieuthu** [formvalidation/support#450]
Just a simple question, HOW can I validate a login form, which displays an error message when user login with wrong username / password? The username and password are stored in database, of course... !

Thank you first !

**Comment by nghuuphuoc** [comment]
You should use the [remote](http://formvalidation.io/validators/remote/) validator to send an Ajax request to the server to check if the username/password is valid or not.
The [Basic example](http://formvalidation.io/validators/remote/#basic-example) is a starting point.
