### ISSUE TITLE
Bootstrap tabs validation

### ISSUE THREAD

**Issue by michaelt05** [formvalidation/support#454]
I see that for Bootstrap tabs validation, if fields in the in-active tab are invalid, you put a awesome icon on tab label.

Is there anyway to make the invalid field tab active and showing the required field?
![image](https://cloud.githubusercontent.com/assets/4210979/12374668/3a34acba-bc68-11e5-8c9d-77dda5f20e55.png)

Showing small icon like that does not help much.

**Comment by nghuuphuoc** [comment]
@michaelt05 
Yes, it's possible. I added new [Activating tab containing invalid field](http://formvalidation.io/examples/bootstrap-tab/#activating-tab-containing-invalid-field) example.

**Comment by michaelt05** [comment]
Your fixed only fix portion of this issue. Here is the problem

If you go to http://formvalidation.io/examples/bootstrap-tab/#activating-tab-containing-invalid-field

Without filling in any thing in First Tab
Then click on Validate button, you will see fields Full Name and Company invalid.
So go ahead and fill in Full Name and Company then click validate button again. 

You will see that the Second tab is not showing active to let us know that we need to fill in fields in second tab
can you look in to this?

Thanks
