### ISSUE TITLE
Validate 2 date fields ...!

### ISSUE THREAD

**Issue by naktieuthu** [formvalidation/support#455]
Any example of validation of comparison of 2 date fields?
For example: start date and end date, so we compare those 2 fields:
- if start date is later than end date (or end date is sooner than start date, what ever) -> display error msg

In brief, I want to validate after compare 2 dates....
I used bootstrap datepicker, and my date format is YYYY-MM-DD, if it does matter ....

**Comment by nghuuphuoc** [comment]
Please take a look at the [Validating start and end datetimes](http://formvalidation.io/examples/validating-start-end-datetimes/) example.

**Comment by naktieuthu** [comment]
Oh yeah, thank you, just found it ^^
