### ISSUE TITLE
FormValidation Validator remote validate Support dynamic data

### ISSUE THREAD

**Issue by JanaVanMaele** [formvalidation/support#457]
using following @version     v0.6.1-dev, built on 2015-02-09 11:20:35 PM

I encountered a problem using the remote dynamic data function.
In the doc it says:
data: function(validator, $field, value) {
    // validator is FormValidation instance
    // $field is the field element
    // value is the field value

    // Return an object
    return {
        key: value,
        otherKey: otherValue
    };
}

but when I log the $field and value argument, I get 'undefined'.
Can you please add in the original code following @ FormValidation.Validator.remote > validate > Support dynamic data

 if ('function' === typeof data) {
                data = data.call(this, validator, $field, value);
            }

instead of

 if ('function' === typeof data) {
                data = data.call(this, validator);
            }

thank you in advance

**Comment by nghuuphuoc** [comment]
Thanks for reporting the issue but it's already fixed. You should upgrade to the latest version (v0.7.0, in the case you made a purchase).

**Comment by JanaVanMaele** [comment]
Please, can you tell me how to upgrade ? 
We purchased the previous version  for commercial use.
Can we upgrade by a license key or some ?

**Comment by nghuuphuoc** [comment]
@JanaVanMaele 
You can use the current download link to get the latest (and future) releases.
If you can't find that link or the link doesn't work, please give me your email address you used to purchased. Then the new download link will be sent to you.

**Comment by JanaVanMaele** [comment]
So, when i fill in the same requested data from the previous purchase in the purchase box and I press 'buy', then nothing would be charged ?

**Comment by nghuuphuoc** [comment]
If it shows a Buy button, then the current download link doesn't work (For example, the number of downloads are limited to prevent users to share the link).
Please give me the email address and you will get the latest version.

**Comment by JanaVanMaele** [comment]
Can I send it somewhere in private ?

**Comment by nghuuphuoc** [comment]
You can send an email to phuoc@huuphuoc.me

On Wednesday, January 27, 2016, Jana Van Maele <notifications@github.com>
wrote:

> Can I send it somewhere in private ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formvalidation/support/issues/457#issuecomment-175569224>
> .
>


-- 
Phuoc Nguyen
Sent from my iPad
