### ISSUE TITLE
bug in class selector: updateMessage()

### ISSUE THREAD

**Issue by pclancy** [formvalidation/support#465]
Hi,

There is a bug in updateMessage where if the selector contains multiple class names (e.g. semantic ui) the selector fails as each class name isn't prefixed with "."

Original:
          
`  $fields.each(function() {
                $(this)
                    .data(ns + '.messages')
                    .find('.' + that.options.err.clazz + '[data-' + ns + '-validator="' + validator + '"][data-' + ns + '-for="' + field + '"]').html(message);
            });
`

Fixed:
`
            $fields.each(function() {
                $(this)
                    .data(ns + '.messages')
                    .find('.' + that.options.err.clazz.split(' ').join('.') + '[data-' + ns + '-validator="' + validator + '"][data-' + ns + '-for="' + field + '"]').html(message);
            });
`

**Comment by nghuuphuoc** [comment]
Thank a lot. This bug will be fixed in the next v0.7.1.
