### ISSUE TITLE
Spanish VAT validator doesn't work

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#47]
Reported by @kongueye
Some example for testing:

* R5000274J
* Q5000274J
* B78640570
* 50222711W

**Comment by nghuuphuoc** [comment]
@kongueye
Thank for giving me the examples. In the latest code, it's fixed.
R5000274J, Q5000274J, B78640570 are valida CIF number.

Anyway, 50222711W isn't valid DNI number. It should be 50222711A (the last character is A not W).
Is it your mistake?

**Comment by kongueye** [comment]
@nghuuphuoc 
50222711W is a valid DNI number, it's not a mistake.
Where can i get the latest code?
Thank you

**Comment by nghuuphuoc** [comment]
@kongueye 
I've made some researches on validating DNI number, such as 

* http://www.cespedes.org/dni2nif/
* https://gist.github.com/afgomez/5691823
* http://kiwwito.com/php-function-for-spanish-dni-nie-validation/

They're using the same calculation as mine to define the last character, and give the result that after 50222711 must be A character, not W.

**Comment by kongueye** [comment]
Hi @nghuuphuoc,
You're right, it's my mistake. Sorry
When can i get the latest code?

Thank you

**Comment by nghuuphuoc** [comment]
@kongueye 
Please wait for the new version (v0.6.2)!

**Comment by nghuuphuoc** [comment]
@kongueye 
v0.6.2 is released.
