### ISSUE TITLE
How to validate multiple textarea with CKEditor ?

### ISSUE THREAD

**Issue by jquellier** [formvalidation/support#474]
Hello, 

I can not configure multiple ckeditor textarea with formValidation script.
Just a single textarea is enabled with ckeditor but the second is not enabled with ckeditor.

```
<div class="form-group has-feedback">
	<label class="control-label" for="eventContent" placeholder="">Content * :</label>
	<textarea name="eventContent" class="form-control" rows="5" required="required"></textarea>
</div>


<div class="form-group has-feedback">
	<label class="control-label" for="eventModality" placeholder="Modality">Modality :</label>
	<textarea name="eventModality" class="form-control" rows="5"></textarea>
</div>
```

This code is possible just for the first textarea named "eventContent" :
```
.find('[name="eventContent"]')
			.ckeditor()
			.editor
				// To use the 'change' event, use CKEditor 4.2 or later
				.on('change', function() {
				// Revalidate the field
				$('#form_event').formValidation('revalidateField', 'eventContent');
			});
```

I don't know how to do for the second textarea named "eventModality" to activate ckeditor...

Do you have a code snippet to illustrate how to do for multiple textarea ckeditor with formValidation ?

Think you very much

**Comment by nghuuphuoc** [comment]
I added new example for you: http://formvalidation.io/examples/ckeditor/#multiple-editors

<img width="714" alt="ckeditor" src="https://cloud.githubusercontent.com/assets/4226036/12872115/57265d22-cdcb-11e5-85da-fde039380807.png">

**Comment by jquellier** [comment]
Hello,

Thank you very much for your answer.

I will try quickly.

Thanks
M. QUELLIER

Le dim. 7 févr. 2016 à 12:48, Phuoc Nguyen <notifications@github.com> a
écrit :

**Comment by jquellier** [comment]
Hi,

It works well :)
Thanks again for your help.

M. QUELLIER

Le dim. 7 févr. 2016 à 13:08, Jérôme QUELLIER <jquellier@gmail.com> a
écrit :
