### ISSUE TITLE
I have license. How do I download new version?

### ISSUE THREAD

**Issue by manovraresoft** [formvalidation/support#481]
I have license. How do I download new version?

Can't figure it out, want newest version

**Comment by nghuuphuoc** [comment]
You can use the current download link to get the latest (and future) releases.
If you can't find that link or the link doesn't work, please give me your email address you used to purchased. 
Then the new download link will be sent to you.

**Comment by manovraresoft** [comment]
mbadaracco@altairre.com

I have a Commercial-Developer-License. I purchased on 8/3/2015

**Comment by nghuuphuoc** [comment]
The new download link is just sent to your mailbox. Please check it (including the Junk folder).
