### ISSUE TITLE
Using select with a declarative

### ISSUE THREAD

**Issue by pierre-laplante** [formvalidation/support#483]
I have a select with the following code in formvalidation.io:

`<select class="form-control"  data-fv-notempty="true" data-fv-notempty-message="Ce champ ne doit pas être vide" >
	<option value="">Please select an option</option> 
        <option value="none">Aucun</option>
        <option value="all">Tous</option>
</select>`

The validation is not done. Do you know why ?

**Comment by nghuuphuoc** [comment]
You must specific the `name` attribute for the select element.

```html
<select class="form-control" 
    name="option"
    data-fv-notempty="true"
    data-fv-notempty-message="Ce champ ne doit pas être vide">

    <option value="">Please select an option</option>
    <option value="none">Aucun</option>
    <option value="all">Tous</option>
</select>
```

Here is the [jsfiddle](http://jsfiddle.net/nghuuphuoc/o2poLh96/1/):

<img width="461" alt="not-empty" src="https://cloud.githubusercontent.com/assets/4226036/13052800/6a7aabb2-d433-11e5-9efe-15645daba711.png">

**Comment by pierre-laplante** [comment]
Ah you are right sorry for this error.
Thanks.

Pierre Laplante
Co-Président
791 Saint-Charles
St-Lambert, (Québec), J4P 2A2

http://www.sednove.com
laplante@sednove.com
laplante.p@gmail.com
C 514-945-1779
B 450-671-9307 x221
F 450-671-5326
S pierre-laplante
