### ISSUE TITLE
Validating multiple email adresses separated by ;

### ISSUE THREAD

**Issue by DarkAllMan** [formvalidation/support#486]
I'm having trouble validating email adresses separated by ;
It seems it always returns false:

									fields: {
										to: {
											validators: {
												notEmpty: {
													message: 'Please give us a to address'
												},
												emailAddress: {
													message: 'The value is not a valid email address',
													multiple: true
												}
											}
										},

Am I doing it wrong?

**Comment by DarkAllMan** [comment]
Please, any help is much appreciated!

**Comment by nghuuphuoc** [comment]
I will take a look at it tonight

On Wednesday, March 2, 2016, DarkAllMan <notifications@github.com> wrote:

> Please, any help is much appreciated!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formvalidation/support/issues/486#issuecomment-191180293>
> .
>


-- 
Phuoc Nguyen
Sent from my iPad

**Comment by DarkAllMan** [comment]
And did you?

**Comment by nghuuphuoc** [comment]
Yes. I made a fiddle at http://jsfiddle.net/nghuuphuoc/n97ozkx3/1/
* A valid example (note that `a@b` is [valid](http://formvalidation.io/validators/emailAddress/#is-ab-valid-email-address) email address)

<img width="318" alt="valid" src="https://cloud.githubusercontent.com/assets/4226036/13500505/706214f6-e195-11e5-8054-cfa021742175.png">

* An invalid example (Please note that there's a space between two email addreses)

<img width="336" alt="invalid" src="https://cloud.githubusercontent.com/assets/4226036/13500533/93d523b0-e195-11e5-9d85-a0528d5430b5.png">

Can you please tell me which examples that don't behave as expected?

**Comment by DarkAllMan** [comment]
You guessed right... I used "a@b; a@b"
Problem solved.
