### ISSUE TITLE
exception during formvalidation.destroy()

### ISSUE THREAD

**Issue by myklemykle** [formvalidation/support#488]
Using v0.7.0, we sometimes get an exception when calling destroy() on the plugin.

It happens in formValidation.js on line 1796:

```
                    $field
                        // Remove all error messages
                        .data(ns + '.messages')
                            .find('.' + this.options.err.clazz.split(' ').join('.') + '[data-' + ns + '-validator][data-' + ns + '-for="' + field + '"]').remove().end()
                            .end()
                        .removeData(ns + '.messages')
                        // Remove feedback classes
                        .closest(row)
                            .removeClass(this.options.row.valid)
                            .removeClass(this.options.row.invalid)
                            .removeClass(this.options.row.feedback)
                            .end()
                        // Turn off events
                        .off('.' + ns)
                        .removeAttr('data-' + ns + '-field');
```

We come through here twice per invocation of destroy(). On the second pass, $field.data(ns+'.messages') returns undefined, so the subsequent .find line throws 

> TypeError: Cannot read property 'find' of undefined(…)

We just catch and discard this now, because we're destroying the plugin anyway.  But FYI .

**Comment by nghuuphuoc** [comment]
Thanks for the feedback, but I would like an example that I can reproduce the issue and make it as a test suite.
Without that, it's not easy for me to produce and fix the issue.

**Comment by myklemykle** [comment]
I will get you that as soon as I have some time, but I can't say when that'll be.  FYI we hit this again yesterday.  The issue is pretty simple, and I could do you a two-line pull request to fix it, more easily than writing you an entire test case.

The issue arises because we re-render form elements after running formValidation.  The re-rendering deletes all FV data from the field, including the fv.message object.  Once that's happened, we can't get formValidation to recover.

If we try to submit the form, fv throws an exception in updateStatus() on line 1423, calling $message.find() when $message is undefined.  

If we try to re-initialize the plugin, nothing happens because the plugin init code detects that the plugin is already installed, and exits without doing anything.  

And we can't delete the plugin before re-initializing, because, as noted earlier, destroy() makes the same incorrect assumption on line 1796 and throws an exception there.

The fix would be simple matter of adding `if (typeof $message !== "undefined")`, or your preferred idiom, around those two situations (and possibly others).  Or else just fixing the one in destroy(), so we can remove and re-add manually.

Or if there's some other way to fix the data on an individual form element, maybe we could use that.

**Comment by myklemykle** [comment]
Ok, I've attached an example HTML file that demonstrates the problem.  (Compressed, because github won't let me attach .html files.)

[fvdemo.html.zip](https://github.com/formvalidation/support/files/219705/fvdemo.html.zip)

**Comment by nghuuphuoc** [comment]
The latest version [v0.8.0](http://formvalidation.io/news/v0-8-0-released-supports-bootstrap-4-alpha-foundation-6/) fixes that.
As you suggested, the fix simply adds a check if `$message` is defined or not.
Please upgrade the plugin.

**Comment by myklemykle** [comment]
Thanks!
