### ISSUE TITLE
Two validations in one field

### ISSUE THREAD

**Issue by fabiomtl** [formvalidation/support#49]
I have a trick question, is possible to use two validations in one field?

That will be:
vat - BR - CNPJ (company id)
id - BR - CPF (person id)

The difference is the data length, in Brazil CNPJ has 14 digits and CPF has 11 digits.

If a person type 11 digits, will validate ID... 14 digits, VAT.

Thank you

**Comment by nghuuphuoc** [comment]
@fabiomtl 
This is interesting question! The quick answer is YES.
I will create an example for you.

**Comment by fabiomtl** [comment]
That is awesome!

Thank you very much!

**Comment by nghuuphuoc** [comment]
@fabiomtl 
Here it's: http://formvalidation.io/examples/switching-validators-same-field/

**Comment by fabiomtl** [comment]
I am using already.

Thank you!
