### ISSUE TITLE
email validation with white-spaces before/after

### ISSUE THREAD

**Issue by mcxnet** [formvalidation/support#499]
Hello,
I've a problem with email's validation.
Sometimes the users accidently enter some white-space in their email address, e.g. "test@test.com " and the form won't submit and has a error message: "Please enter a valid email address.".
Non-tech users couldn't understand that there's a white-space before/after and they might just close the site/page rather than try to work out about what they've done wrong.

Is it possible validate the email with white-space before/after?

Thanks!

**Comment by mcxnet** [comment]
If I use this instruction is correct?

`transformer: function($field, validatorName, validator) {
	var value = $field.val();
	return value.replace(/\s/g, '');
}`

**Comment by nghuuphuoc** [comment]
Yes! Using `transformer` is good direction in this case.
You should use the jQuery's [trim](https://api.jquery.com/jQuery.trim/) method:

```javascript
transformer: function($field, validatorName, validator) { 
    var value = $field.val(); 
    return $.trim(value); 
}
```

**Comment by mcxnet** [comment]
Ok. thanks!
