### ISSUE TITLE
Jquery too much recursion - asp.net form

### ISSUE THREAD

**Issue by joekuzma** [formvalidation/support#500]
I just purchased a copy of your formvalidation, and when I placed it on my pages where I wish to validate forms, it fails - giving me a "too much recursion" error.  I understand this is because my bootstrap form is not following proper formatting - at least that's what the docs say... but I can't see where the problem is

    <form id="form1" runat="server" class="signup">
    <div class="container theme-showcase" role="main">
    <div class="panel panel-default">            
            <div class="panel-heading">                
                <h3 class="panel-title">Sign Up</h3>
            </div>
            <div class="panel-body">
                <asp:Panel ID="panelSignup" runat="server">
                <div class="input-group">
                    <span class="input-group-addon" id="username-addon"><strong>User Name</strong></span>
                    <asp:TextBox ID="username" runat="server" CssClass="form-control" placeholder="Username" data-toggle="usernameTip" aria-describedby="username-addon" required autofocus></asp:TextBox>
                </div>
                <asp:Label ID="labelUsernameError" runat="server" ForeColor="Red" Text="Username in use, please select a different one." Visible="false"></asp:Label>
                <br />
                <div class="input-group">
                    <span class="input-group-addon" id="password-addon"><strong>Password</strong></span>
                    <asp:TextBox ID="password" runat="server" CssClass="form-control" placeholder="Password" aria-describedby="password-addon" required TextMode="Password"></asp:TextBox>
                    <span class="input-group-addon" id="password2-addon"><strong>Repeat Password</strong></span>
                    <asp:TextBox ID="confirm_password" runat="server" CssClass="form-control" placeholder="Repeat Password" aria-describedby="password2-addon" required TextMode="Password"></asp:TextBox>
                </div><hr />
                <div class="input-group">
                    <span class="input-group-addon" id="firstname-addon"><strong>First Name</strong></span>
                    <asp:TextBox ID="firstname" runat="server" CssClass="form-control" placeholder="First Name" aria-describedby="firstname-addon" required></asp:TextBox> 
                    <span class="input-group-addon" id="lastname-addon"><strong>Last Name</strong></span>
                    <asp:TextBox ID="lastname" runat="server" CssClass="form-control" placeholder="Last Name" aria-describedby="lastname-addon" required></asp:TextBox>
                </div><br />
                <div class="input-group">
                    <span class="input-group-addon" id="email-addon"><strong>Email</strong></span>
                    <asp:TextBox ID="email" type="email" runat="server" CssClass="form-control" placeholder="someone@somewhere.com" aria-describedby="email-addon"></asp:TextBox>
                </div>
                <asp:Label ID="labelEmailError" runat="server" ForeColor="Red" Text="Email is in use, please click on Login, and fill out the lost passsword or use a different email" Visible="false"></asp:Label>
                    <br />
                <div class="input-group">
                    <span class="input-group-addon" id="company-addon">Company</span>
                    <asp:TextBox ID="company" runat="server" CssClass="form-control" placeholder="Company name" aria-describedby="company-addon"></asp:TextBox>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="phone-addon"><strong>Phone</strong></span>
                    <asp:TextBox ID="phone" runat="server" CssClass="form-control" placeholder="Phone" aria-describedby="phone-addon" required></asp:TextBox>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="address1-addon">Address1</span>
                    <asp:TextBox ID="address1" runat="server" CssClass="form-control" placeholder="Address1" aria-describedby="address1-addon"></asp:TextBox>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="address2-addon">Address2</span>
                    <asp:TextBox ID="address2" runat="server" CssClass="form-control" placeholder="Address2" aria-describedby="address2-addon"></asp:TextBox>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="city-addon">City</span>
                    <asp:TextBox ID="city" runat="server" CssClass="form-control" placeholder="City" aria-describedby="city-addon"></asp:TextBox>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="state-addon">State</span>
                    <asp:TextBox ID="state" runat="server" CssClass="form-control" placeholder="State" aria-describedby="state-addon"></asp:TextBox>
                    <span class="input-group-addon" id="zip-addon">Zip Code</span>
                    <asp:TextBox ID="zip" runat="server" CssClass="form-control" placeholder="Zip Code" aria-describedby="zip-addon"></asp:TextBox>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="country-addon"><strong>Country</strong></span>
                    <select id="ddCountry" name="ddCountry" runat="server" class="form-control" aria-describedby="country-addon" required>
                    </select>
                </div><hr />
                <div class="input-group">
                    <span class="input-group-addon" id="website-addon"><strong>Website URL</strong></span>
                    <asp:TextBox ID="website" runat="server" CssClass="form-control" placeholder="http://www.website.com" aria-describedby="website-addon" required></asp:TextBox>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="icq-addon">ICQ</span>
                    <asp:TextBox ID="icq" runat="server" CssClass="form-control" placeholder="ICQ number" aria-describedby="icq-addon"></asp:TextBox>
                    <span class="input-group-addon" id="skype-addon">Skype</span>
                    <asp:TextBox ID="skype" runat="server" CssClass="form-control" placeholder="Skype Username" aria-describedby="skype-addon"></asp:TextBox>
                    <span class="input-group-addon" id="aim-addon">AIM</span>                    
                    <asp:TextBox ID="aim" runat="server" CssClass="form-control" placeholder="AIM Username" aria-describedby="aimd-addon"></asp:TextBox>
                </div><br />
                <div class="input-group">
                    <span class="input-group-addon" id="service-addon"><strong>What Service do you Want?</strong></span>
                    <select id="ddService" name="ddService" runat="server" class="form-control" aria-describedby="service-addon" required>
                        <option value="" disabled="disabled" selected>What Service do you want to use?</option>
                        <option value="3">Publisher - Sell Traffic</option>
                        <option value="4">Advertiser - Buy Traffic</option>
                    </select>
                    <label id="txtServiceError" runat="server" visible="false"><b><font color=red>You Must Select a Service</font></b></label>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="comments-addon">Comments</span>
                    <asp:TextBox ID="comments" runat="server" CssClass="form-control" placeholder="Comments" aria-describedby="comments-addon"></asp:TextBox>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" value="agree" runat="server" id="cbTerms" required /> I Agree To the <a href="#" target="_blank">Terms and Conditions</a>
                    </label>
                </div>
                <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Sign Up Now" CssClass="btn btn-lg btn-success btn-block"/>
                </asp:Panel>
                <asp:Panel ID="panelError" runat="server" Visible="false">
                    <asp:Label ID="lError" runat="server" BackColor="#CC3300"></asp:Label>
                </asp:Panel>
                <asp:Panel ID="panelAdded" runat="server" Visible="false">
                    <h3>Publisher Status</h3>
                    <asp:Label ID="results" runat="server"></asp:Label>
                    Please check your e-mail to activate your new account.
                </asp:Panel>
            </div>
    </div>
    </div>
    </form>
    <script src="scripts/jquery-2.1.4.min.js"></script>
    <script src="scripts/bootstrap.min.js"></script>
    <script src="scripts/docs.min.js"></script>
    <script src="scripts/ie10-viewport-bug-workaround.js"></script>
    <script src="javascripts/vendor/formvalidation/formValidation.min.js"></script>
    <script src="javascripts/vendor/formvalidation/framework/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#form1').formValidation({
                framework: 'bootstrap',
                icon: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                }
            });
        });
    </script>

**Comment by joekuzma** [comment]
I've attempted to try to pin-point what in my form was causing the error, and when I resorted to a simple one field form with a button, I still get this error.

<head>
<meta charset="utf-8">
<meta content="IE=edge" http-equiv="X-UA-Compatible">
<meta content="width=device-width, initial-scale=1" name="viewport">
<title> AdWorldMedia.com </title>
<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1" name="viewport">
<meta content="IE=edge" http-equiv="X-UA-Compatible">
<link href="/content/css/bootstrap.css" rel="stylesheet">
<link href="/content/css/bootstrap-theme.css" rel="stylesheet">
<link href="/css/font-awesome.min.css" rel="stylesheet">
<script async="" src="//www.google-analytics.com/analytics.js">
<script src="/scripts/jquery-2.1.4.min.js">
<script src="/scripts/bootstrap.js">
<script src="/scripts/ie10-viewport-bug-workaround.js">
<script src="/javascripts/session.js">
<link href="/apple-icon-57x57.png" sizes="57x57" rel="apple-touch-icon">
<link href="/apple-icon-60x60.png" sizes="60x60" rel="apple-touch-icon">
<link href="/apple-icon-72x72.png" sizes="72x72" rel="apple-touch-icon">
<link href="/apple-icon-76x76.png" sizes="76x76" rel="apple-touch-icon">
<link href="/apple-icon-114x114.png" sizes="114x114" rel="apple-touch-icon">
<link href="/apple-icon-120x120.png" sizes="120x120" rel="apple-touch-icon">
<link href="/apple-icon-144x144.png" sizes="144x144" rel="apple-touch-icon">
<link href="/apple-icon-152x152.png" sizes="152x152" rel="apple-touch-icon">
<link href="/apple-icon-180x180.png" sizes="180x180" rel="apple-touch-icon">
<link href="/android-icon-192x192.png" sizes="192x192" type="image/png" rel="icon">
<link href="/favicon-32x32.png" sizes="32x32" type="image/png" rel="icon">
<link href="/favicon-96x96.png" sizes="96x96" type="image/png" rel="icon">
<link href="/favicon-16x16.png" sizes="16x16" type="image/png" rel="icon">
<link href="/manifest.json" rel="manifest">
<meta content="#ffffff" name="msapplication-TileColor">
<meta content="/ms-icon-144x144.png" name="msapplication-TileImage">
<meta content="#ffffff" name="theme-color">
<link href="../css/formValidation.min.css" rel="stylesheet">
<script src="/javascripts/vendor/formvalidation/formValidation.min.js">
<script src="/javascripts/vendor/formvalidation/framework/bootstrap.min.js">
<body role="document">
    <div class="container">
       <asp:TextBox ID="name" runat="server" CssClass="form-control"></asp:TextBox>
<asp:Button ID="Button1" runat="server" Text="Sign Up Now" CssClass="btn btn-lg btn-success btn-block"/>
    </div>
    <script>
        $(document).ready(function () {          
            $('#form1').formValidation({
                framework: 'bootstrap',
                icon: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                },
                fields: {
                    <%=name.UniqueID%>: {
                        validators: {
                            notEmpty: {
                                message: 'The name is required'
                            },
                            stringLength: {
                                min: 6,
                                max: 30,
                                message: 'The name must be more than 6 and less than 30 characters long'
                            },
                            regexp: {
                                regexp: /^[a-zA-Z0-9_]+$/,
                                message: 'The name can only consist of alphabetical, number and underscore'
                            }
                        }
                    }
                }
            });
          });
    </script>
</body>

**Comment by vincejairam** [comment]
I'm getting the same issue, and I just bought this today. Were you able to resolve this?

**Comment by nghuuphuoc** [comment]
@joekuzma The issue is caused by the fact that your form doesn't follow Bootstrap form markup:
http://formvalidation.io/getting-started/#writing-form

In the standard form, each field has to be placed inside a `.form-group` element.
If you want the form to have another markup, please use the [row](http://formvalidation.io/settings/#form-row-selector) option.
