### ISSUE TITLE
CVV not working for test credit card numbers

### ISSUE THREAD

**Issue by laxman4434** [formvalidation/support#501]
Hi nghuuphuoc,

I tried to validate a test credit card '333322223333222' using the following url
[http://formvalidation.io/validators/creditCard/#accept-test-credit-card-numbers]

Everything worked perfectly with credit card validation. But when i am trying to enter CVV for the above test test card, CVV validator is not getting validated.

Could you please help me out.

**Comment by nghuuphuoc** [comment]
Do you use the popular version (`formValidation.popular.min.js`) or normal one (`formValidation.min.js`)?
Because the popular file does NOT consist of CVV validator.

**Comment by laxman4434** [comment]
I use formValidation.min.js

**Comment by laxman4434** [comment]
Hi nghuuphuoc,

 I am just wondering whether you have found any solution for the above problem.

**Comment by nghuuphuoc** [comment]
@laxman4434 
This is actually a bug and will be fixed in the next v0.7.2 (coming in this month)! I will let you know when it's released.

**Comment by nghuuphuoc** [comment]
It's now fixed in [v0.8.0](http://formvalidation.io/news/v0-8-0-released-supports-bootstrap-4-alpha-foundation-6/).
Please upgrade the plugin.
