### ISSUE TITLE
when pressing buton it becomes disabled and data was not sent (BootstrapValidator)

### ISSUE THREAD

**Issue by Renray** [formvalidation/support#505]
here is my code below:
<div class="col-md-6">
		            <div class="col-md-12" id="form">
		                <div class="panel panel-default ">
		                    <div class="panel-heading"><h5><b>Change Password&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-lock"></span></b></h5></div>
		                    <div class="panel-body">
		                        <form id="registration-form" method="POST" class="form-horizontal" action="user_profile.php">
		                            <div class="form-group">
		                                <label class="col-md-2 control-label" for="password">Password</label>
		                                <div class="col-md-4">
		                                    <input type="password" class="form-control"  id="password" name="password" placeholder="Enter new password" required/>
		                                </div>
		                            </div>
		                            <div class="form-group">
		                                <label class="col-md-2 control-label" for="confirmpassword">Confirm Password</label>
		                                <div class="col-md-4">
		                                    <input type="password" class="form-control" id="confirmpassword" name="confirmpassword" placeholder="Confirm password" required/>
		                                </div>
		                            </div>
		                            <div class="form-group">                            
		                                <div class="col-md-6 col-md-offset-2">
		                                    <button type="submit" name="submit" class="btn btn-success">Submit</button>
		                                </div>
		                            </div>
		                        </form>
		                    </div>
		                </div>
		            </div>

		        </div>	
		    </div>

		        <?php
		        	require ('db.php');
     	

		        	    if(isset($_POST['submit']))
			            {   

			                $pass_save = $_POST['password'];
			                $con_pass_save = $_POST['confirmpassword'];
							
							$LRN=$_SESSION['LRN'];

				        	mysql_query("UPDATE student_list SET password ='$pass_save'  WHERE LRN = '$LRN' ")
		                            or die(mysql_error()); 
		                	
		                	echo "<center>";
                                echo "<div class='container'>";
                                    echo "<div class='alert alert-success' role='alert' style='margin-top: -100px; width: 40%;  height: 80px;'>";
                                    	echo '<h1>Success!</h1>';
                                    echo "</div>";
                                echo "</div>";
                            echo "</center>";
		                
		                	echo"<script>
		                			window.location.href='user_profile.php';
		                		</script>";  
		                	}

		                	mysql_close($conn);
		        ?>
			
		</div>

<script type="text/javascript">
		$(function() {
			var validator = $("#registration-form").bootstrapValidator({
				feedbackIcons : {
					valid : "glyphicon glyphicon-ok",
					invalid : "glyphicon glyphicon-remove",
					validating : "glyphicon glyphicon-refresh"
				},
				fields : {
					
					password : {
						validators : {
							notEmpty : {
								message : "Password is required"
							},
							stringLength : {
								min : 8,
								message : "Password must be 8 characters long"
							},
							
						}
					},
					confirmpassword : {
						validators : {
							notEmpty : {
								message : "Confirm password is required"
							},
							identical : {
								field : "password",
								message : "Password and confirmation must match"
							}
						}
					},
					
				}
			});

			// Intercept the success event
			validator.on("success.form.bv", function (e) {
				e.preventDefault();

				
				$.post(url, $("#registration-form").serialize(), function(data) {
					if(data == 1){
						$("#registration-form").addClass("hidden");
						$("#confirmation").removeClass("hidden");
					}
					else {
						alert("failed");
						$("#confirmation_failed").removeClass("hidden");
					}
				});				

			});
			});
			
	</script>

**Comment by nghuuphuoc** [comment]
The issue is caused by using the `name="submit"` attribute for the Submit button.
See http://formvalidation.io/examples/cant-submit-form-after-validation/#the-submit-buttons-name-is-not-valid
