### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#51]
_From @san360 on March 5, 2015 16:41_

Hello,

I am getting this error " Uncaught TypeError: Cannot read property 'find' of undefined"

I have a multiple forms in a web page and i am using twitter typeahed for auto complete. The validation fails for the auto complete controls.

Please advice.

![image](https://cloud.githubusercontent.com/assets/6613457/6509302/c26c4506-c35e-11e4-931e-98ca98a27153.png)

_Copied from original issue: formvalidation/formvalidation#1449_

**Comment by nghuuphuoc** [comment]
@san360
Please give me the HTML form or JS code.
There's basic [typeahead](http://formvalidation.io/examples/typeahead/) example.

**Comment by san360** [comment]
Thanks for your reply

Please see below details

HTML

<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body style="margin:6px;">
<div id="i360-new-server-form" class="input-group i360-forms">
                <div style="padding: 40px 15px; text-align: center;">
                    <h1>Server Provisioning</h1>
                </div>
                <form role="form" id="serverProvisioningRequestForm" method="post">
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-summary">Summary</label>
                        <input type="text" class="form-control i360-form-element" name="serverProvisioningSummary" id="i360-server-provisioning-form-summary">
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-description">Description</label>
                        <textarea class="form-control i360-form-element" id="i360-server-provisioning-form-description" name="serverProvisioningDescription" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-project-name" class="i360-typeahead-label">Project Name</label>
                        <input type="text" class="form-control i360-form-element i360-project-name" name="serverProvisioningProjectName" id="i360-server-provisioning-form-project-name" placeholder="Type in to search for a project">
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-application-name" class="i360-typeahead-label">Application Name</label>
                        <input type="text" class="form-control i360-form-element i360-application-name" id="i360-server-provisioning-form-application-name" name="serverProvisioningApplicationName" placeholder="Type in to search for an application">
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-operating-system">Operating System</label>
                        <select class="form-control" id="i360-server-provisioning-form-operating-system" name="serverProvisioningOperatingSystem">
                            <option value="" selected disabled>None</option>                            
                            <option>RedHat</option>                            
                            <option>Windows</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-adminaccess">Admin access</label>
                        <input type="text" class="form-control i360-form-element person-suggest tagme" id="i360-server-provisioning-form-adminaccess" name="adminAccess" placeholder="Type in to search for a person, For groups provide in description" />
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-useraccess">User access</label>
                        <input type="text" class="form-control i360-form-element person-suggest tagme" id="i360-server-provisioning-form-useraccess" name="userAccess" placeholder="Type in to search for a person, For groups provide in description" />
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-sudorights">Sudo Rights</label>
                        <select class="form-control" id="i360-server-provisioning-form-sudorights" name="sudoRights">
                            <option value="" selected>None</option>
                            <option>Application</option>
                            <option>Full</option>
                            <option>Service</option>
                            <option>View</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-ram">RAM</label>
                        <select class="form-control" id="i360-server-provisioning-form-ram" name="ram">
                            <option value="" selected disabled>None</option>
                            <option valueid="12004">2 GB</option>
                            <option valueid="12005">4 GB</option>
                            <option valueid="12006">8 GB</option>
                            <option valueid="12007">16 GB</option>
                            <option valueid="12008">32 GB</option>
                            <option valueid="12009">64 GB</option>
                            <option valueid="12010">128 GB</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-processors">Processor</label>
                        <select class="form-control" id="i360-server-provisioning-form-processors" name="processor">
                            <option value="" selected disabled>None</option>
                            <option valueid="12011">1</option>
                            <option valueid="12012">2</option>
                            <option valueid="12013">3</option>
                            <option valueid="12014">4</option>
                            <option valueid="12015">5</option>
                            <option valueid="12016">6</option>
                            <option valueid="12017">7</option>
                            <option valueid="12018">8</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-data-capacity">Required Data Capacity</label>
                        <select class="form-control" id="i360-server-provisioning-form-data-capacity" name="dataCapacity">
                            <option value="" selected disabled>None</option>
                            <option valueid="12019">10 GB</option>
                            <option valueid="12020">20 GB</option>
                            <option valueid="12021">30 GB</option>
                            <option valueid="12022">40 GB</option>
                            <option valueid="12023">50 GB</option>
                            <option valueid="12024">Other - Specify in Description</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-classification">Classification</label>
                        <select class="form-control" id="i360-server-provisioning-form-classification" name="serverProvisioningClassification">
                            <option value="" selected disabled>None</option>
                            <option valueid="12025">Dev</option>
                            <option valueid="12026">Test</option>
                            <option valueid="12027">Production</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-puppet-class">Server Role</label>
                        <select class="form-control" id="i360-server-provisioning-form-puppet-class" name="serverRole">
                            <option value="" selected disabled>None</option>
                            <option>a</option>
                            <option>Dat</option>
                            <option>De</option>
                            <option>Da</option>
                            <option>Dev</option>
                            <option>Gene</option>
                            <option>Ha</option>                            
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-server-contact">Server Contact</label>
                        <input type="text" class="form-control i360-form-element person-suggest" id="i360-server-provisioning-form-server-contact" name="serverContact" placeholder="Type in to search for a person">
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-server-deputy">Server Contact Deputy</label>
                        <input type="text" class="form-control i360-form-element person-suggest" id="i360-server-provisioning-form-server-deputy" name="serverContactDeputy" placeholder="Type in to search for a person">
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-site-location" style="margin-top:10px; margin-bottom:-15px;">Infrastructure Site Location</label>
                        <div id="i360-server-provisioning-form-site-location" class="i360-radio-group">
                            <div class="radio">
                                <label>
                                    <input type="radio" name="i360-server-provisioning-form-site-location" id="i360-server-provisioning-form-site-location-chbs" value="Basel" checked>
                                    AAA
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="i360-server-provisioning-form-site-location" id="i360-server-provisioning-form-site-location-usca" value="Cambridge">
                                    CCCC
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="i360-server-provisioning-form-site-location" id="i360-server-provisioning-form-site-location-usem" value="Emeryville">
                                    DDD
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="i360-server-provisioning-form-site-location" id="i360-server-provisioning-form-site-location-cnzj" value="Shanghai">
                                    SSSS
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="i360-server-provisioning-form-site-location" id="i360-server-provisioning-form-site-location-cnzj" value="Singapore">
                                    VVVVV
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="i360-server-provisioning-form-appliance" style="margin-top:10px; margin-bottom:-15px;">Is An Appliance</label>
                        <div id="i360-server-provisioning-form-appliance" class="i360-radio-group">
                            <div class="radio">
                                <label>
                                    <input type="radio" name="i360-server-provisioning-form-appliance" id="i360-server-provisioning-form-appliance-no" value="No" checked>
                                    No
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="i360-server-provisioning-form-appliance" id="i360-server-provisioning-form-appliance-yes" value="Yes">
                                    Yes
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" class="i360-form-element" id="i360-server-provisioning-form-stateless"> Stateless
                            </label>
                            <div>
                                <span style="font-style:italic">A stateless server cannot be backed up and will not be restored.</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-9 col-xs-offset-3">
                            <div class="alert alert-danger">
                                <h2>There were problems with following fields:</h2>
                                <ul id="serverProvisioningValidationErrors" class="errors"></ul>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-10">
                            <div style="float:right; margin-top:10px;">
                                <a href="#" class="btn btn-default">Cancel</a>
                                <button type="button" style="display:none" class="dummybutton">
                                    Dummy Cancel
                                </button>
                                <button type="submit" class="btn btn-primary i360-form-submit-button" id="i360-server-provisioning-form-submit">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
</body>
</html>

Javascript Form Validation:

 $('#serverProvisioningRequestForm')
        .on('init.form.fv', function (e, data) {
            // $(e.target)  --> The form instance
            // data.fv      --> The FormValidation instance
            // data.options --> The form options
            $("#serverProvisioningValidationErrors").closest("div.alert").hide();
            // Do something ...
        })
    .formValidation({
        framework: 'bootstrap',
        excluded: [':disabled', ':hidden', ':not(:visible)'],
        button: {
            selector: '#i360-server-form-submit',
            disabled: 'disabled'
        },
        fields: {
            serverProvisioningSummary: {
                validators: {
                    notEmpty: {
                        message: 'The summary is required and cannot be empty'
                    },
                    stringLength: {
                        max: 255,
                        message: 'The summary must be less than 255 characters long'
                    }
                }
            },
            serverProvisioningDescription: {
                validators: {
                    notEmpty: {
                        message: 'The description is required and cannot be empty'
                    }
                }
            },
            serverProvisioningProjectName: {
                validators: {
                    notEmpty: {
                        message: 'The project name is required and cannot be empty'
                    }
                }
            },
            serverProvisioningApplicationName: {
                validators: {
                    notEmpty: {
                        message: 'The application name is required and cannot be empty'
                    }
                }
            },
            sudoRights: {
                validators: {
                    notEmpty: {
                        message: 'The sudo rights is required and cannot be empty'
                    }
                }
            },
            serverProvisioningOperatingSystem: {
                validators: {
                    notEmpty: {
                        message: 'The operating system is required and cannot be empty'
                    }
                }
            },
            ram: {
                validators: {
                    notEmpty: {
                        message: 'The ram is required and cannot be empty'
                    }
                }
            },
            serverProvisioningClassification: {
                validators: {
                    notEmpty: {
                        message: 'The classification is required and cannot be empty'
                    }
                }
            },
            dataCapacity: {
                validators: {
                    notEmpty: {
                        message: 'The data capacity is required and cannot be empty'
                    }
                }
            },
            processor: {
                validators: {
                    notEmpty: {
                        message: 'The processor is required and cannot be empty'
                    }
                }
            },
            serverContact: {
                validators: {
                    notEmpty: {
                        message: 'The server contact is required and cannot be empty'
                    }
                }
            },
            serverContactDeputy: {
                validators: {
                    notEmpty: {
                        message: 'The server contact deputy is required and cannot be empty'
                    }
                }
            }
        }
    })
.on('err.field.fv', function (e, data) {
    // data.fv      --> The FormValidation instance
    // data.field   --> The field name
    // data.element --> The field element
    // Get the messages of field
    var messages = data.fv.getMessages(data.element);
    // Remove the field messages if they're already available
    $('#serverProvisioningValidationErrors').find('li[data-field="' + data.field + '"]').remove();

    // Loop over the messages
    for (var i in messages) {
        // Create new 'li' element to show the message
        $('<li/>')
            .attr('data-field', data.field)
            .wrapInner(
                $('<a/>')
                    .attr('href', 'javascript: void(0);')
                    .html(messages[i])
                    .on('click', function (e) {
                        // Focus on the invalid field
                        data.element.focus();
                    })
            )
            .appendTo('#serverProvisioningValidationErrors');
    }
    $("#serverProvisioningValidationErrors").closest("div.alert").show();
    // Hide the default message
    // $field.data('fv.messages') returns the default element containing the messages
    data.element
        .data('fv.messages')
        .find('.help-block[data-fv-for="' + data.field + '"]')
        .hide();
    data.fv.disableSubmitButtons(false);
})
    .on('success.field.fv', function (e, data) {
        // Remove the field messages
        $('#serverProvisioningValidationErrors').find('li[data-field="' + data.field + '"]').remove();
    })
     .on('success.form.fv', function (e) {
         //e.fv.disableSubmitButtons(true);
         //validateField('databaseOwner')
         $("#serverProvisioningValidationErrors").closest("div.alert").hide();
         $('#serverProvisioningValidationErrors').html('');
         e.preventDefault();
     });

jQuery to make field auto complete using typeahead

//Manages store autocomplete
function mangestoreConnection() {
    $.ajax({
        url: "util/service/applications",
        success: function (data) {
            var storeLookUp = new Bloodhound({
                datumTokenizer: function (d) {
                    return Bloodhound.tokenizers.whitespace(d.value);
                },
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                local: $.map(data, function (storeEntry) { return { value: storeEntry.Name, applicationOwner: storeEntry.ASM }; })
            });
            storeLookUp.initialize();
            $('.i360-application-name').typeahead({
                hint: true, highlight: true, minLength: 1
            },
            {
                name: 'store', displayKey: 'value', source: storeLookUp.ttAdapter()
            }).blur(function () {//Set flag if selected value is from the source
                var selectedValue = $(this).val();
                var result = $.grep(storeLookUp.local, function (e) {
                    return e.value == selectedValue
                });
                if (result.length == 1) {
                    $(this).attr("isvalid", '1');
                }
                else {
                    $(this).attr("isvalid", '0');
                }
                //Handle Placeholder for IE
                if (!Modernizr.input.placeholder) {
                    if ($(this).val() == '' || $(this).val() == $(this).attr('placeholder')) {
                        $(this).val($(this).attr('placeholder'));
                        $(this).addClass('placeholder');
                    }
                }
            }).on("typeahead:selected", function (object, data) {
                if ($(this).attr('id') == 'i360-database-form-application-name') {
                    setControlValue('#i360-database-form-application-owner', data.applicationOwner);
                    $('#i360-database-form-application-owner').attr('userid', data.applicationOwner);
                }
            });
        },
        xhrFields: {
            withCredentials: true
        }
    });
}
//Manages dataStore connection
function managedataStoreConnection() {
    $.ajax({
        url: "util/apis/active_activities.json",
        success: function (data) {
            var dataStoreLookUp = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                local: $.map(data, function (dataStoreEntry) { return { value: dataStoreEntry[0] }; })
            });
            dataStoreLookUp.initialize();
            $('.i360-project-name').typeahead({
                hint: true, highlight: true, minLength: 1
            },
            {
                name: 'dataStoreActivities', displayKey: 'value', source: dataStoreLookUp.ttAdapter()
            }).blur(function () { //Set flag if selected value is from the source 
                var selectedValue = $(this).val(),
                 result = $.grep(dataStoreLookUp.local, function (e) {
                     return e.value == selectedValue
                 });
                if (result.length == 1) {
                    $(this).attr("isvalid", '1');
                }
                else {
                    $(this).attr("isvalid", '0');
                }
                //Handle Placeholder for IE
                if (!Modernizr.input.placeholder) {
                    if ($(this).val() == '' || $(this).val() == $(this).attr('placeholder')) {
                        $(this).val($(this).attr('placeholder'));
                        $(this).addClass('placeholder');
                    }
                }
            });
        },
        xhrFields: {
            withCredentials: true
        }
    });
}

**Comment by san360** [comment]
Hi,

Did you get a chance to look at this issue?

I am enhancing a production application and these changes need to go asap.

Thanks
Sanjay

**Comment by nghuuphuoc** [comment]
The problem is caused by calling ```$('.i360-project-name').typeahead()``` two times.
In the past, one of FormValidation users faced to the same issue. The reason is that he uses typeahead() for the same field more than 1 time.
We solved it by refactoring the code to ensure that the typeahead is initiallized only 1 time.

For your case, I don't know how ```mangestoreConnection()``` and ```managedataStoreConnection()``` are called, but you can try to destroy the typehead before initializing:

```javascript
$('.i360-project-name')
.typeahead('destroy') // Destroy the current instance if it's available
.typeahead({
    hint: true, highlight: true, minLength: 1
}, {
    name: 'dataStoreActivities', displayKey: 'value', source: dataStoreLookUp.ttAdapter()
});
```

**Comment by iamchriswick** [comment]
I'm getting `Uncaught TypeError: Cannot read property 'find' of undefined`...

Any suggestions?

**Comment by manioo** [comment]
proly you have been adding fields to validator dynamically , which you forgot to remove before closing the form/modal..
