### ISSUE TITLE
Submit form with Ajax

### ISSUE THREAD

**Issue by jkrassman** [formvalidation/support#511]
Hi, nice library!

When I am sending of a form with Ajax, all fields are getting green indicating success.

I dont want the fields to be green, I just want them to stay as they where from the begining.

How should I manage to solve this?

Best regards, Joakim

**Comment by jkrassman** [comment]
Got it,

 $("#frmMain").data('formValidation').resetForm();

**Comment by nghuuphuoc** [comment]
I'm glad that you found the solution quickly :+1:
