### ISSUE TITLE
Manual validation

### ISSUE THREAD

**Issue by RashidNawaz** [formvalidation/support#513]
hi can you explain how to validate a form manually on button click bacuase i have a dynamic form in modal generated form server response i want to validate but find no clue how to do it can you help to do that

**Comment by nghuuphuoc** [comment]
You can use the [validate](http://formvalidation.io/api/#validate) method:

```javascript
$('#yourForm').formValidation('validate');
```

**Comment by RashidNawaz** [comment]
where i should place that code in that below code

$(document).ready(function() {
    $('#groupForm').formValidation({
        framework: 'bootstrap',
        err: {
            container: 'tooltip'
        },
        row: {
            selector: 'td'
        },
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            'oqty[]': {
                validators: {
                    excluded: false
                }
            },
            'rqty[]': {
                validators: {
                    notEmpty: {
                        message: 'Qty is required'
                    },
                    stringLength: {
                        min: 1,
                        message: ' Qty must be less than or equal to order qty'
                    },
                    regexp: {
                        regexp: /^[0-9]+$/,
                        message: 'Qty can only consist of numbers'
                        }
                    
                }
            },
            'price[]': {
                validators: {
                    notEmpty: {
                        message: 'The price is required'
                    }
                },
                stringLength: {
                    min: 1,
                    max: 10,
                    message: ' Unit Price must be more than 1 and less than 10 numbers long'
                },
                regexp: {
                    regexp: /^[0-9\.]+$/,
                    message: 'Unit Price can only consist of numbers nd .'
                }
                    
            },
            'tprice[]': {
                validators: {
                    notEmpty: {
                        message: 'Total Price is required'
                    },
                stringLength: {
                    min: 1,
                    max: 10,
                    message: ' Total Price must be more than 1 and less than 10 numbers long'
                },
                regexp: {
                    regexp: /^[0-9\.]+$/,
                    message: 'Total Price can only consist of numbers nd .'
                }
                }
            },
            'kgpiece[]': {
                validators: {
                    notEmpty: {
                        message: 'quanity in Unit/kg is required'
                    },
                regexp: {
                    regexp: /^[0-9\.]+$/,
                    message: 'Sale Price can only consist of numbers nd .'
                }
                }
            }
        }
    })
});

**Comment by RashidNawaz** [comment]
got it my bad placing it in a wrong file

**Comment by nghuuphuoc** [comment]
I'm glad that you found the solution!
