### ISSUE TITLE
Using data attributes for defining messages in multiple languages

### ISSUE THREAD

**Issue by tbrcrl** [formvalidation/support#523]
Hello, 
I would like to define messages in different languages using the i18n add-on and specifying messages via HTML attributes.
So my question is if it is possible to use attributes like
`data-fv-notempty-message--en_US="The message in English" data-fv-notempty-message--fr_FR="The message in French"`
(I used two dashes '--' to specify the level of nesting)
instead of
`message: {
                        en_US: 'The message in English',
                        fr_FR: 'The message in French'`
I tried, but it seems not working (I am using jQuery 2.2.1 that should support  nested options using HTML attributes).

Thanks

**Comment by nghuuphuoc** [comment]
It's not possible at the moment.
