### ISSUE TITLE
E-mail id is not validating currectly

### ISSUE THREAD

**Issue by rahul-mutyalkar** [formvalidation/support#526]

**Comment by nghuuphuoc** [comment]
Please tell me an example of email address.

**Comment by rahul-mutyalkar** [comment]
"rahulmutyalkar@g" this is accepted by formvalidatio.io script for email
validation....please fix this issue

**Comment by nghuuphuoc** [comment]
Please take a look at the [Is a@b valid email address](http://formvalidation.io/validators/emailAddress/#is-ab-valid-email-address) section.

**Comment by mohdshahzar1996** [comment]
Hi everyone edit formValidation.min.js
Fint var emailRegExp and replace its value with 

/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/

**Comment by nghuuphuoc** [comment]
Updating the final build file directly isn't recommend because you will lose these changes when upgrading to new version.
In this case, you can use the `regexp` validator.
