### ISSUE TITLE
Date is valid though validation is fired

### ISSUE THREAD

**Issue by juhi7029** [formvalidation/support#531]
![reportbug](https://cloud.githubusercontent.com/assets/7126637/13947401/54ae5c74-f040-11e5-9922-1fd199f9ca3f.PNG)

As per the given example i tried to validate datepicker,
Entered valid date though validation is fired.

In last example in given link http://formvalidation.io/examples/bootstrap-datepicker/

**Comment by nghuuphuoc** [comment]
You might need to clear the browser cache:

<img width="882" alt="date-picker" src="https://cloud.githubusercontent.com/assets/4226036/14584522/0e83c8cc-0474-11e6-831b-683ab98ea250.png">
