### ISSUE TITLE
External Submit Button

### ISSUE THREAD

**Issue by crazyhor77** [formvalidation/support#535]
Hi,

I have created a form and want to submit with a button that is not contained within the form element. Quick example below:

```
<form id="form1">
  <input name="test" type="text" required />
</form>

<button type="submit" form="form1" value="Submit">Submit</button>
```

Pressing the button will validate the form, but will not continue to submit the form. Including the same button inside the form element will work perfectly fine. I'm not heavily experienced in this, but I think this might be a bug in the library not supporting external buttons with the html5 form attribute.

Appreciate any help.

**Comment by nghuuphuoc** [comment]
Yes, as you mentioned. External submit button isn't supported at the moment.
The issue is marked as _feature request_ to be implemented in the future.

**Comment by crazyhor77** [comment]
ok, good to know its not just me then :)
