### ISSUE TITLE
Error cause to put in red all field in a row

### ISSUE THREAD

**Issue by marccollin** [formvalidation/support#539]
I use bootstrap.

On the same line, i have 4 fields.
If one have a error all other is show in red

```
<form id="lodgerRoomPaymentForm" class="form-horizontal" role="form" data-fv-framework="bootstrap" data-fv-icon-valid="glyphicon glyphicon-ok" data-fv-icon-invalid="glyphicon glyphicon-remove" data-fv-icon-validating="glyphicon glyphicon-refresh">
   <input type="hidden" id="lodgerRentAmountId">
   <input type="hidden" name="lodgerId">
   <div class="form-group">
      <label class="col-sm-1 control-label" for="lodgerRoomPaymentType">Mode de paiement</label>
      <div class="col-sm-2">
         <select id="lodgerRoomPaymentType" name="paymentType.paymentTypeId" class="form-control">
         </select>
      </div>
      <label for="lodgerPaymentAmountReceived" class="col-sm-1 control-label">$ reçue</label>
      <div class="col-sm-2">
         <input type="text" class="form-control" id="lodgerPaymentAmountReceived" name="amountReceived" placeholder="Entrer le montant reçue" data-fv-numeric="true" data-fv-numeric-message="Le montant doit être numérique" data-fv-numeric-decimalseparator=","/>
      </div>
      <label for="lodgerPaymentChangeAmount" class="col-sm-1 control-label">$ à remettre</label>
      <div class="col-sm-2">
         <input type="text" class="form-control" id="lodgerPaymentChangeAmount" name="changeAmount" placeholder="montant à remettre" readonly/>
      </div>
      <label for="lodgerPaymentAdvanceAmount" class="col-sm-1 control-label">$ d'avance</label>
      <div class="col-sm-2">
         <input type="text" class="form-control" id="lodgerPaymentAdvanceAmount" name="advanceAmount" placeholder="Entrer le montant d'avance" data-fv-numeric="true" data-fv-numeric-message="Le montant doit être numérique" data-fv-numeric-decimalseparator=","/>
      </div>
   </div>
</form>
```

This is what i get

![formvalidation_error](https://cloud.githubusercontent.com/assets/4097381/14051187/6a5c9bea-f297-11e5-901d-f73ba0b45660.jpeg)

I tried to put a row after the form group, i get the same issue.

**Comment by nghuuphuoc** [comment]
When placing many fields in the same row (`.form-group`), you have to use the [row](http://formvalidation.io/settings/#form-row) option. 
See an example at http://formvalidation.io/examples/complex-form/

**Comment by marccollin** [comment]
like i wrote, puting row don't change nothing.

`<form id="lodgerRoomPaymentForm" class="form-horizontal" role="form" data-fv-framework="bootstrap" data-fv-icon-valid="glyphicon glyphicon-ok" data-fv-icon-invalid="glyphicon glyphicon-remove" data-fv-icon-validating="glyphicon glyphicon-refresh">
   <div class="form-group">
      <div class="row">
         <label class="col-sm-1 control-label" for="lodgerRoomPaymentType">Mode de paiement</label>
         <div class="col-sm-2">
            <select id="lodgerRoomPaymentType" name="paymentType.paymentTypeId" class="form-control">
            </select>
         </div>
         <label for="lodgerPaymentAmountReceived" class="col-sm-1 control-label">$ reçue</label>
         <div class="col-sm-2">
            <input type="text" class="form-control" id="lodgerPaymentAmountReceived" name="amountReceived" placeholder="Entrer le montant reçue" data-fv-numeric="true" data-fv-numeric-message="Le montant doit être numérique" data-fv-numeric-decimalseparator=","/>
         </div>
         <label for="lodgerPaymentChangeAmount" class="col-sm-1 control-label">$ à remettre</label>
         <div class="col-sm-2">
            <input type="text" class="form-control" id="lodgerPaymentChangeAmount" name="changeAmount" placeholder="montant à remettre" readonly/>
         </div>
         <label for="lodgerPaymentAdvanceAmount" class="col-sm-1 control-label">$ d'avance</label>
         <div class="col-sm-2">
            <input type="text" class="form-control" id="lodgerPaymentAdvanceAmount" name="advanceAmount" placeholder="Entrer le montant d'avance" data-fv-numeric="true" data-fv-numeric-message="Le montant doit être numérique" data-fv-numeric-decimalseparator="," readonly />
         </div>
      </div>
   </div>
   <div class="form-group">
      <div class="row">
         <label for="paymentDueDate" class="col-sm-1 control-label">Date prévue</label>
         <div class="col-sm-2">
            <div class="input-group date" id="lodgerPaymentDatePicker">
               <input type="text" id="lodgerPaymentDate" name="paymentDueDate" class="form-control">
               <span class="input-group-addon">
               <span class="glyphicon glyphicon-calendar">
               </span>
               </span>
            </div>
         </div>
         <label class="col-sm-1 control-label" for="lodgerRoomPaymentComment">Commentaire</label>
         <div class="col-sm-8">                     
            <textarea class="form-control" id="lodgerRoomPaymentComment" name="comment"></textarea>
         </div>
      </div>
   </div>
   <div class="form-group">
      <div class="row">
         <div class="col-sm-12">
            <div class="pull-right">
               <button id="lodgerRoomPaymentSave" type="button" class="btn btn-primary">Sauvegarder</button>
               <button id="lodgerRoomPaymentReset" type="reset" class="btn btn-primary">Reset</button>
            </div>
         </div>
      </div>
   </div>
</form>`

when there is an error, has-error is put on the form group
