### ISSUE TITLE
Integrating with geocomplete plugin

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#54]
_From @toolsmith on March 6, 2015 12:52_

Thanks for a great plugin! I have one question before I purchase.  I'm using typeahead with some geocode values and want to validate the parent field "location" based on a hidden value that gets updated when a user selects a location from the drop down list.  Is this possible?

My hidden two fields look like this:

    <form name="form" id="geoInfoForm">
        <fieldset id="geo-data">
            <input type="hidden" id="lat" name="lat" value="">	
	    <input type="hidden" id="lng" name="lng" value="">
	</fieldset>
    </form>

The location field that should display the field looks like this:

    <div class="form-group">
         <input type="text" class="form-control" name="location" id="location">
    </div>

It gets updated via:

    $("#location").geocomplete({
        details: "#geo-data",
       	types: ["geocode", "establishment"],
    });

Can I validate the location field based on valid values from the hidden lat and lng fields?

_Copied from original issue: formvalidation/formvalidation#1451_

**Comment by nghuuphuoc** [comment]
@toolsmith
What kind of validation you want to use for location field?

As I understand, when using ```$("#location").geocomplete()```, the location will be treated as invalid if the geocomplete plugin can't find/determine the lat, lng values.

Am I right?

**Comment by toolsmith** [comment]
That is the case but I'm trying to force users to select an entry from the geo drop down list.  Currently they can enter straight text so I want to ensure that a user has selected an entry from the dynamic drop down by checking that the hidden field(s) lat and lng have valid values. These two fields get updated after a user has selected a location from the drop down.

Is it possible to validate a hidden field as a dependency to a parent field?

Thanks,
-Paul

**Comment by nghuuphuoc** [comment]
@toolsmith 
I hope this [fiddle](http://jsfiddle.net/nghuuphuoc/9pc21dt7/) helps you.

**Comment by nghuuphuoc** [comment]
@toolsmith 
May I know whether or not the fiddle is helpful?
If it works as you expect, please let me know. I will create an example on official website.

**Comment by toolsmith** [comment]
Sorry for my delayed response. The example you created will solve my issue.

Thanks again for the help,
-Paul

**Comment by asthas** [comment]
Hi paul,
I am facing the same problem which Smith had. I am unable to see your solution on fiddle
