### ISSUE TITLE
how to setup facebook or any social media account url validation?

### ISSUE THREAD

**Issue by gfmservice** [formvalidation/support#540]
<div class="col-md-6">
								<div class="control-group form-group">							
									<div class="controls">
										<label class="control-label" for="imgFacebook">
											<i class="fa fa-facebook-square fa-lg"></i> Facebook
										</label>
										<input type="url" class="form-control" id="imgFacebook" name="imgFacebook[]" placeholder="Facebook Account" >					
									</div>
								</div>
							</div>
														
							<div class="col-md-6">
								<div class="control-group form-group">							
									<div class="controls">
										<label class="control-label" for="imgGooglePlus">
											<i class="fa fa-google-plus-square fa-lg"></i> Google Plus
										</label>
										<input type="url" class="form-control" id="imgGooglePlus" name="imgGooglePlus[]" placeholder="Google Plus Account">					
									</div>
								</div>
							</div>
							
							<div class="col-md-6">
								<div class="control-group form-group">							
									<div class="controls">
										<label class="control-label" for="imgLinkedin">
											<i class="fa fa-linkedin-square fa-lg"></i> Linkedin
										</label>
										<input type="url" class="form-control" id="imgLinkedin" name="imgLinkedin[]" placeholder="Linkedin Account">					
									</div>
								</div>
							</div>
							
							<div class="col-md-6">
								<div class="control-group form-group">							
									<div class="controls">
										<label class="control-label" for="imgTwitter">
											<i class="fa fa-twitter-square fa-lg"></i> Twitter
										</label>
										<input type="url" class="form-control" id="imgTwitter" name="imgTwitter[]" placeholder="Twitter Account">					
									</div>
								</div>
							</div>					

			'imgFacebook[]':
			{				
				valid: true,
				message: 'The URL Address is not valid',
				validators: 
				{
                    uri: 
					{
                        message: 'The value is not a valid URL Address'
                    }
                }
			},
			'imgGooglePlus[]':
			{				
				valid: true,
				message: 'The URL Address is not valid',
				validators: 
				{
                    uri: 
					{
                        message: 'The value is not a valid URL Address'
                    }
                }
			}
			'imgLinkedin[]':
			{				
				valid: true,
				message: 'The URL Address is not valid',
				validators: 
				{
                    uri: 
					{
                        message: 'The value is not a valid URL Address'
                    }
                }
			},
			'imgTwitter[]':
			{				
				valid: true,
				message: 'The URL Address is not valid',
				validators: 
				{
                    uri: 
					{
                        message: 'The value is not a valid URL Address'
                    }
                }
			}

for example:

if i type this https://www.facebook.com/eugcar.sanchez to **imgGooglePlus[]**
and notifying for invalid Google Plus URL Address.
.
if i type this https://www.facebook.com/eugcar.sanchez to **imgFacebook[]**
and notifying valid Facebook URL Address.

**Comment by nghuuphuoc** [comment]
In this case, you should use the `regexp` validator.
I just made a new [Validating social account URL](http://formvalidation.io/validators/regexp/#validating-social-account-url) example.
For Google Plus URL regular expression, you can search on StackOverflow. [this dicussion](http://stackoverflow.com/questions/25583711/regex-matching-for-g-profile-url) is one of examples.

**Comment by gfmservice** [comment]
thanks fpr response master.
i resolve now.
			'imgFacebook[]':
			{				
				valid: true,
				message: 'The URL Address is not valid',
				validators: 
				{
					regexp: 
					{
						regexp: '/\w.+facebook.co+[^/]+|\d{21}/',
						message: 'The value is not a valid URL Address'
					}
                }
			},
			'imgGooglePlus[]':
			{				
				valid: true,
				message: 'The URL Address is not valid',
				validators: 
				{
					regexp: 
					{
						regexp: '/\plus.google.co+[^/]+|\d{21}/',
						message: 'The value is not a valid URL Address'
					}
                }
			},

**Comment by nghuuphuoc** [comment]
:+1:
