### ISSUE TITLE
IP address CIDR notation

### ISSUE THREAD

**Issue by Svashta** [formvalidation/support#546]
IP address validator is missing a CIDR notation option, something along: XXX.XXX.XXX.XXX/YY
Is it possible to do it some other way?

**Comment by kgorman** [comment]
+1

**Comment by kgorman** [comment]
This seems to work:

```
validators: {
                    regexp: {
                        regexp: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$',
                        message: 'Must be CIDR address mask format: 0.0.0.0/0'
                    }
                }
```

**Comment by Svashta** [comment]
Works great! Thx

**Comment by nghuuphuoc** [comment]
It's now supported by [v0.8.0](http://formvalidation.io/news/v0-8-0-released-supports-bootstrap-4-alpha-foundation-6/). See more examples at the [ip validator](http://formvalidation.io/validators/ip/).
Please upgrade the plugin.
