### ISSUE TITLE
Summernote version 0.8.1 not working with formvalidation

### ISSUE THREAD

**Issue by quangvision** [formvalidation/support#549]
Hello
I tried to implement original example to play with summernote from formvalidation.io but got following error:

`Uncaught TypeError: $(...).code is not a function`

**Comment by nghuuphuoc** [comment]
It's because Summernote changed its API:

```javascript
// Old version (v0.6.9)
var code = $('[name="content"]').code();

// Latest version (v0.8.1)
var code = $('[name="content"]').summernote('code');
```

I updated the [Playing with Summernote](http://formvalidation.io/examples/summernote/) for Summernote v0.8.1 as well.
