### ISSUE TITLE
Confirm sent message in the same page

### ISSUE THREAD

**Issue by mcxnet** [formvalidation/support#55]
Hello... how can I view the confirm sent message without open a new page after form's validation?
Thanks

**Comment by nghuuphuoc** [comment]
Let's say that, after clicking the Submit button, the form is validated.
Then a confirm message box is shown? "Are you sure that you want to do it?" with two buttons __Yes__ and __No__.

Clicking __Yes__ button will submit the form as usual.
Clicking __No__ button will close the message box.

Is it what you want to archive?

**Comment by microluxnet** [comment]
Yes, a bootstrap modal window with Yes or No, but also with the confirm sent message in the same window, with the behavior "when the form is successfuly submitted -> view the confirm message (available in a hidden div)".
I need to avoid to open another page for the confirm/error sent message (ajax request).

Do you know if exist a jQuery plugin for this and the instruction to integrate it with formvalidation?
Thanks!

**Comment by nghuuphuoc** [comment]
> when the form is successfuly submitted -> view the confirm message

Are the form data sent to back-end via Ajax?

**Comment by microluxnet** [comment]
For the moment I'm using a traditional ASP script to send the request (with confirm/error popup message):
-------------
document.subform.action = '/include/send.asp';
 if (sent==true)
  {
  //fin=window.open("about:blank","fin","width=400,height=300,scrollbars=1,resizable=1");
  fin = popup_center("about:blank","fin",500,350,0,0)
  timer=setTimeout("return true",200)
  }
  else
  {
  alert("impossible to send request");
  return false;
  }
 }
-----------------
