### ISSUE TITLE
Missing download link for formvalidation

### ISSUE THREAD

**Issue by qreftan** [formvalidation/support#550]
Hi,

I purchased formvalidation 1 or 2 years ago and now I can't find the email with the download link.

I couldn't find a contact form for supports. Sorry for creating an issue on github for this.

Where can I get my download link?

**Comment by qreftan** [comment]
Dont remember which of these emails i used to purchase formvalidaiton:

qreftan@hotmail.com
filipdanielsson@hotmail.se

Thanks

**Comment by nghuuphuoc** [comment]
The new download link is just sent to your mailbox.
Please keep that link because you can use it to download future releases.
