### ISSUE TITLE
select notEmpty didin't validate

### ISSUE THREAD

**Issue by a6091731** [formvalidation/support#557]
i set select option value="" but it didn't validate

**Comment by a6091731** [comment]
`<div class="form-group">
	                            <label>題庫類型</label>
	                            <select class="form-control" name="examCategory.id" id="examCategoryID">
	                                <c:forEach items="${examCategoryList}" var="examCategory">
	                                	<option value="${examCategory.id }">${examCategory.name}</option>
	                                </c:forEach>
	                            </select>
	                        </div>`

**Comment by nghuuphuoc** [comment]
Please provide the HTML and Javascript code!
