### ISSUE TITLE
Bootstrap Navbar Collapse Conflicts With Form Validation

### ISSUE THREAD

**Issue by Tigerman55** [formvalidation/support#566]
I'm attempting to use the mobile navigation collapse feature shown in the Bootstrap docs here:

https://getbootstrap.com/components/#navbar

When I click on the navigation icon on mobile view to show the navigation menu items (with the animation effect), it does not perform the animation to display the nav items. I think it has to be that the older version of bootstrap.min.js used in FormValidation is not the same as the bootstrap.min.js used in the latest version of Bootstrap. Cause when I include the latest bootstrap.min.js (3.3.6) in addition to the FormValidation's bootstrap.min.js, it works perfectly. The reason I am mentioning this bug is because I find it quite annoying to have to include two of the "same" bootstrap files. If I try to leave out the bootstrap.min.js file in located in dist/js/framework/ and just use the latest Bootstrap version I get an error as follows:

Error: The class FormValidation.Framework.Bootstrap is not implemented

Up to this point, this is the only way I can get the navigation collapse feature in Bootstrap to work along with FormValidation library:

```
<link rel="stylesheet" href="lib/formvalidation-dist-v0.7.1/dist/css/formValidation.css">
<script src="lib/formvalidation-dist-v0.7.1/dist/js/formValidation.min.js"></script>
<script src="lib/formvalidation-dist-v0.7.1/dist/js/framework/bootstrap.min.js"></script>
<script src="lib/bootstrap-3.3.6-dist/js/bootstrap.min.js"></script>
```

**Comment by nghuuphuoc** [comment]
Please notice that the `/dist/js/framework/bootstrap.min.js` provided by FormValidation and `bootstrap.min.js` provided by Bootstrap ARE NOT the same.

It is also mentioned in the [Including library](http://formvalidation.io/getting-started/#including-library) section:

<img width="879" alt="including" src="https://cloud.githubusercontent.com/assets/4226036/14680383/48f7396e-0747-11e6-9212-8b4500359fc4.png">
