### ISSUE TITLE
Issue with multiple checkbox validation using selector

### ISSUE THREAD

**Issue by balakj75** [formvalidation/support#568]
If I have a form with multiple checkboxes and I use a selector to define a callback validator, the error message does not show up. The label of the first checkbox changes to red but the rest stay as it is. I noticed this piece of code
`total = ('radio' === type || 'checkbox' === type) ? 1 : fields.length`
which will update only the first checkbox in case there are multiple fields in the validator. The actual error message is attached to the last checkbox and never shows.

**Comment by nghuuphuoc** [comment]
Please take a look at this example
http://formvalidation.io/examples/validating-checkbox-list-placed-multiple-columns/
