### ISSUE TITLE
Close date picker when user input date

### ISSUE THREAD

**Issue by Nur-jaman** [formvalidation/support#571]
Is it possible to close date picker as soon as user select date ?
and also when i used it in bootstrap modal and scroll it's stick with a fixed position of  modal window ? like this http://prnt.sc/aw3yc3
@nghuuphuoc Please help

Thanks

**Comment by nghuuphuoc** [comment]
You should use the [autoclose](https://bootstrap-datepicker.readthedocs.io/en/stable/options.html#autoclose) option provided by the date picker plugin.

**Comment by nghuuphuoc** [comment]
The example is now available at http://formvalidation.io/examples/bootstrap-datepicker/#auto-closing-the-date-picker
