### ISSUE TITLE
phone validation doesn't work

### ISSUE THREAD

**Issue by mtedone** [formvalidation/support#572]
Hi, I'm trying to use phone validation programmatically. Here is my validation code: 

![js-validation](https://cloud.githubusercontent.com/assets/366368/14766928/94387704-0a11-11e6-923c-2bd9d645db54.jpg)

And here is my HTML form declaration for country and phone:

![form](https://cloud.githubusercontent.com/assets/366368/14766923/6bd7738c-0a11-11e6-9776-0c6b9b7f9802.jpg)

When displaying the form, I've tried entering a list of characters (no numbers) and the validator displays it as OK. 

![phone-ok](https://cloud.githubusercontent.com/assets/366368/14766894/e5cc46aa-0a10-11e6-8973-fdbb0ef12250.jpg)

**Comment by mtedone** [comment]
Found the problem. The id and name attributes in the country HTML select element had different names and this caused some problems to the API. I've now named both as country and the validation works

**Comment by nghuuphuoc** [comment]
:+1:
