### ISSUE TITLE
Max call stack exceeded

### ISSUE THREAD

**Issue by BobBuford** [formvalidation/support#573]
I have a web page that has on it 2 textarea fields that I need to validate as having between 1 and 255 characters whenever that field is exposed.  Each field has a href link to click to show or hide the field.  The validation on each field is to be enabled when the field is shown, disabled when the field is hidden.

With the FormValidation methods commented out, this performs as expected with no errors.  
When FV methods are enabled, and the page reloads, the first error occurs (range error, max call stack exceeded).  Then when I click on the link to show one of the textarea input fields, the field does not show, and the 2nd error occurs.  I'm not able to tell where in my code the problem exists - Screenshots are attached of the errors.

I reviewed instructions on [Writing Form](http://formvalidation.io/getting-started/#writing-form), confirming that I did not have a problem with using 'submit' inappropriately.  I added the row selector to the initial field definition (updating the code below), without remedy.

I also reviewed issues [204](https://github.com/formvalidation/support/issues/204) and [218](https://github.com/formvalidation/support/issues/218) without seeing how those might be relevant to my situation.
The single code file is attached.  The form ID line is

                    <form id="giftgiveform">

The textarea code is:  

                <div class="panel panel-default give-modal-panel">
                <div class="panel-heading">Optional Comments</div>
                <div class="panel-body">
                    <ul class="list-unstyled">
                        <li>
                            <a href="#staff-comments" class="commentLink"
                               onclick="toggle_visibility('staffComments')">Include a message for
                                {Recipient}</a>
                        <textarea rows="3" name="staffComments" id="staff-comments"
                                  class="staff-comments give-modal-comments"
                                  style="display:none" title="Staff Comments"></textarea>
                        </li>
                        <li>
                            <a href="#cru-comments" class="commentLink"
                               onclick="toggle_visibility('cruComments')">Include a message for
                                Donation Services</a>
                        <textarea rows="3" name="cruComments" id="cru-comments"
                                  class="cru-comments give-modal-comments"
                                  style="display:none" title="Cru Comments"></textarea>
                        </li>
                    </ul>
                </div>
            </div>

and the script in the HTML file is:

    <script>

    function toggle_visibility(id) {
        var e = document.getElementById(id);
        var eName = e.name;
        if (e.style.display == 'block') {
            e.style.display = 'none';
            $('#giftgiveform').formValidation('enableFieldValidators', eName, false);
        } else {
            e.style.display = 'block';
            $('#giftgiveform').formValidation('enableFieldValidators', eName, true);
        }
        console.log(e.id + ': ' + e.style.display + ': ' + eName);
    }

    $(document).ready(function () {
        $('#giftgiveform')
                .formValidation({
                    framework: 'bootstrap',
                    icon: {
                        valid: 'glyphicon glyphicon-ok',
                        invalid: 'glyphicon glyphicon-remove',
                        validating: 'glyphicon glyphicon-refresh'
                    },
                    fields: {
                        staffComments: {
                            row: '.staff-comments',
                            enabled: false,
                            validators: {
                                stringLength: {
                                    min: 1,
                                    max: 250,
                                    message: 'This comment must be between 1 and 250 comments.'
                                }
                            }
                        },
                        cruComments: {
                            row: '.cru-comments',
                            enabled: false,
                            validators: {
                                stringLength: {
                                    min: 1,
                                    max: 250,
                                    message: 'This comment must be between 1 and 250 comments.'
                                }
                            }
                        }
                    }

                });
    });

</script>

The error reports, expanded, are:  
![screen shot 2016-04-25 at 12 35 50 pm](https://cloud.githubusercontent.com/assets/6683403/14791238/02e8508a-0ae3-11e6-9d10-0b409084fbd6.png)

and the line with the 2nd error is shown here:  
![screen shot 2016-04-25 at 12 33 12 pm](https://cloud.githubusercontent.com/assets/6683403/14791270/2099eec2-0ae3-11e6-8688-dc8db92e9407.png)

and finally, the HTML file, including the JS script, is:  
[component.html.zip](https://github.com/formvalidation/support/files/234970/component.html.zip)

Thank you

**Comment by nghuuphuoc** [comment]
The issue is caused by the reason that your form doesn't follow Bootstrap form. It means that the fields aren't placed inside a `.form-group` element.

In your case, you should add a class to your `li` element (for example: `li class="fieldContainer") and set `row: '.fieldContainer'`.

Your sample code setting `row: '.staff-comments'` doesn't work because the fields are placed inside `li`, not the associated `a` element.
