### ISSUE TITLE
Only validate form on submit

### ISSUE THREAD

**Issue by qreftan** [formvalidation/support#576]
Is it possible to disable change/keyup events for inputs and only validate the form when you click the submit button?

In jquery validation you would do something like..

        onkeyup: false,
        onclick: false,
        onfocusout: false

I would like to call it as a plugin method...
$('#form').formValidation('enableChangeValidators', 'Firstname', false);

**Comment by nghuuphuoc** [comment]
The [live](http://formvalidation.io/settings/#form-live) option might help you, not completely but still useful.
