### ISSUE TITLE
Validation is not working

### ISSUE THREAD

**Issue by harisx** [formvalidation/support#587]
Hi, please review this page http://www.novelty.id/subscribe.php the validation with recaptcha2 addons is not working there. is there something i've missed? Thanks

**Comment by nghuuphuoc** [comment]
I've just tried to access the page and it gave me the `Token is missing or expired` message and then redirect to the homepage.
Can you give me the correct link?

**Comment by harisx** [comment]
sorry my mistake, i have bypass token checking on that page, please recheck....Thank you

**Comment by harisx** [comment]
Hello...any updates on this?

**Comment by nghuuphuoc** [comment]
It seems that you forgot to add `js/framework/bootstrap.min.js` provided by the plugin:

```html
<!-- Bootstrap Core JavaScript -->
<script src="./js/bootstrap.min.js"></script>

<script src="./js/creative.js"></script>
<script src="./js/subscribe.js"></script>
<script src="./js/formvalidation/dist/js/formValidation.min.js"></script>
<script src="./js/formvalidation/dist/js/framework/bootstrap.min.js"></script> // <---- You missed that
<script src="./js/formvalidation/dist/js/addons/reCaptcha2.min.js"></script>
```

See http://formvalidation.io/getting-started/#including-library

<img width="838" alt="including-libs" src="https://cloud.githubusercontent.com/assets/4226036/15235001/da6f8206-18e1-11e6-84c8-c738daeedfe3.png">

**Comment by harisx** [comment]
Hi, thank you for your respond. I have added it but the problem remain the same

**Comment by harisx** [comment]
Hi, i found the problem....it's fully my mistake...there are some function in subscribe.js which is doesn't exist

Thank you

**Comment by nghuuphuoc** [comment]
Thanks for your confirmation!
