### ISSUE TITLE
Can get this to work at all

### ISSUE THREAD

**Issue by SiNiSoftware** [formvalidation/support#588]
Tried few samples and just nothing works.   

can't even put a sample code up here.  We paid for this code and would like some support please

**Comment by nghuuphuoc** [comment]
Can you please give some code here?
I guess you miss something.
You also should look at the [basic example](http://formvalidation.io/getting-started/demo/bootstrap.html).

**Comment by SiNiSoftware** [comment]
I tried to put code up here and it does not display

`

<!DOCTYPE html>
<html lang="en">

<head>
    <link href = "css/bootstrap.min.css" rel = "stylesheet">
    <link href = "css/modern-business.css" rel = "stylesheet">
    <link href = "font-awesome/css/font-awesome.min.css" rel = "stylesheet" type = "text/css">
    <link href = "css/main.css" rel = "stylesheet" type = "text/css">
	
	<link href="css/formValidation.min.css" rel="stylesheet">
	
</head>

</body>
<style type="text/css">
#loginForm .has-error .control-label,
#loginForm .has-error .help-block,
#loginForm .has-error .form-control-feedback {
    color: #f39c12;
}

#loginForm .has-success .control-label,
#loginForm .has-success .help-block,
#loginForm .has-success .form-control-feedback {
    color: #18bc9c;
}
</style>

<form id="loginForm" method="post" class="form-horizontal">
    <div class="form-group">
        <label class="col-xs-3 control-label">Username</label>
        <div class="col-xs-5">
            <input type="text" class="form-control" name="username" />
        </div>
    </div>

    <div class="form-group">
        <label class="col-xs-3 control-label">Password</label>
        <div class="col-xs-5">
            <input type="password" class="form-control" name="password" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-9 col-xs-offset-3">
            <button type="submit" class="btn btn-primary">Sign in</button>
        </div>
    </div>
</form>

<script>
$(document).ready(function() {
    $('#loginForm').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            username: {
                validators: {
                    notEmpty: {
                        message: 'The username is required'
                    },
                    stringLength: {
                        min: 6,
                        max: 30,
                        message: 'The username must be more than 6 and less than 30 characters long'
                    },
                    regexp: {
                        regexp: /^[a-zA-Z0-9_\.]+$/,
                        message: 'The username can only consist of alphabetical, number, dot and underscore'
                    }
                }
            },
            password: {
                validators: {
                    notEmpty: {
                        message: 'The password is required'
                    }
                }
            }
        }
    });
});
</script>

    
    
	<script src="js/jquery.min.js"></script>
	
    
    <script src="js/bootstrap.min.js"></script>
	
	
	<script src="js/formValidation.min.js"></script>
	<script src="js/framework/bootstrap.min.js"></script> 

</body>
</html>
`

**Comment by SiNiSoftware** [comment]
here is what we have been using.

http://sinisoftware.com/v013.rar

**Comment by nghuuphuoc** [comment]
You should wrap the code between _```_ and _```_.
I updated your comment and now we can see the code.

**Comment by SiNiSoftware** [comment]
``` 

<!DOCTYPE html>
<html lang="en">

<head>
    <link href = "css/bootstrap.min.css" rel = "stylesheet">
    <link href = "css/modern-business.css" rel = "stylesheet">
    <link href = "font-awesome/css/font-awesome.min.css" rel = "stylesheet" type = "text/css">
    <link href = "css/main.css" rel = "stylesheet" type = "text/css">
	<!-- FormValidation CSS file -->
	<link href="css/formValidation.min.css" rel="stylesheet">
	
</head>

</body>
<style type="text/css">
#loginForm .has-error .control-label,
#loginForm .has-error .help-block,
#loginForm .has-error .form-control-feedback {
    color: #f39c12;
}

#loginForm .has-success .control-label,
#loginForm .has-success .help-block,
#loginForm .has-success .form-control-feedback {
    color: #18bc9c;
}
</style>

<form id="loginForm" method="post" class="form-horizontal">
    <div class="form-group">
        <label class="col-xs-3 control-label">Username</label>
        <div class="col-xs-5">
            <input type="text" class="form-control" name="username" />
        </div>
    </div>

    <div class="form-group">
        <label class="col-xs-3 control-label">Password</label>
        <div class="col-xs-5">
            <input type="password" class="form-control" name="password" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-9 col-xs-offset-3">
            <button type="submit" class="btn btn-primary">Sign in</button>
        </div>
    </div>
</form>

<script>
$(document).ready(function() {
    $('#loginForm').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            username: {
                validators: {
                    notEmpty: {
                        message: 'The username is required'
                    },
                    stringLength: {
                        min: 6,
                        max: 30,
                        message: 'The username must be more than 6 and less than 30 characters long'
                    },
                    regexp: {
                        regexp: /^[a-zA-Z0-9_\.]+$/,
                        message: 'The username can only consist of alphabetical, number, dot and underscore'
                    }
                }
            },
            password: {
                validators: {
                    notEmpty: {
                        message: 'The password is required'
                    }
                }
            }
        }
    });
});
</script>

    <!-- jQuery -->
    <!--<script src="js/jquery.js"></script> -->
	<script src="js/jquery.min.js"></script>
	
    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
	
	<!-- FormValidation plugin -->
	<script src="js/formValidation.min.js"></script>
	<script src="js/framework/bootstrap.min.js"></script> 

</body>
</html>

```

**Comment by nghuuphuoc** [comment]
You have to put the required scripts before calling `$(document).ready(function() {`.
The current code doesn't work because at the time you call `$(document)`, the page doesn't know where `$` from (it's from jQuery, but jQuery isn't loaded at that moment).

So, the correct usage should be

```
    <script src="js/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- FormValidation plugin -->
    <script src="js/formValidation.min.js"></script>
    <script src="js/framework/bootstrap.min.js"></script> 

<script>
$(document).ready(function() {
    $('#loginForm').formValidation({
        ...
    });
});
</script>
```

**Comment by SiNiSoftware** [comment]
Thanks for you great help.  That fixed it.
