### ISSUE TITLE
live validation with fields without validator

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#59]
_From @andresendo on March 10, 2015 20:16_

hi,
i have a form with 4 fields and live validation. but i have only 2 fields with validationsettings. but after i submit the form, the submit button is disabled and it is only active after i change something in the 2 fields with validator...

what i make wrong?

_Copied from original issue: formvalidation/formvalidation#1454_

**Comment by nghuuphuoc** [comment]
@andresendo
There's something wrong :)
Please give me your form markup (HTML) and the Javascript you're calling.

**Comment by andresendo** [comment]
<script>
	$( document ).ready(function() {

	
    $('#form1').formValidation()
        .on('success.form.fv', function(e) {
	        toastr.options = {
			  "closeButton": false,
			  "debug": false,
			  "newestOnTop": true,
			  "progressBar": false,
			  "positionClass": "toast-top-center",
			  "preventDuplicates": false,
			  "onclick": null,
			  "showDuration": "300",
			  "hideDuration": "1000",
			  "timeOut": "500",
			  "extendedTimeOut": "0",
			  "showEasing": "swing",
			  "hideEasing": "swing",
			  "showMethod": "fadeIn",
			  "hideMethod": "fadeOut"
			}
	        toastr.info('Wird gespeichert...');
	        toastr.clear();
	        toastr.options.timeOut = 2000;
		    toastr.options.fadeOut = 350;
		    toastr.options.fadeIn = 0;
            // Prevent form submission
            e.preventDefault();

            // Get the form instance
            var $form = $(e.target);

            // Get the FormValidation instance
            var bv = $form.data('formValidation');
			
            // Use Ajax to submit form data
            $.post($form.attr('action'), $form.serialize(), function(result) {
                
                
                if (result.status == 1)
                {
                toastr.success('Wurde erfolgreich gespeichert!');
                }
                if (result.status == 0)
                {
                toastr.options.timeOut = 2000;
			    toastr.options.fadeOut = 1500;
			    toastr.options.fadeIn = 0;
                toastr.error('Konnte nicht gespeichert werden!');
                }
                
                
            }, 'json');
        });

	
	});
</script>

**Comment by nghuuphuoc** [comment]
By default, the submit button is disabled right after you click on it. This is to avoid double clicking.
You're using Ajax to submit the form data. Do you want the button to be enabled after sending data to the server?

**Comment by andresendo** [comment]
And the html.. 

```html
<body>


	
	<div class="container-fluid">
	
	
	<form  class="form-horizontal" action="#" method="post" name="form1" id="form1" 
	data-fv-addons="mandatoryIcon"
    data-fv-addons-mandatoryicon-icon="fa fa-asterisk"
    data-fv-framework="bootstrap"
    data-fv-message="This value is not valid"
    data-fv-icon-valid="fa fa-check"
    data-fv-icon-invalid="fa fa-remove"
	data-fv-icon-validating="fa fa-refresh">
	
		<input type="hidden" name="seite" value="1"  />
		<input type="hidden" name="artikelid" value="48"  />
		
	<div class="row">

			<div class="col-xs-6">
							
									<div class="headline_little">Artikeldaten</div>								
								
								
								
							
								
									<div class="form-group">
	<label for="artikelnr" class="col-sm-5 control-label">Artikelnr:</label>
	<div class="col-sm-5">
		<input name="artikelnr" id="artikelnr" class="form-control" value="01009" type="text" 					
											data-fv-notempty="true" 
data-fv-notempty-message="Dieses Feld darf nicht leer sein."										
											data-fv-regexp="true"
data-fv-regexp-regexp="^[0-9\-]+$"
data-fv-regexp-message="Darf nur Zahlen und Bindestriche enthalten"
										
										
										
                 />
	</div>
</div>								
								
								
							
								
								
									<div class="form-group">
	<label for="artikelart" class="col-sm-5 control-label">Artikelart:</label>
	<div class="col-sm-5">
		<select name="artikelart" id="artikelart" class="form-control select2" >
			<option value=""></option>
							<option value="1" selected>1 - Domains</option>
							<option value="2" >2 - Standard</option>
							<option value="3" >3 - Verbrauchsmaterial</option>
							<option value="4" >4 - Sonstiges</option>
							<option value="5" >5 - Komponenten</option>
							<option value="6" >6 - Software</option>
							<option value="7" >7 - Webhosting</option>
							<option value="8" >8 - Dienstleistung</option>
							<option value="99" >99 - Kabel</option>
					</select>
	</div>
</div>								
								
							
								
									<div class="form-group">
	<label for="artikelname" class="col-sm-5 control-label">Artikelname:</label>
	<div class="col-sm-5">
		<input name="artikelname" id="artikelname" class="form-control" value=".asia Domain" type="text" 					
											data-fv-notempty="true" 
data-fv-notempty-message="Dieses Feld darf nicht leer sein."										
										
										data-fv-regexp="true"
data-fv-regexp-regexp="^[a-zA-Z0-9öäüÖÄÜ_\-\ \.]+$"
data-fv-regexp-message="Darf nur Buchstaben, Zahlen, Unterstriche, Bindestriche und Punkte enthalten"
										
										
										
                 />
	</div>
</div>								
								
								
							
								
									<div class="form-group">
	<label for="artikelname_int" class="col-sm-5 control-label">Artikelname (international):</label>
	<div class="col-sm-5">
		<input name="artikelname_int" id="artikelname_int" class="form-control" value="" type="text"  />
	</div>
</div>								
								
														
					</div>  
			<div class="col-xs-6">
							
									<div class="headline_little">Daten</div>								
								
								
		....						
					</div>  
		
	
	</form>


<footer class="footer">
<div class="footer-container">
	<p class="text-muted">		
		<div class="pull-right">
			<button type="submit" name="submit" class="btn btn-primary">Speichern</button>
			
			<input type="reset" name="reset" id="reset" value="Zur&uuml;cksetzen" class="btn btn-default" />  
		</div>
	</p>
</div>
</footer>

</body>

```

**Comment by andresendo** [comment]
yes and no..

the button is on default disabled.. right.. i change something in a field with validation and the button is enabled.. but if i change something in a field without validation the button is still disabled..

**Comment by nghuuphuoc** [comment]
1)
```html
<button type="submit" name="submit" class="btn btn-primary">Speichern</button>
```

Also, please DO NOT use submit for id, name attributes of submit button.
It has been [warned](http://formvalidation.io/getting-started/#name-conflict).

2)
> but if i change something in a field without validation the button is still disabled

Because there's invalid field. The plugin asks you to fix all fields untill all of them are valid. After that, the button will be enabled. It's expected behaviour.

If you want to force the button to be enabled, you can call the [disableSubmitButtons(false)](http://formvalidation.io/api/#disable-submit-buttons) method.

**Comment by andresendo** [comment]
1. Oh f*** - i have change the button but i forgot the name.. 

2. But the two fields with validation are valid...  that means i can't have fields without validation and the "disabled submit button"?

**Comment by nghuuphuoc** [comment]
> But the two fields with validation are valid... that means i can't have fields without validation and the "disabled submit button

Tell me the steps I can follow to make the button to be disabled? And how you want it to be enabled again?

**Comment by andresendo** [comment]
I change something ... e.g. in "Artikelname" .. after i click on submit the button is disabled.  Now i want so change something in "artikelname_int" and the button is disabled.. but if i change something in "artikelname" the button goes enabled..

**Comment by nghuuphuoc** [comment]
> I change something ... e.g. in "Artikelname" .. after i click on submit the button is disabled

The button is disabled to avoild double click

> Now i want so change something in "artikelname_int" and the button is disabled

The button still be disabled until all the field are valid. So you need to fix all the invalid field.
Changing a field without any validation rules doesn't effect to the button status.

I hope you're clear about the behaviour.
