### ISSUE TITLE
FormValidation does not reset on success and the button is enabled. Why? 

### ISSUE THREAD

**Issue by francisngo** [formvalidation/support#592]
I am having trouble resetting the form after its been submitted. In addition, the submit button, by default, should be disabled but it is enabled before and after submission. What I'd like to accomplish is have the form - once filled out and submit is clicked - a success message will pop up below the form. The form fields should then be reset and button is again disabled.  

    $(document).ready(function() {
	$('#contactForm').formValidation({
		framework: 'bootstrap',
		icon: {
			valid: 'glyphicon glyphicon-ok',
                        invalid: 'glyphicon glyphicon-remove',
                        validating: 'glyphicon glyphicon-refresh'
        },
		excluded: [':disabled'],
		fields: {
			firstName: {
				trigger: 'blur',
				validators: {
					stringLength: {
						min: 2,
					},
					notEmpty: {
						message: 'First name is required'
					}
				}
			},
			lastName: {
				trigger: 'blur',
				validators: {
					stringLength: {
						min: 2,
					},
					notEmpty: {
						message: 'Last name is required'
					}
				}
			},
			company: {
				trigger: 'blur',
				validators: {
					stringLength: {
						min: 2,
					},
					notEmpty: {
						message: 'Company is required'
					}
				}
			},
			emailAddress: {
				trigger: 'blur',
				validators: {
					notEmpty: {
						message: 'Email is required'
					},
					emailAddress: {
						message: 'Please enter a valid email'
					}
				}
			},
			busPhone: {
				trigger: 'blur',
				validators: {
					notEmpty: {
						message: 'Phone number is required'
					},
					phone: {
						country: 'US',
						message: 'Please enter a valid phone number'
					}
				}
			}
		},
		onSuccess: function(e) {
			$('#success_message').slideDown({opacity: "show"}, "slow");
			var $form = $(e.target),
				fv = $form.data('formValidation');
			$.post(form.attr('action'), form.serialize(), function(result) {
					console.log(result);
			}, 'json');
			$('#contactForm').formValidation('resetForm', true);
		}
	});
	$('#formModal').on('hidden.bs.modal', function() {
    	        $('#contactForm').formValidation('resetForm', true);
    	        $('#success_message').hide();
	});
    });

**Comment by nghuuphuoc** [comment]
I saw that you are trying to use Ajax to post the data to your back-end after verifying that all fields are valid.
In this case, you need to prevent the default behaviour as seen in the [Using Ajax to submit the form](http://formvalidation.io/examples/ajax-submit/):

```javascript
$('#contactForm').formValidation({
    framework: 'bootstrap',
    icon: {
        ...
    },
    excluded: [':disabled'],
    fields: {
        ...
    },
    onSuccess: function(e) {
        // Prevent form submission
        e.preventDefault();

        // Show message
        $('#success_message').slideDown({opacity: "show"}, "slow");

        // Send Ajax request
        var $form = $(e.target),
            fv = $form.data('formValidation');
        $.post(form.attr('action'), form.serialize(), function(result) {
               console.log(result);
              
        }, 'json');

        // Reset form
        fv.resetForm(true);

        // Disable the submit button 
        fv.disableSubmitButtons(true);
    }
});
```
In the sample code above, inside the `onSuccess` (or `success.form.fv`) event, you already have a FormValidation instance (`fv = $form.data('formValidation')). So you can call the APIs directly, such as

* [resetForm](http://formvalidation.io/api/#reset-form)
* [disableSubmitButtons](http://formvalidation.io/api/#disable-submit-buttons)
