### ISSUE TITLE
checkbox list validation fails when live='disabled'

### ISSUE THREAD

**Issue by madsbrydegaard** [formvalidation/support#593]
Previously raised here: https://github.com/formvalidation/support/issues/364
Still a problem in 0.7.1!

See fiddle: http://jsfiddle.net/a72ywfou/3/
1. Submit form to render invalid. 
2. Check last checkbox and re-submit
Form cannot submit!

Any possible solution for this?

**Comment by nghuuphuoc** [comment]
Please try the solution [here](https://github.com/formvalidation/support/issues/611#issuecomment-225349312)

**Comment by nghuuphuoc** [comment]
The latest version [v0.8.0](http://formvalidation.io/news/v0-8-0-released-supports-bootstrap-4-alpha-foundation-6/) fixes that.
Please upgrade the plugin.
