### ISSUE TITLE
Hiding success status only works for JS defined validators

### ISSUE THREAD

**Issue by amccoll111** [formvalidation/support#596]
If I define validators in HTML the "Hiding success class" snippet doesn't appear to work?

**Comment by nghuuphuoc** [comment]
It should work as expected. 
See a sample [jsfiddle](http://jsfiddle.net/nghuuphuoc/5caz6cxL/):

![hide-success-class](https://cloud.githubusercontent.com/assets/4226036/15452387/493797e0-2018-11e6-91d2-d42d160c1157.gif)
