### ISSUE TITLE
validation / post request

### ISSUE THREAD

**Issue by vjeko11** [formvalidation/support#597]
Hi,
I have issue with IE 11.... I don't sure what caused problem... maybe validator...
I am sending ajax post request after  form is validated... but in the first time nothing happen...
after change some filed to be validated again IE send post data.....

do you know what can to cause problem

**Comment by nghuuphuoc** [comment]
Does this issue happen on other browser such as Chrome, Firefox or older versions of IE (9/10)?

**Comment by vjeko11** [comment]
HI,

no only IE... but I solved problem....

it is not validation problem..... it is ssl problem....

thank you very much

**Comment by nghuuphuoc** [comment]
Thanks for your information.
