### ISSUE TITLE
formValidation is not a funtion

### ISSUE THREAD

**Issue by tomwhalen** [formvalidation/support#598]
I'm pretty sure the issue lies in how the `<script>` and `<link>` call-outs are setup but can't seem to identify the bad-apple.  Here's my preamble:"
```
<link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

    <!--Import Multi Step Indicator css-->
    <link href="assets/css/gsi-step-indicator.min.css" rel="stylesheet" />

    <!--Import  Step Form Wizard css-->
    <link href="assets/css/tsf-step-form-wizard.min.css" rel="stylesheet" />
    <!--Import  demo css-->
    <link href="assets/css/demo.min.css" rel="stylesheet" />
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- jQuery v1.9.1 or higher -->
    <script type="text/javascript" src="assets/js/jquery-1.11.3.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <!--Plugin for validation-->
    <!-- <link href="assets/plugin/parsley/css/parsley.css" rel="stylesheet" />
    <!--
    <!-- setting up FormValidation Plug-in and classes for Bootstrap form validations -->
    <link rel="stylesheet" href="assets/FormValidator/dist/css/formValidation.min.css">
    <!-- FormValidation plugin and the class supports validating Bootstrap form -->
    <script src="assets/FormValidator/dist/js/formValidation.min.js"></script>
    <script src="assets/FormValidator/dist/js/framework/bootstrap.min.js"></script>
    <!-- END FORMVALIDATOR SETUP -->
```
MentorEntryForm-v10.html:434 Uncaught TypeError: $(...).formValidation is not a function
(anonymous function)	@	MentorEntryForm-v10.html:434
j	@	jquery-1.11.3.min.js:2
k.fireWith	@	jquery-1.11.3.min.js:2
m.extend.ready	@	jquery-1.11.3.min.js:2
J	@	jquery-1.11.3.min.js:2

any help would be greatly appreciated - love the tool so I want to get it setup for a new project i'm working on :0

Tom

**Comment by nghuuphuoc** [comment]
The order of included JavaScript files are correct.
Can you tell me where do you put your `.formValidation()` call? Is it used with special framework?

**Comment by tomwhalen** [comment]
the script call is the last <script> before the </body> tag 
`
<script>
$(document).ready(function() {
    $('#step1-form').formValidation({
    framework: 'bootstrap',
    icon: {
        valid: 'glyphicon glyphicon-ok',
        invalid: 'glyphicon glyphicon-remove',
        validating: 'glyphicon glyphicon-refresh'
    },
    fields: {
        mentor_empno: {
            validators: {
                notEmpty: {
                    message: 'Employee Number is required'
            },
                regexp: {
                    regexp: /^[a-zA-Z\s]+$/,
                    message: 'The first name can only consist of alphabetical and space'
                }
            }
        }
    }
    });
});
</script>

`

**Comment by tomwhalen** [comment]
update on this. I created a new site instance on my apache server and just installed the bootstrap libs along with formValidatition and I'm getting the same .formValidation not a function error.  So I'm starting to be out of my reach for troubleshooting this. The only thing that's different is the version of jQuery is 1.12.3 which should be compliant with your code but that is different.  Also I'm running the formValidation-dist-v0.7.1 and pointing to the /dist directory.

preamble before <body> tag

    <link href="css/bootstrap.min.css" rel="stylesheet">
    
      <link rel="stylesheet" href="formvalidation-dist-v0.7.1/dist/css/formValidation.min.css">

      
      <script type="text/javascript" src="jQuery/jquery-1.12.3.min.js"></script>

      
      <script src="js/bootstrap.min.js"></script>

      
      <script src="formvalidation-dist-v0.7.1/dist/js/formValidation.min.js"></script>
      <script src="formvalidation-dist-v0.7.1/dist/js/framework/bootstrap.min.js"></script>

callout at the bottom of the </body> tag


    <script type="text/javascript" src="jQuery/jquery-1.12.3.min.js"></script>
    
    <script src="js/bootstrap.min.js"></script>

the HTML code being used for the textbox validation:
<form id="profileForm">
        <fieldset class="form-group"
            <div class="row">
                <div class="container">
                    <div class="col-md-2">
                        <label for="empnbr-mentor">Employee Number</label>
                        <input type="text" class="form-control" name="mentor_empno" placeholder="Emp Nbr" />
                    </div>
                </div>
            </div>
        </fieldset>
</form>
Actual formValidation code call-out:
<script>
        $(document).ready(function() {
            $('#profileForm').formValidation({
                framework: 'bootstrap',
                icon: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                },
                fields: {
                    mentor_empno: {
                        validators: {
                            notEmpty: {
                                message: 'The name is required'
                            },
                            stringLength: {
                                min: 6,
                                max: 30,
                                message: 'The name must be more than 6 and less than 30 characters long'
                            },
                            regexp: {
                                regexp: /^[a-zA-Z0-9_]+$/,
                                message: 'The name can only consist of alphabetical, number and underscore'
                            }
                        }
                    }
                }
            });
        });
    </script>

**Comment by tomwhalen** [comment]
the HTML code being used for the textbox validation:
<form id="profileForm">
        <fieldset class="form-group"
            <div class="row">
                <div class="container">
                    <div class="col-md-2">
                        <label for="empnbr-mentor">Employee Number</label>
                        <input type="text" class="form-control" name="mentor_empno" placeholder="Emp Nbr" />
                    </div>
                </div>
            </div>
        </fieldset>
</form>
Actual formValidation code call-out:
<script>
        $(document).ready(function() {
            $('#profileForm').formValidation({
                framework: 'bootstrap',
                icon: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                },
                fields: {
                    mentor_empno: {
                        validators: {
                            notEmpty: {
                                message: 'The name is required'
                            },
                            stringLength: {
                                min: 6,
                                max: 30,
                                message: 'The name must be more than 6 and less than 30 characters long'
                            },
                            regexp: {
                                regexp: /^[a-zA-Z0-9_]+$/,
                                message: 'The name can only consist of alphabetical, number and underscore'
                            }
                        }
                    }
                }
            });
        });
    </script>

**Comment by tomwhalen** [comment]
RESOLVED

In your documentation - in the "Including Library" section where you call out the specific css and .js link references, the way the document is stated is that all of the example commands shown should all be grouped together.  This is not the case.  Only the CSS links should be at the top of the html page.  The formValidation and formValidation-specific bootstrap.js files should only be placed at the bottom of the <body> tag along with any other .js files you need.  Once I made this change, the tool started to work as it should.  So I suggest you make a clarification in the 'Including Library' to illustrate what goes at the top (css) files and what goes at the bottom of the <body> tag - the JScript/JQuery sources.  I would also suggest making this an entry in your FAQ document for troubleshooting purposes.
I have another issue now that the tool is working but I'll open a different ticket for that.

**Comment by nghuuphuoc** [comment]
Thanks for the suggestion 👍
