### ISSUE TITLE
Valid US phone format fails: 999 999 9999

### ISSUE THREAD

**Issue by lumberjackchester** [formvalidation/support#599]
The following phone format fails validation for the US:  999 999 9999

**Comment by nghuuphuoc** [comment]
[v0.8.0](http://formvalidation.io/news/v0-8-0-released-supports-bootstrap-4-alpha-foundation-6/) now supports this format.
You can check the [phone validator](http://formvalidation.io/validators/phone/) example.

Please upgrade the plugin.
