### ISSUE TITLE
Use custom validators after server submit

### ISSUE THREAD

**Issue by corneliutusnea** [formvalidation/support#6]
Hi,
You build a fantastic validation.

Can I use/define custom validations or validation placeholders? I could not find any example in your documentation.
Here is my scenario: I define a lot of validations on the client side, they all pass, then the data gets submitted to the server. The server reports back that some field (e.g. the username) is in use.
I want to use the updateStatus to mark the field as INVALID and updateMessage to write the server validation error. However to trigger the updateMessage I need the name of one of the validators that is marked as invalid and I don't have any such validator.

Am I missing something?
Thanks,
Corneliu.

**Comment by nghuuphuoc** [comment]
Your approach is quite straightforward. #13 might help you.

**Comment by nghuuphuoc** [comment]
I've just added the [Showing custom message returned from server](http://formvalidation.io/examples/showing-custom-message-returned-from-server/) example.
