### ISSUE TITLE
Need To Pass Along Validator With status.field.fv Event

### ISSUE THREAD

**Issue by ksidibe** [formvalidation/support#607]
I have followed this example of yours: [Getting notified while field is being validated](http://formvalidation.io/examples/getting-notified-field-being-validated). But there's a problem.
The field that I have (username) has two validators associated with it: Not Empty and Remote.
The Not Empty validator quickly finishes before the Remote and cause the code below to hide the progressBar before even the Remote has returned.
```
if (data.field === 'username') {        // Change “username” to your field name
            (data.status === 'VALIDATING')
                ? $('#progressBar').show()      // Show the progress bar while we are validating
                : $('#progressBar').hide();     // Otherwise, hide it
        }
```
To address this issue, it might be necessary to pass along the name of the vaildator like "remote", or "not-empty" for example. That was, we can provide fine grained handler for the status update events.

**Comment by nghuuphuoc** [comment]
Thanks for the suggestion.
I will add this feature to the next version.

**Comment by nghuuphuoc** [comment]
The latest version [v0.8.0](http://formvalidation.io/news/v0-8-0-released-supports-bootstrap-4-alpha-foundation-6/) implements that.
I also updated the [example](http://formvalidation.io/examples/getting-notified-field-being-validated/).

Please upgrade the plugin.

**Comment by ksidibe** [comment]
Great, thank you.
