### ISSUE TITLE
Validating a start date and end date simultaneously

### ISSUE THREAD

**Issue by harshalsakpal** [formvalidation/support#61]
Hi Phuoc -
Thanks for this amazing plugin.

I am trying to validate the start date and end date simultaneously. It sounds confusing, allow to me elaborate to my best capacity.
The scenario: I am having a start date and end date on a form and an individual validation for both works fine which is start date should be equal and lesser than the end date. If I enter a start date greater than the end date it shows error (expected). Now, at this point when I change the end date for the validation to be true, it only checks for the end date validation which passes and but ignores the start date validation because it was unchanged.
I was wondering if anyone came across this issue before or this is something new.

Code Snippet is as below:

fe.async.poll(function(){
    returndocument.getElementById('saveBtn');
}).done(function(el){
    $('#editStartEndDateForm').formValidation({
        framework: 'bootstrap',
        excluded: ': disabled',
        fields: {
            startDate: {
                validators: {
                    notEmpty: {
                        message: 'Please enter start Date.'
                    },
                    callback: {
                        message: 'Please make sure that the end Date is after the start Date.',
                        callback: function(value, validator, $field){
                            var dateOne=new Date(startDate.value);
                            var dateTwo=new Date(endDate.value);
                            if(dateOne>dateTwo){
                                return false;
                            }else{
                                return true;
                            }
                        }
                    }
                }
            },
            endDate: {
                validators: {
                    notEmpty: {
                        message: 'Please enter end Date.'
                    },
                    callback: function(value, validator, $field){
                        var dateOne=new Date(startDate.value);
                        var dateTwo=new Date(endDate.value);
                         if(dateOne>dateTwo){
                            return false;
                        }else{
                            return true;
                        }
                    }
                }
            }
        },
        submitButtons: '#saveBtn'
    }).on('success.field.fv',function(e, data){
        if(!data.fv.isValid()){
            data.fv.disableSubmitButtons(true);
        }elseif(data.fv.isValid()){
            data.fv.disableSubmitButtons(false);
        }
    });
});fe.async.poll(function(){
    returndocument.getElementById('saveBtn');
}).done(function(el){
    $('#editPayoutTransactionForm').formValidation('revalidateField', 'payoutEffectiveDate');
    $('#editPayoutTransactionForm').formValidation('revalidateField', 'payoutTransactionPostDate');
});

**Comment by nghuuphuoc** [comment]
@harshalsakpal 
It's interesting question. I'm going to create an example on the official website for you.

**Comment by harshalsakpal** [comment]
Great!
Thank you.

**Comment by nghuuphuoc** [comment]
@harshalsakpal 
Here it's: http://formvalidation.io/examples/validating-fields-depend-each-other/

I really appriciate if you can [retweet](https://twitter.com/formvalidation/status/577843180671926272) or [like](https://www.facebook.com/formvalidation) it.

**Comment by jayaVishwakarma** [comment]
@nghuuphuoc, Thanks for awesome solution but even its working I am getting too much recursion error. 
My code looks like:

 form.bootstrapValidator({
          onSuccess: function(e) {
            e.preventDefault();
            scope.changePassword();
          },
          fields : {
            password : {
              validators : {
                notEmpty : {
                  message : 'Please enter old password'
                },
                stringLength: {
                  min: 5,
                  max: 64
                }
              }
            },
            new_password : {
              validators : {
                notEmpty : {
                  message : 'Please enter new password'
                },
                stringLength: {
                  min: 5,
                  max: 64
                }
              },
              onSuccess: function(e, data){
                if (!data.bv.isValidField('new_password_repeat')) {
                  // Revalidate it
                  data.bv.revalidateField('new_password_repeat');
                }
              }
            },
            new_password_repeat : {
              validators : {
                notEmpty : {
                  message : 'Please re-type new password'
                },
                stringLength: {
                  min: 5,
                  max: 64
                },
                identical: {
                  field: 'new_password'
                  //message: 'The password and its confirm are not the same'
                }
              }
            }
          }
        });
Problem is when I choose new_repeat_password to fill first it gives me error because new_password is empty (that's fine) but then I choose new_password and fill it and even if its validated, new_repeat_password error doesn't hide until keypress event fires for it. So I tried this http://formvalidation.io/examples/validating-fields-depend-each-other/ and its working but getting "too much recursion" error in firefox. Any possible solution?

**Comment by nghuuphuoc** [comment]
@jayaVishwakarma 
This example might be useful to you: http://formvalidation.io/examples/enable-validator/

**Comment by jayaVishwakarma** [comment]
Thank you @nghuuphuoc, It is really helpful.
