### ISSUE TITLE
Radio button revalidation error with live mode disabled

### ISSUE THREAD

**Issue by henrypenny** [formvalidation/support#611]
In `live: 'disabled'` mode:

- Make no selection within a given radio group
- Submit form (notEmpty error messages appear as expected)
- Check a radio option - BUT not the first one
- Try to submit, the form won't submit, but no error appears.

I've tracked the issue to the following code:

    // base.js line:1386
    $field.data(ns + '.result.' + v, status);

This updates the status of the individual radio input only, not each input in the group.

If this is the first radio input in the group everything works as expected. If its not then validation fails based on the first radio having INVALID.
This also applies to when the data function is applied to an array of all the radio buttons in the group, as jQuery gets the data from the first element.

Currently my work around is this:

    	.on('submit', function(e) {
		    $('[type=radio]').data('fv.result.notEmpty', 'NOT_VALIDATED');
	    });

I don't know what the behaviour is when `live` is not `disabled`.

**Comment by nghuuphuoc** [comment]
Thanks for reporting the issue and tell me know how to reproduce it 👍 
I fixed that as you can try by downloading this attachment and override your `formValidation.min.js`.

[fix-disabled-mode.zip](https://github.com/formvalidation/support/files/310179/fix-disabled-mode.zip)

I will tell you when the next v0.8.0 is released officially.

**Comment by nghuuphuoc** [comment]
The latest version [v0.8.0](http://formvalidation.io/news/v0-8-0-released-supports-bootstrap-4-alpha-foundation-6/) fixes that.
Please upgrade the plugin.
