### ISSUE TITLE
Support Bootstrap 4 alpha 2

### ISSUE THREAD

**Issue by MarceloRGomes** [formvalidation/support#616]
Hi,
The bootstrap v4 announce has dropped form-group class.  Do you plan update formvalidation for bootstrap 4? 
I bought your framework, and now I´m using bootstrap v4 alpha.03

Thanks,

**Comment by nghuuphuoc** [comment]
Don't worry, I will support v4 when it gets stable.
Because it's just alpha, and there will be a lot of change things which we aren't sure about.

**Comment by nghuuphuoc** [comment]
As I see in the alpha documentation, the form still uses `.form-group`:
http://v4-alpha.getbootstrap.com/components/forms/#form-groups

**Comment by nghuuphuoc** [comment]
The [latest version v0.8.0](http://formvalidation.io/news/v0-8-0-released-supports-bootstrap-4-alpha-foundation-6/) now supports Bootstrap 4 alpha.
Please upgrade the plugin 👍
