### ISSUE TITLE
reCaptcha2 add-on causes "too much recursion" / "stack size exceeded"

### ISSUE THREAD

**Issue by JanBrinker** [formvalidation/support#620]
Hi,
I wanted to include a recaptcha into a form and I'm running into a few issues. I guess the root of the problem is that upon intitalisation of the add-on I get this:
<img width="422" alt="bildschirmfoto 2016-06-20 um 12 40 23" src="https://cloud.githubusercontent.com/assets/11256194/16194496/5ca52e86-36e4-11e6-8c07-45c59b0de38b.png">

This does only show up when I include the add-on initialisation to my code. Without the reCaptcha everything works well.

Any ideas?

**Comment by nghuuphuoc** [comment]
The issue is caused by the fact that the captcha isn't place inside a standard `.form-group` element.
See http://formvalidation.io/getting-started/#writing-form

You should follow the [example](http://formvalidation.io/addons/recaptcha2/#example):
```html
<div class="form-group">
        <label class="col-xs-3 control-label">Captcha</label>
        <div class="col-xs-8">
            <!-- The captcha container -->
            <div id="captchaContainer"></div>
        </div>
    </div>
```

**Comment by JanBrinker** [comment]
Ah, thanks! My form builder forgot to wrap the reCaptcha. :) Everything works now :)

**Comment by nghuuphuoc** [comment]
Awesome 💯
