### ISSUE TITLE
How to acquire upgrade..?

### ISSUE THREAD

**Issue by daza110** [formvalidation/support#634]
Please forgive me.. I have previously purchased 0.7.1, but I cannot find, for the life of me, where the download option is for version 8.0. It keeps asking me to purchase it again.

**Comment by nghuuphuoc** [comment]
You can use the current download link to get the latest (and future) releases.
If you can't find that link or the link doesn't work, please give me your email address you used to purchased.
Then the new download link will be sent to you.

**Comment by daza110** [comment]
Sorry, I pressed enter before putting in description.
I cannot see anywhere on your website to log in to download? I have been to http://formvalidation.io/download/ and it just asks me to pay again.
I am trying to find the receipt for my purchase so I know which email it was I purchased it with

**Comment by nghuuphuoc** [comment]
You do NOT need to purchase again.
If you can't find that receipt, then just give me your email address.

**Comment by daza110** [comment]
georgesmarch123@gmail.com

**Comment by nghuuphuoc** [comment]
The new download link is just sent to your mailbox.
Please keep that link because you can use it to download future releases.

**Comment by trainbolt** [comment]
Also still have not received a link to download the latest...

t.rainbolt@rogers.com

Thanks.
