### ISSUE TITLE
Q: Remote Ajax validator, can it do more?

### ISSUE THREAD

**Issue by DarkAllMan** [formvalidation/support#64]
I have a remote validator (ajax) which nicely returns true or false.
but it also gives me other data which I want to use.
For instance, when the response is as follows:
{"valid":true,"reactivate":true}
I want to load/reload a url..... how would I proceed to take care of that:

					remote: {
						url: 'ajax/checkCustomerid.php',
						type: 'POST',
						delay: 2000,     // Send Ajax request every 2 seconds
						message: 'Customer id already exists!'
					}

**Comment by nghuuphuoc** [comment]
Yes, you can reuse the data which is responsed by the server.

> I want to load/reload a url

How do you mean load/reload?

**Comment by DarkAllMan** [comment]
1. How can I call the returned data......
2. Can I run a extra function when the extra data is true or false. (extra function being: location.reload(); )

**Comment by DarkAllMan** [comment]
I guess I would have to call the returned data in here, where response.reactivate would be the return value:

.on('err.form.fv', function(e) {
		if(response.reactivate){
			location.href = '/request/all';
		}
})


How can I use the other returned data?

**Comment by nghuuphuoc** [comment]
In order to use the returned data of callback/remote/your own validator, try this

```javascript
$(form)
    .formValidation({
        fields: {
            username: {
                validators: {
                    remote: {
                        ...
                    }
                }
            }
        }
    })
    .on('success.validator.fv', function(e, data) {
        // data.field     --> The field name
        // data.validator --> The validator name
        // data.result    --> returned data from server
        if (data.field === 'username' && data.validator === 'remote') {
            // Do something with it ...
        }
    })
    .on('err.validator.fv', function(e, data) {
        if (data.field === 'username' && data.validator === 'remote') {
            // Do something with it ...
        }
    });
```

See some examples:
* [Using Mailgun API to validate email address](http://formvalidation.io/examples/using-mailgun-api-validate-email-address/)
* [Showing credit card icon](http://formvalidation.io/validators/creditCard/#showing-card-icon)

**Comment by nghuuphuoc** [comment]
@DarkAllMan 
You can try the following code:

```javascript
$(form)
    .formValidation()
    .on('err.form.fv', function(e) {
        var response = $(e.target)
                        .find('[name="..."]')   // Replace with the name of field using remote validator
                        .data('fv.response.remote') // Get the returned data of remote validator
                        
        if (response.reactivate) {
            location.href = '/request/all';
        }
    });
```

**Comment by DarkAllMan** [comment]
I will check it later today. Thx.

**Comment by DarkAllMan** [comment]
I cant seem to get this working.
'.on('err.form.fv', function(e) {
		
		var response = $(e.target)
						.find('name="customer_id"')   // Replace with the name of field using remote validator
						.data('fv.response.remote') // Get the returned data of remote validator
		
		if (response.reactivate) {
			
			bootbox.alert("This is a deactivated customer. Activation request sent.", function(){
				location.href = '/request/all';
			});
			window.setTimeout(function(){
				bootbox.hideAll();
				location.href = '/request/all';
			}, 3000);
		}
	})'

**Comment by nghuuphuoc** [comment]
There's issue on your code.

Instead of ```.find('name="customer_id"')```, you have to use ```.find('[name="customer_id"]')```

**Comment by DarkAllMan** [comment]
I noticed that.... the other issue I have, is that this should be triggered on LIVE... right after the remote AJAX has run...... and it doesnt.
I put in an alert('fail') on the error part... its only triggered by a submit... not after the ajax run.

**Comment by nghuuphuoc** [comment]
The ```err.form.fv``` is triggered after the submit button is clicked and the form is invalid.

I don't think redirect to other page right after the remote validator responses, because the user might haven't idea why he/she is redirected.
If you want to do it, try to trigger the ```err.validator.fv``` as in https://github.com/formvalidation/support/issues/64#issuecomment-80498608

**Comment by DarkAllMan** [comment]
Superb... its working now, just how I like it.
