### ISSUE TITLE
ASP.net form submits despite invalid validation

### ISSUE THREAD

**Issue by vikassethiji** [formvalidation/support#640]
I am coming into web programming after 2 years. Was working on C++ and C#. My immediate action was purchasing your plugin so that I spend less time in validations. Unfortunately, I have lost two days making this code work, but the form keeps submitting on click of Submit button despite invalid data.

Your plugin is able to highlight the invalid data excellently and I love the interface for the same. However, then it submits which is wrong. Please help as its very urgent project.

Here is the code:

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Ferrel Fuel</title>

        

        
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

        
        <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
        		
        
        <link rel="stylesheet" href="css/style.css">

        
        <link rel="stylesheet" href="formvalidation/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="formvalidation/dist/css/formValidation.min.css">

        
        <script src="js/jquery-3.0.0.min.js"></script>
        <script src="bootstrap/js/bootstrap.min.js"></script>
        
        
        <script src="formvalidation/dist/js/formValidation.min.js"></script>
        <script src="formvalidation/dist/js/framework/bootstrap.min.js"></script>
        <script src="formvalidation/mandatoryIcon/dist/mandatoryIcon.min.js"></script>

        <script>
            //function disablebutton() {
            //    document.getElementById("cmdProceed").disabled = true;
            //};

            $(document).ready(function () {
                $('#frmGatewayStep1').formValidation({
                    framework: 'bootstrap',

                    /*These are font-awesome icons*/
                    icon: {
                        valid: 'fa fa-check',
                        invalid: 'fa fa-times',
                        validating: 'fa fa-refresh'
                    },
                    addOns: {
                        mandatoryIcon: {
                            icon: 'fa fa-asterisk'
                        }
                    },

                    // List of fields and their validation rules
                    fields: {
                        txtFirstName: {
                            validators: {
                                notEmpty: {
                                    message: 'First name is required and cannot be empty'
                                }
                            }
                        },
                        txtLastName: {
                            validators: {
                                notEmpty: {
                                    message: 'Last name is required and cannot be empty'
                                }
                            }
                        }
                    }
                })            
            });
        </script>
    </head>

    <body>
        <form name="frmGatewayStep1" id="frmGatewayStep1" action="GatewayStep1.aspx" method="post" runat="server">
		
        <div class="top-content">
        	<div class="container">
                    <div class="row">
                        <div class="col-sm-10 col-sm-offset-1 form-box">
                        	
								<fieldset>
		                        	<div class="form-top">
		                        		<div class="form-top-left">
		                        			<h3>Step 1 / 3</h3>
		                            		<p>Enter your details:</p>
		                        		</div>
										<div class="form-top-main">
											<div class="form-logo">
												<img src="img/logo.jpg" alt="logo" />
												<span class="form-address">
												607 Philadelphia Road<br />
												Aberdeen, MD 21001<br />
												( 410 ) 272 - 4650
												</span>
											</div>
										</div>
		                        	</div>
		                            <div class="form-bottom">
										<div class="row">
											
											<div class="col-sm-12">
												<div class="form-group">
													<label class="control-label">First Name on Check</label>
													<input type="text" name="txtFirstName" id="txtFirstName" placeholder="" class="form-control" runat="server" autofocus="autofocus">
													<div class="clearfix"></div>
												</div>
												
												<div class="form-group">
													<label>Last Name on Check</label>
													<input type="text" name="txtLastName" id="txtLastName" placeholder="" class="form-control" runat="server">
													<div class="clearfix"></div>
												</div>
												
												<div class="form-group">
													<label>Check Street Address or P.O.#</label>
													<input type="text" name="txtAddress" id="txtAddress" placeholder="" class="form-control" runat="server">
													<div class="clearfix"></div>
												</div>
												
												<div class="form-group">
													<label>Check City, State, Zipcode</label>
                                                    <input type="text" name="txtCity" id="txtCity" placeholder="" class="form-control small-form2" runat="server">
                                                    <input type="text" name="txtState" id="txtState" placeholder="" class="form-control small-form1" runat="server">
                                                    <input type="text" name="txtZip" id="txtZip" placeholder="" class="form-control small-form2" runat="server">
                                                    <div class="clearfix"></div>
												</div>
												
												<div class="form-group">
													<label>Amount</label>
													<input type="text" name="txtAmount" id="txtAmount" placeholder="" class="form-control" runat="server">
													<div class="clearfix"></div>
												</div>
												
												<div class="form-group">
													<label>Ferrel Fuel Account #</label>
													<input type="text" name="txtOurAccountNumber" id="txtOurAccountNumber" placeholder="" class="form-control" runat="server">
													<div class="clearfix"></div>
												</div>
												
												<div class="form-group">
													<label>Notes ( Optional )</label>
													<input type="text" name="txtNotes" id="txtNotes" placeholder="" class="form-control" runat="server">
													<div class="clearfix"></div>
												</div>
												
												<div class="form-group">
													<label>Phone # (10 digit - No Dash)</label>
													<input type="text" name="txtPhone" id="txtPhone" placeholder="" class="form-control" runat="server">
													<div class="clearfix"></div>
												</div>
												
												<div class="form-group">
													<label>E-mail Address for Receipt</label>
													<input type="text" name="txtEmail" id="txtEmail" placeholder="" class="form-control" runat="server">
													<div class="clearfix"></div>
												</div>

                                                <button type="submit" class="btn btn-primary CenterControls" id="cmdProceed" name="cmdProceed" runat="server">Proceed to transaction</button>
                                            </div>
											
										 </div>
				                    </div>
			                    </fieldset>
							
			             </div>
                    </div>
                </div>
        </div>
    </form>
    </body>

</html>

**Comment by nghuuphuoc** [comment]
The plugin might doesn't work with latest version of jQuery (v3.0).
Can you try with jQuery 2.x?

**Comment by vikassethiji** [comment]
Thanks for your quick reply. I will try with 2.x and revert.

**Comment by vikassethiji** [comment]
No, its not working with 2.2.4 as well. You want me to try the older versions?

**Comment by vikassethiji** [comment]
Not working with 1.11.1. So not working with any jquery version. Whats the advise?

**Comment by nghuuphuoc** [comment]
Thanks for trying quickly.
Here is a simple [working jsfiddle](http://jsfiddle.net/nghuuphuoc/1fytdq2t/1/) which uses extract markup and JavaScript code as your.

<img width="463" alt="issue-640" src="https://cloud.githubusercontent.com/assets/4226036/16880888/abb728c4-4ae1-11e6-91f9-f42d6f05f6ec.png">

Since there is no _GatewayStep1.aspx_ on _jsfiddle_, when the form is valid, submitting it will take you to 404 page of jsfiddle.

* Do you see anything warnings/errors on the console?
* Does it work when you simplify the page as above?

**Comment by vikassethiji** [comment]
Well the jsfiddle works and so do your demos :). The problem is why it is not working at my end :)

I have 18 years of programming experience but in these 18 years only 5 have been into web programming and rest have gone into others.

So honestly, I am completely banking upon you to point me to the right direction. I don't have slightest of hint why this is not working.

I just removed your code and tried simple classic Javascript form onSubmit code and it works fine.

Please advise. Thanks

**Comment by vikassethiji** [comment]
It seems that you are not interested in providing solution to this problem. For me the purpose of buying this plugin stands defeated as I will now have to write my complete code from scratch.

Although $25 is a small amount, but ethically I would expect a refund for the same as your plugin is of no use to me.

**Comment by nghuuphuoc** [comment]
> I just removed your code and tried simple classic Javascript form onSubmit code and it works fine.
> 
> Please advise. Thanks

I think the problem is coming from your `onSubmit`. It will be more useful to find out the problem if you can provide the sample code of that `onSubmit` handler?

**Comment by vikassethiji** [comment]
Here is the code, but the code on server end will get executed only when validation at user end will fail.

Also, when I use live disable of button, formValidation enables the button when one of the validating controls pass the test. This defeats the purpose of disabling the button till everything has been validated on client end. Although its another issue all together, I found many few tickets on this forum that highlighted this issue.

ASP.Net Code:

If Request("token-id") IsNot Nothing Then
            Dim objRequestDocument As New XmlDocument()

            Dim objDocumentDeclaration As XmlDeclaration = objRequestDocument.CreateXmlDeclaration("1.0", "UTF-8", "yes")

            Dim objRootElement As XmlElement = objRequestDocument.DocumentElement
            objRequestDocument.InsertBefore(objDocumentDeclaration, objRootElement)


            Dim xmlCompleteTransaction As XmlElement = objRequestDocument.CreateElement("complete-action")

            Dim objElementAPIKey As XmlElement = objRequestDocument.CreateElement("api-key")

            objElementAPIKey.InnerText = "2F822Rw39fx762MaV7Yy86jXGTC7sCDy"

            xmlCompleteTransaction.AppendChild(objElementAPIKey)


            Dim xmlTokenId As XmlElement = objRequestDocument.CreateElement("token-id")
            xmlTokenId.InnerText = Request("token-id")
            xmlCompleteTransaction.AppendChild(xmlTokenId)


            objRequestDocument.AppendChild(xmlCompleteTransaction)


            Dim responseFromServer As String = Me.sendobjRequestDocument(objRequestDocument)
            Dim responseReader As XmlReader = XmlReader.Create(New StringReader(responseFromServer))


            Dim xDoc As New XmlDocument()
            xDoc.Load(responseReader)
            Dim response As XmlNodeList = xDoc.GetElementsByTagName("result")
            Dim responseText As XmlNodeList = xDoc.GetElementsByTagName("result-text")

            Session("data") = responseFromServer
            Session("result") = response(0).InnerText
            Session("result-text") = responseText(0).InnerText

            responseReader.Close()

            Server.Transfer("GatewayStep3.aspx")
        End If

**Comment by vikassethiji** [comment]
Sorry, here is code for click button as well:

Protected Sub cmdProceed_ServerClick(sender As Object, e As EventArgs) Handles cmdProceed.ServerClick
        Dim objRequestDocument As New XmlDocument()
        Dim objDocumentDeclaration As XmlDeclaration = objRequestDocument.CreateXmlDeclaration("1.0", "UTF-8", "yes")
        Dim objRootElement As XmlElement = objRequestDocument.DocumentElement

        objRequestDocument.InsertBefore(objDocumentDeclaration, objRootElement)

        Dim objElementSale As XmlElement = objRequestDocument.CreateElement("sale")
        Dim objElementAPIKey As XmlElement = objRequestDocument.CreateElement("api-key")
        objElementAPIKey.InnerText = "2F822Rw39fx762MaV7Yy86jXGTC7sCDy"
        objElementSale.AppendChild(objElementAPIKey)

        Dim objElementRedirectUrl As XmlElement = objRequestDocument.CreateElement("redirect-url")

        'Response.Write(Request.ServerVariables("HTTP_REFERER"))
        'Response.End()

        objElementRedirectUrl.InnerText = Request.ServerVariables("HTTP_REFERER")
        objElementSale.AppendChild(objElementRedirectUrl)

        Dim xmlAmount As XmlElement = objRequestDocument.CreateElement("amount")
        xmlAmount.InnerText = "12.00"
        objElementSale.AppendChild(xmlAmount)

        Dim xmlRemoteAddr As XmlElement = objRequestDocument.CreateElement("ip-address")
        xmlRemoteAddr.InnerText = Request.ServerVariables("REMOTE_ADDR")
        objElementSale.AppendChild(xmlRemoteAddr)

        Dim xmlCurrency As XmlElement = objRequestDocument.CreateElement("currency")
        xmlCurrency.InnerText = "USD"
        objElementSale.AppendChild(xmlCurrency)

        Dim xmlOrderId As XmlElement = objRequestDocument.CreateElement("order-id")
        xmlOrderId.InnerText = "1234"
        objElementSale.AppendChild(xmlOrderId)

        Dim xmlOrderDescription As XmlElement = objRequestDocument.CreateElement("order-description")
        xmlOrderDescription.InnerText = "Small Order"
        objElementSale.AppendChild(xmlOrderDescription)

        Dim xmlMDF1 As XmlElement = objRequestDocument.CreateElement("merchant-defined-field-1")
        xmlMDF1.InnerText = "Red"
        objElementSale.AppendChild(xmlMDF1)

        Dim xmlMDF2 As XmlElement = objRequestDocument.CreateElement("merchant-defined-field-2")
        xmlMDF2.InnerText = "Medium"
        objElementSale.AppendChild(xmlMDF2)

        Dim xmlTax As XmlElement = objRequestDocument.CreateElement("tax-amount")
        xmlTax.InnerText = "0.00"
        objElementSale.AppendChild(xmlTax)

        Dim xmlShipping As XmlElement = objRequestDocument.CreateElement("shipping-amount")
        xmlShipping.InnerText = "0.00"
        objElementSale.AppendChild(xmlShipping)

        'If Not (CustomerVaultId.Text.Equals("") OrElse CustomerVaultId.Text.Equals("0"c)) Then
        '    Dim xmlCustomerVaultId As XmlElement = objRequestDocument.CreateElement("customer-vault-id")
        '    xmlCustomerVaultId.InnerText = CustomerVaultId.Text

        '    objElementSale.AppendChild(xmlCustomerVaultId)
        'End If

        Dim xmlBillingAddress As XmlElement = objRequestDocument.CreateElement("billing")

        Dim xmlFirstName As XmlElement = objRequestDocument.CreateElement("first-name")
        xmlFirstName.InnerText = txtFirstName.Value
        xmlBillingAddress.AppendChild(xmlFirstName)

        Dim xmlLastName As XmlElement = objRequestDocument.CreateElement("last-name")
        xmlLastName.InnerText = txtLastName.Value
        xmlBillingAddress.AppendChild(xmlLastName)

        Dim xmlAddress1 As XmlElement = objRequestDocument.CreateElement("address1")
        xmlAddress1.InnerText = txtAddress.Value
        xmlBillingAddress.AppendChild(xmlAddress1)

        Dim xmlCity As XmlElement = objRequestDocument.CreateElement("city")
        xmlCity.InnerText = txtCity.Value
        xmlBillingAddress.AppendChild(xmlCity)

        Dim xmlState As XmlElement = objRequestDocument.CreateElement("state")
        xmlState.InnerText = txtState.Value
        xmlBillingAddress.AppendChild(xmlState)

        Dim xmlZip As XmlElement = objRequestDocument.CreateElement("postal")
        xmlZip.InnerText = txtZip.Value
        xmlBillingAddress.AppendChild(xmlZip)

        'Dim xmlCountry As XmlElement = objRequestDocument.CreateElement("country")
        'xmlCountry.InnerText = billingAddressCountry.Text
        'xmlBillingAddress.AppendChild(xmlCountry)

        Dim xmlPhone As XmlElement = objRequestDocument.CreateElement("phone")
        xmlPhone.InnerText = txtPhone.Value
        xmlBillingAddress.AppendChild(xmlPhone)

        Dim xmlEmail As XmlElement = objRequestDocument.CreateElement("Email")
        xmlEmail.InnerText = txtEmail.Value
        xmlBillingAddress.AppendChild(xmlEmail)

        objRequestDocument.AppendChild(objElementSale)


        Dim responseFromServer As String = Me.sendobjRequestDocument(objRequestDocument)

        '--- If the Response from server is good then we will get similar response internally from the servers:
        '--- 1 Step 1 completed 3165370593 100 https://avatasgateway.com/api/v2/three-step/3s6n0j5j 
        '--- This response we will store in a Session variable and then move to step 2 through Server.Transfer method.
        '--- In Step2 we will set frmStep2's action to the URL that we stored in session variable. So when the user presses Step 2's button the information will go to the link. This link will check the information and return us the token ID. That will be returned in form Step 1.

        'Response.Write(responseFromServer)
        'Response.End()

        Dim responseReader As XmlReader = XmlReader.Create(New StringReader(responseFromServer))


        Dim xDoc As New XmlDocument()
        xDoc.Load(responseReader)
        Dim responseList As XmlNodeList = xDoc.GetElementsByTagName("result")
        If responseList(0).InnerText.Equals("1") Then
            Dim formUrl As XmlNodeList = xDoc.GetElementsByTagName("form-url")
            Session("formURL") = ""
            Session("formURL") = formUrl(0).InnerText

            responseReader.Close()

            Server.Transfer("GatewayStep2.aspx")
        End If
    End Sub

    Public NotInheritable Class SSLValidator
        Private Shared Function OnValidateCertificate(sender As Object, certificate As X509Certificate, chain As X509Chain, sslPolicyErrors As SslPolicyErrors) As Boolean
            Return True
        End Function
        Public Shared Sub OverrideValidation()
            ServicePointManager.ServerCertificateValidationCallback = AddressOf OnValidateCertificate
            ServicePointManager.Expect100Continue = True
        End Sub
    End Class

    Protected Function sendobjRequestDocument(objRequestDocument As XmlDocument) As String
        SSLValidator.OverrideValidation()

        'ServicePointManager.CertificatePolicy = New Program()
        Dim uri As String = "https://avatasgateway.com/api/v2/three-step"

        Dim req As WebRequest = WebRequest.Create(uri)
        'req.Proxy = WebProxy.GetDefaultProxy(); // Enable if using proxy
        req.Method = "POST"
        ' Post method
        req.ContentType = "text/xml"
        ' content type
        ' Wrap the request stream with a text-based writer
        Dim writer As New StreamWriter(req.GetRequestStream())
        ' Write the XML text into the stream

        objRequestDocument.Save(writer)

        writer.Close()
        ' Send the data to the webserver
        Dim rsp As WebResponse = req.GetResponse()

        Dim dataStream As Stream = rsp.GetResponseStream()
        ' Open the stream using a StreamReader 
        Dim reader As New StreamReader(dataStream)
        ' Read the content.
        Dim responseFromServer As String = reader.ReadToEnd()

        ' int index = responseFromServer.IndexOf("<?");
        'string substr = responseFromServer.Substring(index);
        ' Display the content.
        'MessageBox.Show(responseFromServer);
        ' Clean up the streams.

        reader.Close()
        dataStream.Close()
        rsp.Close()

        Return responseFromServer

    End Function

**Comment by vikassethiji** [comment]
Server side code is a sample code provided by payment gateway company. My job is to make form validations work at client end.

**Comment by vikassethiji** [comment]
Still waiting for you!

**Comment by vikassethiji** [comment]
I think you should mention on your website
1. We have horrible support
2. Our code doesn't work with ASP.net
3. There is no guarantee of this code working on other technologies
4. We can cheat for as low as $25 and won't give you back the money once you have bought our product.

Even if you don't mention it, I will make it a point to spread the good word in all communities I am present in.

What a fake and horrible plugin you are selling.

Shame!

**Comment by nghuuphuoc** [comment]
It's not fair because it's not easy or even possible for me to know and fix your server side.
There are a lot of customers who integrates it successfully with not only ASP.Net but also other server side programming languages.

I always try my best to support and make a lot of examples in client side (since it's just a jquery plugin), how I can make it work for all server side cases?

Anyway, in this particular case, if you can't make it work, please give me the email address you used to purchase, and I will make a refund.

**Comment by vikassethiji** [comment]
1. Your client side code is allowing my submit button to go on the server side. So there is a problem somewhere that you need to look into and rectify.
2. You don't respond to thread on time and test the patience of fellow programmers and buyers who bought your control on trust that it's the best. Even if you can't help, you need to respond.
3. Make a disclaimer on your website if this control may not work with ASP.net pages. So that users can buy it at their own risk.

I loved the way this control works on your website and I don't take credit from you that you made it work well. But then you have to be proactive with support, so that if someone is facing issues they don't feel, they are on their own.

I bought it for a project that was most urgent and not only did I waste time waiting for your response, I end up writing the code from scratch. This is what is not fair.

I got upset only due to your lack of response. Otherwise programmer to programmer, i would have helped you troubleshoot this issue.

My email ID  that I used to buy this control is mail@vikassethi.com.

**Comment by nghuuphuoc** [comment]
Thanks for the feedback and being patient. I did refund.

**Comment by vikassethiji** [comment]
Thanks for the refund. Appreciate it.
