### ISSUE TITLE
How to enabling input validators one by one?

### ISSUE THREAD

**Issue by guille1194** [formvalidation/support#642]
good night, i have a doubt, i want to make a step by step input validator like the example of enabling validators, but in the example, does not validate the password, but the confirm password is validated.
I needed because i want to enable the submit button like the example.

Here is the example that i mean.

http://formvalidation.io/examples/enable-validator/

Thanks.

**Comment by nghuuphuoc** [comment]
> How to enabling input validators one by one

You can enable the input validators whenever you want:

```javascript
$('#enableForm').formValidation('enableFieldValidators', 'password', true_or_false);
```

Am I missing anything?

**Comment by guille1194** [comment]
Oh, thanks for the answer, i found other way to do that, keeping always enabled the submit button 
Thank you so much!!

http://formvalidation.io/examples/enabling-submit-button/

**Comment by nghuuphuoc** [comment]
👍
