### ISSUE TITLE
There are any way to validate a date from the current date to onwards?

### ISSUE THREAD

**Issue by guille1194** [formvalidation/support#649]
Good night, i read the documentation and i don't found nothing about my question, so, if somebody can help me, i will be grateful.

**Comment by nghuuphuoc** [comment]
You can use the `min` option provided by the [date validator](http://formvalidation.io/validators/date/).

```javascript
$('#eventForm').formValidation({
    fields: {
        startDate: {
            validators: {
                date: {
                    min: new Date(),
                    ...
                }
            }
        }
    }
});
```

There is also http://formvalidation.io/examples/validating-start-end-datetimes/ example which provides more complex case.

**Comment by guille1194** [comment]
ok, i'm going to trying tomorrow and i gonna tell you what happened, but, i think that really gonna work.

Thanks :+1:

**Comment by guille1194** [comment]
another thing, can i create functions inside the validator, to do the conditions about the current date?

**Comment by guille1194** [comment]
ok , i wrote the code and it works, but the validator is succesful when i put a day after the current date, and don't validate when i put the current date. So, there are any way to validate starting from the current date?

Thanks for your time.

**Comment by nghuuphuoc** [comment]
So, instead of `min: new Date()`, you should pass the date of yesterday:

```javascript
var yesterday = new Date(Date.now() - 86400000);

// Or
// var yesterday = new Date();
// yesterday.setDate(yesterday.getDate() - 1);

$('#eventForm').formValidation({
    fields: {
        startDate: {
            validators: {
                date: {
                    min: yesterday,
                    ...
                }
            }
        }
    }
});
```

**Comment by guille1194** [comment]
yes, now it's working, in fact i did, but i put the var inside the validator and isn't valid, thank you so much :+1:

**Comment by nghuuphuoc** [comment]
The `min` option is the [dynamic option](http://formvalidation.io/settings/#dynamic-option) which means you can pass a function for that:

```javascript
$('#eventForm').formValidation({
    fields: {
        startDate: {
            validators: {
                date: {
                    min: function() {
                       return new Date(Date.now() - 86400000);
                       // Or:
                       // var yesterday = new Date();
                       // yesterday.setDate(yesterday.getDate() - 1);
                       // return yesterday;
                    },
                    ...
                }
            }
        }
    }
});
```

The _dynamic option_ is very powerful, so you should take a look at the [doc](http://formvalidation.io/settings/#dynamic-option) to use it in the future/other cases.

**Comment by guille1194** [comment]
wow, sounds cool, really is an awesome project, congrats :D
