### ISSUE TITLE
How to show messages in a modal and a help-block at the same time?

### ISSUE THREAD

**Issue by guille1194** [formvalidation/support#652]
The question comes because in the documentation only appears how to show messages in a modal, but don't appears below the input, so here is the documentation. 

http://formvalidation.io/examples/showing-messages-modal/ 

Thanks!!!

**Comment by guille1194** [comment]
I'm not sure if I explain well, but the thing i want to do, it's display the error message in a modal and also   below the input, because, in the example, only is showing in the modal, and no below of the input, so any answer it's welcome.

**Comment by guille1194** [comment]
I'm still waiting for an answer, please.

**Comment by nghuuphuoc** [comment]
Please stay tuned! I understood the requirements and still trying to find the best way to archive this :)

**Comment by guille1194** [comment]
ok, thanks for the answer, i will continue waiting :D

**Comment by nghuuphuoc** [comment]
The example is now available at
http://formvalidation.io/examples/showing-messages-modal/#bonus-keep-showing-errors-below-field-and-inside-the-modal

Ensure that you clear the browser cache.

**Comment by guille1194** [comment]
Thank you so much for the quick answer :smile:

**Comment by guille1194** [comment]
Sorry, but i don't understand how it works

**Comment by nghuuphuoc** [comment]
The code is quite simple.

__The markup__

```html
<form id="signupForm" method="post" class="form-horizontal">
    <!-- The form elements go here -->
</form>

<!-- Modal for displaying the messages -->
<div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                ...
            </div>

            <div class="modal-body">
                <!-- The messages container -->
                <div id="errors"></div>
            </div>

            <div class="modal-footer">
                ...
            </div>
        </div>
    </div>
</div>
```

Inside the modal, we have an element with id as `errors` to place all the error messages.

__The script__

```javascript
$(document).ready(function() {
    $('#signupForm')
        .formValidation({
            framework: 'bootstrap',
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                ...
            }
        })
        .on('err.form.fv', function(e) {
            // 1) Reset the errors inside the modal first
            $('#errors').html('');

            // 2)
            $('#signupForm')
                // Find all the error messages
                .find('[data-fv-validator][data-fv-result="INVALID"]')
                // And update the error inside the modal body
                .clone().appendTo('#errors');

            // 3) Show the message modal
            $('#messageModal').modal('show');
        });
});
```

As you see, the `err.form.fv` event is trigger when the form is invalid after clicking the _Submit_ button. In that handler, we do 3 things:

1) Reset the `errors` element
2) We find all the error messages which are currently shown (by querying the `[data-fv-validator][data-fv-result="INVALID"]` selector), cloning them, and append to the `errors`
3) Show the modal

That's all.

**Comment by guille1194** [comment]
ok, it doesn't affect if i display the modal with the href feature in the modal? 

Because didn't work.

Apologize for the late response, i was busy.

**Comment by nghuuphuoc** [comment]
> ok, it doesn't affect if i display the modal with the href feature in the modal?

I don't understand what you mean. But based on the code of example, you can customize the error message to suit with your need.

**Comment by guille1194** [comment]
I mean if it's possible with the second example whose title is "Bonus: Focusing on the field when clicking the message"

Because I tried , and it did not work me.

**Comment by nghuuphuoc** [comment]
So, you want to 
* Display the error message below the field and inside the modal
* And when click the error message inside the modal, the associated field will be focused?

**Comment by guille1194** [comment]
yes, i want to do this, if it's possible, thanks.

**Comment by guille1194** [comment]
Can you make an example in jsfiddle or something similar?

**Comment by nghuuphuoc** [comment]
Here is the [working fiddle](http://jsfiddle.net/nghuuphuoc/4omoj1wa/2/) which uses mostly code from the http://formvalidation.io/examples/showing-messages-modal/#bonus-focusing-on-the-field-when-clicking-the-message

Please take a look at the code.

**Comment by guille1194** [comment]
oh, perfect, but i forgot another thing, the submit button is always enable, i don't know if it cause conflict?

**Comment by guille1194** [comment]
Great work, thanks :D
