### ISSUE TITLE
Error when try to validate a regexp validation with filled inputs at the beginning

### ISSUE THREAD

**Issue by guille1194** [formvalidation/support#672]
When i put my regexp condition to the respective inputs, and i try with filled inputs previously, the validator catch the error, but save the data anyway, my doubt is, how to block the button with filled inputs if one of the input is incorrect.

**Comment by guille1194** [comment]
Please, i need a answer

**Comment by guille1194** [comment]
i'm sorry, but i need an answer to know if i explained well. Thanks.

**Comment by nghuuphuoc** [comment]
> how to block the button with filled inputs if one of the input is incorrect

Maybe this example is useful to you: http://formvalidation.io/examples/enabling-submit-button/

**Comment by guille1194** [comment]
nop, didn't solve

**Comment by nghuuphuoc** [comment]
So maybe I didn't understand the question clearly. Can you clarify it?

**Comment by guille1194** [comment]
my problem is that when I want to edit data that was before using the validator , says the data are incorrect , but still stored in sql.

I explain?

**Comment by guille1194** [comment]
there is no way to solve it?

**Comment by guille1194** [comment]
someone have any idea that can be?

**Comment by nghuuphuoc** [comment]
Not yet :(

**Comment by guille1194** [comment]
ooh, ok, thank you anyway :'(

**Comment by guille1194** [comment]
Has anyone else had this issue?

**Comment by guille1194** [comment]
You should mark it as an bug , no?

**Comment by guille1194** [comment]
Ok, i believe that is possible with the remote validator, but i'm not sure if it work with asp.net (specifically c# handler, with request, response, not mvc.)
