### ISSUE TITLE
FormValidation not working in grails

### ISSUE THREAD

**Issue by bilalsha** [formvalidation/support#678]
I am trying to integrate formvalidation in grails application but it is not working.

I have included formvalidation files like below 
```
<asset:stylesheet href="bootstrap.css"/>
        <asset:stylesheet href="formValidation.min.css"/>
        <asset:stylesheet href="al-webapp-style.css"/>
        <asset:stylesheet href="style.css"/>
        <asset:stylesheet href="responsive.css" media="screen"/>
        <asset:stylesheet href="font-awesome.min.css"/>
        <asset:stylesheet href="https://fonts.googleapis.com/css?family=Lato:400,100,300,700,900" type="text/css"/>
        <asset:javascript src="jquery-2.2.4.min.js"/>
        <asset:javascript src="bootstrap.js"/>
        <asset:javascript src="js/formValidation.min.js"/>
        <asset:javascript src="js/formValidation.popular.min.js"/>
        <asset:javascript src="js/framework/bootstrap.min.js"/>
```

my `gsp` page:

```
<form id="emailForm">
                <div class="form-group">
                    <div class="al-label-ctrl ">
                        Work Email*
                    </div>
                    <div class="al-control">
                        <input  name="email" class="form-control"/>
                    </div>
                </div>
                <div class="al-wb-btn">
                    <input name="resend" type="submit" value="Resend Invitation Code" class="al-wbtn">
                </div>
            </form>

<asset:script type="text/javascript">
    $(document).ready(function() {
    $('#emailForm').formValidation({
        framework: 'bootstrap',
        fields: {
            email: {
                validators: {
                    emailAddress: {
                        message: 'The value is not a valid email address'
                    }
                }
            }
        }
    });
});
</asset:script>
```

What I am doing wrong here? Nothing displays when I try to send form.

**Comment by nghuuphuoc** [comment]
```html
<asset:javascript src="js/formValidation.min.js"/>
<asset:javascript src="js/formValidation.popular.min.js"/>
```

These files duplicate core plugin and multiple validators definitions. Please use one of them.
`formValidation.min.js` includes all validators, meanwhile `formValidation.popular.min.js` only includes the popular one.

**Comment by bilalsha** [comment]
It is still not working.

**Comment by bilalsha** [comment]
@nghuuphuoc please respond asap. I have a deadline to come.

**Comment by nghuuphuoc** [comment]
I think you need to add `type="text"` to the email field.
Here is the [working fiddle](http://jsfiddle.net/nghuuphuoc/cq0zfcxr/1/):

<img width="634" alt="email" src="https://cloud.githubusercontent.com/assets/4226036/17879739/910f2cd2-691e-11e6-9af6-c56b36433ff9.png">

**Comment by bilalsha** [comment]
@nghuuphuoc yes it is working but in grails application it is not working. Have you checked your plugin with `asset` plugin which grails uses

**Comment by nghuuphuoc** [comment]
I haven't worked with grails, so I am not sure about this case.
Do you see any warnings in the _Console_ window of browser? What do you have in browser when the page is rendered by Grails?

**Comment by bilalsha** [comment]
Hi, It is now working. Thanks

**Comment by nghuuphuoc** [comment]
Awesome! Can you tell me what you have fixed?

**Comment by bilalsha** [comment]
Added `<div class="al-label-ctrl control-label">` instead of `<div class="al-label-ctrl">` makes it work. Actually it was working but the class wasn't used in `div`
