### ISSUE TITLE
Hidden field validation fails with Uncaught RangeError

### ISSUE THREAD

**Issue by jb000** [formvalidation/support#679]
```html
<html>
<head>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"   integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="   crossorigin="anonymous"></script>
    <script type='text/javascript' src='/formvalidation-dist-v0.8.1/dist/js/formValidation.min.js'></script>
    <script type='text/javascript' src='/formvalidation-dist-v0.8.1/dist/js/framework/bootstrap.min.js'></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#form-test').formValidation({
                framework: 'bootstrap',
                fields: {
                    hiddenInput: {
                        excluded: false,
                        validators: {
                        notEmpty: {
                            message: 'Is Required'
                        }
                        }
                    }
                }
            });
        });
    </script>
</head>
<body>
<button type="button" id="button-submit">Submit</button>
<form id="form-test" action="#url" method="POST">
    <input type="hidden" name="hiddenInput" />
</form>
</body>
</html>
```

**Stack trace:**
jquery-1.12.4.min.js:2 Uncaught RangeError: Maximum call stack size exceeded
[Symbol.replace] @ (program):563
[Symbol.replace] @ (program):675
replace @ (program):121
fa @ jquery-1.12.4.min.js:2
fa.matches @ jquery-1.12.4.min.js:2
n.filter @ jquery-1.12.4.min.js:2
z @ jquery-1.12.4.min.js:2
is @ jquery-1.12.4.min.js:2
_getMessageContainer @ formValidation.min.js:10
_getMessageContainer @ formValidation.min.js:10

**Comment by nghuuphuoc** [comment]
Not only hidden input, the plugin also requires the field/form to follow standard Bootstrap form markup.
This `Maximum call stack size exceeded` warning is mentioned at the [Writing form](http://formvalidation.io/getting-started/#writing-form) section.

So, there are two solutions for this:
1) Place your `hiddenInput` inside a `.form-group` as other field
```html
<div class="form-group">
    <input type="hidden" name="hiddenInput" />
</div>
```

2) Place `hiddenInput` inside an element which can be defined by the [row](http://formvalidation.io/settings/#form-row-selector) option.
See the [complex form](http://formvalidation.io/examples/complex-form/) example.

**Comment by jb000** [comment]
That’s grand old chap!!

Was using the example http://formvalidation.io/examples/using-hidden-field-technique/ which didn’t include the mark up.

Keep up the good work.
