### ISSUE TITLE
Validate immediatly on page load

### ISSUE THREAD

**Issue by adamjmcd91** [formvalidation/support#682]
I have some pre-set values for a few of my fields that are set dynamically on page load.

Right now, it doesn't validate until I make a change in the field (such as adding a character or choosing a different item from dropdown).

Not a pro at this jquery stuff yet, but is this possible?

**Comment by nghuuphuoc** [comment]
You can use the [validate()](http://formvalidation.io/api/#validate) method:

```javascript
// Init first
$('#yourForm').formValidation(options);

// Validate it manually when the page is loaded
$('#yourForm').formValidation('validate');
// or
$('#yourForm').data('formValidation').validate();
```
