### ISSUE TITLE
FormValidation with grails tag

### ISSUE THREAD

**Issue by bilalsha** [formvalidation/support#686]
Can we validate a field by using id, class or something. Because I am using grails and I need to use ```<g:textField type="email" name="inviteMeEmail" class="form-control"/>``` 

instead of 

```<input type="email" name="inviteMeEmail" class="form-control"/>```

It is not working with `g:textField`, How can I make it work?

**Comment by nghuuphuoc** [comment]
> Can we validate a field by using id, class or something

You can use the [selector](http://formvalidation.io/settings/#field-selector) option.
