### ISSUE TITLE
Emails fields named as emais[] to handle multiple email entry not working

### ISSUE THREAD

**Issue by chateauv** [formvalidation/support#7]
We just paid for the library and we are afraid we cannot achieve what we need.
How can we handle email validation on multiple email fields named emails[] to handle multiple emails on POST ?

**Comment by nghuuphuoc** [comment]
When working with multiple elements with the same name, you must wrap the name ```emails[]``` between ' and '.
See this example: http://formvalidation.io/examples/multiple/

```javascript
$(form).formValidation({
    framework: '...',
    fields: {
        'emails[]': {
            validators: {
                ...    
            }
        }
    }
});
```

**Comment by chateauv** [comment]
Thank you for the answer.
We are trying to apply the err.container to tooltip but we are getting the following error message when we first click in the input box:
TypeError: d.tooltip is not a function
Any idea why is that ?

**Comment by chateauv** [comment]
Also, is there any way to know if the whole form is validated. i.e. $('#invitationForm').formValidation() would return true when all the form's fields are passing validation. Any way to achieve this with one of your functions ?
Thank you

**Comment by nghuuphuoc** [comment]
Does the [Using tooltip to show message](http://formvalidation.io/examples/using-tooltip-to-show-message/) example work on my browser?

If yes, maybe you don't include ```bootstrap(.min).js``` (provided by Bootstrap framework). Ensure that you have 2 ```bootstrap(.min).js``` files in your page, one provided by Bootstrap framework, one provided by FormValidation:

```html
<!-- Bootstrap JS -->
<script src="/vendor/bootstrap/js/bootstrap.min.js"></script>

<!-- FormValidation plugin and the class supports validating Bootstrap form -->
<script src="/vendor/formvalidation/dist/js/formValidation.min.js"></script>
<script src="/vendor/formvalidation/dist/js/framework/bootstrap.min.js"></script>
```

PS: Can you create separated issue for each question? So, if it is not possible at the current version, I can mark it as requirement for next one.
It's more easy for me to manage the user's issues/requirements.

**Comment by nghuuphuoc** [comment]
> Also, is there any way to know if the whole form is validated. i.e. $('#invitationForm').formValidation() would return true when all the form's fields are passing validation

You can archive it by triggering the [success.form.fv](http://formvalidation.io/settings/#event-form) event.

**Comment by chateauv** [comment]
Thank you for your assistance. It turns out I was missing the bootstrap min file (I though I had it).
Yes, absolutely, I can separate my requests in the future, sorry for that. Did it the lasy way. ;)
