### ISSUE TITLE
An invalid form control with name='product_category_id' is not focusable.

### ISSUE THREAD

**Issue by geshwin** [formvalidation/support#701]
Hi,
I'm using chosen-select for the select dropdown box (https://harvesthq.github.io/chosen/)
Not sure how to handle this error with the element hidden.
Any help would be greatly appreciated. Thanks.

**Comment by geshwin** [comment]
http://formvalidation.io/examples/chosen/

**Comment by nghuuphuoc** [comment]
You're quicker than me 👍 
Also, please keep these rules in mind when integrating the plugin with other one: http://formvalidation.io/examples/#compatibility
