### ISSUE TITLE
How do you upload images with Summernote

### ISSUE THREAD

**Issue by bobmeetin** [formvalidation/support#723]
I followed the example to set up Summernote. That part is fine. I tested the image uploader and find that it is preparing  a base64 (?) image which I don't know how to deal with. Can you provide formvalidation/jQuery code which will switch to using a standard Ajax upload function such that I stored uploaded images in a folder along with the filename. Tx.

**Comment by nghuuphuoc** [comment]
I am sorry. This question is out of plugin scope.
