### ISSUE TITLE
trigger in field validation spec object being overuled

### ISSUE THREAD

**Issue by nickweavers** [formvalidation/support#744]
I have a field in my html that looks like this:

```
<div class="form-group has-feedback">
  <label class="col-md-3 control-label" for="mobile">Mobile:</label>
  <div class="col-md-9">                  
      <input class="form-control blue-tooltip" type="text" name="mobile" id="mobile" data-toggle="tooltip" data-placement="top" required title="We'll need a number to contact you on.">
  </div>    
</div>
```

And the corresponding field spec in the formValidation object looks like this:

```
mobile: {
    validators: {
        trigger: 'blur',                    
        pcaPhone: {
            key: 'my-pcaDirect-api-key',
            country: 'GB',
            type: 'mobile',                        
            message: 'Not a valid UK mobile number'
        }                                         
    }
},
```
Whats confusing me is that my custom validator is getting called when I key in a single character rather than when I leave the field. This is bad in this case since each call to PcaDirect costs money so I really only want to to call them once when I have the full number.

What could be overriding the trigger I have specified in my field object?

Thanks,
Nick

**Comment by nickweavers** [comment]
I moved the custom validation up to the server, used the remote validator to call it and added the notEmpty and regexp validators. I also added the verbose property to the field as you'd suggested in another of my issues which prevented the costly remote validation being performed unto the cheaper notEmpty and regexp validations have failed.

Thanks

**Comment by nghuuphuoc** [comment]
Awesome. Thanks for the feedback.
