### ISSUE TITLE
Is it possible to cascade validators?

### ISSUE THREAD

**Issue by nickweavers** [formvalidation/support#745]
My use case is a where I want to make an js API call in my custom validator to a service that provides a check on whether a phone number is in service (not is just valid as per regexp). But I don't want to call my validator unless I've first established that the phone number format is valid since it costs real money to use the service. So what I'm wondering is, is it possible to specify a cascading sequence when you have multiple validator per field> That way I could say that the the "phone" validator passed, then my custom validator "phoneInService" should be called, and only the failing validator would then set the appropriate message. eg "invalid phone number format" for the phone validator, or "phone number not in service" for the "phoneInService" validator.

I could probably achieve what I need using a solution similar to the one shown in the example at [switching-validators-same-field](http://formvalidation.io/examples/switching-validators-same-field/
), but I think the cascaded implementation might offer much better modularity and reuse. Also, if I wanted to separate out phone (ie landline) from mobile (cell) then could I use delegation in the .on('input keyup', '[name="yourId"]', function() {... part, passing context so the appropriate field's secondary validator would be enabled?
 
Thanks,
Nick

**Comment by nghuuphuoc** [comment]
You can use the [verbose](http://formvalidation.io/settings/#field-verbose) option.
For example, it's recommended when using with [remote](http://formvalidation.io/validators/remote/#using-verbose-option) validator.

**Comment by nickweavers** [comment]
Thanks, that did the trick.
