### ISSUE TITLE
Validation remains even after entering correct values

### ISSUE THREAD

**Issue by Gardezi1** [formvalidation/support#752]
Hello guys, first of all awesome package. It has got mostly everything one needs for form validation. But there is one problem that I'm facing. Don't know if it's at my end or there is something wrong in your code. 

I have a form which have alot of dates using jquery datepicker. Now when I do not enter a date and click on submit the validation kicks in and tells me to enter the date which is perfect but after I enter the date it remains stuck. The message telling me to enter the date remains over there and until and unless I do not reload the page it remain stuck over there. Please help me out. What is going wrong

![1350](https://cloud.githubusercontent.com/assets/13199724/20918970/65f6f3c8-bbbb-11e6-84b8-3a213a3f45fa.png)

**Comment by nghuuphuoc** [comment]
You need to ask the plugin to revalidate the field after choosing from the date picker.
See 
* http://formvalidation.io/examples/jquery-ui-datepicker/
* http://formvalidation.io/examples#compatibility for basic principles when integrating FormValidation with other plugins

**Comment by Gardezi1** [comment]
thanks @nghuuphuoc, that works
