### ISSUE TITLE
Error when using callback validator

### ISSUE THREAD

**Issue by echohive** [formvalidation/support#772]
Hi,

I'm trying to use FormValidation with Complexify, however the callback constantly seems to fail. I have since simplified the code simply to read:

```javascript
                callback: {
                  callback: {
                        callback: function(value, validator, $field) {
                                return {
                                    valid: true,    // or false
                                    message: 'The error message'
                                }

                        }
                    }

                }
```

However, even this comes up with the following error:

![Image of Error](https://deltahive.com/issues/FormValidation_Error.png)

Which once PrettyPrinted in Chrome refers to:

![Image of Error](https://deltahive.com/issues/FormValidation_Code.png)

Am I going crazy here or have I done something stupid?

Thanks,
Dave

**Comment by nghuuphuoc** [comment]
It seems that the options you pass aren't correct because I saw 3 `callback`:
```javascript
callback: {
  callback: {
    callback: function(value, validator, $field) {
    }
  }
}
``` 

It should be
```javascript
callback: { // It should be your field name
  validators: {
    callback: function(value, validator, $field) {
    }
  }
}
```
