### ISSUE TITLE
Error when trying to use with Bootstrap on Meteor

### ISSUE THREAD

**Issue by nicholasalanbrown** [formvalidation/support#78]
Hello:

I've used other jQuery plugins with Meteor with no trouble but can't et this one to work. I keep getting this error in Chrome after page load:

```
Exception from Tracker afterFlush function: Error: The class FormValidation.Framework.Bootstrap is not implemented
```
I've included fromValidation.js, bootstrap.js, and formValidation.css in my client/lib folder.

I'm using one of the examples in the "Getting Started" section straight out of the box:

```
<form id="signinForm" class="form-inline">
    <div class="form-group" style="width: 40%;">
        <input type="text" class="form-control" name="username" placeholder="Username" style="width: 100%;" />
    </div>

    <div class="form-group" style="width: 40%;">
        <input type="password" class="form-control" name="password" placeholder="Password" style="width: 100%;" />
    </div>

    <!-- Do NOT use name="submit" or id="submit" for the Submit button -->
    <button type="submit" class="btn btn-default">Sign in</button>
</form>

<script>
$(document).ready(function() {
    $('#signinForm').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            username: {
                validators: {
                    notEmpty: {
                        message: 'The username is required'
                    },
                    stringLength: {
                        min: 6,
                        max: 30,
                        message: 'The username must be more than 6 and less than 30 characters long'
                    },
                    regexp: {
                        regexp: /^[a-zA-Z0-9_]+$/,
                        message: 'The username can only consist of alphabetical, number and underscore'
                    }
                }
            },
            password: {
                validators: {
                    notEmpty: {
                        message: 'The password is required'
                    }
                }
            }
        }
    });
});
</script>
```
Any ideas?

**Comment by nghuuphuoc** [comment]
@nicholasalanbrown 
You forgot to include the ```bootstrap(.min).js``` provided by FormValidation.

> Don't confuse bootstrap(.min).js file provided by the Bootstrap framework with bootstrap(.min).js provided by FormValidation which is placed inside the formvalidation/dist/js/framework directory.
They are two different files and both of them need to be included as mentioned above.

See http://formvalidation.io/getting-started/#including-library

**Comment by gholol** [comment]
I have the same problem.

And i'm 100% sure that every file is included correctly.

    //include css and jquery

       //form with validator

    //include scripts (at the end of body)
    {% block scripts %}
      {{ parent() }} //bootstrap.js, etc
      <script src="/js/formvalidation/bootstrap.js"></script>
      <script src="/js/formvalidation/formValidation.min.js"></script>
    {% endblock %}

**Comment by nghuuphuoc** [comment]
Please ensure that the order of scripts must be as following:

<script src="bootstrap.js">
<script src="/js/formvalidation/formValidation.min.js"></script>
<script src="/js/formvalidation/bootstrap.js"></script>

@gholol 
So, your scripts order are not correct.

**Comment by gholol** [comment]
Yup, i discovered it just a few seconds ago :). Damn, i'm dummy.

As you said, formValidation.min.js must be included before bootstrap.js
