### ISSUE TITLE
Error: this.options.fields[b] is undefined

### ISSUE THREAD

**Issue by periscuelo** [formvalidation/support#79]
Hello.
I use the 0.5.2 version of bootstrapValidator and I am getting this error message:
"Error: this.options.fields[b] is undefined".
Although not interfere in anything and everything works, do not know why the error persists. And in my whole system this is the only error that occurs. Can anyone tell me why this happens? Because it tells a number of things, but very confused, I did not know what I'm doing wrong. I will be grateful if someone can help me because all the links that I think about this error on the Internet are down.
In advance, thank you all.

**Comment by nghuuphuoc** [comment]
@periscuelo 
Please give me the HTML form markup and Javascript code you're calling.
I will try to help you.

**Comment by periscuelo** [comment]
That's not so simple but, i will try.
I use AngularJs, SummerNote and Bootstrap validator.
Then, the form field is in a loop and switch. Everything is ok except by the error.
Everything is work.

You can get the script here http://www.4shared.com/zip/Y6_HFtpMce/markup_files.html

Thank you very much for the dispensed attention and time.

**Comment by periscuelo** [comment]
If you can tell me the most common motives for this error i can search if i'm doing anything else wrong.

**Comment by periscuelo** [comment]
I found it. I use the method revalidateField in one field undefined. Thank you very much.

**Comment by nghuuphuoc** [comment]
:+1: I'm glad that you found it!

**Comment by shariqalee** [comment]
i have the same issue like periscuelo  told but i didn't find the solution. please help me to solve this problem

**Comment by nghuuphuoc** [comment]
@shariqalee Please give me the HTML/JS code you're using. 
There's no way for me to help without sample code.
