### ISSUE TITLE
Iban validator accepts non-existing country codes

### ISSUE THREAD

**Issue by reind** [formvalidation/support#82]
The Iban-validator accepts non-iban countrycodes as 'valid'. Existing iban country codes are handled as expected and validated Ok.

**Comment by reind** [comment]
It would be nice to add 'SEPA' as option to the Iban validator. (SEPA is a European subset of the Iban range)

**Comment by nghuuphuoc** [comment]
> It would be nice to add 'SEPA' as option to the Iban validator

Can you give me the specifications of this format?

**Comment by nghuuphuoc** [comment]
> The Iban-validator accepts non-iban countrycodes as 'valid'

Thank for the suggestion. 
From the next v0.6.2, the IBAN number with non-support country code will be treated as invalid.

**Comment by reind** [comment]
Hi,

thank you for your quick support, seeing forward to use the modified iban
validator.


About SEPA:  as mentioned, the format is Iban.
Several Eurpean counties have aggreed to accept international
banc-transfers as (almost) local. You only need the Iban to transfer money
between the participating countries.
( eq internet banking)

Check Link below for more information:
https://www.ecb.europa.eu/paym/retpaym/paymint/html/index.en.html
there is a video introduction and a link to the SEPA-countries page.

So the "sepa" option should addtionally check if the Iban is from a
SEPA-country.
With the option set is should return 'invalid' for a non-sepa country.

SEPA countries: {
                    AT: 'Austria',
                    BE: 'Belgium',
                    BG: 'Bulgaria',
                    CH: 'Switzerland',
                    CY: 'Cyprus',
                    CZ: 'Czech Republic',
                    DK: 'Denmark',
                    DE: 'Germany',
                    EE: 'Estonia',
                    ES: 'Spain',
                    FI: 'Finland',
                    FR: 'France',
                    GB: 'United Kingdom',
                    GR: 'Greece',
                    HR: 'Croatia',
                    HU: 'Hungary',
                    IE: 'Ireland',
                    IS: 'Iceland',
                    IT: 'Italy',
                    LI: 'Liechtenstein',
                    LT: 'Lithuania',
                    LU: 'Luxembourg',
                    LV: 'Latvia',
                    MC: 'Monaco',
                    MT: 'Malta',
                    NL: 'Netherlands',
                    NO: 'Norway',
                    PL: 'Poland',
                    PT: 'Portugal',
                    RO: 'Romania',
                    SE: 'Sweden',
                    SI: 'Slovenia',
                    SK: 'Slovakia'
                }


greets,
Rein



2015-03-22 16:05 GMT+01:00 Phuoc Nguyen <notifications@github.com>:

> The Iban-validator accepts non-iban countrycodes as 'valid'
>
> Thank for the suggestion.
> From the next v0.6.2, the IBAN number with non-support country code will
> be treated as invalid.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formvalidation/support/issues/82#issuecomment-84626829>
> .
>



-- 
met vriendelijke groet,

Rein Dolfing

**Comment by nghuuphuoc** [comment]
I added the ```sepa``` option to the iban validator:
> ```sepa```: Set it to true (false) to indicate that the IBAN number must be (not be) from SEPA countries
> By default, this option is not defined

This option will be available in the next v0.6.2.

Accroding to [IBAN Registry (Release 56)](http://www.swift.com/dsp/resources/documents/IBAN_Registry.pdf), updated on __March 2015__, the set of SEPA countries are:

* AT (Austria)
* BE (Belgium)
* BG (Bulgaria)
* CH (Switzerland)
* CY (Cyprus)
* CZ (Czech Republic)
* DE (Germany)
* DK (Denmark)
* EE (Estonia)
* ES (Spain)
* FI (Finland)
* FR (France)
* GB (United Kingdom)
* GI (Gibraltar) <--- You dont' add it
* GR (Greece)
* ~~HR (Croatia)~~ (not in the list)
* HU (Hungary)
* IE (Ireland)
* IS (Iceland)
* IT (Italy)
* LI (Liechtenstein)
* LU (Luxembourg)
* LV (Latvia)
* LT (Lithuania)
* MC (Monaco)
* MT (Malta)
* NL (Netherlands)
* NO (Norway)
* PL (Poland)
* PT (Portugal)
* RO (Romania)
* SE (Sweden)
* SI (Slovenia)
* SK (Slovak Republic)
* SM (San Marino) <--- You dont' add it

Next v0.6.2 also adds support for IBAN numbers in new 2 countries which are
* XK (Republic of Kosovo)
* TL (Timor-Leste)

**Comment by reind** [comment]
Hi,

thank you for the corrections.

one remark:

HR Croatia  is a SEPA country according to
https://www.ecb.europa.eu/paym/retpaym/paymint/html/index.en.html

thank you and seeing forward  to version 0.6.2.

Greet,
Rein






2015-03-23 5:07 GMT+01:00 Phuoc Nguyen <notifications@github.com>:

> I added the sepa option to the iban validator:
>
> sepa: Set it to true (false) to indicate that the IBAN number must be
> (not be) from SEPA countries
> By default, this option is not defined
>
> This option will be available in the next v0.6.2.
>
> Accroding to IBAN Registry (Release 56)
> <http://www.swift.com/dsp/resources/documents/IBAN_Registry.pdf>, updated
> on *March 2015*, the set of SEPA countries are:
>
>    - AT (Austria)
>    - BE (Belgium)
>    - BG (Bulgaria)
>    - CH (Switzerland)
>    - CY (Cyprus)
>    - CZ (Czech Republic)
>    - DE (Germany)
>    - DK (Denmark)
>    - EE (Estonia)
>    - ES (Spain)
>    - FI (Finland)
>    - FR (France)
>    - GB (United Kingdom)
>    - GI (Gibraltar) <--- You dont' add it
>    - GR (Greece)
>    - HR (Croatia) (not in the list)
>    - HU (Hungary)
>    - IE (Ireland)
>    - IS (Iceland)
>    - IT (Italy)
>    - LI (Liechtenstein)
>    - LU (Luxembourg)
>    - LV (Latvia)
>    - LT (Lithuania)
>    - MC (Monaco)
>    - MT (Malta)
>    - NL (Netherlands)
>    - NO (Norway)
>    - PL (Poland)
>    - PT (Portugal)
>    - RO (Romania)
>    - SE (Sweden)
>    - SI (Slovenia)
>    - SK (Slovak Republic)
>    - SM (San Marino) <--- You dont' add it
>
> Next v0.6.2 also adds support for IBAN numbers in new 2 countries which are
>
>    - XK (Republic of Kosovo)
>    - TL (Timor-Leste)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formvalidation/support/issues/82#issuecomment-84788065>
> .
>



-- 
met vriendelijke groet,

Rein Dolfing

**Comment by nghuuphuoc** [comment]
> HR Croatia  is a SEPA country according to
> https://www.ecb.europa.eu/paym/retpaym/paymint/html/index.en.html

I added HR (Croatia) to the list of SEPA countries. Thank you :+1:

**Comment by nghuuphuoc** [comment]
@reind 
v0.6.2 is released. If you already purchase the previous version, please [drop me](mailto: phuoc@huuphuoc.me) an email, or give me your email address. You will get an update version.

**Comment by reind** [comment]
Hi Phuoc,

thanks for announcement.

I already downloaded the 0.6.2 version from Sellfy.

greets,
Rein




2015-04-02 14:46 GMT+02:00 Phuoc Nguyen <notifications@github.com>:

> @reind <https://github.com/reind>
> v0.6.2 is released. If you already purchase the previous version, please drop
> me <%20phuoc@huuphuoc.me> an email, or give me your email address. You
> will get an update version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formvalidation/support/issues/82#issuecomment-88886060>
> .
>



-- 
met vriendelijke groet,

Rein Dolfing

**Comment by nghuuphuoc** [comment]
Great :+1: 
By the way, thank for reporting new issue!
