### ISSUE TITLE
SummerNote Validation

### ISSUE THREAD

**Issue by periscuelo** [formvalidation/support#86]
The example of SummerNote validation in this link http://formvalidation.io/examples/summernote/ is limited to SummerNote 0.5.10 version. If use SummerNote 0.6.2 version the example not work.
Have any update of example to work with last SummerNote?

Thanks

**Comment by nghuuphuoc** [comment]
@periscuelo 
I updated the [Summernote](http://formvalidation.io/examples/summernote/) example that now uses the latest version.

Does it work as you expect? :)

**Comment by periscuelo** [comment]
@nghuuphuoc, first thank you very much for the quickly solution.
It work, but (ever have one "but") i found other problem.
However i'm go make a new issue. Thanks.
