### ISSUE TITLE
Login form is never submited after validation

### ISSUE THREAD

**Issue by ashishpatel1992** [formvalidation/support#88]
Hi,
I have created a Login form but after clicking on submit it doesnt post the form data.
I have checked the same in chrome debugger.
Here is my code:
===========================================
<?php if (isset($_POST['submit'])){
				session_start();
				$username = $_POST['username'];
				$password = $_POST['password'];
				$query = "SELECT * FROM users WHERE username='$username' AND password='$password'";
				$result = mysql_query($query)or die(mysql_error());
				$num_row = mysql_num_rows($result);
				$row=mysql_fetch_array($result);
				if( $num_row > 0 ) {
				header('location:dashboard.php');
				//echo "<script>window.location.href=\"dashboard.php\";</script>";
				$_SESSION['id']=$row['user_id'];
				$_SESSION['fname']=$row['firstname']." ".$row['lastname'];
				}
				else{ ?>
				<div class="alert alert-danger">Access Denied</div>		
				<?php
				}}
				?>

     <div class="container" role="main">
		<div class="jumbotron alert-info">
        <div class="logo"><h1><img src="<?php echo $baseurl; ?>images/logo.png"> Jabalpur Engineering College</h1></div>
        <center><p>This Project Titled <a style="color:Red">"Open Public Access Catalogue for a College Library"</a> <br>Developed by Rashmi Verma 4th Semester as Minor Project.</p></center>
		</div>
	  
	  <div class="span12">
				<div class="header">
				<div class="pull-left">
				</div>
				</div>
				<div class="alert alert-info"><Strong>Welcome </strong>&nbsp; to Jabalpur Engineering College Online Library
					<div class="pull-right">
						<i class="icon-calendar icon-large"></i>
						<?php
						$Today = date('y:m:d');
						$new = date('l, F d, Y', strtotime($Today));
						echo $new;
						?>
					</div>
				</div>
		</div>
	  
	 
	<div class="row">
		<div class="col-md-3">&nbsp;</div>
		<div class="col-md-5">
			<div class="panel panel-primary">
				<div class="panel-heading">
				  <h3 class="panel-title">Please Sign In</h3>
				</div>
				<div class="panel-body">
					<form id="loginValidation" method="post" class="form-horizontal" >
						<div class="form-group">
							<label for="inputEmail" class="control-label col-md-4">Username</label>
							<div class="col-md-6">
								<input type="username" name="username" id="username" class="form-control" placeholder="Username" required autofocus>
							</div>
							<div class="col-md-2"></div>
						</div>
						<div class="form-group">
							<label for="inputPassword" class="control-label col-md-4">Password</label>
							<div class="col-md-6">
								<input type="password" name="password" id="password" class="form-control" placeholder="Password" required>
							</div>
							<div class="col-md-2"></div>
						</div>
						<div class="form-group">        
							<div class="col-sm-offset-4 col-sm-2">
								<button name="submit" class="btn btn-default" type="submit">Sign in</button>
							</div>
							<div class="col-sm-offset-1 col-sm-5">
								<a href="#">Forgot Password?</a>
							</div>
						</div>
					</form>
				</div>
			 </div>
		</div>
	  <div class="col-md-4">&nbsp;</div>
	</div>
	 <script>
	$(document).ready(function() {
		$('#loginValidation').formValidation({
			framework: 'bootstrap',
			icon: {
				valid: 'glyphicon glyphicon-ok',
				invalid: 'glyphicon glyphicon-remove',
				validating: 'glyphicon glyphicon-refresh'
			},
			fields: {
				username: {
					validators: {
						notEmpty: {
							message: 'The username is required'
						},
						stringLength: {
							min: 4,
							max: 30,
							message: 'The username must be more than 4 and less than 30 characters long'
						},
						regexp: {
							regexp: /^[a-zA-Z0-9_]+$/,
							message: 'The username can only consist of alphabetical, number and underscore'
						}
					}
				},
				password: {
					validators: {
						notEmpty: {
							message: 'The password is required'
						},
						stringLength: {
							min: 4,
							max: 30,
							message: 'The username must be more than 4 and less than 30 characters long'
						}
					}
				}
			}
		});
		
	});
	</script>
</div>
===========================================

**Comment by nghuuphuoc** [comment]
```
<button name="submit" class="btn btn-default" type="submit">Sign in</button>
```

Don't use ```name="submit"``` or ```id="submit"``` for the submit button.
Change it to [something else](http://formvalidation.io/getting-started/#name-conflict) and the issue will be solved.

**Comment by ashishpatel1992** [comment]
Hello,
Thanks a lot man you saved my day!! I tried with name="submit-login" and it worked!. :+1:
