### ISSUE TITLE
Bootstrap4 no longer in Alpha - formvalidation does not render correctly with release version

### ISSUE THREAD

**Issue by RambosRide** [formvalidation/support#899]
Bootstrap has finally gone release (Currently v4.1.0)

The current formsvalidation version 8.1 does not work correctly with the release version.

How long will it be until the source is updated to work with release version?

Thanks!

Dan

**Comment by RambosRide** [comment]
@nghuuphuoc  hello, just a bump up the ladder.

**Comment by alandolsi** [comment]
Is there a new Version for Bootstrap 4.1 ?????????

**Comment by RambosRide** [comment]
Hmmm...I love this plugin but can't wait around. guess I'll do it myself for now with what I have.

**Comment by danypd69** [comment]
Hei @nghuuphuoc, is this plugin still supported? There is mention of a 1.0 version on twitter.

**Comment by RambosRide** [comment]
For anyone interested, too bad seems like the author is taking the money but not supporting the work.? 

Mostly what I've found is for Bootstrap 4 release bits - that you'll need to override the default selector, and or use the row selector to target what you want and I found input groups need a form-group surrounding them..mostly small stuff so far, but haven't tested all validators to be honest.

Still hoping the author is found alive and was just working on ugrading it to Bootstrap 4 release ;)

Good luck!
