### ISSUE TITLE
Problem with reading default messages from correct localization file

### ISSUE THREAD

**Issue by nghuuphuoc** [formvalidation/support#9]
_From @budik21 on February 1, 2015 11:6_

After implementing 0.6.1 I have problem with reading default messages

Base on preferred language I set correct localization file on application start

    <?php    	
    	switch (strtolower($_SESSION['LANG'])) {
     		case 'cs':
     			echo "<script type='text/javascript' src='js/language/cs_CZ.js'></script>";
     	   		break;
     		case 'sk':
     			echo "<script type='text/javascript' src='js/language/sk_SK.js'></script>";
                        break;
    	}
    ?>

The result is, that in case of Czech language I have in rendered HTML page this line:

    <script type='text/javascript' src='js/language/cs_CZ.js'>

...and the link is correct and leads to formvalidation localization resource.

Next I  have following piece of code

    <input type="text"
          class="form-control"
          name="polluxusername"
          id="polluxUsername"
          placeholder="<?php echo $localization->getLocalizationByCode('20'); ?>"
                                 
          data-fv-notempty="true"
          data-fv-notempty-message="<?php echo $localization->getLocalizationByCode('11');?>"
                                 
          data-fv-stringlength="true"
 	  data-fv-stringlength-min="6"
	  data-fv-stringlength-max="20"
					 			 
  	  data-fv-regexp="true"
	  data-fv-regexp-regexp="^[a-zA-Z0-9_-]*$"
	  data-fv-regexp-message="<?php echo $localization->getLocalizationByCode('161');?>"
    >

So, it means, that in two cases I  set message programaticalyy, but in case of wrong string length I would like to use default formvaliatin message. **But the message is displayed in English, not in Czech language, although I have set correct localization package.**

What I am doing wrong?

_Copied from original issue: formvalidation/formvalidation#1404_

**Comment by nghuuphuoc** [comment]
@budik21
Do you set the ```locale``` option?
See the [Using language package](http://formvalidation.io/examples/using-language-package/) example.

**Comment by budik21** [comment]
You are right, of course, I didn't. I have just written it as is in example, and all is OK

Maybe...It migration description (0.5.3 -> 0.6.0) there was no information about it, and I am sure, that in 0.5.3 this was not necessary. It will be nice to have link to this example on "Getting started" page, because on this page is only a half on required information.

Many thanks for your effort

**Comment by nghuuphuoc** [comment]
> and I am sure, that in 0.5.3 this was not necessary

You are right! I added new ```locale``` option to support using multiple languages. It means that it's possible to switch between languages (the document will come soon).
