### ISSUE TITLE
clear validations after clearing form

### ISSUE THREAD

**Issue by ashishpatel1992** [formvalidation/support#90]
Hi,
I was able to achieve clearing my modal form in bootstrap by using code 

$(".modal").on('hidden.bs.modal', function () {
         $(this).data('bs.modal', null);
});

but how do i clear all validations at once.

**Comment by nghuuphuoc** [comment]
Take a look at the last section in [modal](http://formvalidation.io/examples/modal/) example.

**Comment by ashishpatel1992** [comment]
Hi,
Thank you for your response. Well I have tried this but it partially worked.
Let me explain my scenario I am using two modal in a page and both are having a form. One for adding data and one for editing data which is already present in the table Example table of books.
I am using code 
$('#add_books').on('shown.bs.modal', function() {
		$('form').formValidation('resetForm', true);
	});
But this code clears the data from both the forms #add_books and from #edit_book
I dont know why jQuery is resetting #edit_book when i am not even calling it.
So probably jQuery is resetting all the modals irrespective of the div ID.

**Comment by nghuuphuoc** [comment]
```
$('#add_books').on('shown.bs.modal', function() {
    $('form').formValidation('resetForm', true);
});
```

You're using ```$('form').formValidation('resetForm', true)```, that's why all forms are reset.

**Comment by ashishpatel1992** [comment]
Well So what code should I use to reset Just one form based on its div ID?

**Comment by russellpabon** [comment]
Change `$('form').formValidation('resetForm', true);` to `$('div#yourID form').formValidation('resetForm', true);`

**Comment by ashishpatel1992** [comment]
This worked for me
<pre>
$(document).ready(function() {
	$('#add_books').on('shown.bs.modal', function() {
		$('div#add_books form').formValidation('resetForm', true);
	});
});
</pre>
Thanks a Lot :smile:
