### ISSUE TITLE
Id validator - country NL ( BSN)

### ISSUE THREAD

**Issue by reind** [formvalidation/support#92]
There is a small bug in the dutch BSN definition. 
a dutch BSN is defined as a string with only numbers and a length of 8 or 9 characters.
(points  '.'  are not allowed, although handy for readability), So after the points '.' are removed the resulting string MUST be 8 or 9 characters. If the length of the resulting string is  < 8 characters it should not validate. If the length of the string is 8 characters it is allowed to add JUST ONE '0' in front of the string to get a string of 9 characters.
Example  '187318' and '0187318' validate, they should not, both are too short.

**Comment by nghuuphuoc** [comment]
@reind 
The improvement for this suggestion is done and will be availble in the next v0.6.3.
In the next version, 187318 and 0187318 are NOT valid.
The numbers with dot inside such as 9413.31.490 are still accepted.

**Comment by nghuuphuoc** [comment]
v0.6.3 is out! You can use the previous download link to get the new version.
