### ISSUE TITLE
formvalidation 0.5.2 duplicate the summernote

### ISSUE THREAD

**Issue by periscuelo** [formvalidation/support#93]
Here me again :)
"In this time, is other enemy" by Nascimento Captain =)
When i call the validator it's duplicate the summernote textarea to validate the second text area

![duplicate](https://cloud.githubusercontent.com/assets/6675426/6965119/69f00d04-d925-11e4-81ac-42289de15d6d.jpg)

The detail is that this happens if I use summernote 0.6.2. If I use the 0.5.10 summernote this does not occur

Have you any idea of why it happens?
Again, thank you by the attention.

**Comment by nghuuphuoc** [comment]
@periscuelo 
Can you please give me the HTML form markup and the Javascript code?

**Comment by periscuelo** [comment]
Javascript
$scope.validar = function(op, table, field, value) {
      $scope.fTRR = [];
      var vtd = 'jQuery("#angular_form").bootstrapValidator({';
          vtd+= '  excluded: [":disabled"],';
          vtd+= '  feedbackIcons: {';
          vtd+= '    valid: "glyphicon glyphicon-ok",';
          vtd+= '    invalid: "glyphicon glyphicon-remove",';
          vtd+= '    validating: "glyphicon glyphicon-refresh"';
          vtd+= '  },';
          vtd+= '  fields: {';
          angular.forEach(jQuery('.taSummernote'), function(obj, index) {
              if ($scope.fTRequired[obj.id]==true) {
                  $scope.fTRR[index] = { name: obj.name, required: $scope.fTRequired[obj.id] };
                  vtd+= obj.name+': { validators: { callback: { callback: function(value, validator, $field) {';
                  vtd+= 'var code = jQuery(\'[name="'+obj.name+'"]\').code();';
                  vtd+= 'return (code !== "" && code !== "<p><br></p>"); }}}},';
              }
          });
          vtd+= '  },';
          vtd+= '  onSuccess: function() {';
          vtd+= '    $scope.gravar(op, table, field, value);';
          vtd+= '  }';
          vtd+= '}).find(\'[class="taSummernote"]\').summernote({';
          vtd+= '  onkeyup: function() { $scope.validateEditor($scope.fTRR); },';
          vtd+= '  onpaste: function() { $scope.validateEditor($scope.fTRR); }';
          vtd+= '}).end();';
      eval(vtd);
  }

HTML
<textarea ng-init="getTextCode($index, entity[field.name], field.required)" id="ta{{$index}}" name="{{field.name}}" class="taSummernote"></textarea>

And i call the $scope.validar() in a button to validate the form
