### ISSUE TITLE
Documentation typographical error for field events

### ISSUE THREAD

**Issue by russellpabon** [formvalidation/support#95]
Hi,

In this link http://formvalidation.io/settings/#event-field "err.field.fv" should be "error.field.fv"? I am using v0.6.0 and error.field.bv is working while err.field.bv is not, unless the name event is changed in the newer version?

**Comment by nghuuphuoc** [comment]
Both are supported. ```error.field.bv``` is for anyone who started using the ```data-bv-xxx``` prefix.
See http://formvalidation.io/news/upgrading-to-v0.6.0/

**Comment by russellpabon** [comment]
Thanks for the response, I forgot to check the upgrade section of the documentation. But I wonder why you use "err.field.fv" instead of “error.field.fv”? I think "error" is name specific than "err" just my opinion.

**Comment by nghuuphuoc** [comment]
> I think "error" is name specific than "err" just my opinion

The reason for changing ```error``` to ```err``` is to prevent the window.onerror event from being invoked by jQuery.

**Comment by russellpabon** [comment]
Thanks for clarifying.
