### ISSUE TITLE
mandatoryIcon addOn doesnot handle enabled: true/false property

### ISSUE THREAD

**Issue by reind** [formvalidation/support#98]
I use this code as a conditional validator, the mandatoryIcon is always shown even if the validator is disabled.
validator {
                 enabled: false,
                 validators:
                    {
                        notEmpty: {},
                        id: {
                            country: 'NL'
                        }
                    }

**Comment by nghuuphuoc** [comment]
Thank for reporting the issue.
I fixed it and you can [upgrade](http://formvalidation.io/addons/mandatoryIcon/) the v0.1.1.

Please notice that the mandatory will not shown when you enable the validators later.
