### ISSUE TITLE
bootstrap-datepicker options datesDisabled and daysOfWeekDisabled

### ISSUE THREAD

**Issue by prietoedgardo** [formvalidation/support#99]
Hi im using bootstrap-datepicker with your formvalidation plugin and is working wonderful. Anyway in your plugin i missed some options present in datepicker like datesDisabled: an array to avoid selecting some dates, and daysOfWeekDisabled to avoid selecting sundays per example. Im trying to do the same with callbacks, but maybe you can add that options to the date validation in your plugin, this can help some other people too. Thank you for your great work!

**Comment by nghuuphuoc** [comment]
Thank for the suggestion.
In the next version, I will show you how to do it without using the callback validator.

**Comment by prietoedgardo** [comment]
thank you! another question, currently im programming using version 0.6.1, i must to pay again for a possible update?

**Comment by nghuuphuoc** [comment]
> i must to pay again for a possible update

No, you will get the update versions for free forever. Please drop me an email at phuoc@huuphuoc.me and you will get the update whenever it is available.

**Comment by prietoedgardo** [comment]
ok, thank you!
